CREATE OR REPLACE FUNCTION calcula_cs (id	NUMBER)
   RETURN NUMBER
IS
   FORMAT_TIME   NUMBER;
BEGIN

IF id IS NOT NULL THEN


SELECT  sum(t.DATA_FIM_CS - t.DATA_INI_CS) INTO FORMAT_TIME from TEMPOS_LONG1 T WHERE T.ID_EXTERNAL_REQUEST = id;

   RETURN FORMAT_TIME;

ELSE
   RETURN NULL;
END IF;

END calcula_cs;
/
DROP FUNCTION CALCULA_CS;
