CREATE OR REPLACE TRIGGER B_IU_DOC_AREA_INST_SOFT_PROF
  BEFORE INSERT OR UPDATE ON DOC_AREA_INST_SOFT_PROF
  FOR EACH ROW
BEGIN
    :NEW.adw_last_update := SYSDATE;
END b_iu_doc_area_inst_soft_prof;
/
