CREATE OR REPLACE TRIGGER B_IU_REP_PROF_TEMPLATE
 BEFORE INSERT OR UPDATE OF ID_SOFTWARE, ID_PROFESSIONAL, ID_INSTITUTION, ID_REP_PROF_TEMPLATE, ID_REP_PROFILE_TEMPLATE
 ON REP_PROF_TEMPLATE
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
begin
  :new.adw_last_update := sysdate;
end;
/
