CREATE OR REPLACE TRIGGER B_IU_SR_INTERV_DPCLIN_SERV
 BEFORE INSERT OR UPDATE OF ID_SR_INTERV_DEP_CLIN_SERV, ID_DEP_CLIN_SERV, ID_SR_INTERVENTION, RANK, ID_PROFESSIONAL, ID_INSTITUTION, FLG_TYPE, ID_SOFTWARE
 ON SR_INTERV_DEP_CLIN_SERV
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
begin
    :new.adw_last_update := sysdate;
end;
/
