-- CHANGED BY: Rita Lopes
-- CHANGE REASON: Acrescentar trigger à tabela CHILD_FEED_DEV_INST
-- CHANGE DATE: 2007/09/06

CREATE OR REPLACE TRIGGER B_IU_CHILD_FEED_DEV_INST
 BEFORE INSERT OR UPDATE
 ON CHILD_FEED_DEV_INST
 FOR EACH ROW

-- PL/SQL Block
BEGIN
:NEW.ADW_LAST_UPDATE := SYSDATE;
END;

-- CHAGE END