CREATE OR REPLACE
TRIGGER B_IU_EPIS_REPORT
 BEFORE INSERT OR UPDATE OF ID_PROFESSIONAL, ID_EPIS_REPORT, ID_REPORTS, ID_EPISODE, DT_CREATION_TSTZ
 ON EPIS_REPORT
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
BEGIN
    :NEW.adw_last_update := SYSDATE;
END;
/
