CREATE OR REPLACE TRIGGER B_IU_SYS_REQUEST
BEFORE INSERT OR UPDATE
ON ALERT.SYS_REQUEST 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE

BEGIN

  :NEW.dt_req_day := trunc(:new.dt_request);
END B_IU_SYS_REQUEST;
/
