CREATE OR REPLACE TRIGGER B_IU_DOCUMENTATION_ACCESS
 BEFORE INSERT OR UPDATE
 ON DOCUMENTATION_ACCESS
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
begin
  :new.adw_last_update := sysdate;
end;

