CREATE OR REPLACE TRIGGER B_IU_REP_PROFILE_TEMPLATE_DET
 BEFORE INSERT OR UPDATE OF ID_REPORTS, ID_REP_PROFILE_TEMPLATE_DET, FLG_AREA_REPORT, FLG_ACTION, ID_REP_SCREEN, ID_REP_PROFILE_TEMPLATE, VALUE_ACTION
 ON ALERT.REP_PROFILE_TEMPLATE_DET 
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
begin
  :new.adw_last_update := sysdate;
end;
/
