CREATE OR REPLACE TRIGGER B_IU_SUMMARY_PAGE_ACCESS
 BEFORE INSERT OR UPDATE
 ON SUMMARY_PAGE_ACCESS
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
begin
  :new.adw_last_update := sysdate;
end;

