CREATE OR REPLACE TRIGGER B_IU_SR_interv_desc
 BEFORE INSERT OR UPDATE 
 ON SR_interv_desc
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
BEGIN
:NEW.ADW_LAST_UPDATE := SYSDATE;
END;
/
