CREATE OR REPLACE TRIGGER B_IUD_HIDRICS_RELATION
 BEFORE INSERT 
 ON HIDRICS_RELATION
 FOR EACH ROW
-- PL/SQL Block
BEGIN
    :NEW.adw_last_update := SYSDATE;
END;
/


--Sofia Mendes (17-11-2009)
drop trigger B_IUD_HIDRICS_RELATION;