CREATE OR REPLACE TRIGGER B_IUD_SCALES_DOC_VALUE
 BEFORE DELETE OR INSERT OR UPDATE
 ON SCALES_DOC_VALUE
 FOR EACH ROW
-- PL/SQL Block
BEGIN
:NEW.ADW_LAST_UPDATE := SYSDATE;
END;
/
--CHANGED BY: Ariel Geraldo Machado
--CHANGE DATE: 2009-01-30
--CHANGE REASON: ALERT-15638. Trigger no longer needed and don't allow to delete a row because on DELETE is trying to update NEW.ADW_LAST_UPDATE! .
DROP TRIGGER B_IUD_SCALES_DOC_VALUE;
--CHANGE END