CREATE OR REPLACE TRIGGER B_IU_SR_EQUIP_PERIOD
 BEFORE INSERT OR UPDATE 
 ON SR_EQUIP_PERIOD
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
BEGIN
:NEW.ADW_LAST_UPDATE := SYSDATE;
END;
/
