CREATE OR REPLACE TRIGGER B_IU_SR_EQUIP_KIL
 BEFORE INSERT OR UPDATE OF DESC_EQUIP_KIT, ID_SR_EQUIP_KIT, QTY, ID_SR_EQUIP_PARENT, ID_SPECIALITY, ID_SR_EQUIP, FLG_AVAILABLE, ID_PROFESSIONAL
 ON SR_EQUIP_KIT
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW

-- PL/SQL Block
BEGIN
:NEW.ADW_LAST_UPDATE := SYSDATE;
END;
/
