PROMPT DROPPING DEPRECATED TRIGGERS...
--cmf 18-12-2012
declare

my_trg      table_varchar := table_varchar
                        (
                        'B_IUD_MATERIAL',
                        'B_IUD_CARE_PLAN_TYPE',
                        'B_IU_SR_EQUIP',
                        'B_IU_SR_INTERVENTION',
                        'B_IU_SR_PROF_SHIFT',
                        'B_IU_SR_SURGERY_TIME',
                        'B_IU_SR_SURG_PERIOD',
                        'B_IUD_ADVANCED_INPUT_FIELD',
                        'B_IUD_ACTION',
                        'B_IUD_ALLERGY',
                        'B_IUD_ANALYSIS',
                        'B_IUD_ANALYSIS_ALIAS',
                        'B_IUD_ANALYSIS_DESC',
                        'B_IUD_ANALYSIS_GROUP',
                        'B_IUD_ANALYSIS_PARAMETER',
                        'B_IUD_AUDIT_CRITERIA',
                        'B_IUD_AUDIT_TYPE',
                        'B_IUD_BED',
                        'B_IUD_BIBLIOGRAPHY_CONT_TYPE',
                        'B_IUD_BODY_PART',
                        'B_IUD_BUILDING',
                        'B_IUD_CALC_FIELD',
                        'B_IUD_CATEGORY',
                        'B_IUD_CHILD_FEED_DEV',
                        'B_IUD_CITY',
                        'B_IUD_CLINICAL_SERVICE',
                        'B_IUD_COMPLAINT',
                        'B_IUD_CONF_BUTTON_BLOCK',
                        'B_IUD_CONTRACEPTIVE',
                        'B_IUD_COUNTRY',
                        'B_IUD_CRITERIA',
                        'B_IUD_CRITICAL_CARE',
                        'B_IUD_DRUG_PHARMA_CLASS',
                        'B_IUD_FAST_TRACK',
                        'B_IUD_SUPPLIES',
                        'B_IU_BODY_SIDE',
                        'B_IU_CATEGORY_SUB',
                        'B_IUD_DRUG_FORM',
                        'B_IUD_DRUG_JUSTIFICATION',
                        'B_IUD_DRUG_PHARMA',
                        'B_IUD_DRUG_PLAN',
                        'B_IUD_DRUG_POSOLOGIA',
                        'B_IUD_DRUG_ROUTE',
                        'B_IUD_DRUG_TAKE_TIME',
                        'B_IUD_EBM',
                        'B_IUD_EHR_ACCESS_CONTEXT',
                        'B_IUD_EPIS_TYPE',
                        'B_IUD_EXAM',
                        'B_IUD_EXAM_ALIAS',
                        'B_IUD_EXAM_CAT',
                        'B_IUD_EXAM_GROUP',
                        'B_IUD_EXTERNAL_CAUSE',
                        'B_IUD_FAMILY_RELATIONSHIP',
                        'B_IUD_FLOORS',
                        'B_IUD_FOLLOW_UP_TYPE',
                        'B_IUD_GEO_LOCATION',
                        'B_IUD_GINEC_OBSTET',
                        'B_IUD_GRAFFAR_CRITERIA',
                        'B_IUD_GRAFFAR_CRIT_VALUE',
                        'B_IUD_GRAPHIC',
                        'B_IUD_GRAPH_SCALE',
                        'B_IUD_GUIDELINE_CRITERIA_TYPE',
                        'B_IUD_GUIDELINE_TYPE',
                        'B_IUD_TRIAGE_CONSIDERATIONS',
                        'B_IUD_TRIAGE_DISC_HELP',
                        'B_IUD_TRIAGE_DISCRIMINATOR',
                        'B_IUD_TRIAGE_NURSE',
                        'B_IUD_TRIAGE_TYPE',
                        'B_IUD_TRIAGE_UNITS',
                        'B_IUD_TRIAGE_WHITE_REASON',
                        'B_IUD_UNIT_MEASURE',
                        'B_IUD_UNIT_MEASURE_ENUM',
                        'B_IUD_UNITS',
                        'B_IUD_VACC',
                        'B_IUD_VACCINE',
                        'B_IUD_VITAL_SIGN',
                        'B_IUD_VITAL_SIGN_ALIAS',
                        'B_IUD_VITAL_SIGN_DESC',
                        'B_IUD_WOUND_CHARAC',
                        'B_IUD_WOUND_TYPE',
                        'B_IUD_SAMPLE_TEXT',
                        'B_IUD_SAMPLE_RECIPIENT',
                        'B_IUD_SAMPLE_TEXT_TYPE',
                        'B_IUD_SAMPLE_TYPE',
                        'B_IUD_SCALES',
                        'B_IUD_SCALES_CLASS',
                        'B_IUD_SCH_AUTOPICK_CRIT',
                        'B_IUD_SCH_CANCEL_REASON',
                        'B_IUD_SCH_DEP_TYPE',
                        'B_IUD_SCH_DEP_TYPE_SUB',
                        'B_IUD_SCH_EVENT',
                        'B_IUD_SCH_EVENT_ABRV',
                        'B_IUD_SOCIAL_CLASS',
                        'B_IUD_SOCIAL_DIAGNOSIS',
                        'B_IUD_SOCIAL_INTERVENTION',
                        'B_IUD_SPECIALITY',
                        'B_IUD_SR_EVAL_SUMM',
                        'B_IUD_SR_EVAL_TYPE',
                        'B_IUD_SR_INTERV_GROUP',
                        'B_IUD_SUMMARY_PAGE',
                        'B_IUD_SYS_ALERT',
                        'B_IUD_SYS_ALERT_TYPE',
                        'B_IUD_SYS_BUTTON',
                        'B_IUD_SYS_BUTTON_IN',
                        'B_IUD_SYS_BUTTON_PROP',
                        'B_IUD_SYS_FUNCTIONALITY',
                        'B_IUD_SYSTEM_APPARATI',
                        'B_IUD_SYS_TIME_EVENT_GROUP',
                        'B_IUD_TASK_TYPE',
                        'B_IUD_THERAPEUTIC_PROTOCOLS',
                        'B_IUD_TIME_UNIT',
                        'B_IUD_TL_SCALE',
                        'B_IUD_TL_TIMELINE',
                        'B_IUD_TRANSFER_OPTION',
                        'B_IUD_TRANSP_ENTITY',
                        'B_IUD_TRANSPORT_TYPE',
                        'B_IUD_TRIAGE_BOARD',
                        'B_IUD_TRIAGE_BOARD_GROUP',
                        'B_IUD_TRIAGE_COLOR',
                        'B_UID_DIETARY_DRUG',
                        'B_UID_IMPLEMENTATION',
                        'B_UID_INGREDIENT',
                        'B_UID_MANIPULATED',
                        'B_IUD_ALERT_DIAGNOSIS',
                        'B_IUD_DIAGNOSIS',
                        'B_IUD_CDR_TYPE',
                        'B_IUD_CDR_SEVERITY',
                        'B_IUD_CDR_MESSAGE',
                        'B_IUD_CDR_INSTANCE',
                        'B_IUD_CDR_DEFINITION',
                        'B_IUD_CDR_CONDITION',
                        'B_IUD_CDR_CONCEPT',
                        'B_IUD_CDR_ACTION',
                        'B_IUD_REPORTS_SECTION',
                        'B_IUD_PN_DATA_BLOCK',
                        'B_IUD_DEPARTMENT',
                        'B_IUD_DEPT',
                        'B_IUD_DIAGRAM_TOOLS_GROUP',
                        'B_IUD_DIET',
                        'B_IUD_DIET_SCHEDULE',
                        'B_IUD_DISCHARGE_DEST',
                        'B_IUD_DISCHARGE_REASON',
                        'B_IUD_DISCHARGE_STATUS',
                        'B_IUD_DISCH_INSTRUCTIONS',
                        'B_IUD_DISCH_INSTRUCTIONS_GROUP',
                        'B_IUD_DISTRICT',
                        'B_IUD_DOC_AREA_SOFTWARE',
                        'B_IUD_DOC_DESTINATION',
                        'B_IUD_DOC_FILE_TYPE',
                        'B_IUD_DOC_ORIGINAL',
                        'B_IUD_CURRENCY',
                        'B_IUD_DOC_ORI_TYPE',
                        'B_IUD_DOC_SPECIFICATION',
                        'B_IUD_DOC_TYPE',
                        'B_IUD_DRUG',
                        'B_IUD_DRUG_BRAND',
                        'B_IUD_DRUG_DESPACHOS',
                        'B_IUD_DRUG_DRIP',
                        'B_IUD_HABIT',
                        'B_IUD_HEALTH_PLAN',
                        'B_IUD_HEALTH_PROGRAM',
                        'B_IUD_HEMO_TYPE',
                        'B_IU_DIAGRAM_IMAGE',
                        'B_IU_DIAGRAM_LAYOUT',
                        'B_IUD_ICF',
                        'B_IUD_ICNP_AXIS',
                        'B_IUD_ICNP_COMPO_FOLDER',
                        'B_IUD_ICNP_COMPOSITION',
                        'B_IUD_ICNP_TERM',
                        'B_IUD_INSTITUTION',
                        'B_IUD_INST_TYPE',
                        'B_IUD_INTERVENTION',
                        'B_IUD_INTERVENTION_ALIAS',
                        'B_IUD_INTERV_PHYSIATRY_AREA',
                        'B_IUD_IV_FLUIDS_GROUP',
                        'B_IUD_LOCATION',
                        'B_IUD_VACC_TYPE_GROUP',
                        'B_IUD_UNIT_MEASURE_SUBTYPE',
                        'B_IUD_UNIT_MEASURE_TYPE',
                        'A_D_GEO_STATE',
                        'B_IUD_NECESSITY',
                        'B_IUD_NOTES_CONFIG',
                        'B_IUD_OPINION_TYPE',
                        'B_IUD_ORDER_TYPE',
                        'B_IUD_PAT_HISTORY_TYPE',
                        'B_IUD_PERIODIC_EXAM_EDUC',
                        'B_IUD_PERIOD_OBS_DESC',
                        'B_IUD_PERIOD_OBS_PARAM',
                        'B_IUD_PHYSIATRY_AREA',
                        'B_IUD_PLANT',
                        'B_IUD_LOCATION_TAX',
                        'B_IUD_POSITIONING',
                        'B_IUD_POSITIONING_TYPE',
                        'B_IUD_PREGNANCY_RISK_EVAL',
                        'B_IUD_PREP_MESSAGE',
                        'B_IUD_PRESCRIPTION_TYPE',
                        'B_IUD_PROFILE_TEMPLATE',
                        'B_IUD_PROTOCOL_CRITERIA_TYPE',
                        'B_IUD_PROTOCOLS',
                        'B_IUD_PROTOCOL_TYPE',
                        'B_IUD_P1_DATA_EXPORT_CONFIG',
                        'B_IUD_P1_REASON_CODE',
                        'B_IUD_P1_SPEC_HELP',
                        'B_IUD_P1_SPECIALITY',
                        'B_IUD_P1_TASK',
                        'B_IUD_REASON_ENC',
                        'B_IUD_RECM',
                        'B_IUD_RECORDS_REVIEW',
                        'B_IUD_RELATION_SERVICE',
                        'B_IUD_RELATION_TYPE',
                        'B_IUD_REP_DESTINATION',
                        'B_IUD_REPORTS',
                        'B_IUD_RISK_FACTOR_HELP',
                        'B_IUD_ROOM',
                        'B_IU_SYSTEM_ORGAN',
                        'B_IUD_SUMMARY_PAGE_SECTION',
                        'B_IU_BODY_LAYER',
                        'B_IUD_CDR_ANSWER'
                        );

k_placeholder   constant varchar2(0050)      := '#TRIGGER#';
k_sql           constant varchar2(1000 char) := 'drop trigger '||k_placeholder;
l_execute       varchar2(1000 char);

err_obj_does_not_exist  exception;
pragma exception_init( err_obj_does_not_exist, -04080 );

begin
    
        <<LOOP_THRU_ARRAY>>
        for i in 1..my_trg.count loop

                begin
                    
                l_execute := replace ( k_sql, k_placeholder, my_trg(i) );
                --dbms_output.put_line( l_execute );
                execute immediate l_execute;
                
                exception 
                when err_obj_does_not_exist then
                    dbms_output.put_line('Trigger '||my_trg(i)||' does not exist...continuing...l');
                end;
    
        end loop;
    
end;
/


-- CMF 28-12-2012
--cmf 18-12-2012
declare

my_trg      table_varchar := table_varchar
                        (
                        'B_IUD_MATERIAL',
                        'B_IUD_CARE_PLAN_TYPE',
                        'B_IU_SR_EQUIP',
                        'B_IU_SR_INTERVENTION',
                        'B_IU_SR_PROF_SHIFT',
                        'B_IU_SR_SURGERY_TIME',
                        'B_IU_SR_SURG_PERIOD',
                        'B_IUD_ADVANCED_INPUT_FIELD',
                        'B_IUD_ACTION',
                        'B_IUD_ALLERGY',
                        'B_IUD_ANALYSIS',
                        'B_IUD_ANALYSIS_ALIAS',
                        'B_IUD_ANALYSIS_DESC',
                        'B_IUD_ANALYSIS_GROUP',
                        'B_IUD_ANALYSIS_PARAMETER',
                        'B_IUD_AUDIT_CRITERIA',
                        'B_IUD_AUDIT_TYPE',
                        'B_IUD_BED',
                        'B_IUD_BIBLIOGRAPHY_CONT_TYPE',
                        'B_IUD_BODY_PART',
                        'B_IUD_BUILDING',
                        'B_IUD_CALC_FIELD',
                        'B_IUD_CATEGORY',
                        'B_IUD_CHILD_FEED_DEV',
                        'B_IUD_CITY',
                        'B_IUD_CLINICAL_SERVICE',
                        'B_IUD_COMPLAINT',
                        'B_IUD_CONF_BUTTON_BLOCK',
                        'B_IUD_CONTRACEPTIVE',
                        'B_IUD_COUNTRY',
                        'B_IUD_CRITERIA',
                        'B_IUD_CRITICAL_CARE',
                        'B_IUD_DRUG_PHARMA_CLASS',
                        'B_IUD_FAST_TRACK',
                        'B_IUD_SUPPLIES',
                        'B_IU_BODY_SIDE',
                        'B_IU_CATEGORY_SUB',
                        'B_IUD_DRUG_FORM',
                        'B_IUD_DRUG_JUSTIFICATION',
                        'B_IUD_DRUG_PHARMA',
                        'B_IUD_DRUG_PLAN',
                        'B_IUD_DRUG_POSOLOGIA',
                        'B_IUD_DRUG_ROUTE',
                        'B_IUD_DRUG_TAKE_TIME',
                        'B_IUD_EBM',
                        'B_IUD_EHR_ACCESS_CONTEXT',
                        'B_IUD_EPIS_TYPE',
                        'B_IUD_EXAM',
                        'B_IUD_EXAM_ALIAS',
                        'B_IUD_EXAM_CAT',
                        'B_IUD_EXAM_GROUP',
                        'B_IUD_EXTERNAL_CAUSE',
                        'B_IUD_FAMILY_RELATIONSHIP',
                        'B_IUD_FLOORS',
                        'B_IUD_FOLLOW_UP_TYPE',
                        'B_IUD_GEO_LOCATION',
                        'B_IUD_GINEC_OBSTET',
                        'B_IUD_GRAFFAR_CRITERIA',
                        'B_IUD_GRAFFAR_CRIT_VALUE',
                        'B_IUD_GRAPHIC',
                        'B_IUD_GRAPH_SCALE',
                        'B_IUD_GUIDELINE_CRITERIA_TYPE',
                        'B_IUD_GUIDELINE_TYPE',
                        'B_IUD_TRIAGE_CONSIDERATIONS',
                        'B_IUD_TRIAGE_DISC_HELP',
                        'B_IUD_TRIAGE_DISCRIMINATOR',
                        'B_IUD_TRIAGE_NURSE',
                        'B_IUD_TRIAGE_TYPE',
                        'B_IUD_TRIAGE_UNITS',
                        'B_IUD_TRIAGE_WHITE_REASON',
                        'B_IUD_UNIT_MEASURE',
                        'B_IUD_UNIT_MEASURE_ENUM',
                        'B_IUD_UNITS',
                        'B_IUD_VACC',
                        'B_IUD_VACCINE',
                        'B_IUD_VITAL_SIGN',
                        'B_IUD_VITAL_SIGN_ALIAS',
                        'B_IUD_VITAL_SIGN_DESC',
                        'B_IUD_WOUND_CHARAC',
                        'B_IUD_WOUND_TYPE',
                        'B_IUD_SAMPLE_TEXT',
                        'B_IUD_SAMPLE_RECIPIENT',
                        'B_IUD_SAMPLE_TEXT_TYPE',
                        'B_IUD_SAMPLE_TYPE',
                        'B_IUD_SCALES',
                        'B_IUD_SCALES_CLASS',
                        'B_IUD_SCH_AUTOPICK_CRIT',
                        'B_IUD_SCH_CANCEL_REASON',
                        'B_IUD_SCH_DEP_TYPE',
                        'B_IUD_SCH_DEP_TYPE_SUB',
                        'B_IUD_SCH_EVENT',
                        'B_IUD_SCH_EVENT_ABRV',
                        'B_IUD_SOCIAL_CLASS',
                        'B_IUD_SOCIAL_DIAGNOSIS',
                        'B_IUD_SOCIAL_INTERVENTION',
                        'B_IUD_SPECIALITY',
                        'B_IUD_SR_EVAL_SUMM',
                        'B_IUD_SR_EVAL_TYPE',
                        'B_IUD_SR_INTERV_GROUP',
                        'B_IUD_SUMMARY_PAGE',
                        'B_IUD_SYS_ALERT',
                        'B_IUD_SYS_ALERT_TYPE',
                        'B_IUD_SYS_BUTTON',
                        'B_IUD_SYS_BUTTON_IN',
                        'B_IUD_SYS_BUTTON_PROP',
                        'B_IUD_SYS_FUNCTIONALITY',
                        'B_IUD_SYSTEM_APPARATI',
                        'B_IUD_SYS_TIME_EVENT_GROUP',
                        'B_IUD_TASK_TYPE',
                        'B_IUD_THERAPEUTIC_PROTOCOLS',
                        'B_IUD_TIME_UNIT',
                        'B_IUD_TL_SCALE',
                        'B_IUD_TL_TIMELINE',
                        'B_IUD_TRANSFER_OPTION',
                        'B_IUD_TRANSP_ENTITY',
                        'B_IUD_TRANSPORT_TYPE',
                        'B_IUD_TRIAGE_BOARD',
                        'B_IUD_TRIAGE_BOARD_GROUP',
                        'B_IUD_TRIAGE_COLOR',
                        'B_UID_DIETARY_DRUG',
                        'B_UID_IMPLEMENTATION',
                        'B_UID_INGREDIENT',
                        'B_UID_MANIPULATED',
                        'B_IUD_ALERT_DIAGNOSIS',
                        'B_IUD_DIAGNOSIS',
                        'B_IUD_CDR_TYPE',
                        'B_IUD_CDR_SEVERITY',
                        'B_IUD_CDR_MESSAGE',
                        'B_IUD_CDR_INSTANCE',
                        'B_IUD_CDR_DEFINITION',
                        'B_IUD_CDR_CONDITION',
                        'B_IUD_CDR_CONCEPT',
                        'B_IUD_CDR_ACTION',
                        'B_IUD_REPORTS_SECTION',
                        'B_IUD_PN_DATA_BLOCK',
                        'B_IUD_DEPARTMENT',
                        'B_IUD_DEPT',
                        'B_IUD_DIAGRAM_TOOLS_GROUP',
                        'B_IUD_DIET',
                        'B_IUD_DIET_SCHEDULE',
                        'B_IUD_DISCHARGE_DEST',
                        'B_IUD_DISCHARGE_REASON',
                        'B_IUD_DISCHARGE_STATUS',
                        'B_IUD_DISCH_INSTRUCTIONS',
                        'B_IUD_DISCH_INSTRUCTIONS_GROUP',
                        'B_IUD_DISTRICT',
                        'B_IUD_DOC_AREA_SOFTWARE',
                        'B_IUD_DOC_DESTINATION',
                        'B_IUD_DOC_FILE_TYPE',
                        'B_IUD_DOC_ORIGINAL',
                        'B_IUD_CURRENCY',
                        'B_IUD_DOC_ORI_TYPE',
                        'B_IUD_DOC_SPECIFICATION',
                        'B_IUD_DOC_TYPE',
                        'B_IUD_DRUG',
                        'B_IUD_DRUG_BRAND',
                        'B_IUD_DRUG_DESPACHOS',
                        'B_IUD_DRUG_DRIP',
                        'B_IUD_HABIT',
                        'B_IUD_HEALTH_PLAN',
                        'B_IUD_HEALTH_PROGRAM',
                        'B_IUD_HEMO_TYPE',
                        'B_IU_DIAGRAM_IMAGE',
                        'B_IU_DIAGRAM_LAYOUT',
                        'B_IUD_ICF',
                        'B_IUD_ICNP_AXIS',
                        'B_IUD_ICNP_COMPO_FOLDER',
                        'B_IUD_ICNP_COMPOSITION',
                        'B_IUD_ICNP_TERM',
                        'B_IUD_INSTITUTION',
                        'B_IUD_INST_TYPE',
                        'B_IUD_INTERVENTION',
                        'B_IUD_INTERVENTION_ALIAS',
                        'B_IUD_INTERV_PHYSIATRY_AREA',
                        'B_IUD_IV_FLUIDS_GROUP',
                        'B_IUD_LOCATION',
                        'B_IUD_VACC_TYPE_GROUP',
                        'B_IUD_UNIT_MEASURE_SUBTYPE',
                        'B_IUD_UNIT_MEASURE_TYPE',
                        'A_D_GEO_STATE',
                        'B_IUD_NECESSITY',
                        'B_IUD_NOTES_CONFIG',
                        'B_IUD_OPINION_TYPE',
                        'B_IUD_ORDER_TYPE',
                        'B_IUD_PAT_HISTORY_TYPE',
                        'B_IUD_PERIODIC_EXAM_EDUC',
                        'B_IUD_PERIOD_OBS_DESC',
                        'B_IUD_PERIOD_OBS_PARAM',
                        'B_IUD_PHYSIATRY_AREA',
                        'B_IUD_PLANT',
                        'B_IUD_LOCATION_TAX',
                        'B_IUD_POSITIONING',
                        'B_IUD_POSITIONING_TYPE',
                        'B_IUD_PREGNANCY_RISK_EVAL',
                        'B_IUD_PREP_MESSAGE',
                        'B_IUD_PRESCRIPTION_TYPE',
                        'B_IUD_PROFILE_TEMPLATE',
                        'B_IUD_PROTOCOL_CRITERIA_TYPE',
                        'B_IUD_PROTOCOLS',
                        'B_IUD_PROTOCOL_TYPE',
                        'B_IUD_P1_DATA_EXPORT_CONFIG',
                        'B_IUD_P1_REASON_CODE',
                        'B_IUD_P1_SPEC_HELP',
                        'B_IUD_P1_SPECIALITY',
                        'B_IUD_P1_TASK',
                        'B_IUD_REASON_ENC',
                        'B_IUD_RECM',
                        'B_IUD_RECORDS_REVIEW',
                        'B_IUD_RELATION_SERVICE',
                        'B_IUD_RELATION_TYPE',
                        'B_IUD_REP_DESTINATION',
                        'B_IUD_REPORTS',
                        'B_IUD_RISK_FACTOR_HELP',
                        'B_IUD_ROOM',
                        'B_IU_SYSTEM_ORGAN',
                        'B_IUD_SUMMARY_PAGE_SECTION',
                        'B_IU_BODY_LAYER',
                        'B_IUD_CDR_ANSWER'
                        );

k_placeholder   constant varchar2(0050)      := '#TRIGGER#';
k_sql           constant varchar2(1000 char) := 'drop trigger '||k_placeholder;
l_execute       varchar2(1000 char);

err_obj_does_not_exist  exception;
pragma exception_init( err_obj_does_not_exist, -04080 );

begin
    
        <<LOOP_THRU_ARRAY>>
        for i in 1..my_trg.count loop

                begin
                    
                l_execute := replace ( k_sql, k_placeholder, my_trg(i) );
                --dbms_output.put_line( l_execute );
                execute immediate l_execute;
                
                exception 
                when err_obj_does_not_exist then
                    dbms_output.put_line('Trigger '||my_trg(i)||' does not exist...continuing...l');
                end;
    
        end loop;
    
end;
/



-- 28-12-2012
declare

my_trg      table_varchar := table_varchar
                        (
                        'B_IUD_MATERIAL',
                        'B_IUD_CARE_PLAN_TYPE',
                        'B_IU_SR_EQUIP',
                        'B_IU_SR_INTERVENTION',
                        'B_IU_SR_PROF_SHIFT',
                        'B_IU_SR_SURGERY_TIME',
                        'B_IU_SR_SURG_PERIOD',
                        'B_IUD_ADVANCED_INPUT_FIELD',
                        'B_IUD_ACTION',
                        'B_IUD_ALLERGY',
                        'B_IUD_ANALYSIS',
                        'B_IUD_ANALYSIS_ALIAS',
                        'B_IUD_ANALYSIS_DESC',
                        'B_IUD_ANALYSIS_GROUP',
                        'B_IUD_ANALYSIS_PARAMETER',
                        'B_IUD_AUDIT_CRITERIA',
                        'B_IUD_AUDIT_TYPE',
                        'B_IUD_BED',
                        'B_IUD_BIBLIOGRAPHY_CONT_TYPE',
                        'B_IUD_BODY_PART',
                        'B_IUD_BUILDING',
                        'B_IUD_CALC_FIELD',
                        'B_IUD_CATEGORY',
                        'B_IUD_CHILD_FEED_DEV',
                        'B_IUD_CITY',
                        'B_IUD_CLINICAL_SERVICE',
                        'B_IUD_COMPLAINT',
                        'B_IUD_CONF_BUTTON_BLOCK',
                        'B_IUD_CONTRACEPTIVE',
                        'B_IUD_COUNTRY',
                        'B_IUD_CRITERIA',
                        'B_IUD_CRITICAL_CARE',
                        'B_IUD_DRUG_PHARMA_CLASS',
                        'B_IUD_FAST_TRACK',
                        'B_IUD_SUPPLIES',
                        'B_IU_BODY_SIDE',
                        'B_IU_CATEGORY_SUB',
                        'B_IUD_DRUG_FORM',
                        'B_IUD_DRUG_JUSTIFICATION',
                        'B_IUD_DRUG_PHARMA',
                        'B_IUD_DRUG_PLAN',
                        'B_IUD_DRUG_POSOLOGIA',
                        'B_IUD_DRUG_ROUTE',
                        'B_IUD_DRUG_TAKE_TIME',
                        'B_IUD_EBM',
                        'B_IUD_EHR_ACCESS_CONTEXT',
                        'B_IUD_EPIS_TYPE',
                        'B_IUD_EXAM',
                        'B_IUD_EXAM_ALIAS',
                        'B_IUD_EXAM_CAT',
                        'B_IUD_EXAM_GROUP',
                        'B_IUD_EXTERNAL_CAUSE',
                        'B_IUD_FAMILY_RELATIONSHIP',
                        'B_IUD_FLOORS',
                        'B_IUD_FOLLOW_UP_TYPE',
                        'B_IUD_GEO_LOCATION',
                        'B_IUD_GINEC_OBSTET',
                        'B_IUD_GRAFFAR_CRITERIA',
                        'B_IUD_GRAFFAR_CRIT_VALUE',
                        'B_IUD_GRAPHIC',
                        'B_IUD_GRAPH_SCALE',
                        'B_IUD_GUIDELINE_CRITERIA_TYPE',
                        'B_IUD_GUIDELINE_TYPE',
                        'B_IUD_TRIAGE_CONSIDERATIONS',
                        'B_IUD_TRIAGE_DISC_HELP',
                        'B_IUD_TRIAGE_DISCRIMINATOR',
                        'B_IUD_TRIAGE_NURSE',
                        'B_IUD_TRIAGE_TYPE',
                        'B_IUD_TRIAGE_UNITS',
                        'B_IUD_TRIAGE_WHITE_REASON',
                        'B_IUD_UNIT_MEASURE',
                        'B_IUD_UNIT_MEASURE_ENUM',
                        'B_IUD_UNITS',
                        'B_IUD_VACC',
                        'B_IUD_VACCINE',
                        'B_IUD_VITAL_SIGN',
                        'B_IUD_VITAL_SIGN_ALIAS',
                        'B_IUD_VITAL_SIGN_DESC',
                        'B_IUD_WOUND_CHARAC',
                        'B_IUD_WOUND_TYPE',
                        'B_IUD_SAMPLE_TEXT',
                        'B_IUD_SAMPLE_RECIPIENT',
                        'B_IUD_SAMPLE_TEXT_TYPE',
                        'B_IUD_SAMPLE_TYPE',
                        'B_IUD_SCALES',
                        'B_IUD_SCALES_CLASS',
                        'B_IUD_SCH_AUTOPICK_CRIT',
                        'B_IUD_SCH_CANCEL_REASON',
                        'B_IUD_SCH_DEP_TYPE',
                        'B_IUD_SCH_DEP_TYPE_SUB',
                        'B_IUD_SCH_EVENT',
                        'B_IUD_SCH_EVENT_ABRV',
                        'B_IUD_SOCIAL_CLASS',
                        'B_IUD_SOCIAL_DIAGNOSIS',
                        'B_IUD_SOCIAL_INTERVENTION',
                        'B_IUD_SPECIALITY',
                        'B_IUD_SR_EVAL_SUMM',
                        'B_IUD_SR_EVAL_TYPE',
                        'B_IUD_SR_INTERV_GROUP',
                        'B_IUD_SUMMARY_PAGE',
                        'B_IUD_SYS_ALERT',
                        'B_IUD_SYS_ALERT_TYPE',
                        'B_IUD_SYS_BUTTON',
                        'B_IUD_SYS_BUTTON_IN',
                        'B_IUD_SYS_BUTTON_PROP',
                        'B_IUD_SYS_FUNCTIONALITY',
                        'B_IUD_SYSTEM_APPARATI',
                        'B_IUD_SYS_TIME_EVENT_GROUP',
                        'B_IUD_TASK_TYPE',
                        'B_IUD_THERAPEUTIC_PROTOCOLS',
                        'B_IUD_TIME_UNIT',
                        'B_IUD_TL_SCALE',
                        'B_IUD_TL_TIMELINE',
                        'B_IUD_TRANSFER_OPTION',
                        'B_IUD_TRANSP_ENTITY',
                        'B_IUD_TRANSPORT_TYPE',
                        'B_IUD_TRIAGE_BOARD',
                        'B_IUD_TRIAGE_BOARD_GROUP',
                        'B_IUD_TRIAGE_COLOR',
                        'B_UID_DIETARY_DRUG',
                        'B_UID_IMPLEMENTATION',
                        'B_UID_INGREDIENT',
                        'B_UID_MANIPULATED',
                        'B_IUD_ALERT_DIAGNOSIS',
                        'B_IUD_DIAGNOSIS',
                        'B_IUD_CDR_TYPE',
                        'B_IUD_CDR_SEVERITY',
                        'B_IUD_CDR_MESSAGE',
                        'B_IUD_CDR_INSTANCE',
                        'B_IUD_CDR_DEFINITION',
                        'B_IUD_CDR_CONDITION',
                        'B_IUD_CDR_CONCEPT',
                        'B_IUD_CDR_ACTION',
                        'B_IUD_REPORTS_SECTION',
                        'B_IUD_PN_DATA_BLOCK',
                        'B_IUD_DEPARTMENT',
                        'B_IUD_DEPT',
                        'B_IUD_DIAGRAM_TOOLS_GROUP',
                        'B_IUD_DIET',
                        'B_IUD_DIET_SCHEDULE',
                        'B_IUD_DISCHARGE_DEST',
                        'B_IUD_DISCHARGE_REASON',
                        'B_IUD_DISCHARGE_STATUS',
                        'B_IUD_DISCH_INSTRUCTIONS',
                        'B_IUD_DISCH_INSTRUCTIONS_GROUP',
                        'B_IUD_DISTRICT',
                        'B_IUD_DOC_AREA_SOFTWARE',
                        'B_IUD_DOC_DESTINATION',
                        'B_IUD_DOC_FILE_TYPE',
                        'B_IUD_DOC_ORIGINAL',
                        'B_IUD_CURRENCY',
                        'B_IUD_DOC_ORI_TYPE',
                        'B_IUD_DOC_SPECIFICATION',
                        'B_IUD_DOC_TYPE',
                        'B_IUD_DRUG',
                        'B_IUD_DRUG_BRAND',
                        'B_IUD_DRUG_DESPACHOS',
                        'B_IUD_DRUG_DRIP',
                        'B_IUD_HABIT',
                        'B_IUD_HEALTH_PLAN',
                        'B_IUD_HEALTH_PROGRAM',
                        'B_IUD_HEMO_TYPE',
                        'B_IU_DIAGRAM_IMAGE',
                        'B_IU_DIAGRAM_LAYOUT',
                        'B_IUD_ICF',
                        'B_IUD_ICNP_AXIS',
                        'B_IUD_ICNP_COMPO_FOLDER',
                        'B_IUD_ICNP_COMPOSITION',
                        'B_IUD_ICNP_TERM',
                        'B_IUD_INSTITUTION',
                        'B_IUD_INST_TYPE',
                        'B_IUD_INTERVENTION',
                        'B_IUD_INTERVENTION_ALIAS',
                        'B_IUD_INTERV_PHYSIATRY_AREA',
                        'B_IUD_IV_FLUIDS_GROUP',
                        'B_IUD_LOCATION',
                        'B_IUD_VACC_TYPE_GROUP',
                        'B_IUD_UNIT_MEASURE_SUBTYPE',
                        'B_IUD_UNIT_MEASURE_TYPE',
                        'A_D_GEO_STATE',
                        'B_IUD_NECESSITY',
                        'B_IUD_NOTES_CONFIG',
                        'B_IUD_OPINION_TYPE',
                        'B_IUD_ORDER_TYPE',
                        'B_IUD_PAT_HISTORY_TYPE',
                        'B_IUD_PERIODIC_EXAM_EDUC',
                        'B_IUD_PERIOD_OBS_DESC',
                        'B_IUD_PERIOD_OBS_PARAM',
                        'B_IUD_PHYSIATRY_AREA',
                        'B_IUD_PLANT',
                        'B_IUD_LOCATION_TAX',
                        'B_IUD_POSITIONING',
                        'B_IUD_POSITIONING_TYPE',
                        'B_IUD_PREGNANCY_RISK_EVAL',
                        'B_IUD_PREP_MESSAGE',
                        'B_IUD_PRESCRIPTION_TYPE',
                        'B_IUD_PROFILE_TEMPLATE',
                        'B_IUD_PROTOCOL_CRITERIA_TYPE',
                        'B_IUD_PROTOCOLS',
                        'B_IUD_PROTOCOL_TYPE',
                        'B_IUD_P1_DATA_EXPORT_CONFIG',
                        'B_IUD_P1_REASON_CODE',
                        'B_IUD_P1_SPEC_HELP',
                        'B_IUD_P1_SPECIALITY',
                        'B_IUD_P1_TASK',
                        'B_IUD_REASON_ENC',
                        'B_IUD_RECM',
                        'B_IUD_RECORDS_REVIEW',
                        'B_IUD_RELATION_SERVICE',
                        'B_IUD_RELATION_TYPE',
                        'B_IUD_REP_DESTINATION',
                        'B_IUD_REPORTS',
                        'B_IUD_RISK_FACTOR_HELP',
                        'B_IUD_ROOM',
                        'B_IU_SYSTEM_ORGAN',
                        'B_IUD_SUMMARY_PAGE_SECTION',
                        'B_IU_BODY_LAYER',
                        'B_IUD_CDR_ANSWER'
                        );

k_placeholder   constant varchar2(0050)      := '#TRIGGER#';
k_sql           constant varchar2(1000 char) := 'drop trigger '||k_placeholder;
l_execute       varchar2(1000 char);

err_obj_does_not_exist  exception;
pragma exception_init( err_obj_does_not_exist, -04080 );

begin
    
        <<LOOP_THRU_ARRAY>>
        for i in 1..my_trg.count loop

                begin
                    
                l_execute := replace ( k_sql, k_placeholder, my_trg(i) );
                --dbms_output.put_line( l_execute );
                execute immediate l_execute;
                
                exception 
                when err_obj_does_not_exist then
                    dbms_output.put_line('Trigger '||my_trg(i)||' does not exist...continuing...l');
                end;
    
        end loop;
    
end;
/
