
@@table_number.syn
@@table_varchar.syn
@@adverse_exam_allergy.syn
@@matr_scheduled.syn
@@matr_room.syn
@@matr_dep_clin_serv.syn
@@material_type.syn
@@material_req_det.syn
@@material_req.syn
@@material_protocols.syn
@@material.syn
@@manchester.syn
@@language.syn

@@java$options.syn
@@java$class$md5$table.syn
@@isencao.syn
@@interv_room.syn
@@interv_protocols.syn
@@interv_presc_plan.syn
@@interv_presc_det.syn
@@interv_prescription.syn
@@interv_prep_msg.syn
@@interv_physiatry_area.syn
@@interv_ext_sys.syn
@@interv_drug.syn
@@interv_dep_clin_serv.syn

@@intervention.syn
@@instit_ext_sys.syn
@@institution.syn
@@implementation.syn
@@icnp_term.syn
@@icnp_relationship.syn
@@icnp_predefined_action.syn
@@icnp_morph.syn
@@icnp_folder.syn
@@icnp_epis_interv_plan.syn
@@icnp_epis_intervention.syn
@@icnp_epis_diag_interv.syn
@@icnp_epis_diagnosis.syn

@@icnp_dictionary.syn
@@icnp_compo_inst.syn
@@icnp_compo_folder.syn
@@icnp_composition_term.syn
@@icnp_composition.syn
@@icnp_classification.syn
@@icnp_axis.syn
@@home.syn
@@hemo_type.syn
@@hemo_req_supply.syn
@@hemo_req_det.syn
@@hemo_req.syn
@@hemo_protocols.syn

@@health_plan.syn
@@harvest.syn
@@habit.syn
@@grid_task.syn
@@ginec_obstet.syn
@@external_sys.syn
@@external_cause.syn
@@exam_room.syn
@@exam_result.syn
@@exam_req_ext_sys.syn
@@exam_req_det.syn
@@exam_req.syn
@@exam_protocols.syn

@@exam_prep_mesg.syn
@@exam_group.syn
@@exam_ext_sys.syn
@@exam_egp.syn
@@exam_drug.syn
@@exam_dep_clin_serv.syn
@@exam.syn
@@event.syn
@@estate.syn
@@epis_type_room.syn
@@epis_type.syn
@@sr_interv_desc.syn
@@sr_epis_interv_desc.syn

@@sr_chklist_det.syn
@@sr_chklist.syn
@@sr_cancel_reason.syn
@@sqln_explain_plan.syn
@@spec_sys_appar.syn
@@speciality.syn
@@soft_inst_services.syn
@@soft_inst_impl.syn
@@software_institution.syn
@@software.syn
@@snomed_relationships.syn
@@snomed_descriptions.syn
@@snomed_concepts.syn

@@slot.syn
@@serv_sched_access.syn
@@sch_service.syn
@@sch_resource.syn
@@sch_prof_outp.syn
@@sch_group.syn
@@school.syn
@@scholarship.syn
@@schedule_sr2.syn
@@schedule_sr.syn
@@schedule_outp.syn
@@schedule_alter.syn
@@schedule.syn

@@sample_type.syn
@@sample_text_type_cat.syn
@@sample_text_type.syn
@@sample_text_prof.syn
@@sample_text_freq.syn
@@sample_text.syn
@@sample_recipient.syn
@@room_scheduled.syn
@@room_ext_sys.syn
@@room_dep_clin_serv.syn
@@room.syn
@@religion.syn
@@rb_grid_doctor.syn

@@quest_temp_explain.syn
@@quest_sl_temp_explain1.syn
@@protoc_diag.syn
@@protocols.syn
@@prof_team_det.syn
@@prof_team.syn
@@prof_soft_inst.syn
@@prof_scheduled.syn
@@prof_room.syn
@@prof_profile_template.syn
@@prof_preferences.syn
@@prof_photo.syn
@@prof_in_out.syn

@@prof_institution.syn
@@prof_func.syn
@@prof_ext_sys.syn
@@prof_epis_interv.syn
@@prof_doc.syn
@@prof_dep_clin_serv.syn
@@prof_cat.syn
@@prof_access_field_func.syn
@@prof_access.syn
@@profile_templ_acc_func.syn
@@profile_templ_access.syn
@@profile_template.syn
@@professional.syn

@@prep_message.syn
@@pregnancy_risk_eval.syn
@@plan_table.syn
@@periodic_exam_educ.syn
@@pat_vaccine.syn
@@pat_soc_attributes.syn
@@wl_patient_sonho_imp.syn
@@wl_patient_sonho.syn
@@wl_msg_queue.syn
@@wl_mach_prof_queue.syn
@@wl_machine.syn
@@wl_demo_bck.syn
@@wl_demo.syn

@@wl_call_queue.syn
@@white_reason.syn
@@vs_clin_serv.syn
@@vital_sign_relation.syn
@@vital_sign_read.syn
@@vital_sign_desc.syn
@@vital_sign.syn
@@visit.syn
@@vbz$object_stats.syn
@@vaccine_presc_plan.syn
@@vaccine_presc_det.syn
@@vaccine_prescription.syn
@@vaccine_dep_clin_serv.syn

@@vaccine.syn
@@transp_req_group.syn
@@transp_req.syn
@@transp_ent_inst.syn
@@transp_entity.syn
@@transport_type.syn
@@transportation.syn
@@translation.syn
@@toad_plan_table.syn
@@toad_plan_sql.syn
@@time_unit.syn
@@time_event_group.syn
@@time.syn

@@sys_toolbar.syn
@@sys_time_event_group.syn
@@sys_shortcut.syn
@@sys_session.syn
@@sys_screen_area.syn
@@sys_request.syn
@@sys_message_bck.syn
@@sys_message.syn
@@sys_functionality.syn
@@sys_field.syn
@@sys_error.syn
@@sys_domain.syn
@@sys_config.syn

@@sys_button_prop_bck.syn
@@sys_button_prop.syn
@@sys_button_group.syn
@@sys_button.syn
@@sys_btn_sbg.syn
@@sys_btn_crit.syn
@@sys_application_type.syn
@@sys_application_area.syn
@@sys_alert_type.syn
@@sys_alert_software.syn
@@sys_alert_prof_deny.syn
@@sys_alert_profile.syn
@@sys_alert_prof.syn

@@sys_alert_det.syn
@@sys_alert.syn
@@system_apparati.syn
@@sr_surg_task.syn
@@sr_surg_prot_task_det.syn
@@sr_surg_prot_task.syn
@@sr_surg_prot_det.syn
@@sr_surg_protocol.syn
@@sr_surgery_record.syn
@@sr_receive_proc_notes.syn
@@sr_receive_proc_det.syn
@@sr_receive_proc.syn
@@sr_prof_team_det.syn

@@sr_prof_recov_schd.syn
@@xxx.syn
@@wound_type.syn
@@wound_treat.syn
@@wound_eval_charac.syn
@@wound_evaluation.syn
@@wound_charac.syn
@@wl_waiting_room.syn
@@wl_waiting_line_0104.syn
@@wl_waiting_line.syn
@@wl_topics.syn
@@wl_status.syn
@@wl_queue.syn

@@wl_prof_room.syn
@@wl_patient_sonho_transfered.syn
@@pat_sick_leave.syn
@@pat_prob_visit.syn
@@pat_problem_hist.syn
@@pat_problem.syn
@@pat_pregn_measure.syn
@@pat_pregn_fetus_det.syn
@@pat_pregn_fetus_biom.syn
@@pat_pregn_fetus.syn
@@pat_pregnancy_risk.syn
@@pat_pregnancy.syn
@@pat_photo.syn

@@pat_permission.syn
@@pat_notes.syn
@@pat_necessity.syn
@@pat_med_decl.syn
@@pat_medication.syn
@@pat_job.syn
@@pat_health_plan.syn
@@pat_habit.syn
@@pat_ginec_obstet.syn
@@pat_ginec.syn
@@pat_fam_soc_hist.syn
@@pat_family_prof.syn
@@pat_family_member.syn

@@pat_family_disease.syn
@@pat_family.syn
@@pat_ext_sys.syn
@@pat_doc.syn
@@pat_delivery.syn
@@pat_cntrceptiv.syn
@@pat_cli_attributes.syn
@@pat_child_feed_dev.syn
@@pat_child_clin_rec.syn
@@pat_blood_group.syn
@@pat_allergy_hist.syn
@@pat_allergy.syn
@@patient.syn

@@param_analysis_ext_sys.syn
@@parameter_analysis.syn
@@p1_recomended_procedure.syn
@@p1_problem_dep_clin_serv.syn
@@p1_problem.syn
@@p1_prblm_rec_procedure.syn
@@p1_history.syn
@@p1_ext_req_tracking.syn
@@p1_external_request.syn
@@p1_doc_external_request.syn
@@p1_doc_external.syn
@@p1_documents_done.syn
@@p1_documents.syn

@@outlook.syn
@@origin.syn
@@opinion_prof.syn
@@opinion.syn
@@occupation.syn
@@nurse_tea_req.syn
@@nurse_discharge.syn
@@nurse_actv_req_det.syn
@@nurse_activity_req.syn
@@necessity.syn
@@movement.syn
@@monitorization_vs_plan.syn
@@monitorization_vs.syn

@@monitorization.syn
@@epis_task.syn
@@epis_recomend.syn
@@epis_readmission.syn
@@epis_protocols.syn
@@epis_problem.syn
@@epis_photo.syn
@@epis_obs_photo.syn
@@epis_obs_exam.syn
@@epis_observation.syn
@@epis_man.syn
@@epis_interv.syn
@@epis_institution.syn

@@epis_info.syn
@@epis_health_plan.syn
@@epis_ext_sys.syn
@@epis_drug_usage.syn
@@epis_diagnosis.syn
@@epis_body_painting_det.syn
@@epis_body_painting.syn
@@epis_anamnesis.syn
@@episode.syn
@@drug_take_time.syn
@@drug_take_plan.syn
@@drug_route.syn
@@drug_req_supply.syn

@@drug_req_det.syn
@@drug_req.syn
@@drug_protocols.syn
@@drug_presc_plan.syn
@@drug_presc_det.syn
@@drug_prescription.syn
@@drug_plan.syn
@@drug_pharma_interaction.syn
@@drug_pharma_class.syn
@@drug_pharma.syn
@@drug_form.syn
@@drug_dep_clin_serv.syn
@@drug_brand.syn

@@drug.syn
@@dr$d_idx$r.syn
@@dr$d_idx$n.syn
@@dr$d_idx$k.syn
@@dr$d_idx$i.syn
@@doc_type.syn
@@disc_vs_valid.syn
@@disc_help.syn
@@discriminator_help.syn
@@discriminator.syn
@@disch_reas_dest.syn
@@disch_prep_mesg.syn
@@discharge_reason.syn

@@discharge_dest.syn
@@discharge.syn
@@diagnosis_dep_clin_serv.syn
@@diagnosis.syn
@@analysis_result_par.syn
@@analysis_result.syn
@@analysis_req_par.syn
@@analysis_req_det.syn
@@analysis_req.syn
@@analysis_protocols.syn
@@analysis_prep_mesg.syn
@@analysis_param.syn
@@analysis_harvest.syn

@@ch_contents_text.syn
@@ch_contents.syn
@@child_feed_dev.syn
@@category.syn
@@bp_clin_serv.syn
@@body_part_image.syn
@@body_part.syn
@@board_grouping.syn
@@board_group.syn
@@consult_req.syn
@@color.syn
@@cli_rec_req_mov.syn
@@cli_rec_req_det.syn

@@cli_rec_req.syn
@@clin_srv_type.syn
@@clin_serv_ext_sys.syn
@@clin_record.syn
@@clinical_service.syn
@@dep_clin_serv_type.syn
@@dep_clin_serv.syn
@@dependency.syn
@@department.syn
@@criteria.syn
@@create$java$lob$table.syn
@@country.syn
@@contraceptive.syn

@@consult_req_prof.syn
@@board.syn
@@birds_eye_view.syn
@@beye_view_screen.syn
@@bed_schedule.syn
@@bed.syn
@@anesthesia_type.syn
@@analy_parm_limit.syn
@@analysis_room.syn
@@analysis.syn
@@analysis_agp.syn
@@analysis_dep_clin_serv.syn
@@analysis_group.syn

@@analysis_ext_sys.syn
@@allergy.syn
@@adverse_interv_allergy.syn
@@unit_measure.syn
@@sch_event_dcs.syn
@@sch_event.syn
@@origin_soft.syn
@@sr_chklist_manual.syn
@@sr_evaluation.syn
@@sr_equip_kit.syn
@@sr_intervention.syn
@@sr_pat_status.syn
@@sr_pat_status_notes.syn

@@sr_pos_eval_visit.syn
@@sr_posit_req.syn
@@sr_nurse_rec.syn
@@sr_equip.syn
@@sr_posit.syn
@@sr_pre_anest.syn
@@sr_receive_manual.syn
@@sr_room_status.syn
@@sr_surg_period.syn
@@sr_pre_anest_det.syn
@@sr_epis_interv.syn
@@sr_eval_visit.syn
@@sr_pos_eval_det.syn

@@sr_surgery_rec_det.syn
@@sr_reserv_req.syn
@@sr_eval_det.syn
@@sr_eval_notes.syn
@@documentation_type.syn
@@triage_type.syn
@@sys_element_crit.syn
@@sys_element.syn
@@doc_template_diagnosis.syn
@@doc_template.syn
@@doc_quantification.syn
@@doc_qualification.syn
@@doc_dimension.syn

@@doc_criteria.syn
@@doc_component.syn
@@document_type.syn
@@doc_area.syn
@@document_area.syn
@@complaint.syn
@@doc_element_rel.syn
@@triage_color.syn
@@epis_documentation_det.syn
@@epis_documentation.syn
@@epis_complaint.syn
@@doc_element_quantif.syn
@@documentation_rel.syn

@@doc_element.syn
@@doc_element_crit.syn
@@doc_element_qualif.syn
@@documentation.syn
@@doc_action_criteria.syn
@@epis_triage.syn
@@triage.syn
@@epis_bartchart_det.syn
@@epis_bartchart.syn
@@action_criteria.syn
@@floors.syn
@@floors_dep_position.syn
@@floors_department.syn

@@dimension.syn
@@vs_soft_inst.syn
@@doc_external.syn
@@pk_sr_evaluation.syn
@@epis_prof_resp.syn
@@triage_board_group.syn
