CREATE OR REPLACE VIEW ME_DIETARY_USA AS
SELECT D.ID_DIETARY_DRUG, D.QTY, D.MEASURE_UNIT, D.FLG_TYPE, PK_TRANSLATION.GET_TRANSLATION(2, CODE_DIETARY_DRUG) DIETARY_DESCR,
 'USA' VERS FROM DIETARY_DRUG D;