CREATE OR REPLACE VIEW ME_MED_ROUTE_PT AS 
SELECT TO_CHAR(IE.EMB_ID) EMB_ID, TO_CHAR(IVA.VIAS_ADMIN_ID) ROUTE_ID, TRIM(IVA.DESCR) ROUTE_DESCR,
			 'PT' VERS
  FROM INF_EMB IE, INF_VIAS_ADMIN_LNK IVAL, INF_VIAS_ADMIN IVA
 WHERE IE.MED_ID = IVAL.MED_ID
   AND IVA.VIAS_ADMIN_ID = IVAL.VIAS_ADMIN_ID;