CREATE OR REPLACE VIEW ME_MED_PHARM_GROUP_USA AS 
SELECT A.MEDID EMB_ID, B.GTC GROUP_ID,NULL GROUP_ID_L2,
       'USA' VERS
  FROM RMIID_MED A, RGCNSEQ_GCNSEQNO_MSTR B
 WHERE A.GCN_SEQNO = B.GCN_SEQNO;