CREATE OR REPLACE VIEW ME_MED_ROUTE_USA AS 
SELECT DISTINCT A.MEDID EMB_ID, B.GCRT ROUTE_ID, INITCAP(C.GCRT_DESC) ROUTE_DESCR,
       'USA' VERS
  FROM RMIID_MED A, RGCNSEQ_GCNSEQNO_MSTR B, RROUTED_ROUTE_DESC C
 WHERE A.GCN_SEQNO = B.GCN_SEQNO
   AND B.GCRT = C.GCRT;