CREATE OR REPLACE VIEW ME_MED_PT AS 
SELECT TO_CHAR(IE.EMB_ID) EMB_ID,
       IM.MED_ID,
			 IM.NOME MED_NAME,
       DECODE(IM.GENERICO,
              'N',
              ID.DESCR || ' / <b>' || IM.NOME || '</b> ',
							 '<b>' || IM.NOME || '</b> ') || 
              DECODE(IM.SHORT_DOS_COMP, NULL, ' / ', '(' || IM.SHORT_DOS_COMP || ') / ')||
              IFF.DESCR || ' / ' || IE.SHORT_DESCR MED_DESCR_FORMATED,
       DECODE(IM.GENERICO,
              'N',
              ID.DESCR || ' / ' || IM.NOME,
							IM.NOME)||
              DECODE(IM.SHORT_DOS_COMP, NULL, ' / ', '(' || IM.SHORT_DOS_COMP || ') / ')||
              IFF.DESCR || ' / ' || IE.SHORT_DESCR MED_DESCR,
			 DECODE(IM.GENERICO,
                          'N',
                          ID.DESCR || ' / <b>' || IM.NOME || '</b> ',
													'<b>' || IM.NOME || '</b> ')||
                          DECODE(IM.SHORT_DOS_COMP, NULL, ' / ', '(' || IM.SHORT_DOS_COMP || ')') SHORT_MED_DESCR,
       IE.DESCR EMB_DESCR,
			 IE.PRICE_PVP,
       pk_prescription.GET_PRICE(IE.EMB_ID, 1) PRICE_REF,
       pk_prescription.GET_PRICE(IE.EMB_ID, 2) PRICE_PENS,
       DECODE(IM.CLASS_DISP_ID,
              1,
              DECODE(IE.COMPART, 0, 'OTC', 'G'),
              'G') OTC_DESCR,
			 IM.GENERICO,
			 DECODE(IM.GENERICO, 'S', 'Sim', 'Não') GENERICO_DESCR,
       --ADDED
       ID.DCIPT_ID DCI_ID, ID.DESCR DCI_DESCR, 
			 IFF.FORM_FARM_ID FORM_FARM_ID, IFF.DESCR FORM_FARM_DESCR, 
			 IM.TIPO_PROD_ID,
       IM.QT_DOS_COMP,IM.UNIT_DOS_COMP, 
			 IE.N_UNITS,IE.QT_PER_UNIT,  
			 IM.DOS_COMP DOSAGEM,
			 ITA.TITULAR_AIM_ID TITULAR_ID,
       ITA.DESCR TITULAR_DESCR,
       IM.DATA_AIM,
			 IEA.ESTADO_AIM_ID ESTADO_ID,
       IEA.DESCR ESTADO_DESCR,
			 ICD.CLASS_DISP_ID DISP_ID,
       ICD.DESCR DISP_DESCR,
			 ICE.CLASS_ESTUP_ID ESTUP_ID,
       ICE.DESCR ESTUP_DESCR,
			 IT.TRATAMENTO_ID TRAT_ID,
       IT.DESCR TRAT_DESCR,
			 IEU.EMB_UNIT_ID,
       IEU.DESCR EMB_UNIT_DESCR,
			 IGH.GRUPO_HOM_ID,
       IGH.DESCR GRUPO_HOM_DESCR,
       IE.N_REGISTO,
       IE.COMPART,
			 IE.FLG_COMERC,
			 IE.FLG_AVAILABLE,		
			 IC.DISPO_ID,
			 IC.DATA DISPO_DATA,			 
			 'PT' VERS
  FROM INF_MED IM, INF_EMB IE, INF_FORM_FARM IFF, INF_DCIPT ID,
       INF_TITULAR_AIM ITA,
       INF_CLASS_DISP  ICD,
       INF_ESTADO_AIM  IEA,
       INF_CLASS_ESTUP ICE,
       INF_TRATAMENTO  IT,
       INF_EMB_UNIT    IEU,
       INF_GRUPO_HOM   IGH,
			 INF_COMERC IC 
WHERE IE.MED_ID = IM.MED_ID
   AND IFF.FORM_FARM_ID = IM.FORM_FARM_ID
   AND ID.DCIPT_ID = IM.DCIPT_ID
   AND IM.TIPO_PROD_ID != 13
   AND ITA.TITULAR_AIM_ID = IM.TITULAR_AIM_ID
   AND ICD.CLASS_DISP_ID = IM.CLASS_DISP_ID
   AND IEA.ESTADO_AIM_ID = IM.ESTADO_AIM_ID
   AND ICE.CLASS_ESTUP_ID = IM.CLASS_ESTUP_ID
   AND IT.TRATAMENTO_ID = IE.TRATAMENTO
   AND IEU.EMB_UNIT_ID = IE.EMB_UNIT_ID
   AND IGH.GRUPO_HOM_ID = IE.GRUPO_HOM_ID	
	 AND IC.EMB_ID (+) = IE.EMB_ID 
	 AND IC.DISPO_ID (+) = 4
UNION ALL
SELECT TO_CHAR(IE.EMB_ID) EMB_ID,
       IM.MED_ID,
			 IM.NOME MED_NAME,
       ITDM.DESCR || ' / <b>' || IM.NOME || '</b> / ' || IE.SHORT_DESCR MED_DESCR_FORMATED,
       ITDM.DESCR || ' / ' || IM.NOME || ' / ' || IE.SHORT_DESCR MED_DESCR,
			 ITDM.DESCR || ' / <b>' || IM.NOME || '</b>' SHORT_MED_DESCR,
			 IE.DESCR EMB_DESCR,
       IE.PRICE_PVP,
       pk_prescription.GET_PRICE(IE.EMB_ID, 1) PRICE_REF,
       pk_prescription.GET_PRICE(IE.EMB_ID, 2) PRICE_PENS,
       DECODE(IM.CLASS_DISP_ID, 
              1,
              DECODE(IE.COMPART, 0, 'OTC', 'G'),
              'G') OTC_DESCR,
			 IM.GENERICO,
			 			 DECODE(IM.GENERICO, 'S', 'Sim', 'Não') GENERICO_DESCR,
       --ADDED
       ITDM.TIPO_DIAB_MEL_ID DCI_ID, ITDM.DESCR DCI_DESCR,
			 NULL FORM_FARM_ID, NULL FORM_FARM_DESCR,  
			 IM.TIPO_PROD_ID,
       IM.QT_DOS_COMP, IM.UNIT_DOS_COMP,
			 IE.N_UNITS,IE.QT_PER_UNIT, 
			 IM.DOS_COMP DOSAGEM,
			 ITA.TITULAR_AIM_ID TITULAR_ID,
       ITA.DESCR TITULAR_DESCR,
       IM.DATA_AIM,
			 IEA.ESTADO_AIM_ID ESTADO_ID,
       IEA.DESCR ESTADO_DESCR,
			 ICD.CLASS_DISP_ID DISP_ID,
       ICD.DESCR DISP_DESCR,
			 ICE.CLASS_ESTUP_ID ESTUP_ID,
       ICE.DESCR ESTUP_DESCR,
			 IT.TRATAMENTO_ID TRAT_ID,
       IT.DESCR TRAT_DESCR,
			 IEU.EMB_UNIT_ID,
       IEU.DESCR EMB_UNIT_DESCR,
			 IGH.GRUPO_HOM_ID,
       IGH.DESCR GRUPO_HOM_DESCR,
       IE.N_REGISTO,
       IE.COMPART,
			 IE.FLG_COMERC,
			 IE.FLG_AVAILABLE,		
			 IC.DISPO_ID,
			 IC.DATA DATA_DISPO,			 
			 'PT' VERS
  FROM INF_MED IM, INF_EMB IE, INF_DIABETES_LNK IDL, INF_TIPO_DIAB_MEL ITDM,
	     INF_TITULAR_AIM ITA,
       INF_CLASS_DISP  ICD,
       INF_ESTADO_AIM  IEA, 
       INF_CLASS_ESTUP ICE,
       INF_TRATAMENTO  IT,
       INF_EMB_UNIT    IEU,
       INF_GRUPO_HOM   IGH,
			 INF_COMERC IC 
 WHERE IM.TIPO_PROD_ID = 13
   AND IE.MED_ID = IM.MED_ID
   AND IDL.MED_ID = IM.MED_ID
   AND ITDM.TIPO_DIAB_MEL_ID = IDL.TIPO_DIAB_MEL_ID
   AND ITA.TITULAR_AIM_ID = IM.TITULAR_AIM_ID
   AND ICD.CLASS_DISP_ID = IM.CLASS_DISP_ID
   AND IEA.ESTADO_AIM_ID = IM.ESTADO_AIM_ID
   AND ICE.CLASS_ESTUP_ID = IM.CLASS_ESTUP_ID
   AND IT.TRATAMENTO_ID = IE.TRATAMENTO
   AND IEU.EMB_UNIT_ID = IE.EMB_UNIT_ID
   AND IGH.GRUPO_HOM_ID = IE.GRUPO_HOM_ID
	 AND IC.EMB_ID (+) = IE.EMB_ID
	 AND IC.DISPO_ID (+) = 4;