CREATE OR REPLACE VIEW ME_MED_SUBST_USA AS 
SELECT A.MEDID EMB_ID, E.HIC_SEQN SUBST_ID, E.HIC_DESC SUBST_DESCR, NULL SUBST_QUANT,
       'USA' VERS
  FROM RMIID_MED           A,
       RGCNSEQ_GCNSEQNO_MSTR    B,
       RHICL_HIC_HICLSEQNO_LINK C,
       RHICD_HIC_DESC           E
 WHERE A.GCN_SEQNO = B.GCN_SEQNO
   AND B.HICL_SEQNO = C.HICL_SEQNO
   AND C.HIC_SEQN != 9870 -- HIC_SEQNO 009870 WAS CREATED FOR THE SPECIFIC PURPOSE OF SIGNIFYING PRESERVATIVE FREE PRODUCTS. IF THE PROSPECTIVE PRODUCT CONTAINS HIC_SEQN 009870, EXCLUDE THIS INGREDIENT
   AND E.HIC_SEQN = C.HIC_SEQN;