CREATE OR REPLACE VIEW ME_MED_ATC_USA AS
SELECT A.MEDID EMB_ID, C.ATC ATC_ID, C.ATC_DESC ATC_DESCR,
       'USA' VERS
  FROM RMIID_MED A, RATCGC_ATC_GCNSEQNO_LINK B, RATCD_ATC_DESC C
 WHERE A.GCN_SEQNO = B.GCN_SEQNO
   AND C.ATC = B.ATC;