CREATE OR REPLACE VIEW ME_PHARM_GROUP_USA AS 
SELECT A.GTC GROUP_ID,
       INITCAP(A.GTC_DESC) GROUP_DESCR,
       NULL PARENT_ID,
       NULL PARENT_DESCR,
       1 LEVEL_NUM,
       1 RANK,
       'USA' VERS
  FROM RGTCD_GEN_THERAP_CLASS_DESC A;