CREATE OR REPLACE VIEW ME_ROUTE_USA AS 
SELECT GCRT ROUTE_ID, INITCAP(GCRT_DESC) ROUTE_DESCR,
       'USA' VERS
  FROM RROUTED_ROUTE_DESC;

-- MED_REGULATION 
CREATE OR REPLACE VIEW ME_REGULATION_USA AS
SELECT  NULL AS REGULATION_ID ,
NULL AS REGULATION_DESCR,
NULL AS VERS FROM DUAL
where 1=0
;