CREATE OR REPLACE VIEW MI_MED_USA AS 
SELECT A.MEDID ID_DRUG,
       --A.GCN_SEQNO MED_ID,
			 --A.MED_MEDID_DESC MED_NAME,			 
       A.MED_MEDID_DESC MED_DESCR_FORMATED,
       A.MED_MEDID_DESC MED_DESCR,  
       A.MED_MEDID_DESC SHORT_MED_DESCR, 
			 'M' FLG_TYPE, 'Y' FLG_AVAILABLE,'N' FLG_JUSTIFY,
			 NULL ID_DRUG_BRAND,
       NULL DCI_ID, NULL DCI_DESCR, 
       (SELECT GCDF FROM RDOSED_DOSE_DESC G WHERE G.GCDF = D.GCDF) FORM_FARM_ID,
       (SELECT GCDF_DESC FROM RDOSED_DOSE_DESC G WHERE G.GCDF = D.GCDF) FORM_FARM_DESCR,
			 E.GCRT ROUTE_ID, INITCAP(E.GCRT_DESC) ROUTE_DESCR,
       NULL QT_DOS_COMP, NULL UNIT_DOS_COMP, 
       MED_STRENGTH ||MED_STRENGTH_UOM DOSAGEM,
			 NULL GENDER, NULL AGE_MIN, NULL AGE_MAX,
       NULL MDM_CODING, NULL CHNM_ID,
			 NULL FLG_MIX_FLUID,NULL ID_UNIT_MEASURE,NULL AS NOTES,
       'USA' vers
  FROM RMIID_MED A,
       RGCNSEQ_GCNSEQNO_MSTR D, 
			 RROUTED_ROUTE_DESC E,
			 RMILGND_REF_FED_LGND_DESC F 
 WHERE A.MED_STATUS_CD = 0--ACTIVE
   AND D.GCN_SEQNO = A.GCN_SEQNO
	 AND E.GCRT = D.GCRT
   AND F.MED_REF_FED_LEGEND_IND = A.MED_REF_FED_LEGEND_IND;