CREATE OR REPLACE VIEW V_AB_INSTITUTION AS
SELECT id_ab_institution        id_institution,
       code_institution,
       flg_type,
       flg_available,
       rank,
       barcode,
       shortname                abbreviation,
       address2                 location,
       ine_location,
       id_ab_institution_parent id_parent,
       phone_number,
       address1                 address,
       zip_code,
       fax_number,
       address3                 district,
       id_timezone_region,
       id_ab_market             id_market,
       ext_code,
       flg_external,
       dn_flg_status,
       adress_type,
       contact_detail
  FROM alert_core_data.ab_institution ab;

CREATE OR REPLACE VIEW V_AB_INSTITUTION AS
SELECT id_ab_institution        id_institution,
       code_institution,
       flg_type,
       flg_available,
       rank,
       barcode,
       shortname                abbreviation,
       address2                 location,
       ine_location,
       id_ab_institution_parent id_parent,
       phone_number,
       address1                 address,
       zip_code,
       fax_number,
       address3                 district,
       id_timezone_region,
       id_ab_market             id_market,
       ext_code,
       flg_external,
       dn_flg_status,
       adress_type,
       contact_detail,
       county,
       address_other_name
  FROM alert_core_data.ab_institution ab;

CREATE OR REPLACE VIEW ALERT.V_AB_INSTITUTION AS
SELECT id_ab_institution        id_institution,
       code_institution,
       flg_type,
       flg_available,
       rank,
       barcode,
       shortname                abbreviation,
       address2                 location,
       ine_location,
       id_ab_institution_parent id_parent,
       phone_number,
       address1                 address,
       zip_code,
       fax_number,
       address3                 district,
       id_timezone_region,
       id_ab_market             id_market,
       ext_code,
       flg_external,
       dn_flg_status,
       adress_type,
       contact_detail,
       county,
       address_other_name,
       id_clues
  FROM alert_core_data.ab_institution ab;



CREATE OR REPLACE VIEW V_AB_INSTITUTION AS
SELECT id_ab_institution        id_institution,
       code_institution,
       flg_type,
       flg_available,
       rank,
       barcode,
       shortname                abbreviation,
       address2                 location,
       ine_location,
       id_ab_institution_parent id_parent,
       phone_number,
       address1                 address,
       zip_code,
       fax_number,
       address3                 district,
       id_timezone_region,
       id_ab_market             id_market,
       ext_code,
       flg_external,
       dn_flg_status,
       adress_type,
       contact_detail,
       county,
       address_other_name,
       id_clues,
       email,
       rb_country_key
  FROM alert_core_data.ab_institution ab;
  
  
  CREATE OR REPLACE VIEW V_AB_INSTITUTION AS
SELECT id_ab_institution        id_institution,
       code_institution,
       flg_type,
       flg_available,
       rank,
       barcode,
       shortname                abbreviation,
       address2                 location,
       ine_location,
       id_ab_institution_parent id_parent,
       phone_number,
       address1                 address,
       zip_code,
       fax_number,
       address3                 district,
       id_timezone_region,
       id_ab_market             id_market,
       ext_code,
       flg_external,
       dn_flg_status,
       adress_type,
       contact_detail,
       county,
       address_other_name,
       id_clues,
       email,
       rb_country_key
  FROM alert_core_data.ab_institution ab;
  
  
  