CREATE OR REPLACE VIEW V_ADW_MAX_TRACKING AS
SELECT "ID_TRACKING","EXT_REQ_STATUS","DT_TRACKING","ID_EXTERNAL_REQUEST","ID_INSTITUTION","ID_PROFESSIONAL","FLG_TYPE","ID_PROF_DEST","ID_DEP_CLIN_SERV","ROUND_ID","REASON_CODE" 
 FROM ALERT.P1_TRACKING 
 WHERE (ID_EXTERNAL_REQUEST, DT_TRACKING) 
       IN (SELECT ID_EXTERNAL_REQUEST, MIN(DT_TRACKING) MIN_DT_TRACKING 
         FROM ALERT.P1_TRACKING 
         GROUP BY ID_EXTERNAL_REQUEST,ROUND_ID)

