CREATE OR REPLACE VIEW v_adm_request AS
SELECT ar.id_adm_request,
       ar.id_adm_indication,
       ar.id_dest_episode,
       ar.id_dest_prof,
       ar.id_dest_inst,
       ar.id_department,
       ar.id_dep_clin_serv,
       ar.id_room_type,
       ar.id_pref_room,
       ar.id_admission_type,
       ar.expected_duration,
       ar.id_adm_preparation,
       ar.flg_mixed_nursing,
       ar.id_bed_type,
       ar.dt_admission,
       ar.flg_nit,
       ar.dt_nit_suggested,
       ar.id_nit_dcs,
       ar.id_nit_req,
       ar.notes,
       ar.flg_status,
       ar.id_upd_episode,
       ar.id_upd_prof,
       ar.id_upd_inst,
       ar.dt_upd,
       we.id_waiting_list,
       ar.flg_regim,
       ar.flg_benefi,
       ar.flg_contact,
       ar.flg_precauc
  FROM adm_request ar
  LEFT JOIN wtl_epis we
    ON we.id_episode = ar.id_dest_episode;
