CREATE OR REPLACE VIEW V_ANALYSIS_REQUEST_DETAIL AS
SELECT ard.id_analysis_req_det,
       ard.id_analysis_req,
       ard.id_analysis,
       ard.id_sample_type,
       ard.id_analysis_group,
       ard.id_ard_parent,
       ard.id_exam_cat,
       ard.flg_time_harvest,
       ard.flg_status,
       ard.flg_referral,
       ard.dt_target_tstz,
       ard.dt_schedule,
       ard.dt_final_target_tstz,
       ard.dt_final_result_tstz,
       ard.dt_pend_req_tstz,
       ard.dt_begin_harvest,
       ard.dt_begin_result,
       ard.id_order_recurrence,
       ard.flg_urgency,
       ard.flg_prn,
       ard.notes_prn,
       ard.flg_fasting,
       ard.id_clinical_purpose,
       ard.clinical_purpose_notes,
       ard.flg_col_inst,
       ard.flg_exec_result,
       ard.flg_pre_req,
       ard.id_room,
       ard.id_exec_institution,
       ard.id_room_req,
       ard.id_movement,
       ard.notes,
       ard.notes_scheduler,
       ard.notes_tech,
       ard.notes_patient,
       ard.notes_justify,
       ard.id_analysis_codification,
       ard.id_pat_health_plan,
       ard.id_pat_exemption,
       ard.id_task_dependency,
       ard.id_cdr,
       ard.id_co_sign_order,
       ard.id_prof_cancel,
       ard.dt_cancel_tstz,
       ard.id_cancel_reason,
       ard.notes_cancel,
       ard.id_co_sign_cancel,
       ard.flg_req_origin_module,
       ard.id_episode_origin,
       ard.id_episode_destination,
       ard.id_prof_last_update,
       ard.dt_last_update_tstz,
       NULL                         flg_ref_type,
       NULL                         id_prof_ref,
       NULL                         id_inst_ref,
       bpea.id_patient              id_patient_new_born
  FROM analysis_req_det ard
  LEFT OUTER JOIN blood_product_execution bpe
    ON bpe.id_analysis_req_det = ard.id_analysis_req_det
   AND bpe.action = 'LAB_MOTHER_ID'
  LEFT OUTER JOIN blood_products_ea bpea
    ON bpea.id_blood_product_det = bpe.id_blood_product_det;
