CREATE OR REPLACE VIEW v_analysis_request AS
SELECT ar.id_analysis_req,
       ar.id_patient,
       ar.id_episode,
       ar.id_episode_origin,
       ar.id_episode_destination,
       ar.id_prev_episode,
       ar.id_visit,
       ar.id_institution,
       ar.flg_time,
       ar.flg_status,
       ar.id_prof_writes,
       ar.dt_req_tstz,
       ar.dt_begin_tstz,
       ar.dt_pend_req_tstz,
       ar.flg_priority,
       ar.id_exec_institution,
       ar.barcode,
       ar.id_prof_authorize,
       ar.id_prof_approve,
       ar.id_schedule,
       ar.id_sched_consult,
       ar.id_prof_cancel,
       ar.dt_cancel_tstz,
       ar.id_cancel_reason,
       ar.notes_cancel,
       ar.id_analysis_group,
       ar.id_prof_last_update,
       ar.dt_last_update_tstz
  FROM analysis_req ar;
