-- CHANGED BY: Vanessa Barsottelli
-- CHANGE DATE: 09/02/2017 09:02
-- CHANGE REASON: [ALERT-327700] NOM024 - API para Interface ALERT - SINAC (SUBSISTEMA DE INFORMACIÓN SOBRE NACIMIENTOS)
CREATE OR REPLACE VIEW v_birth_sinac AS
SELECT preg.id_pat_pregnancy,
       emother.id_institution,
       edoc.child_number,
       pk_adt.get_rb_reg_classifier_code(i_rb_reg_class => pk_adt.get_clues_id_rb_regional(i_id_clues       => NULL,
                                                                                           i_id_institution => emother.id_institution),
                                         i_rank         => 5) cedocve,
       -- PATIENT ID
       patchild.code_birth_certificate folio,
       patchild.code_type_birth_certificate tipo_formato,
       patmother.first_name nombre,
       patmother.last_name paterno,
       patmother.middle_name materno,
       pk_patient.get_patient_ssn(17,
                                  profissional(NULL, emother.id_institution, NULL),
                                  i_patient => patmother.id_patient) social_security_number,
       pk_patient.get_patient_ssn(17,
                                  profissional(NULL, emother.id_institution, NULL),
                                  i_patient => patmother.id_patient) curp_m,
       bpmother.code_state ent_nacm,
       bpmother.code_municipality mpo_nacm,
       (SELECT c.id_content
          FROM country c
         WHERE c.id_country = ca.id_country) country_id_content,
       pk_date_utils.date_send_tsz(17, patmother.dt_birth_tstz, emother.id_institution, 0) fech_nacm_serial,
       pk_patient.get_partial_pat_age(i_lang    => 17,
                                      i_prof    => profissional(0, emother.id_institution, 0),
                                      i_patient => patmother.id_patient) fech_nacm,
       pk_patient.get_pat_age_num(i_lang    => NULL,
                                  i_prof    => profissional(NULL, emother.id_institution, NULL),
                                  i_patient => patmother.id_patient,
                                  i_type    => 'Y',
                                  i_view    => 'Y') edadm,
       patmother.flg_native_group con_indm,
       CASE
            WHEN patmother.pat_native_lang = 2 THEN
             'N'
            WHEN patmother.pat_native_lang IN (4, 8) THEN
             'SI'
            WHEN patmother.pat_native_lang = 3 THEN
             'NE'
            ELSE
             'Y'
        END AS habla_indm,
       patmother.pat_native_lang cual_lengm,
       psa.marital_status edocivil,
       ca.road_type tipovial_res,
       ca.road calle_res,
       ca.door_number numext_res,
       ca.floor numint_res,
       ca.cve_tipo_asen tipoasen_res,
       ca.ca_desc_settlement nomasen_res,
       ca.postal_code codpos_res,
       ca.code_state ent_res,
       ca.code_municipality mpo_res,
       ca.code_city loc_res,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 36111,
                                      i_doc_int_name  => 'NUM_EMB') num_emb,
       cp.phone_number tel_res,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 36111,
                                      i_doc_int_name  => 'NAC_MUE') num_nacmto,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 36111,
                                      i_doc_int_name  => 'NAC_VIV') num_nacvivo,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 36111,
                                      i_doc_int_name  => 'SOBREVIV') hijo_sobv,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 36111,
                                      i_doc_int_name  => 'COND_NAC',
                                      i_show_internal => 'Y') hijo_ante,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 36111,
                                      i_doc_int_name  => 'VIV_AUN',
                                      i_show_internal => 'Y') vive_aun,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 36111,
                                      i_doc_int_name  => 'FECHA_NAC_EMB_ANT',
                                      i_mask          => 'DD/MM/YYYY') fech_nhea,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'ORDEN_NAC') orden_nac,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => NULL,
                                      i_doc_area      => 1097,
                                      i_doc_int_name  => 'ATEN_PREN',
                                      i_show_internal => 'Y') aten_pren,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => NULL,
                                      i_doc_area      => 1097,
                                      i_doc_int_name  => 'TRIM_ATEN_PREN',
                                      i_show_internal => 'Y') trim_cons,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => NULL,
                                      i_doc_area      => 1097,
                                      i_doc_int_name  => 'TOT_CONS_EMB') tot_cons,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patmother.id_patient,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => NULL,
                                      i_doc_area      => 1097,
                                      i_doc_int_name  => 'MADRE_SOBREVIV',
                                      i_show_internal => 'Y') sob_parto,
       pk_delivery.get_death_folio_cert(i_lang          => 17,
                                        i_prof          => NULL,
                                        i_patient       => patmother.id_patient,
                                        i_pat_pregnancy => preg.id_pat_pregnancy) certdef,
       pk_adt.get_health_plan_field_mx(emother.id_episode, 'Y', 'ID_CONTENT') derhab,
       pk_adt.get_health_plan_field_mx(emother.id_episode, 'Y', 'AFFILIATION_NUMBER') numafiliac,
       pk_adt.get_health_plan_field_mx(emother.id_episode, 'N', 'ID_CONTENT') derhab2,
       --pk_adt.get_health_plan_sinac(i_episode => emother.id_episode, i_mode => 2) derhab2,
       (SELECT id_content
          FROM scholarship s
         WHERE s.id_scholarship = psa.id_scholarship) niv_escol,
       (SELECT psa.usual_occupation
          FROM pat_soc_attributes psa
         WHERE psa.id_patient = patmother.id_patient
           AND psa.id_institution = emother.id_institution) ocuphab,
       (SELECT id_content
          FROM occupation o
         WHERE o.id_occupation = pk_patient.get_pat_job(i_id_pat => patmother.id_patient)) cveocuphab,
       psa.flg_job_status trab_act,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'H_F_NAC',
                                      i_mask          => 'DD/MM/YYYY') fech_nach,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'H_F_NAC',
                                      i_mask          => 'HH24:MI') hora_nach,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'GENERO',
                                      i_show_internal => 'Y') sexoh,
       pk_pregnancy_core.get_pregnancy_weeks(NULL, preg.dt_init_preg_lmp, preg.dt_intervention, preg.num_gest_weeks) gestach,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'TALLA',
                                      i_show_internal => 'Y') tallah,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'PESO',
                                      i_show_internal => 'Y') pesoh,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patchild.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 52,
                                      i_doc_int_name  => 'APGAR',
                                      i_show_internal => 'Y') apgarh,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patchild.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 52,
                                      i_doc_int_name  => 'SILVERMAN',
                                      i_show_internal => 'Y') silverman,
       pk_delivery.get_delivery_value(i_lang             => 17,
                                      i_prof             => NULL,
                                      i_patient          => patchild.id_patient,
                                      i_pat_pregnancy    => NULL,
                                      i_child_number     => NULL,
                                      i_doc_area         => 52,
                                      i_element_int_name => 'VACUNA_BCG') bcg,
       pk_delivery.get_delivery_value(i_lang             => 17,
                                      i_prof             => NULL,
                                      i_patient          => patchild.id_patient,
                                      i_pat_pregnancy    => NULL,
                                      i_child_number     => NULL,
                                      i_doc_area         => 52,
                                      i_element_int_name => 'VACUNA_HEPB') hep_b,
       pk_delivery.get_delivery_value(i_lang             => 17,
                                      i_prof             => NULL,
                                      i_patient          => patchild.id_patient,
                                      i_pat_pregnancy    => NULL,
                                      i_child_number     => NULL,
                                      i_doc_area         => 52,
                                      i_element_int_name => 'MED_VITA') vit_a,
       pk_delivery.get_delivery_value(i_lang             => 17,
                                      i_prof             => NULL,
                                      i_patient          => patchild.id_patient,
                                      i_pat_pregnancy    => NULL,
                                      i_child_number     => NULL,
                                      i_doc_area         => 52,
                                      i_element_int_name => 'MED_VITK') vit_k,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patchild.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 52,
                                      i_doc_int_name  => 'TAMIZ_AUDIT') tam_aud,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_patient       => patchild.id_patient,
                                      i_pat_pregnancy => NULL,
                                      i_child_number  => NULL,
                                      i_doc_area      => 52,
                                      i_doc_int_name  => 'PRODUCTO',
                                      i_show_internal => 'Y') producto,
       pk_delivery.get_born_anomaly_acelrn(i_lang      => 17,
                                           i_prof      => NULL,
                                           i_patient   => echild.id_patient,
                                           i_data_show => 'ANOM_CONG1',
                                           i_text_show => 'NINGUNA APARENTE') acelrn,
       pk_delivery.get_born_anomaly_cve(i_lang         => 17,
                                        i_prof         => profissional(NULL, echild.id_institution, 0),
                                        i_patient      => echild.id_patient,
                                        i_episode      => echild.id_episode,
                                        i_data_show    => 'CVE_CIE',
                                        i_text_show    => '8888',
                                        i_text_na_show => '0000') cve_cie,
       pk_delivery.get_born_anomaly_acelrn(i_lang      => 17,
                                           i_prof      => NULL,
                                           i_patient   => echild.id_patient,
                                           i_data_show => 'ANOM_CONG2',
                                           i_text_show => 'NO APLICA') acelrn2,
       pk_delivery.get_born_anomaly_cve(i_lang         => 17,
                                        i_prof         => profissional(NULL, echild.id_institution, 0),
                                        i_patient      => echild.id_patient,
                                        i_episode      => echild.id_episode,
                                        i_data_show    => 'CVE_CIE2',
                                        i_text_show    => '8888',
                                        i_text_na_show => '7777') cve_cie2,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'PROC',
                                      i_show_internal => 'Y') procnac,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'FORC',
                                      i_show_internal => 'Y') forceps,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1047,
                                      i_doc_int_name  => 'DESC_PROC') especifique,
       pk_adt.is_place_of_birth_inst(i_lang       => 17,
                                     i_prof       => NULL,
                                     i_patient    => patchild.id_patient,
                                     i_birth_inst => bpchild.id_institution) inst_nac_hospital,
       pk_multichoice.get_id_content(i_multichoice_option => bpchild.id_occurrence_site) inst_nac,
       bpchild.institution_name unimed,
       pk_adt.get_clues_code(i_id_clues => NULL, i_id_institution => bpchild.id_institution) clues,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'PERSON_ATEND',
                                      i_show_internal => 'Y') atendio,
       pk_delivery.get_delivery_value(i_lang          => 17,
                                      i_prof          => NULL,
                                      i_pat_pregnancy => preg.id_pat_pregnancy,
                                      i_child_number  => edoc.child_number,
                                      i_doc_area      => 1048,
                                      i_doc_int_name  => 'O_PERSON_ATEND') aten_otro,
       bpchild.road_type tipovial_nac,
       --    pk_sysdomain.get_domain_val(i_lang => 17,i_code_domain => 'CONTACT_ADDRESS_MX.ROAD_TYPE', i_val => bpchild.road_type ) tipovial_nac,
       bpchild.road              calle_nac,
       bpchild.door_number       numext_nac,
       bpchild.floor             numint_nac,
       bpchild.cve_tipo_asen     tipoasen_nac,
       bpchild.desc_settlement   nomasen_nac,
       bpchild.postal_code       codpos_nac,
       bpchild.code_state        ent_nac,
       bpchild.code_municipality mpo_nac,
       bpchild.code_city         loc_nac,
       -- certificado -- patient ID
       bpchild.physician_name        nombre_c, --nombre 
       bpchild.physician_middle_name paterno_c, --primeiro appelido
       bpchild.physician_last_name   materno_c, -- segundo apelido
       bpchild.certified_by          cert_por, -- persona que certifico
       bpchild.specify_certifier     otromedico,
       bpchild.num_order             ced_medc,
       --fim certificado
       CASE
            WHEN bpchild.id_institution IS NULL THEN
             pk_adt.get_clues_name(i_id_clues => pk_adt.get_clues_inst(i_lang           => NULL,
                                                                       i_prof           => NULL,
                                                                       i_id_institution => emother.id_institution))
            ELSE
             NULL
        END unimed_33_1,
       CASE
            WHEN bpchild.id_institution IS NULL THEN
             pk_adt.get_clues_field(i_id_clues => pk_adt.get_clues_inst(i_lang           => 17,
                                                                        i_prof           => NULL,
                                                                        i_id_institution => emother.id_institution),
                                    i_field    => 'CODE_CLUES')
            ELSE
             NULL
        END clues_33_2,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'STREET_TYPE') tipovial_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'STREET') calle_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'OUTSIDE_NUMBER') numext_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'INSIDE_NUMBER') numint_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'CODE_SETTLEMENT') tipoasen_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'SETTLEMENT') nomasen_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'POSTAL_CODE') codpos_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'CODE_ENTITY') ent_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'CODE_MUNICIP') mpo_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'CODE_LOCATION') loc_cert,
       pk_adt.get_birth_certificate_data(i_lang      => 17,
                                         i_prof      => profissional(NULL, emother.id_institution, 0),
                                         i_patient   => patchild.id_patient,
                                         i_data_show => 'PHONE_NUMBER') tel_cert,
       -- certificado
       nvl2(bpchild.dt_certification, to_char(bpchild.dt_certification, 'DD/MM/YYYY'), NULL) fech_cert,
       pk_adt.get_birth_certificate_data(i_lang        => NULL,
                                         i_prof        => profissional(NULL, emother.id_institution, 0),
                                         i_patient     => patchild.id_patient,
                                         i_flg_edition => 'N',
                                         i_data_show   => 'PROF_NAME') user_alta,
       pk_adt.get_birth_certificate_data(i_lang        => NULL,
                                         i_prof        => profissional(NULL, emother.id_institution, 0),
                                         i_patient     => patchild.id_patient,
                                         i_flg_edition => 'N',
                                         i_data_show   => 'REG_DATE') fech_alta,
       pk_adt.get_birth_certificate_data(i_lang        => NULL,
                                         i_prof        => profissional(NULL, emother.id_institution, 0),
                                         i_patient     => patchild.id_patient,
                                         i_flg_edition => 'E',
                                         i_data_show   => 'PROF_NAME') user_camb,
       pk_adt.get_birth_certificate_data(i_lang        => NULL,
                                         i_prof        => profissional(NULL, emother.id_institution, 0),
                                         i_patient     => patchild.id_patient,
                                         i_flg_edition => 'E',
                                         i_data_show   => 'REG_DATE') fech_camb,
       1 idcaptura,
       emother.id_patient
  FROM (SELECT row_number() over(PARTITION BY pp.id_patient ORDER BY pp.n_pregnancy DESC) pregnancy_rn, pp.*
          FROM pat_pregnancy pp
         WHERE pp.flg_status NOT IN ('C', 'A')) preg
  JOIN (SELECT t.id_pat_pregnancy, t.id_child_episode, t.child_number, id_episode
          FROM (SELECT row_number() over(PARTITION BY edd.id_pat_pregnancy ORDER BY edd.dt_register_tstz) rn,
                       edd.id_pat_pregnancy,
                       edd.id_child_episode,
                       edd.child_number,
                       ed.id_episode
                  FROM epis_doc_delivery edd
                  JOIN epis_documentation ed
                    ON edd.id_epis_documentation = ed.id_epis_documentation
                 WHERE edd.id_child_episode IS NOT NULL) t) edoc
    ON edoc.id_pat_pregnancy = preg.id_pat_pregnancy
  JOIN episode emother
    ON emother.id_episode = edoc.id_episode
  JOIN episode echild
    ON echild.id_episode = edoc.id_child_episode
  JOIN patient patmother
    ON patmother.id_patient = preg.id_patient
  JOIN patient patchild
    ON patchild.id_patient = echild.id_patient
  LEFT JOIN person pmother
    ON pmother.id_person = patmother.id_person
  LEFT JOIN pat_soc_attributes psa
    ON psa.id_patient = patmother.id_patient
  LEFT JOIN v_contact_address_mx ca
    ON ca.id_contact_entity = pmother.id_person
   AND ca.flg_main_address = 'Y'
  LEFT JOIN v_contact_phone cp
    ON cp.id_contact_entity = ca.id_contact_entity
   AND cp.id_contact_type = 12
  LEFT JOIN v_birthplace_address_mx bpchild
    ON bpchild.id_patient = patchild.id_patient
  LEFT JOIN v_birthplace_address_mx bpmother
    ON bpmother.id_patient = patmother.id_patient
 WHERE patchild.code_birth_certificate IS NOT NULL
   AND nvl(patchild.flg_action_certificate, 'U') <> 'C'
-- WHERE preg.pregnancy_rn = 1
;
-- CHANGED END: Vanessa Barsottelli
