CREATE OR REPLACE VIEW V_COMPLICATIONS AS
SELECT t.id_concept_version id_diagnosis,
       NULL id_diagnosis_parent,
       NULL id_epis_diagnosis,
       t.description desc_diagnosis,
       t.code code_icd,
       NULL flg_other,
       NULL status_diagnosis,
       NULL icon_status,
       NULL avail_for_select,
       NULL default_new_status,
       NULL default_new_status_desc,
       t.id_concept_term id_alert_diagnosis,
       NULL desc_epis_diagnosis,
       NULL flg_terminology,
       NULL flg_diag_type,
       t.code_translation code_diagnosis,
       NULL flg_icd9,
       'N' flg_show_term_code,
       NULL id_language,
       t.rank content_rank,
       30 views_rank
  FROM alert_core_data.v_ts1_terms_ea_with_free_text t --alert_core_data.v_ts1_terms_ea t
 WHERE alert_core_func.pk_ts1_api.set_ts_context(i_lang            => sys_context('ALERT_CONTEXT', 'PK_TERM_SEARCH.LANG'),
                                                 i_concept_type    => 'COMPLICATION',
                                                 i_id_task_type    => 63, -- complications are also diagnosis
                                                 i_id_institution  => sys_context('ALERT_CONTEXT',
                                                                                  'PK_TERM_SEARCH.INSTITUTION'),
                                                 i_id_software     => sys_context('ALERT_CONTEXT',
                                                                                  'PK_TERM_SEARCH.SOFTWARE'),
                                                 i_id_professional => -1,
                                                 i_id_category     => -1,
                                                 i_text_search     => sys_context('ALERT_CONTEXT',
                                                                                  'PK_TERM_SEARCH.TEXT_SEARCH'),
                                                 i_format_text     => 'N',
                                                 i_id_patient      => sys_context('ALERT_CONTEXT',
                                                                                  'PK_TERM_SEARCH.PATIENT')) = 1;
