create or replace view v_consult_req as
select id_consult_req id_consult_req,
       consult_type consult_type,
       cr.id_clinical_service id_clinical_service,
       cs.code_clinical_service code_clinical_service,
       id_patient id_patient,
       id_instit_requests id_instit_requests,
       id_inst_requested id_inst_requested,
       id_episode id_episode,
       id_prof_req id_prof_req,
       id_prof_auth id_prof_auth,
       id_prof_appr id_prof_appr,
       id_prof_proc id_prof_proc,
       notes notes,
       id_prof_cancel id_prof_cancel,
       notes_cancel notes_cancel,
       id_dep_clin_serv id_dep_clin_serv,
       id_prof_requested id_prof_requested,
       flg_status flg_status,
       notes_admin notes_admin,
       id_schedule id_schedule,
       dt_consult_req_tstz dt_consult_req_tstz,
       dt_scheduled_tstz dt_scheduled_tstz,
       dt_cancel_tstz dt_cancel_tstz,
       next_visit_in_notes next_visit_in_notes,
       flg_instructions flg_instructions,
       id_complaint id_complaint,
       flg_type_date flg_type_date,
       status_flg status_flg,
       status_icon status_icon,
       status_msg status_msg,
       status_str status_str,
       reason_for_visit reason_for_visit,
       flg_type flg_type,
       creason.id_cancel_reason id_cancel_reason,
      creason.code_cancel_reason,
     creason.id_content id_content_cancel_reason,
     cast(null as varchar2(800)) flg_type_name,
     cast(null as varchar2(4000)) appointment_type_description,
     cr.id_epis_documentation,
     cr.id_epis_type,
     cr.dt_last_update,
     cr.id_prof_last_update,
       cr.id_inst_last_update,
     cr.id_sch_event,
     cr.dt_begin_event,
     cr.dt_end_event,
     cr.flg_priority,
     cr.flg_contact_type,
     cr.instructions,
     cr.id_room,
     cr.flg_request_type,
     cr.flg_req_resp,
     cr.request_reason,
     cr.id_language,
     cr.flg_recurrence,
     cr.frequency,
     cr.dt_rec_begin,
     cr.dt_rec_end,
     cr.nr_events,
     cr.week_day,
     cr.week_nr,
     cr.month_day,
     cr.month_nr,
     cr.id_task_dependency,
     cr.flg_freq_origin_module,
     cr.id_episode_to_exec,
     cr.id_soft_reg_by
 from consult_req cr
 left join clinical_service cs on cr.id_clinical_service = cs.id_clinical_service
 left join cancel_reason creason on cr.id_cancel_reason = creason.id_cancel_reason;

