CREATE OR REPLACE VIEW V_DAILY_ACTIVE_UNPAYED_03 AS
SELECT t.sys_lang,
       t.sys_prof_id,
       t.sys_prof_institution,
       t.sys_prof_software,
       profissional(alert_context('l_prof_id'), alert_context('l_prof_institution'), alert_context('l_prof_software')) sys_lprof,
       t.currency,
       t.dt_admin_tstz,
       t.dt_med_tstz,
       t.flg_payment,
       t.flg_status_adm,
       t.id_discharge,
       t.price,
       t.dt_begin_tstz,
       t.id_episode,
       t.dt_first_obs_tstz,
       t.id_dep_clin_serv,
       t.ei_id_schedule,
       t.p_name,
       t.p_nick_name,
       t.p1_name,
       t.p1_nick_name,
       t.id_patient,
       t.gender,
       t.flg_contact_type,
       t.dt_target_tstz,
       t.flg_sched,
       t.flg_state,
       t.sp_id_schedule,
       t.id_schedule_outp,
       (SELECT pk_sysdomain.get_img(t.sys_lang, 'SCHEDULE_OUTP.FLG_SCHED', t.flg_sched)
          FROM dual) sd_img_name,
       (SELECT pk_sysdomain.get_rank(t.sys_lang, 'SCHEDULE_OUTP.FLG_SCHED', t.flg_sched)
          FROM dual) sd_rank,
       (SELECT pk_sysdomain.get_img(t.sys_lang, 'SCHEDULE_OUTP.FLG_STATE', t.flg_state)
          FROM dual) sd2_img_name,
       (SELECT cr.num_clin_record
          FROM clin_record cr
         WHERE cr.id_patient = T.id_patient
           AND cr.id_institution = T.sys_prof_institution
           AND rownum < 2) num_clin_record
  FROM (SELECT v1.sys_lang,
               v1.sys_prof_id,
               v1.sys_prof_institution,
               v1.sys_prof_software,
               v1.currency,
               v1.dt_admin_tstz,
               v1.dt_med_tstz,
               v1.flg_payment,
               v1.flg_status_adm,
               v1.id_discharge,
               v1.price,
               v1.dt_begin_tstz,
               v1.id_episode,
               v1.dt_first_obs_tstz,
               v1.id_dep_clin_serv,
               v1.ei_id_schedule,
               v1.p_name,
               v1.p_nick_name,
               v1.p1_name,
               v1.p1_nick_name,
               v1.id_patient,
               v1.gender,
               v1.flg_contact_type,
               v1.dt_target_tstz,
               v1.flg_sched,
               v1.flg_state,
               v1.sp_id_schedule,
               v1.id_schedule_outp
          FROM v_daily_active_unpayed_01 v1
        UNION
        SELECT v2.sys_lang,
               v2.sys_prof_id,
               v2.sys_prof_institution,
               v2.sys_prof_software,
               v2.currency,
               v2.dt_admin_tstz,
               v2.dt_med_tstz,
               v2.flg_payment,
               v2.flg_status_adm,
               v2.id_discharge,
               v2.price,
               v2.dt_begin_tstz,
               v2.id_episode,
               v2.dt_first_obs_tstz,
               v2.id_dep_clin_serv,
               v2.ei_id_schedule,
               v2.p_name,
               v2.p_nick_name,
               v2.p1_name,
               v2.p1_nick_name,
               v2.id_patient,
               v2.gender,
               v2.flg_contact_type,
               v2.dt_target_tstz,
               v2.flg_sched,
               v2.flg_state,
               v2.sp_id_schedule,
               v2.id_schedule_outp
          FROM v_daily_active_unpayed_02 v2) t;
