-->V_DISCHARGE
CREATE OR REPLACE VIEW V_DISCHARGE AS
SELECT id_discharge,
       id_prof_med,
       dt_med_tstz,
       notes_med,
       id_prof_admin,
       dt_admin_tstz,
       notes_admin,
       id_prof_cancel,
       dt_cancel_tstz,
       notes_cancel,
       id_episode,
       d.id_disch_reas_dest,
       id_cpt_code,
       flg_status,
       flg_type,
       id_discharge_reason,
       id_discharge_dest,
       id_dep_clin_serv,
       id_department,
       id_institution,
       id_discharge_status,
       id_prof_therapist,
       dt_therapist,
       notes_therapist,
       flg_bill_type,
       id_prof_nutritionist,
       dt_nutritionist,
       notes_nutricionist,
       flg_type_disch,
       flg_payment,
       id_prof_nurse,
       dt_nurse,
       notes_nurse,
       d.dt_pend_tstz,
       d.dt_pend_active_tstz
  FROM discharge d, disch_reas_dest drd
 WHERE d.id_disch_reas_dest = drd.id_disch_reas_dest(+);
