CREATE OR REPLACE VIEW ALERT.V_DOC_EXTERNAL AS
SELECT id_doc_external,
       id_doc_type,
       num_doc,
       dt_emited,
       notes,
       dt_digit,
       id_doc_ori_type,
       id_doc_destination,
       dt_expire,
       id_external_request,
       desc_doc_type,
       desc_doc_ori_type,
       desc_doc_destination,
       id_episode,
       id_patient,
       flg_status,
       local_emited,
       id_institution,
       flg_sent_by,
       flg_received,
       id_doc_original,
       desc_doc_original,
       id_professional,
       title,
       dt_inserted,
       dt_updated,
       id_professional_upd,
       id_prof_perf_by,
       desc_perf_by,
       id_grupo,
       dt_last_identification dt_last_identification_tstz,
       organ_shipper,
			 id_specialty
  FROM doc_external;
