CREATE OR REPLACE VIEW V_DOC_ELEMENT AS
SELECT id_doc_element,
       id_documentation,
       id_doc_dimension,
       internal_name,
       flg_type,
       flg_gender,
       position,
       age_max,
       age_min,
       rank,
       flg_available,
       input_mask,
       flg_optional_value,
       code_element_domain,
       flg_element_domain_type,
       flg_behavior,
       min_value,
       max_value,
       id_content,
       score,
       id_unit_measure_type,
       id_unit_measure_subtype,
       id_unit_measure_reference,
       display_format,
       separator,
       flg_ref_op_min,
       ref_val_min,
       flg_ref_op_max,
       ref_val_max
  FROM doc_element;