CREATE OR REPLACE VIEW V_DRUG_PRESCRIPTION_PLAN AS
SELECT id_drug_presc_plan,
       id_drug_presc_det,
       id_prof_writes,
       dosage,
       flg_status,
       notes,
       id_prof_cancel,
       notes_cancel,
       id_episode,
       application_spot,
       lot_number,
       dt_plan_tstz,
       dt_take_tstz,
       dt_cancel_tstz,
       id_administred id_prof_adm,
       dt_adm_tstz,
       origin,
       dt_next_take,
       dosage_unit_measure,
       id_cancel_reason,
       cancel_reason_descr,
       id_vacc_funding_cat,
       id_vacc_funding_source,
       funding_source_desc,
       id_vacc_doc_vis,
       doc_vis_desc,
       id_vacc_origin,
       origin_desc,
       vacc_route_data,
       id_ordered,
       ordered_desc,
       administred_desc,
       dt_doc_delivery_tstz,
       id_vacc_adv_reaction,
       application_spot_code,
       dt_expiration,
       notes_advers_react
  FROM drug_presc_plan dpp;
