CREATE OR REPLACE VIEW V_EPIS_DIAGNOSIS AS
SELECT ed.id_epis_diagnosis,
       ed.id_episode,
       e.id_visit,
       ed.id_diagnosis,
       pk_diagnosis_core.get_prof_create_diagnosis(i_lang              => NULL,
                                                   i_prof              => NULL,
                                                   i_id_epis_diagnosis => ed.id_epis_diagnosis) id_professional_diag,
       ed.flg_type epis_diagnosis_flg_type,
       ed.flg_final_type,
       ed.flg_status,
       ed.desc_epis_diagnosis,
       pk_diagnosis_core.get_dt_create_diagnosis(i_lang              => NULL,
                                                 i_prof              => NULL,
                                                 i_id_epis_diagnosis => ed.id_epis_diagnosis) dt_epis_diagnosis_tstz,
       ed.id_prof_base,
       ed.dt_base_tstz,
       ed.id_professional_cancel,
       ed.dt_cancel_tstz,
       ed.id_prof_confirmed,
       ed.dt_confirmed_tstz,
       ed.id_prof_rulled_out,
       ed.dt_rulled_out_tstz,
       d.code_icd,
       d.flg_type diagnosis_flg_type,
       d.code_diagnosis,
       ad.code_alert_diagnosis,
       ad.code_medical,
       ad.code_surgical,
       ad.code_problems,
       ad.code_cong_anomalies,
       d.mdm_coding,
       d.id_content,
       dc.id_codification,
       ed.id_alert_diagnosis AS id_concept_term,
       ed.id_adiag_inst_owner AS id_inst_owner,
       pk_prof_utils.get_reg_prof_id_dcs(i_prof_id => pk_diagnosis_core.get_prof_diagnosis(i_lang                => NULL,
                                                                                           i_prof                => NULL,
                                                                                           i_flg_status          => ed.flg_status,
                                                                                           i_professional_diag   => ed.id_professional_diag,
                                                                                           i_prof_confirmed      => ed.id_prof_confirmed,
                                                                                           i_professional_cancel => ed.id_professional_cancel,
                                                                                           i_prof_base           => ed.id_prof_base,
                                                                                           i_prof_rulled_out     => ed.id_prof_rulled_out),
                                         i_dt_reg  => pk_diagnosis_core.get_dt_diagnosis(i_lang              => NULL,
                                                                                         i_prof              => NULL,
                                                                                         i_flg_status        => ed.flg_status,
                                                                                         i_dt_epis_diagnosis => ed.dt_epis_diagnosis_tstz,
                                                                                         i_dt_confirmed      => ed.dt_confirmed_tstz,
                                                                                         i_dt_cancel         => ed.dt_cancel_tstz,
                                                                                         i_dt_base           => ed.dt_base_tstz,
                                                                                         i_dt_rulled_out     => ed.dt_rulled_out_tstz),
                                         i_episode => ed.id_episode) id_dep_clin_serv,
       ed.flg_add_problem,
       ed.notes
  FROM epis_diagnosis ed
  JOIN diagnosis d
    ON ed.id_diagnosis = d.id_diagnosis
  JOIN episode e
    ON ed.id_episode = e.id_episode
  LEFT JOIN diag_codification dc
    ON dc.flg_diag_type = d.flg_type
  LEFT JOIN alert_diagnosis ad
    ON ad.id_alert_diagnosis = ed.id_alert_diagnosis;
