create or replace view v_epis_report as 
SELECT t.id_epis_report,
       t.id_reports,
       t.id_episode,
       t.id_professional,
       t.flg_status,
       t.adw_last_update,
       t.flg_edit,
       t.rep_binary_file,
       t.dt_creation_tstz,
       t.id_audit_req_prof_epis,
       t.id_audit_req_prof,
       t.id_reports_gen_param,
       t.signed_binary_file,
       t.flg_signed,
       t.id_patient,
       t.id_social_episode,
       t.id_visit,
       t.id_external_request,
       t.id_audit_req,
       t.dig_sig_type,
       t.temporary_signed_binary_file,
       t.flg_confidential,
       t.elapsed_time,
       t.json_params,
       t.id_doc_external,
       t.epis_report_thumbnail,
       t.flg_report_origin,
       t.dt_timeframe_begin,
       t.dt_timeframe_end,
       t.flg_background,
       t.flg_date_filters,
       t.flg_disclosure,
       t.flg_encrypted,
       t.rep_binary_encrypted_file,  
       t.id_professional_req
  FROM epis_report t;
