CREATE OR REPLACE VIEW V_EPIS_RECOMEND AS
SELECT ID_EPIS_RECOMEND,
       DESC_EPIS_RECOMEND_CLOB DESC_EPIS_RECOMEND,  
       FLG_TYPE,
       ID_EPISODE,
       ID_PROFESSIONAL,
       FLG_TEMP,
       DT_EPIS_RECOMEND_TSTZ,
       ID_NOTES_CONFIG,
       SESSION_ID,	
       ID_ITEM,	
       ID_PATIENT
FROM epis_recomend;
 
