CREATE OR REPLACE VIEW V_EPIS_OBSERVATION AS
SELECT ID_EPIS_OBSERVATION,      
       DESC_EPIS_OBSERVATION,    
       ID_EPISODE,
       ID_PROFESSIONAL,  
       FLG_TEMP,
       ID_INSTITUTION,
       ID_SOFTWARE,
       FLG_TYPE,
       DT_EPIS_OBSERVATION_TSTZ,     
       ID_EPIS_OBSERVATION_PARENT,
       FLG_STATUS,
       FLG_EDITION_TYPE
FROM EPIS_OBSERVATION;
 
