-->V_EPIS_PROF_RESP
CREATE OR REPLACE VIEW V_EPIS_PROF_RESP AS
SELECT epr.id_epis_prof_resp,
       epr.id_episode,
       epr.id_prof_req,
       epr.id_prof_to,
       epr.id_prof_comp,
       epr.id_speciality,
       epr.id_movement,
       epr.notes_clob notes,
       epr.flg_type,
       epr.flg_status,
       epr.id_prof_decline,
       epr.id_prof_cancel,
       epr.notes_cancel,
       epr.trf_reason,
       epr.trf_answer,
       epr.id_room,
       epr.id_bed,
       epr.id_department_orig,
       epr.id_department_dest,
       epr.id_prof_execute,
       epr.transport_notes,
       epr.id_prof_prev,
       epr.flg_transfer,
       epr.id_bed_execute,
       epr.id_room_execute,
       epr.flg_escort,
       epr.flg_transf_type,
       epr.id_clinical_service_orig,
       epr.id_clinical_service_dest,
       epr.dt_request_tstz,
       epr.dt_cancel_tstz,
       epr.dt_decline_tstz,
       epr.dt_comp_tstz,
       epr.dt_trf_requested_tstz,
       epr.dt_trf_accepted_tstz,
       epr.dt_execute_tstz,
       epr.dt_end_transfer_tstz,
       empr.flg_profile,
       epr.id_cancel_reason,
       (SELECT cr.code_cancel_reason
          FROM cancel_reason cr
         WHERE cr.id_cancel_reason = epr.id_cancel_reason) code_cancel_reason,
       empr.flg_main_responsible,
       empr.flg_resp_type,
       empr.flg_status AS epis_multi_resp_flg_status,
       empr.id_speciality AS epis_multi_resp_id_speciality,
	   empr.id_professional AS epis_multi_resp_id_prof
  FROM epis_prof_resp epr
  LEFT JOIN epis_multi_prof_resp empr ON empr.id_epis_prof_resp = epr.id_epis_prof_resp;
