CREATE OR REPLACE VIEW V_EPIS_OUT_ON_PASS AS
  SELECT eoop.id_epis_out_on_pass,
         eoop.id_patient,
         eoop.id_episode,
         eoop.id_status,
         eoop.id_request_reason,
         eoop.code_request_reason,
         eoop.dt_out,
         eoop.dt_in,
         eoop.total_allowed_hours,
         eoop.flg_attending_physic_agree,
         eoop.code_note_admission_office,
         eoop.code_other_notes,
         eoop.id_conclude_reason,
         eoop.id_cancel_reason,
         eoop.code_cancel_reason,
         eoop.dt_last_update,
         eoop.id_prof_last_update,
         eoop.create_user,
         eoop.create_time,
         eoop.create_institution,
         eoop.update_user,
         eoop.update_time,
         eoop.update_institution,
         eoop.id_workflow,
         eoop.dt_in_returned,
         eoop.code_conclude_notes,
         eoop.code_start_notes,
         eoop.id_requested_by,
         eoop.code_requested_by,
         eoop.patient_contact_number
    FROM epis_out_on_pass eoop;
