CREATE OR REPLACE VIEW ALERT.V_EPIS_DOCUMENTATION_DET AS
SELECT ID_EPIS_DOCUMENTATION_DET,
       ID_EPIS_DOCUMENTATION,
       ID_DOCUMENTATION,
       ID_DOC_ELEMENT,
       ID_DOC_ELEMENT_CRIT,
       VALUE,
       NOTES,
       ID_PROFESSIONAL,
       DT_CREATION_TSTZ,
       ADW_LAST_UPDATE,
       VALUE_PROPERTIES
FROM epis_documentation_det;
