CREATE OR REPLACE VIEW v_exam_request AS
SELECT er.id_exam_req,
       er.id_patient,
       er.id_episode,
       er.id_episode_origin,
       er.id_episode_destination,
       er.id_prev_episode,
       er.id_visit,
       er.id_institution,
       er.flg_time,
       er.flg_status,
       er.id_prof_req,
       er.dt_req_tstz,
       er.dt_begin_tstz,
       er.dt_schedule_tstz,
       er.dt_pend_req_tstz,
       er.priority,
       er.id_exec_institution,
       er.barcode,
       er.id_prof_authorize,
       er.id_prof_approve,
       er.id_schedule,
       er.id_sched_consult,
       er.id_prof_cancel,
       er.dt_cancel_tstz,
       er.id_cancel_reason,
       er.notes_cancel,
       er.flg_contact,
       er.dt_contact,
       er.id_exam_group,
       er.id_prof_last_update,
       er.dt_last_update_tstz,
       e.id_epis_type
  FROM exam_req er
  LEFT JOIN episode e
    ON er.id_episode = e.id_episode;
