CREATE OR REPLACE VIEW V_EXAM AS
SELECT e.id_exam,
       e.code_exam,
       e.flg_pat_resp,
       e.flg_pat_prep,
       e.duration,
       e.result_time,
       e.INTERVAL,
       e.flg_mov_pat,
       e.cost,
       e.price,
       e.code_help_exam,
       e.flg_available,
       e.flg_type,
       e.gender,
       e.age_min,
       e.age_max,
       e.id_exam_cat,
       e.mdm_coding,
       e.cpt_code,
       e.ref_form_code,
       e.id_content,
       e.barcode,
	   e.rank,
	   e.flg_technical
  FROM exam e;