CREATE OR REPLACE VIEW v_exam_request_detail AS
SELECT erd.id_exam_req_det,
       erd.id_exam_req,
       erd.id_exam,
       erd.id_exam_group,
       erd.id_erd_parent,
       e.code_exam,
       e.flg_type,
       e.id_exam_cat,
       ec.code_exam_cat,
       e.id_content,
       erd.flg_status,
       erd.flg_referral,
       erd.dt_target_tstz,
       erd.dt_final_target_tstz,
       erd.dt_final_result_tstz,
       erd.id_order_recurrence,
       erd.flg_priority,
       erd.flg_prn,
       erd.prn_notes,
       erd.flg_fasting,
       erd.id_clinical_purpose,
       erd.clinical_purpose_notes,
       erd.flg_laterality,
       erd.flg_pre_req,
       erd.flg_location,
       erd.id_room,
       erd.id_exec_institution,
       erd.id_movement,
       erd.barcode request_detail_barcode,
       erd.notes,
       erd.notes_scheduler,
       erd.notes_tech,
       erd.notes_patient,
       erd.id_exam_codification,
       erd.id_pat_health_plan,
       erd.id_pat_exemption,
       erd.id_task_dependency,
       erd.id_cdr,
       erd.id_pat_pregnancy,
       erd.id_co_sign_order,
       erd.id_prof_performed,
       erd.start_time,
       erd.end_time,
       erd.prof_dep_clin_serv,
       erd.id_prof_performed_reg,
       erd.dt_performed_reg,       
       erd.id_prof_cancel,
       erd.dt_cancel_tstz,
       erd.id_cancel_reason,
       erd.notes_cancel,
       cr.code_cancel_reason,
			 erd.id_co_sign_cancel,
       erd.flg_req_origin_module,
       erd.id_prof_last_update,
       erd.dt_last_update_tstz,
       NULL                      flg_ref_type,
       NULL                      id_prof_ref,
       NULL                      id_inst_ref
  FROM exam_req_det erd
  JOIN exam e
    ON erd.id_exam = e.id_exam
  LEFT JOIN exam_cat ec
    ON e.id_exam_cat = ec.id_exam_cat
  LEFT JOIN cancel_reason cr
    ON erd.id_cancel_reason = cr.id_cancel_reason;
