CREATE OR REPLACE VIEW V_GRID_CDOC_BASE_02 AS
SELECT /*+ index(v.e epis_search08_idx) */
 v.flg_status_discharge,
 v.e_id_department,
 v.e_id_visit,
 v.v_id_origin,
 v.id_institution,
 v.id_visit,
 v.e_flg_ehr,
 v.e_dt_begin_tstz,
 v.e_flg_status,
 v.e_id_episode,
 v.e_id_fast_track,
 v.dt_begin_tstz,
 v.dt_end_tstz,
 v.e_dt_cancel_tstz,
 v.ei_id_episode,
 v.ei_id_software,
 v.ei_id_professional,
 v.ei_id_first_nurse_resp,
 v.ei_id_room,
 v.ei_id_dep_clin_serv,
 v.acuity,
 v.color_text,
 v.triage_flg_letter,
 v.id_triage_color,
 v.rank_acuity,
 v.id_first_nurse_resp,
 v.dt_first_obs_tstz,
 v.epis_info_flg_status,
 v.ei_id_schedule,
 v.gt_id_episode,
 v.gt_drug_presc,
 v.gt_icnp_intervention,
 v.gt_nurse_activity,
 v.gt_intervention,
 v.gt_monitorization,
 v.gt_teach_req,
 v.gt_movement,
 v.gt_discharge_pend,
 v.oth_exam_n,
 v.oth_exam_d,
 v.img_exam_n,
 v.img_exam_d,
 v.opinion_state,
 v.pat_gender,
 v.id_patient,
 v.ei_nick_name,
 v.ei_name,
 v.id_epis_type,
 v.sys_institution,
 v.sys_lang,
 v.sys_software,
 v.sys_prof_id,
 v.sys_lprof,
 v.sys_yes,
 v.sys_no,
 v.dt_med_tstz,
 v.dt_pend_tstz,
 v.dt_admin_tstz
  FROM v_grid_cdoc_base v
 WHERE v.e_flg_status = alert_context('g_epis_status_inactive')
   AND v.dt_end_tstz >
       CAST((current_timestamp - numtodsinterval(alert_context('l_edis_timelimit'), 'HOUR')) AS TIMESTAMP WITH LOCAL TIME ZONE);
