create or replace view v_grid_outp_nurse_app_dcs as
SELECT view_id,
       get_schedule_real_state,
       cmpt_code_complaint,
       flg_group_header,
       e_id_department,
       e_id_visit,
       e_flg_ehr,
       e_flg_status,
       e_dt_begin_tstz,
       ec_id_complaint,
       ec_patient_complaint,
       ei_id_episode,
       ei_id_software,
       ei_id_professional,
       ei_id_first_nurse_resp,
       ei_id_room,
       ei_id_dep_clin_serv,
       ei_nick_name,
       ei_name,
       prof_ei_name,
       gt_id_episode,
       gt_drug_presc,
       gt_icnp_intervention,
       gt_nurse_activity,
       gt_intervention,
       gt_monitorization,
       gt_teach_req,
       pat_gender,
       ps_nick_name,
       ps_name,
       prof_ps_name,
       ps_id_professional,
       s_id_schedule,
       s_id_group,
       s_flg_present,
       s_id_dcs_requested,
       s_id_sch_event,
       se_code_sch_event,
       sg_flg_contact_type,
       sp_dt_target_tstz,
       sp_id_epis_type,
       sp_flg_state,
       sp_flg_sched,
       sp_id_software,
       s_flg_status,
       se_id_sch_event,
       sg_id_patient,
       sys_institution,
       sys_lang,
       sys_software,
       sys_prof_id,
       sys_dt_min,
       sys_dt_max,
       sys_sched_adm_disch,
       sys_epis_type_nurse,
       s_id_instit_requested,
       sys_lprof,
       sys_no,
       sys_yes,
       e_id_epis_type
  FROM v_grid_outp_base vg
  JOIN prof_dep_clin_serv pdcs
    ON pdcs.id_dep_clin_serv = s_id_dcs_requested
 WHERE pdcs.id_professional = sys_prof_id
   AND pdcs.flg_status = 'S';
