CREATE OR REPLACE VIEW V_GRID_OUTP_BASE_TODAY AS
SELECT view_type view_id,
       ( select pk_grid.get_schedule_real_state(v00.sp_flg_state, v00.e_flg_ehr) from dual ) get_schedule_real_state,
       cmpt_code_complaint,
       flg_group_header,
       e_id_department,
       e_id_visit,
       e_flg_ehr,
       e_flg_status,
       e_dt_begin_tstz,
       ec_id_complaint,
       ec_patient_complaint,
       ei_id_episode,
       ei_id_software,
       ei_id_professional,
       ei_id_first_nurse_resp,
       ei_id_room,
       ei_id_dep_clin_serv,
       ei_nick_name,
       ei_name,
       nvl(ei_name, ei_nick_name) prof_ei_name,
       gt_id_episode,
       gt_drug_presc,
       gt_icnp_intervention,
       gt_nurse_activity,
       gt_intervention,
       gt_monitorization,
       gt_teach_req,
       pat_gender,
       ps_nick_name,
       ps_name,
       nvl(ps_name, ps_nick_name) prof_ps_name,
       ps_id_professional,
       s_id_schedule,
       s_id_group,
       s_flg_present,
       s_id_dcs_requested,
       s_id_sch_event,
       se_code_sch_event,
       sg_flg_contact_type,
       sp_dt_target_tstz,
       sp_id_epis_type,
       sp_flg_state,
       sp_flg_sched,
       sp_id_software,
       s_flg_status,
       se_id_sch_event,
       sg_id_patient,
       sys_institution,
       sys_lang,
       sys_software,
       sys_prof_id,
       sys_dt_min,
       sys_dt_max,
       sys_sched_adm_disch,
       sys_epis_type_nurse,
       s_id_instit_requested,
       sys_lprof,
       sys_no,
       sys_yes,
       flg_leader,
       e_id_epis_type
  FROM (SELECT view_type,
               cmpt_code_complaint,
               flg_group_header,
               e_id_department,
               e_id_visit,
               e_flg_ehr,
               e_flg_status,
               e_dt_begin_tstz,
               ec_id_complaint,
               ec_patient_complaint,
               ei_id_episode,
               ei_id_software,
               ei_id_professional,
               ei_id_first_nurse_resp,
               ei_id_room,
               ei_id_dep_clin_serv,
               ei_nick_name,
               ei_name,
               gt_id_episode,
               gt_drug_presc,
               gt_icnp_intervention,
               gt_nurse_activity,
               gt_intervention,
               gt_monitorization,
               gt_teach_req,
               pat_gender,
               ps_nick_name,
               ps_name,
               ps_id_professional,
               s_id_schedule,
               s_id_group,
               s_flg_present,
               s_id_dcs_requested,
               s_id_sch_event,
               se_code_sch_event,
               sg_flg_contact_type,
               sp_dt_target_tstz,
               sp_id_epis_type,
               sp_flg_state,
               sp_flg_sched,
               sp_id_software,
               s_flg_status,
               se_id_sch_event,
               sg_id_patient,
               sys_institution,
               sys_lang,
               sys_software,
               sys_prof_id,
               (SELECT pk_date_utils.get_string_tstz(i_lang      => sys_lang,
                                                     i_prof      => sys_lprof,
                                                     i_timestamp => alert_context('i_dt'),
                                                     i_timezone  => '')
                  FROM dual) sys_dt_min,
               (SELECT pk_date_utils.add_to_ltstz(i_timestamp => pk_date_utils.add_days(i_lang   => sys_lang,
                                                                                        i_prof   => sys_lprof,
                                                                                        i_date   => pk_date_utils.get_string_tstz(i_lang      => sys_lang,
                                                                                                                                  i_prof      => sys_lprof,
                                                                                                                                  i_timestamp => alert_context('i_dt'),
                                                                                                                                  i_timezone  => ''),
                                                                                        i_amount => alert_context('AMOUNT')),
                                                  i_amount    => -1,
                                                  i_unit      => 'SECOND')
                  FROM dual) sys_dt_max,
               sys_sched_adm_disch,
               sys_epis_type_nurse,
               s_id_instit_requested,
               sys_lprof,
               sys_no,
               sys_yes,
               flg_leader,
               e_id_epis_type
          FROM v_grid_outp_base_today_00 v0
         WHERE v0.s_flg_status NOT IN ('V')
              --and v0.sp_id_epis_type != v0.sys_epis_type_nurse
           AND v0.s_id_instit_requested = v0.sys_institution
           AND sp_id_epis_type<>50 
           AND v0.flg_leader = decode(alert_context('filter_leader'), 'Y', 'Y', v0.flg_leader)) v00
;
