-- CHANGED BY: Telmo Castro
-- CHANGE DATE: 12-03-2010
-- CHANGE REASON: SCH-386
CREATE OR REPLACE VIEW V_LANGUAGE AS 
SELECT ID_LANGUAGE,DESC_LANGUAGE,FLG_AVAILABLE,NLS_CODE,LOCALE,FLG_AVAILABLE_ONLINE, CODE_LANGUAGE FROM LANGUAGE;

-- CHANGE END: Telmo Castro