-- CHANGED BY: Telmo Castro
-- CHANGE DATE: 12-03-2010
-- CHANGE REASON: SCH-386
CREATE OR REPLACE VIEW V_MARKET AS
SELECT ID_MARKET, ID_CONTENT, DESC_MARKET, FLG_AVAILABLE, CODE_MARKET
  FROM MARKET;
-- CHANGE END: Telmo Castro