CREATE OR REPLACE VIEW V_MAIN_VWR_CHECKLIST_CFG AS
SELECT
 VC.ID_VIEWER_CHECKLIST   ID_RECORD
,VC.CHECKLIST_INTERNAL_NAME  CHKLIST_INTERNAL_NAME
,VC.id_application_file  ID_APPLICATION_FILE
,CT.ID_CONFIG             ID_CONFIG
,CT.ID_INST_OWNER         ID_INST_OWNER
,CT.FIELD_01              ORDER_RANK
,CT.FIELD_02              FLG_DEFAULT
FROM ALERT_CORE_DATA.CONFIG_TABLE         CT
JOIN VIEWER_CHECKLIST VC ON VC.ID_VIEWER_CHECKLIST = CT.ID_RECORD
WHERE CT.CONFIG_TABLE = 'MAIN_VWR_CHECKLIST';
