CREATE OR REPLACE VIEW v_mcdt_req_diagnosis AS
SELECT mrd.id_mcdt_req_diagnosis,
       mrd.id_diagnosis,
       mrd.id_epis_diagnosis,
       mrd.id_exam_req,
       mrd.id_analysis_req,
       mrd.id_interv_prescription,
       mrd.flg_status,
       mrd.id_prof_cancel,
       mrd.dt_cancel,
       mrd.id_exam_req_det,
       mrd.id_analysis_req_det,
       mrd.id_interv_presc_det,
       mrd.dt_cancel_tstz,
       mrd.id_epis_complication,
       mrd.id_epis_comp_hist,
       mrd.id_diag_inst_owner,
       mrd.id_alert_diagnosis,
       mrd.id_adiag_inst_owner,
       mrd.id_nurse_tea_req,
       mrd.id_exam_result,
       mrd.id_blood_product_req,
       mrd.id_blood_product_det
FROM mcdt_req_diagnosis mrd;