CREATE OR REPLACE VIEW v_monitorization_list AS
SELECT id_vital_sign,
       val_min,
       val_max,
       rank,
       rank_conc,
       id_vital_sign_parent,
       relation_type,
       format_num,
       flg_fill_type,
       flg_sum,
       name_vs,
       desc_unit_measure,
       id_unit_measure,
       dt_server,
       flg_view,
       id_institution,
       id_software
  FROM TABLE(pk_vital_sign.tf_get_vs_header(alert_context('i_lang'),
                                            profissional(alert_context('i_prof_id'),
                                                         alert_context('i_prof_institution'),
                                                         alert_context('i_prof_software')),
                                            alert_context('l_flg_view'),
                                            alert_context('l_institution'),
                                            alert_context('l_software'),
                                            alert_context('l_dt_end'),
                                            alert_context('l_patient')));
