DECLARE
    e_not_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_not_exist, -00942);
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW V_MYPAT_PHARM_GRID_AMB_DISP';
EXCEPTION
    WHEN e_not_exist THEN
        NULL;
END;
/
