CREATE OR REPLACE VIEW V_OPINION AS
SELECT o.id_opinion,
       o.id_episode,
       o.id_patient,
       o.flg_state,
       o.desc_problem,
       o.id_prof_questions,
       o.id_prof_questioned,
       o.id_speciality,
       o.id_cancel_reason,
       o.notes_cancel,
       o.dt_cancel_tstz,
       o.dt_problem_tstz,
       o.status_flg,
       o.status_icon,
       o.status_msg,
       o.status_str,
       o.flg_type,
       o.id_management_level,
       o.id_episode_answer,
       o.dt_last_update,
       o.id_opinion_type,
       o.id_clinical_service,
       o.dt_approved,
       o.id_prof_approved,
       o.notes,
       o.id_episode_approval,
       o.id_prof_cancel
  FROM opinion o;
