CREATE OR REPLACE VIEW V_OUTP_BETW_ALL AS
SELECT
  '00_OUTP_BETWEEN' view_id,
  pat.gender,
  v_all.x_min_dt_treatment,
  v_all.id_schedule,
  v_all.id_patient,
  v_all.id_episode,
  v_all.id_visit,
  v_all.id_epis_type,
  v_all.flg_ehr,
  v_all.dt_begin_tstz,
  v_all.flg_status,
  v_all.flg_state,
  v_all.sp_flg_state,
  v_all.id_dep_clin_serv,
  v_all.flg_sched,
  v_all.id_room,
  v_all.flg_appointment_type,
  v_all.flg_contact_type,
  v_all.flg_drug,
  v_all.gt_drug_presc,
  v_all.flg_interv,
  v_all.gt_interv_presc,
  v_all.flg_monit,
  v_all.gt_monit,
  v_all.flg_nurse_act,
  v_all.gt_nurse_act,
  v_all.id_dcs_requested    ,
  v_all.sys_no          ,
  v_all.sys_yes                 ,
  v_all.k_sched_status_cache    ,
  v_all.sys_selected            ,
  v_all.sys_flg_ehr_n           ,
  v_all.sys_flg_ehr_s           ,
  v_all.k_episode_type_interv   ,
  v_all.sys_institution         ,
  v_all.sys_lang                ,
  v_all.sys_software            ,
  v_all.sys_prof_id             ,
  v_all.sys_lprof,
  v_all.sys_epis_status_active  ,
  v_all.sys_epis_status_inactive,
v_all.sys_g_epis_type_nurse      sys_g_epis_type_nurse,
v_all.sys_use_team_filter              sys_use_team_filter,
v_all.sys_epis_type                    sys_epis_type,
v_all.sys_waiting_room_available       sys_waiting_room_available,
v_all.sys_waiting_room_sys_external    sys_waiting_room_sys_external,
v_all.g_sysdate                        g_sysdate
from
  (
  select
    pk_grid.min_dt_treatment( v1.sys_lang, v1.sys_lprof, v1.id_episode) x_min_dt_treatment,
    v1.id_patient       id_patient,
    v1.id_schedule       id_schedule,
    v1.id_episode        id_episode,
    v1.id_visit      id_visit,
    v1.id_epis_type       id_epis_type,
    v1.flg_ehr         flg_ehr,
    v1.dt_begin_tstz       dt_begin_tstz,
    v1.flg_status      flg_status,
    v1.flg_state        flg_state,
    v1.flg_state        sp_flg_state,
    v1.flg_sched        flg_sched,
    v1.flg_appointment_type    flg_appointment_type,
    v1.flg_contact_type     flg_contact_type,
    v1.ei_id_dep_clin_serv     id_dep_clin_serv,
    v1.id_room          id_room,
    v1.flg_drug         flg_drug,
    v1.gt_drug_presc        gt_drug_presc,
    v1.flg_interv        flg_interv,
    v1.gt_interv_presc       gt_interv_presc,
    v1.flg_monitor       flg_monit,
    v1.gt_monit          gt_monit,
    v1.flg_nurse_act     flg_nurse_act,
    v1.gt_nurse_act       gt_nurse_act,
    v1.id_dcs_requested       id_dcs_requested,
    v1.sys_no           sys_no          ,
    v1.sys_yes                      sys_yes                 ,
    v1.k_sched_status_cache         k_sched_status_cache    ,
    v1.sys_selected                 sys_selected            ,
    v1.sys_flg_ehr_n                sys_flg_ehr_n           ,
    v1.sys_flg_ehr_s                sys_flg_ehr_s           ,
    v1.k_episode_type_interv        k_episode_type_interv   ,
    v1.sys_institution              sys_institution         ,
    v1.sys_lang                     sys_lang                ,
    v1.sys_software                 sys_software            ,
    v1.sys_prof_id                  sys_prof_id             ,
    v1.sys_lprof                    sys_lprof,
    v1.sys_epis_status_active       sys_epis_status_active  ,
    v1.sys_epis_status_inactive     sys_epis_status_inactive
   ,v1.sys_g_epis_type_nurse      sys_g_epis_type_nurse
   ,v1.sys_use_team_filter              sys_use_team_filter
   ,v1.sys_epis_type                    sys_epis_type
   ,v1.sys_waiting_room_available       sys_waiting_room_available
   ,v1.sys_waiting_room_sys_external    sys_waiting_room_sys_external
   ,v1.g_sysdate                        g_sysdate
  from v_outp_betw_1 v1
  union all
  select
    pk_grid.min_dt_treatment( v2.sys_lang, v2.sys_lprof, v2.id_episode) x_min_dt_treatment,
    v2.id_patient         id_patient,
    v2.id_Schedule          id_schedule,
    v2.id_episode         id_episode,
    v2.id_visit           id_visit,
    v2.id_epis_type         id_epis_type,
    v2.flg_ehr            flg_ehr,
    v2.dt_begin_tstz        dt_begin_tstz,
    v2.flg_status         flg_status,
    v2.flg_state          flg_state,
    v2.sp_flg_state          sp_flg_state,
    v2.flg_sched          flg_sched,
    v2.flg_appointment_type     flg_appointment_type,
    v2.flg_contact_type       flg_contact_type,
    v2.id_dcs_requested       id_dep_clin_serv,
    v2.id_room            id_room,
    v2.flg_drug           flg_drug,
    v2.gt_drug_presc        gt_drug_presc,
    v2.flg_interv         flg_interv,
    v2.gt_interv_presc        gt_interv_presc,
    v2.flg_monitor          flg_monit,
    v2.gt_monit          gt_monit,
    v2.flg_nurse_act        flg_nurse_act,
    v2.gt_nurse_act         gt_nurse_act,
    v2.id_dcs_requested       id_dcs_requested,
    v2.sys_no           sys_no          ,
    v2.sys_yes                      sys_yes                 ,
    v2.k_sched_status_cache         k_sched_status_cache    ,
    v2.sys_selected                 sys_selected            ,
    v2.sys_flg_ehr_n                sys_flg_ehr_n           ,
    v2.sys_flg_ehr_s                sys_flg_ehr_s           ,
    v2.k_episode_type_interv        k_episode_type_interv   ,
    v2.sys_institution              sys_institution         ,
    v2.sys_lang                     sys_lang                ,
    v2.sys_software                 sys_software            ,
    v2.sys_prof_id                  sys_prof_id             ,
    v2.sys_lprof                    sys_lprof,
    v2.sys_epis_status_active       sys_epis_status_active  ,
    v2.sys_epis_status_inactive     sys_epis_status_inactive
   ,v2.sys_g_epis_type_nurse      sys_g_epis_type_nurse
   ,v2.sys_use_team_filter              sys_use_team_filter
   ,v2.sys_epis_type                    sys_epis_type
   ,v2.sys_waiting_room_available       sys_waiting_room_available
   ,v2.sys_waiting_room_sys_external    sys_waiting_room_sys_external
   ,v2.g_sysdate                        g_sysdate
  from v_outp_betw_2 v2
  ) V_ALL
join patient pat on pat.id_patient = V_ALL.id_patient;
