CREATE OR REPLACE VIEW V_P1_GRID_TR AS
SELECT v1.id_external_request,
       v1.num_req,
       v1.flg_type,
       v1.dt_requested,
       v1.flg_status,
       v1.dt_status_tstz,
       v1.flg_priority,
       v1.id_speciality,
       v1.code_speciality,
       v1.decision_urg_level,
       v1.id_prof_requested,
       v1.id_inst_orig,
       v1.code_inst_orig,
       v1.abbrev_inst_orig,
       v1.institution_name_roda,
       v1.id_inst_dest,
       v1.code_inst_dest,
       v1.inst_dest_abbrev,
       v1.id_dep_clin_serv,
       v1.id_prof_redirected,
       v1.id_schedule,
       v1.id_prof_schedule,
       v1.dt_schedule_tstz,
       v1.dt_efectiv_tstz,
       v1.id_patient,
       v1.pat_name,
       v1.pat_gender,
       v1.pat_age,
       v1.pat_dt_birth,
       v1.dep_abbreviation,
       v1.code_department,
       v1.code_clinical_service,
       v1.id_match,
       v1.id_prof_status,
       v1.dt_issued,
       v1.id_prof_triage,
       v1.dt_triage,
       v1.dt_forwarded,
       v1.dt_acknowledge,
       v1.dt_new,
       v1.dt_last_interaction_tstz,
       v1.id_workflow,
       tr.id_trans_resp,
       tr.dt_update                tr_dt_update,
       tr.id_prof_dest             tr_id_prof_dest,
       tr.id_prof_transf_owner     tr_id_prof_transf_owner,
       tr.id_status                tr_id_status,
       tr.id_trans_resp            tr_id_trans_resp,
       tr.id_workflow              tr_id_workflow,
       tr.id_inst_orig_tr          tr_id_inst_orig,
       tr.id_inst_dest_tr          tr_id_inst_dest,
       v1.id_prof_orig,
       v1.id_external_sys,
       v1.id_prof_sch_sugg,
       v1.flg_migrated
  FROM v_p1_grid v1
  LEFT JOIN ref_trans_responsibility tr
    ON (tr.id_external_request = v1.id_external_request AND tr.flg_active = 'Y');
