CREATE OR REPLACE VIEW V_PHY_DISCHARGE_NOTES AS
SELECT ID_PHY_DISCHARGE_NOTES,
       ID_PATIENT,
       ID_PROFESSIONAL,
       ID_EPISODE,
       FLG_STATUS,
       DT_CREATION,
       ID_CANCEL_REASON,	
       CANCEL_NOTES,	
       DT_CANCEL,	
       ID_PROFESSIONAL_CANCEL,	
       UPDATE_INSTITUTION,
       NOTES
FROM phy_discharge_notes;
 
