CREATE OR REPLACE VIEW v_proc_hand_off AS
SELECT ipd.id_interv_presc_det,
       ipd.id_intervention,
       ipd.flg_status,
       ipp.flg_status status_plan,
       pk_tools.get_prof_nick_name(sys_context('ALERT_CONTEXT', 'ID_LANG'), cso.id_prof_ordered_by) prof_order,
       ip.flg_time,
       decode(ipd.flg_interv_type,
              'S',
              NULL,
              decode(ip.flg_time,
                     'N',
                     pk_date_utils.dt_chr_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                              ipp.start_time,
                                              profissional(sys_context('ALERT_CONTEXT', 'ID_PROFESSIONAL'),
                                                           sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                           sys_context('ALERT_CONTEXT', 'ID_SOFTWARE'))),
                     decode(ip.id_episode_origin,
                            NULL,
                            pk_date_utils.dt_chr_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                     nvl(ipp.dt_plan_tstz, ip.dt_begin_tstz),
                                                     sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                     sys_context('ALERT_CONTEXT', 'ID_SOFTWARE')),
                            pk_date_utils.dt_chr_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                     epi.dt_begin_tstz,
                                                     sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                     sys_context('ALERT_CONTEXT', 'ID_SOFTWARE'))))) date_target,
       nvl(ipp.dt_plan_tstz, ip.dt_begin_tstz) dt_target,
       pk_procedures_api_db.get_alias_translation(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                  profissional(sys_context('ALERT_CONTEXT', 'ID_PROFESSIONAL'),
                                                               sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                               sys_context('ALERT_CONTEXT', 'ID_SOFTWARE')),
                                                  i.code_intervention,
                                                  NULL) || ' ' || '(' ||
       decode(ipd.flg_interv_type,
              'U',
              pk_sysdomain.get_domain('INTERV_PRESC_DET.FLG_INTERV_TYPE',
                                      ipd.flg_interv_type,
                                      sys_context('ALERT_CONTEXT', 'ID_LANG')),
              'S',
              pk_sysdomain.get_domain('INTERV_PRESC_DET.FLG_INTERV_TYPE',
                                      ipd.flg_interv_type,
                                      sys_context('ALERT_CONTEXT', 'ID_LANG')),
              'A',
              pk_sysdomain.get_domain('INTERV_PRESC_DET.FLG_INTERV_TYPE',
                                      ipd.flg_interv_type,
                                      sys_context('ALERT_CONTEXT', 'ID_LANG')) || ', ' ||
              decode(ip.flg_time,
                     'B',
                     to_char(trunc(ipd.interval / 86400)),
                     to_char(to_date(MOD(ipd.interval, 86400), 'SSSSS'), 'HH24:MI')) || '/' ||
              decode(ip.flg_time,
                     'B',
                     to_char(trunc(ipd.interval / 86400)) ||
                     decode(trunc(ipd.interval / 86400),
                            1,
                            pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'DRUG_PRESC_M008'),
                            pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'DRUG_PRESC_M006')),
                     to_char(to_date(MOD(ipd.interval, 86400), 'SSSSS'), 'HH24:MI') || 'h'),
              'N',
              pk_sysdomain.get_domain('INTERV_PRESC_DET.FLG_INTERV_TYPE',
                                      ipd.flg_interv_type,
                                      sys_context('ALERT_CONTEXT', 'ID_LANG')) || ', ' || ipd.num_take || ', ' ||
              decode(ip.flg_time,
                     'B',
                     to_char(trunc(ipd.interval / 86400)),
                     to_char(to_date(MOD(ipd.interval, 86400), 'SSSSS'), 'HH24:MI')) || '/' ||
              decode(ip.flg_time,
                     'B',
                     to_char(trunc(ipd.interval / 86400)) ||
                     decode(trunc(ipd.interval / 86400),
                            1,
                            pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'DRUG_PRESC_M008'),
                            pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'DRUG_PRESC_M006')),
                     to_char(to_date(MOD(ipd.interval, 86400), 'SSSSS'), 'HH24:MI') || 'h')) || ')' ||
       decode(epi.id_epis_type,
              nvl(t_ti_log.get_epis_type(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                         profissional(sys_context('ALERT_CONTEXT', 'ID_PROFESSIONAL'),
                                                      sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                      sys_context('ALERT_CONTEXT', 'ID_SOFTWARE')),
                                         epi.id_epis_type,
                                         ipd.flg_status,
                                         ipd.id_interv_presc_det,
                                         'PR'),
                  epi.id_epis_type),
              '',
              ' - (' ||
              pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                     profissional(profissional(sys_context('ALERT_CONTEXT', 'ID_PROFESSIONAL'), sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'), sys_context('ALERT_CONTEXT', 'ID_SOFTWARE')).id,
                                                  sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                  t_ti_log.get_epis_type_soft(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                                              profissional(sys_context('ALERT_CONTEXT',
                                                                                                       'ID_PROFESSIONAL'),
                                                                                           sys_context('ALERT_CONTEXT',
                                                                                                       'ID_INSTITUTION'),
                                                                                           sys_context('ALERT_CONTEXT',
                                                                                                       'ID_SOFTWARE')),
                                                                              epi.id_epis_type,
                                                                              ipd.flg_status,
                                                                              ipd.id_interv_presc_det,
                                                                              'PR')),
                                     'IMAGE_T009') || ')') desc_intervenction,
       decode(ipd.flg_referral,
              'R',
              pk_sysdomain.get_img(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                   'INTERV_PRESC_DET.FLG_REFERRAL',
                                   ipd.flg_referral),
              'S',
              pk_sysdomain.get_img(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                   'INTERV_PRESC_DET.FLG_REFERRAL',
                                   ipd.flg_referral),
              decode(ip.id_episode_origin,
                     NULL,
                     decode(ipd.flg_status,
                            'F',
                            pk_sysdomain.get_img(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                 'INTERV_PRESC_DET.FLG_STATUS',
                                                 'F'),
                            'C',
                            pk_sysdomain.get_img(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                 'INTERV_PRESC_DET.FLG_STATUS',
                                                 'C'),
                            'I',
                            pk_sysdomain.get_img(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                 'INTERV_PRESC_DET.FLG_STATUS',
                                                 'I'),
                            decode(ipd.flg_interv_type,
                                   'S',
                                   pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'DRUG_PRESC_M004'),
                                   'C',
                                   decode(ip.flg_status,
                                          'R',
                                          decode(ip.flg_time,
                                                 'N',
                                                 pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'ICON_T056'),
                                                 pk_date_utils.get_elapsed_abs_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                                                   nvl(ipp.dt_plan_tstz,
                                                                                       ip.dt_interv_prescription_tstz))),
                                          'D',
                                          decode(ip.flg_time,
                                                 'N',
                                                 pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'ICON_T056'),
                                                 pk_date_utils.get_elapsed_abs_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                                                   nvl(ipp.dt_plan_tstz,
                                                                                       ip.dt_interv_prescription_tstz))),
                                          NULL),
                                   decode(ip.flg_time,
                                          'N',
                                          pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'ICON_T056'),
                                          pk_date_utils.get_elapsed_abs_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                                            nvl(ipp.dt_plan_tstz,
                                                                                ip.dt_interv_prescription_tstz))))),
                     decode(ipd.flg_status,
                            'F',
                            pk_sysdomain.get_img(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                 'INTERV_PRESC_DET.FLG_STATUS',
                                                 'F'),
                            'C',
                            pk_sysdomain.get_img(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                 'INTERV_PRESC_DET.FLG_STATUS',
                                                 'C'),
                            'I',
                            pk_sysdomain.get_img(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                 'INTERV_PRESC_DET.FLG_STATUS',
                                                 'I'),
                            'R',
                            pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'ICON_T056'),
                            'D',
                            decode(ip.dt_begin_tstz,
                                   NULL,
                                   pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'ICON_T056'),
                                   pk_date_utils.get_elapsed_abs_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                                     nvl(ipp.dt_plan_tstz, ip.dt_interv_prescription_tstz))),
                            decode(ipd.flg_interv_type,
                                   'S',
                                   pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'DRUG_PRESC_M004'),
                                   'C',
                                   decode(ip.flg_status,
                                          'R',
                                          decode(ip.flg_time,
                                                 'N',
                                                 pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'ICON_T056'),
                                                 pk_date_utils.get_elapsed_abs_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                                                   nvl(ipp.dt_plan_tstz,
                                                                                       ip.dt_interv_prescription_tstz))),
                                          'D',
                                          decode(ip.flg_time,
                                                 'N',
                                                 pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'ICON_T056'),
                                                 pk_date_utils.get_elapsed_abs_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                                                   nvl(ipp.dt_plan_tstz,
                                                                                       ip.dt_interv_prescription_tstz))),
                                          NULL),
                                   decode(ip.flg_time,
                                          'N',
                                          pk_message.get_message(sys_context('ALERT_CONTEXT', 'ID_LANG'), 'ICON_T056'),
                                          pk_date_utils.get_elapsed_abs_tsz(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                                            nvl(ipp.dt_plan_tstz,
                                                                                ip.dt_interv_prescription_tstz))))))) desc_status,
       decode(ipd.flg_referral,
              'R',
              NULL,
              'S',
              NULL,
              decode(ip.id_episode_origin,
                     NULL,
                     decode(ipd.flg_status,
                            'F',
                            NULL,
                            'C',
                            NULL,
                            'I',
                            NULL,
                            decode(ipd.flg_interv_type,
                                   'S',
                                   NULL,
                                   'C',
                                   decode(ip.flg_status,
                                          'R',
                                          decode(ip.flg_time,
                                                 'N',
                                                 'G',
                                                 decode(pk_date_utils.compare_dates_tsz(profissional(sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_PROFESSIONAL'),
                                                                                                     sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_INSTITUTION'),
                                                                                                     sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_SOFTWARE')),
                                                                                        ipp.dt_plan_tstz,
                                                                                        current_timestamp),
                                                        'G',
                                                        'G',
                                                        'L',
                                                        'R',
                                                        'R')),
                                          'D',
                                          decode(ip.flg_time,
                                                 'N',
                                                 'G',
                                                 decode(pk_date_utils.compare_dates_tsz(profissional(sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_PROFESSIONAL'),
                                                                                                     sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_INSTITUTION'),
                                                                                                     sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_SOFTWARE')),
                                                                                        ipp.dt_plan_tstz,
                                                                                        current_timestamp),
                                                        'G',
                                                        'G',
                                                        'L',
                                                        'R',
                                                        'R')),
                                          NULL),
                                   decode(ip.flg_time,
                                          'N',
                                          'G',
                                          decode(pk_date_utils.compare_dates_tsz(profissional(sys_context('ALERT_CONTEXT',
                                                                                                          'ID_PROFESSIONAL'),
                                                                                              sys_context('ALERT_CONTEXT',
                                                                                                          'ID_INSTITUTION'),
                                                                                              sys_context('ALERT_CONTEXT',
                                                                                                          'ID_SOFTWARE')),
                                                                                 ipp.dt_plan_tstz,
                                                                                 current_timestamp),
                                                 'G',
                                                 'G',
                                                 'L',
                                                 'R',
                                                 'R')))),
                     decode(ipd.flg_status,
                            'F',
                            NULL,
                            'C',
                            NULL,
                            'I',
                            NULL,
                            'R',
                            'R',
                            'D',
                            decode(ip.dt_begin_tstz,
                                   NULL,
                                   'R',
                                   decode(ipd.flg_interv_type,
                                          'S',
                                          NULL,
                                          decode(pk_date_utils.compare_dates_tsz(profissional(sys_context('ALERT_CONTEXT',
                                                                                                          'ID_PROFESSIONAL'),
                                                                                              sys_context('ALERT_CONTEXT',
                                                                                                          'ID_INSTITUTION'),
                                                                                              sys_context('ALERT_CONTEXT',
                                                                                                          'ID_SOFTWARE')),
                                                                                 ipp.dt_plan_tstz,
                                                                                 current_timestamp),
                                                 'G',
                                                 'G',
                                                 'L',
                                                 'R',
                                                 'R'))),
                            decode(ipd.flg_interv_type,
                                   'S',
                                   NULL,
                                   'C',
                                   decode(ip.flg_status,
                                          'R',
                                          decode(ip.flg_time,
                                                 'N',
                                                 'G',
                                                 decode(pk_date_utils.compare_dates_tsz(profissional(sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_PROFESSIONAL'),
                                                                                                     sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_INSTITUTION'),
                                                                                                     sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_SOFTWARE')),
                                                                                        ipp.dt_plan_tstz,
                                                                                        current_timestamp),
                                                        'G',
                                                        'G',
                                                        'L',
                                                        'R',
                                                        'R')),
                                          'D',
                                          decode(ip.flg_time,
                                                 'N',
                                                 'G',
                                                 decode(pk_date_utils.compare_dates_tsz(profissional(sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_PROFESSIONAL'),
                                                                                                     sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_INSTITUTION'),
                                                                                                     sys_context('ALERT_CONTEXT',
                                                                                                                 'ID_SOFTWARE')),
                                                                                        ipp.dt_plan_tstz,
                                                                                        current_timestamp),
                                                        'G',
                                                        'G',
                                                        'L',
                                                        'R',
                                                        'R')),
                                          NULL),
                                   decode(ip.flg_time,
                                          'N',
                                          'G',
                                          decode(pk_date_utils.compare_dates_tsz(profissional(sys_context('ALERT_CONTEXT',
                                                                                                          'ID_PROFESSIONAL'),
                                                                                              sys_context('ALERT_CONTEXT',
                                                                                                          'ID_INSTITUTION'),
                                                                                              sys_context('ALERT_CONTEXT',
                                                                                                          'ID_SOFTWARE')),
                                                                                 ipp.dt_plan_tstz,
                                                                                 current_timestamp),
                                                 'G',
                                                 'G',
                                                 'L',
                                                 'R',
                                                 'R')))))) color_status, -- G (green), R (red)
       decode(ipd.flg_referral, 'R', 'Y', 'S', 'Y', decode(ipd.flg_status, 'C', 'Y', 'I', 'Y', 'F', 'Y', 'N')) flg_cancel,
       pk_date_utils.to_char_insttimezone(profissional(sys_context('ALERT_CONTEXT', 'ID_PROFESSIONAL'),
                                                       sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                       sys_context('ALERT_CONTEXT', 'ID_SOFTWARE')),
                                          nvl(ipp.dt_plan_tstz, ip.dt_begin_tstz),
                                          'YYYYMMDDHH24MISS') dt_ord1,
       pk_diagnosis.concat_diag(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                NULL,
                                NULL,
                                ipd.id_interv_presc_det,
                                profissional(sys_context('ALERT_CONTEXT', 'ID_PROFESSIONAL'),
                                             sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                             sys_context('ALERT_CONTEXT', 'ID_SOFTWARE'))) desc_diagnosis,
       pk_date_utils.to_char_insttimezone(profissional(sys_context('ALERT_CONTEXT', 'ID_PROFESSIONAL'),
                                                       sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                       sys_context('ALERT_CONTEXT', 'ID_SOFTWARE')),
                                          ipd.dt_end_tstz,
                                          'YYYYMMDDHH24MISS') date_end,
       ipp.dt_plan_tstz,
       ip.dt_begin_tstz
  FROM interv_prescription ip,
       interv_presc_det ipd,
       TABLE(pk_co_sign_api.tf_co_sign_task_hist_info(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                                      profissional(sys_context('ALERT_CONTEXT', 'ID_PROFESSIONAL'),
                                                                   sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'),
                                                                   sys_context('ALERT_CONTEXT', 'ID_SOFTWARE')),
                                                      sys_context('ALERT_CONTEXT', 'ID_EPISODE'),
                                                      NULL)) cso,
       speciality spec,
       system_apparati sai,
       intervention i,
       episode epi,
       spec_sys_appar ssa,
       (SELECT DISTINCT id_intervention
          FROM interv_dep_clin_serv
         WHERE nvl(id_institution, 0) IN (0, sys_context('ALERT_CONTEXT', 'ID_INSTITUTION'))
           AND nvl(id_software, 0) IN (0, sys_context('ALERT_CONTEXT', 'ID_SOFTWARE'))) adcs,
       (SELECT *
          FROM interv_presc_plan
         WHERE flg_status IN ('R', 'D')) ipp
 WHERE ip.id_episode = epi.id_episode
   AND epi.id_episode = sys_context('ALERT_CONTEXT', 'ID_EPISODE')
   AND ipd.id_interv_prescription = ip.id_interv_prescription
   AND ipp.id_interv_presc_det(+) = ipd.id_interv_presc_det
   AND ipd.id_co_sign_order = cso.id_co_sign_hist(+)
   AND i.id_intervention = ipd.id_intervention
   AND ssa.id_spec_sys_appar(+) = i.id_spec_sys_appar
   AND spec.id_speciality(+) = ssa.id_speciality
   AND sai.id_system_apparati(+) = ssa.id_system_apparati
   AND adcs.id_intervention(+) = i.id_intervention
   AND ((nvl(adcs.id_intervention, 0) != 0 AND i.flg_status = 'A') OR i.flg_status = 'I')
 ORDER BY pk_sysdomain.get_rank(sys_context('ALERT_CONTEXT', 'ID_LANG'),
                                'INTERV_PRESC_DET.FLG_STATUS',
                                nvl(ipp.flg_status, ipd.flg_status)),
          dt_target;
