-- CHANGED BY:  Nuno Neves
-- CHANGE DATE: 14/09/2011
-- CHANGE REASON: ALERT-194969
CREATE OR REPLACE VIEW V_REHAB_SESSION AS
SELECT 
S.ID_REHAB_SESSION,
S.DT_REHAB_SESSION,
S.ID_REHAB_PRESC,
S.ID_PROFESSIONAL,
S.ID_EPISODE,
S.FLG_STATUS,
S.ID_EXEC_PROFESSIONAL,
S.DT_BEGIN,
S.DT_END,
S.DURATION,
S.NOTES,
S.ID_CANCEL_REASON,
S.DT_CANCEL,
S.ID_CANCEL_PROFESSIONAL,
S.NOTES_CANCEL
FROM REHAB_SESSION S;
-- CHANGE END:  Nuno Neves
