CREATE OR REPLACE VIEW V_REHAB_PRESC_DET AS
SELECT 
RP.ID_REHAB_PRESC,
RP.DT_REHAB_PRESC,
RP.ID_PROFESSIONAL,
RP.ID_INSTITUTION,
RP.ID_REHAB_SCH_NEED,
RP.ID_EXEC_INSTITUTION,
RP.EXEC_PER_SESSION,
RP.FLG_STATUS,
RP.NOTES,
RP.ID_CANCEL_REASON,
RP.NOTES_CANCEL,
RP.DT_CANCEL,
RP.ID_CANCEL_PROFESSIONAL,
RP.FLG_PRESC_STATUS,
RP.NOTES_CHANGE,
RP.ID_CODIFICATION,
RP.FLG_REFERRAL,
RP.ID_REHAB_AREA_INTERV,
RAI.ID_REHAB_AREA,
RAI.ID_INTERVENTION,
RP.FLG_LATERALITY,
RP.ID_NOT_ORDER_REASON
FROM REHAB_PRESC RP
JOIN REHAB_AREA_INTERV RAI ON RP.ID_REHAB_AREA_INTERV=RAI.ID_REHAB_AREA_INTERV;