-- CHANGED BY:  Nuno Neves
-- CHANGE DATE: 16/09/2011
-- CHANGE REASON: ALERT-194969
CREATE OR REPLACE VIEW V_REHAB_SCH_NEED AS
SELECT 
RSN.ID_REHAB_SCH_NEED,
RSN.ID_REHAB_SESSION_TYPE,
RSN.DT_REHAB_SCH_NEED,
RSN.ID_EPISODE_ORIGIN,
RSN.ID_PROFESSIONAL,
RSN.SESSIONS,
RSN.FREQUENCY,
RSN.FLG_FREQUENCY,
RSN.FLG_PRIORITY,
RSN.DT_BEGIN,
RSN.FLG_STATUS,
RSN.ID_RESP_PROFESSIONAL,
RSN.ID_RESP_REHAB_GROUP,
RSN.NOTES,
RSN.ID_CANCEL_REASON,
RSN.DT_CANCEL,
RSN.ID_CANCEL_PROFESSIONAL ,
RSN.NOTES_CANCEL
FROM REHAB_SCH_NEED  RSN;
-- CHANGE END:  Nuno Neves