-- CHANGED BY:  Nuno Neves
-- CHANGE DATE: 14/09/2011
-- CHANGE REASON: ALERT-194969
CREATE OR REPLACE VIEW V_REHAB_SCH_NEED_DET AS
SELECT 
RSN.ID_REHAB_SCH_NEED,
RSN.ID_REHAB_SESSION_TYPE,
RSN.DT_REHAB_SCH_NEED,
RSN.ID_EPISODE_ORIGIN,
RSN.ID_PROFESSIONAL,
RSN.SESSIONS,
RSN.FREQUENCY,
RSN.FLG_FREQUENCY,
RSN.FLG_PRIORITY,
RSN.DT_BEGIN,
RSN.FLG_STATUS,
RSN.ID_RESP_PROFESSIONAL,
RSN.ID_RESP_REHAB_GROUP,
RSN.NOTES,
RSN.ID_CANCEL_REASON,
RSN.DT_CANCEL,
RSN.ID_CANCEL_PROFESSIONAL ,
RSN.NOTES_CANCEL, 
RST.CODE_REHAB_SESSION_TYPE,
RST.ID_CONTENT,
RG.ID_REHAB_AREA,
RG.NAME,
RG.DESCRIPTION,
RG.ID_INSTITUTION,
RG.ID_PROFESSIONAL ID_PROF_REHAB_GROUP,
RG.DT_REHAB_GROUP,
RG.FLG_STATUS FLG_STATUS_REHAB_GROUP
FROM REHAB_SCH_NEED  RSN
JOIN REHAB_SESSION_TYPE RST ON RSN.ID_REHAB_SESSION_TYPE=RST.ID_REHAB_SESSION_TYPE  
LEFT JOIN REHAB_GROUP RG ON  RSN.ID_RESP_REHAB_GROUP=RG.ID_REHAB_GROUP;
-- CHANGE END:  Nuno Neves

-- CHANGED BY:  Nuno Neves
-- CHANGE DATE: 16/09/2011
-- CHANGE REASON: ALERT-194969
drop view V_REHAB_SCH_NEED_DET;
-- CHANGE END:  Nuno Neves