-- CHANGED BY: Telmo
-- CHANGE DATE: 27-06-2013
-- CHANGE REASON: ALERT-260738
CREATE OR REPLACE VIEW V_SCHEDULE AS
SELECT schedule.id_schedule id_schedule,
        id_instit_requests id_instit_requests,
        id_instit_requested id_instit_requested,
        id_dcs_requests id_dcs_requests,
        id_dcs_requested id_dcs_requested,
        id_prof_requests id_prof_requests,
        id_prof_schedules id_prof_schedules,
        dt_schedule_tstz dt_schedule_tstz,
        dt_request_tstz dt_request_tstz,
        dt_begin_tstz dt_begin_tstz,
        dt_end_tstz dt_end_tstz,
        flg_status flg_status,
        schedule_notes schedule_notes,
        id_prof_cancel id_prof_cancel,
        schedule.id_cancel_reason id_cancel_reason,
        dt_cancel_tstz dt_cancel_tstz,
        schedule_cancel_notes schedule_cancel_notes,
        id_sch_event id_sch_event,
        id_reason id_reason,
        id_origin id_origin,
        id_room id_room,
        flg_urgency flg_urgency,
        flg_notification flg_notification,
        id_schedule_ref id_schedule_ref,
        flg_vacancy flg_vacancy,
        flg_sch_type flg_sch_type,
        reason_notes reason_notes,
        schedule.id_reason id_complaint,
        flg_instructions flg_instructions,
        flg_schedule_via flg_schedule_via,
        id_sch_consult_vacancy id_sch_consult_vacancy,
        flg_request_type flg_request_type,
        id_episode id_episode,
        code_complaint code_complaint,
        sch_group.id_patient id_patient,
        flg_state flg_state,
        flg_sched flg_sched,
        id_software id_software,
        id_epis_type id_epis_type,
        schedule_outp.flg_type flg_type,
        id_lang_preferred id_lang_preferred,
        DT_NOTIFICATION_TSTZ DT_NOTIFICATION_TSTZ,
        ID_PROF_NOTIFICATION ID_PROF_NOTIFICATION,
        FLG_NOTIFICATION_VIA FLG_NOTIFICATION_VIA,
        sch_group.id_cancel_reason id_no_show_reason,
        sch_group.no_show_notes,
        sch_group.flg_ref_type,
        sch_group.id_prof_ref,
        sch_group.id_inst_ref
   FROM schedule LEFT JOIN complaint ON schedule.id_reason = complaint.id_complaint
   LEFT JOIN schedule_outp ON schedule.id_schedule = schedule_outp.id_schedule
   JOIN sch_group ON schedule.id_schedule = sch_group.id_schedule;
-- CHANGE END: Telmo