-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 10/11/2016
-- CHANGE REASON:ALERT-326205
CREATE OR REPLACE VIEW v_SCHOLARSHIP_CAT_SPEC_cfg as
    SELECT
        SCS.ID_SCHOLARSHIP_CAT_SPEC       ID_RECORD,
        'PROF_SCHOLARSHIP'   FILTER_NAME,
        CT.ID_CONFIG     ID_CONFIG,
        CT.id_inst_owner id_inst_owner
    FROM CONFIG_TABLE CT
    JOIN SCHOLARSHIP_CAT_SPEC SCS ON SCS.ID_SCHOLARSHIP_CAT_SPEC = CT.ID_RECORD
WHERE CT.CONFIG_TABLE = 'PROF_SCHOLARSHIP';
-- CHANGED END: Pedro Henriques 