-- CHANGED BY: Telmo
-- CHANGE DATE: 15-10-2010
-- CHANGE REASON: ALERT-126053

CREATE OR REPLACE VIEW V_SCH_RESCHED_REASON_SOFT_INS
 (ID_RESCHED_REASON
 ,ID_INSTITUTION
 ,ID_SOFTWARE
 ,FLG_AVAILABLE)
 AS SELECT SRSRSI.ID_RESCHED_REASON ID_RESCHED_REASON
          ,SRSRSI.ID_INSTITUTION ID_INSTITUTION
          ,SRSRSI.ID_SOFTWARE ID_SOFTWARE
          ,SRSRSI.FLG_AVAILABLE FLG_AVAILABLE
FROM SCH_RESCHED_REASON_SOFT_INST SRSRSI;

-- CHANGE END: Telmo
