-- CHANGED BY: Telmo Castro
-- CHANGE DATE: 05-03-2010
-- CHANGE REASON: SCH_386
CREATE OR REPLACE VIEW V_SOFT_INST AS
	SELECT ID_SOFTWARE_INSTITUTION,ID_SOFTWARE,ID_INSTITUTION FROM SOFTWARE_INSTITUTION;
	
-- CHANGE END: Telmo Castro