-- CHANGED BY: Telmo Castro
-- CHANGE DATE: 12-03-2010
-- CHANGE REASON: SCH-386
CREATE OR REPLACE VIEW V_SOFTWARE AS 
SELECT ID_SOFTWARE,NAME,INTERN_NAME,DESC_SOFTWARE,CODE_SOFTWARE FROM SOFTWARE;

-- CHANGE END: Telmo Castro