CREATE OR REPLACE view v_stg_professional AS 
SELECT id_stg_professional,
       title,
       name,
       first_name,
       middle_name,
       last_name,
       short_name,
       initials,
       dt_birth,
       gender,
       marital_status,
       num_order,
       id_ext_prof_cat,
       speciality_desc,
       address,
       city,
       district,
       zip_code,
       id_country,
       work_phone,
       num_contact,
       cell_phone,
       fax,
       email,
			 id_stg_files,
			 id_institution
  FROM stg_professional;