CREATE OR REPLACE VIEW V_SUPPLY_WORKFLOW AS
SELECT sw.id_supply_workflow,
       sw.id_professional,
       sw.id_episode,
       sw.id_supply_request,
       sw.id_supply,
       sw.id_supply_location,
       sw.barcode_req,
       sw.barcode_scanned,
       sw.quantity,
       sw.id_unit_measure,
       sw.id_context,
       sw.flg_context,
       sw.flg_status,
       sw.dt_request,
       sw.dt_returned,
       sw.notes,
       sw.id_prof_cancel,
       sw.dt_cancel,
       sw.notes_cancel,
       sw.id_cancel_reason,
       sw.notes_reject,
       sw.dt_reject,
       sw.id_prof_reject,
       sw.dt_supply_workflow,
       sw.id_req_reason,
       sw.id_del_reason,
       sw.id_supply_set,
       sw.id_sup_workflow_parent,
       sw.total_quantity,
       sw.asset_number,
       sw.flg_outdated,
       sw.total_avail_quantity,
       sw.cod_table,
       sw.flg_cons_type,
       sw.flg_reusable,
       sw.flg_editable,
       sw.flg_preparing,
       sw.flg_countable,
       sw.id_supply_area,
       sw.dt_expiration,
       sw.flg_validation,
       sw.lot,
       s.code_supply,
       s.id_content,
       s.id_supply_type,
       s.flg_type,
       s_set.id_content AS id_content_supply_set,
       sw.id_consumption_parent
  FROM supply s
  JOIN supply_workflow sw
    ON sw.id_supply = s.id_supply
  LEFT JOIN supply s_set
    ON s_set.id_supply = sw.id_supply_set;