CREATE OR REPLACE VIEW V_TECH_IMG_SCHED_REQ AS
SELECT t1.sel_type,
       t1.event_type,
       t1.id_event_type,
       t1.id_patient,
       t1.age,
       t1.num_clin_record,
       t1.id_episode,
       t1.id_dept,
       t1.id_clinical_service,
       t1.id_professional,
       t1.id_exam_cat,
       t1.id_exam,
       t1.dt_schedule_tstz,
       t1.notes,
       t1.dt_begin_tstz,
       t1.id_exam_req,
       t1.id_exam_req_det,
       t1.flg_status_req_det,
       t1.dt_req_tstz,
       t1.id_prof_req,
       t1.id_institution,
       t1.id_schedule,
       t1.flg_req_origin_module,
       t1.gender,
       t1.name,
       t1.id_room,
			 t1.comb_name,
       t1.id_combination_spec,
			 t1.id_combination_events,
			 t1.rank,
			 t1.dt_suggest_begin,
			 t1.flg_single_visit,
       nvl2(t1.rank, 'ExtendIcon', '') dependency_icon
  FROM v_tech_img_sched_req_01 t1;