-- CHANGED BY: Telmo Castro
-- CHANGE DATE: 05-03-2010
-- CHANGE REASON: SCH_386
CREATE OR REPLACE VIEW V_TIMEZONE_REGION AS
	SELECT ID_TIMEZONE_REGION,TIMEZONE_REGION FROM TIMEZONE_REGION;
	
-- CHANGE END: Telmo Castro