-- CHANGED BY: Bruno Martins
-- CHANGED DATE: 2010-11-05
-- CHANGE REASON: ADT-3437

CREATE OR REPLACE VIEW V_TRANSPORTATION AS
SELECT ID_TRANSPORTATION,
       ID_EPISODE,
       ID_PROFESSIONAL,
       ID_TRANSP_ENTITY,
       ID_TRANSP_REQ,   
       FLG_TIME,
       NOTES,
       DT_TRANSPORTATION_TSTZ,     
       DT_ARRIVAL_TSTZ,     
       DT_PICKUP_TSTZ,     
       ID_ORIGIN,
       ID_EXTERNAL_CAUSE,
       COMPANION
FROM TRANSPORTATION;

-- CHANGED END: Bruno Martins