-- CHANGED BY: Patrícia Neto
-- CHANGED DATE: 2009-MAR-28
-- CHANGING REASON: ALLERGIES MODULE
CREATE OR REPLACE TYPE index_data IS OBJECT(id NUMBER, descr VARCHAR2(4000));
-- CHANGE END Patrícia Neto