-- CHANGED BY: Pedro Maia
-- CHANGED DATE: 2010-JUL-29
-- CHANGING REASON: ALERT-94678

CREATE OR REPLACE TYPE "LT_REF_VALUES"                                          AS TABLE OF T_LT_REF_VALUES
/

-- CHANGE END: Pedro Maia 