CREATE OR REPLACE TYPE OBJ_CREATESCHRESOURCERESPONSE AS OBJECT (  idScheduleResource_ NUMBER,   response_ OBJ_RESPONSE);


-- CHANGED BY: Adriano Ferreira
-- CHANGED DATE: 2017-04-20
-- CHANGE REASON: ALERT-325067
CREATE OR REPLACE TYPE OBJ_CREATESCHRESOURCERESPONSE AS OBJECT (  idScheduleResource_ NUMBER,   response_ OBJ_RESPONSE);
/
-- CHANGED END: Bruno Martins
