CREATE OR REPLACE TYPE "P1_REQUEST" AS OBJECT
(
        id_external_request   NUMBER(24),
        num_req               VARCHAR2(50),
        flg_type              VARCHAR2(1),
        flg_status            VARCHAR2(1),
        dt_status_tstz        TIMESTAMP(6) WITH LOCAL TIME ZONE,
        flg_priority          VARCHAR2(1),
        p1_id_speciality      NUMBER(6),
        p1_code_speciality    VARCHAR2(200),
        decision_urg_level    NUMBER,
        id_prof_requested     NUMBER(24),
        prof_requested_name   VARCHAR2(200),
        id_inst_orig          NUMBER(24),
        code_inst_orig        VARCHAR2(200),
        id_inst_dest          NUMBER(24),
        code_inst_dest        VARCHAR2(200),
        inst_dest_abbrev      VARCHAR2(30),
        id_dep_clin_serv      NUMBER(24),
        id_prof_redirected    NUMBER(24),
        id_schedule           NUMBER(24),
        id_prof_schedule      NUMBER(24),
        dt_schedule_tstz      TIMESTAMP(6) WITH LOCAL TIME ZONE,
        dt_efectiv_tstz       TIMESTAMP(6) WITH LOCAL TIME ZONE,
        id_patient            NUMBER(24),
        pat_name              VARCHAR2(200),
        pat_gender            VARCHAR2(1),
        dep_abbreviation      VARCHAR2(30),
        code_department       VARCHAR2(200),
        code_clinical_service VARCHAR2(200),
        prof_triage_name      VARCHAR2(200),
        id_match              NUMBER(24))
/