CREATE OR REPLACE TYPE pat_cogn_func_rec FORCE AS OBJECT
(
        id                      NUMBER(24),
        id_problem              NUMBER(24),
        TYPE                    VARCHAR2(2),
        dt_problem2             VARCHAR2(200),
        dt_problem              VARCHAR2(50),
        dt_problem_to_print     VARCHAR2(50),
        desc_probl              VARCHAR2(4000),
        title                   VARCHAR2(4000),
        flg_source              VARCHAR2(2),
        dt_order                VARCHAR2(14),
        flg_status              VARCHAR2(2),
        rank_type               NUMBER(6),
        flg_cancel              VARCHAR2(2),
        desc_status             VARCHAR2(200),
        desc_nature             VARCHAR2(200),
        rank_status             NUMBER(6),
        rank_nature             NUMBER(6),
        flg_nature              VARCHAR2(2),
        title_notes             VARCHAR2(4000),
        prob_notes              VARCHAR2(4000),
        title_canceled          VARCHAR2(4000),
        id_prob                 NUMBER(24),
        viewer_category         VARCHAR2(4000),
        viewer_category_desc    VARCHAR2(4000),
        viewer_id_prof          NUMBER(24),
        viewer_id_epis          NUMBER(24),
        viewer_date             VARCHAR2(14),
        registered_by_me        VARCHAR2(1),
        origin_specialty        VARCHAR2(200),
        id_origin_specialty     NUMBER(24),
        precaution_measures_str table_varchar,
        id_precaution_measures  table_number,
        header_warning          VARCHAR2(1),
        header_warning_str      VARCHAR2(200),
        resolution_date_str     VARCHAR2(200),
        resolution_date         VARCHAR2(200),
        warning_icon            VARCHAR2(4000),
        review_info             table_varchar,
        id_pat_habit            NUMBER(24),
        flg_area                VARCHAR2(1),
        id_content              VARCHAR2(200 CHAR),
        is_cognitive            NUMBER(1),
        is_functional           NUMBER(1),
        id_terminology_version  NUMBER(24),
        code_icd                VARCHAR2(200 CHAR)
);
/