DROP TYPE patient_table_type;

DROP TYPE patient_object;

CREATE OR REPLACE TYPE patient_object AS OBJECT
(
    id_patient                    NUMBER(24),
    id_person                     NUMBER(24),
    id_pat_family                 NUMBER(24),
    name                          VARCHAR2(1000 CHAR),
    gender                        VARCHAR2(1 CHAR),
    dt_birth                      DATE,
    nick_name                     VARCHAR2(200 CHAR),
    flg_status                    VARCHAR2(1 CHAR),
    dt_deceased                   TIMESTAMP(6),
    last_name                     VARCHAR2(300 CHAR),
    middle_name                   VARCHAR2(300 CHAR),
    age                           NUMBER(5),
    national_health_number        VARCHAR2(100 CHAR),
    institution_key               NUMBER(24),
    patient_number                VARCHAR2(30 CHAR),
    deceased_motive               VARCHAR2(200 CHAR),
    deceased_place                VARCHAR2(100 CHAR),
    birth_place                   VARCHAR2(40 CHAR),
    first_name                    VARCHAR2(300 CHAR),
    id_ethnics                    NUMBER(19),
    preferred_contact_times       VARCHAR2(100 CHAR),
    id_preferred_contact_method   NUMBER(24),
    id_preferred_com_format       NUMBER(24),
    flg_sensitive_record          VARCHAR2(1 CHAR),
    vip_status                    VARCHAR2(1 CHAR),
    alias                         VARCHAR2(200 CHAR),
    non_disclosure_level          VARCHAR2(1 CHAR),
    flg_origin                    VARCHAR2(1 CHAR),
    flg_dependence_level          VARCHAR2(1 CHAR),
    flg_death_ident_method        VARCHAR2(2 CHAR),
    death_registry_susp_action_id NUMBER(24),
    flg_living_arrangement        VARCHAR2(2 CHAR),
    flg_race                      VARCHAR2(10 CHAR),
    maiden_name                   VARCHAR2(100 CHAR),
    id_place_of_birth             NUMBER(24),
    flg_assigning_authority       VARCHAR2(1 CHAR),
    flg_guarantor                 VARCHAR2(1 CHAR),
    flg_self_pay                  VARCHAR2(1 CHAR),
  flg_living_will               VARCHAR2(1 CHAR),
  flg_overseas_status           VARCHAR2(1 CHAR),
  other_names_1                 VARCHAR2(300 CHAR),
  other_names_2                 VARCHAR2(300 CHAR),
  other_names_3                 VARCHAR2(300 CHAR),
  flg_exemption                 VARCHAR2(1 CHAR),
  flg_financial_type            VARCHAR2(2 CHAR),
  flg_immun_reg_status          VARCHAR2(1 CHAR),
  dt_immun_reg_status_eff       TIMESTAMP(6) WITH LOCAL TIME ZONE,
  flg_protection_indicator      VARCHAR2(1 CHAR),
  dt_protection_ind_eff         TIMESTAMP(6) WITH LOCAL TIME ZONE,
  flg_publicity_code            VARCHAR2(1 CHAR),
  dt_publicity_code_eff         TIMESTAMP(6) WITH LOCAL TIME ZONE,
  flg_organ_donor               VARCHAR2(1 CHAR),
  id_person_father              NUMBER(24),
  id_person_mother              NUMBER(24),
  flg_death_notif_status        VARCHAR2(1 CHAR),
  flg_nhs_record_share_status   VARCHAR2(1 CHAR),
  flg_health_space_status       VARCHAR2(1 CHAR),
  nhais_information             VARCHAR2(200 CHAR),
  flg_interpreter_required      VARCHAR2(1 CHAR),
  surname_prefix                VARCHAR2(100 CHAR),
  partner_surname_prefix        VARCHAR2(100 CHAR),
  partner_surname               VARCHAR2(100 CHAR),
  initials                      VARCHAR2(30 CHAR),
  id_nobility_title             NUMBER(24),
  addressing_preferences        VARCHAR2(100 CHAR),
  flg_pers_data_invest          VARCHAR2(1 CHAR),
  start_date_pers_data_invest   DATE,
  flg_decease_data_invest       VARCHAR2(1 CHAR),
  start_date_deceas_data_invest DATE,
  flg_adjournment_reason        VARCHAR2(1 CHAR),
  flg_secret                    VARCHAR2(3 CHAR),
  partner_surname_maiden        VARCHAR2(100 CHAR),
  partner_name                  VARCHAR2(100 CHAR),
  mother_surname_maiden         VARCHAR2(100 CHAR),
  father_surname_maiden         VARCHAR2(100 CHAR),
  bsn                           VARCHAR2(9 CHAR),
  sbvz_invalid_date             VARCHAR2(8 CHAR),
  last_sbvz_update_time         TIMESTAMP(6) WITH LOCAL TIME ZONE,
  last_wid_check_update_time    TIMESTAMP(6) WITH LOCAL TIME ZONE,
  flg_patient_data_check        VARCHAR2(1 CHAR),
  patient_data_check_time       TIMESTAMP(6) WITH LOCAL TIME ZONE,
  id_last_wid_check_doc_type    NUMBER(24),
  last_wid_check_doc_num        VARCHAR2(200 CHAR),
  flg_last_wid_check_status     VARCHAR2(1 CHAR),
  id_health_center              NUMBER(24),
    id_military_branch            NUMBER(24),
    military_status               VARCHAR2(3 CHAR),
    worship_place                 VARCHAR2(200 CHAR),
    id_military_rank              NUMBER(24),
    flg_spanish_speaker           VARCHAR2(2 CHAR),
    flg_native_group              VARCHAR2(2 CHAR),
    pat_native_lang               VARCHAR2(100 CHAR),
    code_birth_certificate        VARCHAR2(9 CHAR),
    type_birth_certificate        NUMBER(10),
    dt_birth_tstz                 TIMESTAMP(6) WITH LOCAL TIME ZONE,
    code_type_birth_certificate   VARCHAR2(50 CHAR),
    flg_type_dt_birth             VARCHAR2(3 CHAR),
    flg_level_dt_birth            VARCHAR2(3 CHAR),
    identity_code                 VARCHAR2(2),
    flg_action_certificate        VARCHAR2(1),
    other_names_4                 VARCHAR2(300 CHAR),
    second_name                   VARCHAR2(300 CHAR),
    flg_patient_test              VARCHAR2(1),
    dt_birth_hijri                DATE,
    in_alias                      NUMBER(5),
  position                      NUMBER(24),
    relevance                     NUMBER(24, 10)
)
;
/

CREATE OR REPLACE TYPE patient_table_type AS TABLE OF patient_object;
/