CREATE OR REPLACE TYPE t_bp_task_detail_hist_core force AS OBJECT
(
    dt_blood_product_det_hist  VARCHAR2(1000 CHAR),
    id_blood_product_execution NUMBER(24),
    action                     VARCHAR2(1000 CHAR),
    desc_action                VARCHAR2(1000 CHAR),
    exec_number                NUMBER(24),
    desc_hemo_type             VARCHAR2(1000 CHAR),
    clinical_indication        VARCHAR2(1000 CHAR),
    desc_diagnosis             VARCHAR2(1000 CHAR),
    clinical_purpose           VARCHAR2(1000 CHAR),
    instructions               VARCHAR2(1000 CHAR),
    priority                   VARCHAR2(1000 CHAR),
    special_type               VARCHAR2(1000 CHAR),
    desc_time                  VARCHAR2(1000 CHAR),
    order_recurrence           VARCHAR2(1000 CHAR),
    execution                  VARCHAR2(1000 CHAR),
    perform_location           VARCHAR2(1000 CHAR),
    dt_req                     VARCHAR2(1000 CHAR),
    not_order_reason           VARCHAR2(1000 CHAR),
    notes                      VARCHAR2(1000 CHAR),
    co_sign                    VARCHAR2(1000 CHAR),
    prof_order                 VARCHAR2(1000 CHAR),
    dt_order                   VARCHAR2(200 CHAR),
    order_type                 VARCHAR2(1000 CHAR),
    cancellation               VARCHAR2(1000 CHAR),
    cancel_reason              VARCHAR2(1000 CHAR),
    cancel_notes               VARCHAR2(1000 CHAR),
    cancel_prof_order          VARCHAR2(1000 CHAR),
    cancel_dt_order            VARCHAR2(1000 CHAR),
    cancel_order_type          VARCHAR2(1000 CHAR),
    health_insurance           VARCHAR2(1000 CHAR),
    financial_entity           VARCHAR2(1000 CHAR),
    health_plan                VARCHAR2(1000 CHAR),
    insurance_number           NUMBER(24),
    exemption                  VARCHAR2(1000 CHAR),
    transfusion                VARCHAR2(1000 CHAR),
    transfusion_type_desc      VARCHAR2(1000 CHAR),
    quantity_received          VARCHAR2(1000 CHAR),
    barcode                    VARCHAR2(1000 CHAR),
    blood_group                VARCHAR2(1000 CHAR),
    blood_group_rh             VARCHAR2(1000 CHAR),
    expiration_date            VARCHAR2(1000 CHAR),
    special_instr              VARCHAR2(1000 CHAR),
    tech_notes                 VARCHAR2(1000 CHAR),
    prof_perform               VARCHAR2(1000 CHAR),
    start_time                 VARCHAR2(1000 CHAR),
    end_time                   VARCHAR2(1000 CHAR),
    qty_given                  VARCHAR2(1000 CHAR),
    desc_perform               VARCHAR2(1000 CHAR),
    exec_notes                 VARCHAR2(1000 CHAR),
    action_reason              VARCHAR2(1000 CHAR),
    action_notes               VARCHAR2(1000 CHAR),
    id_prof_match              VARCHAR2(1000 CHAR),
    dt_match_tstz              VARCHAR2(1000 CHAR),
    id_professional            NUMBER(24),
    dt_bp_execution_tstz       TIMESTAMP WITH LOCAL TIME ZONE,
    desc_compatibility         VARCHAR2(1000 CHAR),
    notes_compatibility        VARCHAR2(1000 CHAR),
    condition                  VARCHAR2(1000 CHAR),
    blood_group_desc           VARCHAR2(1000 CHAR),
    donation_code              VARCHAR2(200 CHAR),
    duration                   VARCHAR2(50),
    result_1                   VARCHAR2(200 CHAR),
    dt_result_1                VARCHAR2(200 CHAR),
    result_sig_1               VARCHAR2(200 CHAR),
    result_2                   VARCHAR2(200 CHAR),
    dt_result_2                VARCHAR2(200 CHAR),
    result_sig_2               VARCHAR2(200 CHAR)
);