CREATE OR REPLACE TYPE t_clin_quest_row force AS OBJECT
(
    id_ds_cmpt_mkt_rel        NUMBER(24),
    id_ds_component_parent    NUMBER(24),
    code_alt_desc             VARCHAR2(100 CHAR),
    desc_component            VARCHAR2(500 CHAR),
    internal_name             VARCHAR2(200 CHAR),
    flg_data_type             VARCHAR2(200 CHAR),
    internal_sample_text_type VARCHAR2(200 CHAR),
    id_ds_component_child     NUMBER(24),
    rank                      NUMBER(24),
    max_len                   NUMBER(24),
    min_len                   NUMBER(24),
    min_value                 NUMBER(24),
    max_value                 NUMBER(24),
    position                  NUMBER(24),
    flg_multichoice           VARCHAR2(200 CHAR),
    comp_size                 NUMBER(24),
    flg_wrap_text             VARCHAR2(200 CHAR),
    multichoice_code          VARCHAR2(200 CHAR),
    service_params            VARCHAR2(200 CHAR),
    flg_event_type            VARCHAR2(200 CHAR),
    flg_exp_type              VARCHAR2(200 CHAR),
    input_expression          VARCHAR2(200 CHAR),
    input_mask                VARCHAR2(200 CHAR),
    comp_offset               VARCHAR2(200 CHAR),
    flg_hidden                VARCHAR2(200 CHAR),
    placeholder               VARCHAR2(200 CHAR),
    validation_message        VARCHAR2(200 CHAR),
    flg_clearable             VARCHAR2(200 CHAR),
    crate_identifier          VARCHAR2(200 CHAR),
    rn                        NUMBER(24),
    flg_repeatable            VARCHAR2(200 CHAR),
    flg_data_type2            VARCHAR2(200 CHAR),
		TEXT_LINE_NR              NUMBER(24)
)
