CREATE OR REPLACE TYPE t_concept_term force AS OBJECT
(
    id_concept_term          NUMBER(24),
    id_cncpt_trm_inst_owner  NUMBER(24),
    id_task_type             NUMBER(24),
    terminology_1            VARCHAR2(200 CHAR),
    code_1                   VARCHAR2(200 CHAR),
    concept_rel_type         VARCHAR2(200 CHAR),
    terminology_2            VARCHAR2(200 CHAR),
    code_2                   VARCHAR2(200 CHAR),
    institution              VARCHAR2(200 CHAR),
    software                 VARCHAR2(50 CHAR),
    rank                     NUMBER(24),
    flg_active               VARCHAR2(1 CHAR),
    flg_default              VARCHAR2(1 CHAR),
    id_terminology_1         NUMBER(24),
    id_concept1              NUMBER(24),
    id_concept_version_1     NUMBER(24),
    id_terminology_version_1 NUMBER(24),
    id_concept_relation      NUMBER(24),
    id_concept_rel_type      NUMBER(24),
    id_terminology_2         NUMBER(24),
    id_concept2              NUMBER(24),
    id_concept_version_2     NUMBER(24),
    id_terminology_version_2 NUMBER(24),
    id_institution           NUMBER(24),
    id_software              NUMBER(24),
    id_cncpt_rel_inst_owner  NUMBER(24),
    id_concept_inst_owner1   NUMBER(24),
    id_concept_inst_owner2   NUMBER(24),
    id_cncpt_vrs_inst_owner1 NUMBER(24),
    id_cncpt_vrs_inst_owner2 NUMBER(24)
);
/
