CREATE OR REPLACE TYPE t_dyn_tree_row force AS OBJECT
(
    id_ds_cmpt_mkt_rel        NUMBER,
    id_ds_cmpt_inst_rel       NUMBER,
    id_institution            NUMBER,
    id_ds_component_parent    NUMBER,
    code_component_parent     VARCHAR2(0200 CHAR),
    internal_name_parent      VARCHAR2(200 CHAR),
    flg_component_type_parent VARCHAR2(001 CHAR),
    id_ds_component_child     NUMBER,
    code_component_child      VARCHAR2(0200 CHAR),
    internal_name_child       VARCHAR2(200 CHAR),
    flg_component_type_child  VARCHAR2(001 CHAR),
    id_profile_template       NUMBER,
    id_category               NUMBER,
    id_software               NUMBER,
    id_market                 NUMBER,
    rank                      NUMBER,
    gender                    VARCHAR2(001 CHAR),
    age_min_value             NUMBER(5, 2),
    age_min_unit_measure      NUMBER,
    age_max_value             NUMBER(5, 2),
    age_max_unit_measure      NUMBER,
    id_unit_measure           NUMBER,
    id_unit_measure_subtype   NUMBER,
    max_len                   NUMBER,
    min_len                   NUMBER,
    min_value                 NUMBER,
    max_value                 NUMBER,
    position                  NUMBER,
    flg_configurable          VARCHAR2(0001 CHAR),
    service_params            VARCHAR2(1000 CHAR),
    flg_multichoice           VARCHAR2(0010 CHAR),
    multichoice_service       VARCHAR2(1000 CHAR),
    id_action                 NUMBER,
    flg_event_type            VARCHAR2(0010 CHAR),
    comp_size                 NUMBER,
    ds_alias                  VARCHAR2(0200 CHAR),
    code_alt_desc             VARCHAR2(0200 CHAR),
    desc_function             VARCHAR2(1000 CHAR),
    flg_exp_type              VARCHAR2(1 CHAR),
    input_expression          VARCHAR2(1000 CHAR),
    input_mask                VARCHAR2(0200 CHAR),
    comp_offset               NUMBER,
    flg_hidden                VARCHAR2(0001 CHAR),
    placeholder               VARCHAR2(0200 CHAR),
    code_validation_msg       VARCHAR2(0200 CHAR),
    flg_clearable             VARCHAR2(0001 CHAR),
    crate_identifier          VARCHAR2(1000 CHAR),
    flg_label_visible      VARCHAR2(0001 CHAR),
    internal_sample_text_type VARCHAR2(1000 CHAR),
    rn                        NUMBER,
    flg_repeatable         varchar2(0001 char),
    flg_data_type2         varchar2(0002 char),
    text_line_nr           number(6)
);
/

