CREATE OR REPLACE TYPE t_interv_data force AS OBJECT
(
    det_type              VARCHAR2(100 CHAR),
    flg_status            VARCHAR2(1),
    dt_last_update        TIMESTAMP(6) WITH LOCAL TIME ZONE,
    icnp_epis_interv_hist NUMBER(24),
    msg_prn               VARCHAR2(1000 CHAR),
    flg_prn               VARCHAR2(100 CHAR),
    msg_prn_condition     VARCHAR2(1000 CHAR),
    prn_condition         CLOB,
    left_state            VARCHAR2(1000 CHAR),
    left_date             VARCHAR2(1000 CHAR),
    left_prof             VARCHAR2(1000 CHAR),
    left_spec             VARCHAR2(1000 CHAR),
    msg_interv            VARCHAR2(1000 CHAR),
    desc_interv           VARCHAR2(1000 CHAR),
    msg_status            VARCHAR2(1000 CHAR),
    desc_status           VARCHAR2(1000 CHAR),
    msg_instr             VARCHAR2(1000 CHAR),
    desc_instr            VARCHAR2(1000 CHAR),
    msg_assoc_diag        VARCHAR2(1000 CHAR),
    desc_assoc_diag       VARCHAR2(4000 CHAR),
    msg_notes             VARCHAR2(1000 CHAR),
    desc_notes            VARCHAR2(4000 CHAR),
    msg_therapeutic       VARCHAR2(1000 CHAR),
    therapeutic           VARCHAR2(1000 CHAR),
    msg_cancel_res        VARCHAR2(1000 CHAR),
    desc_cancel_res       VARCHAR2(1000 CHAR),
    msg_cancel_notes      VARCHAR2(1000 CHAR),
    desc_cancel_notes     VARCHAR2(4000 CHAR),
    msg_susp_res          VARCHAR2(1000 CHAR),
    desc_susp_res         VARCHAR2(4000 CHAR),
    msg_susp_notes        VARCHAR2(1000 CHAR),
    desc_susp_notes       VARCHAR2(4000 CHAR),
    id_epis_documentation NUMBER(24),
    prev_flg_status       VARCHAR2(1 CHAR)
)
;
/