CREATE OR REPLACE TYPE t_lab_tests_ea force AS OBJECT
(
    id_analysis_req          NUMBER(24),
    id_analysis_req_det      NUMBER(24),
    id_ard_parent            NUMBER(24),
    id_analysis_result       NUMBER(24),
    id_analysis              NUMBER(24),
    dt_req                   TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_target                TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_pend_req              TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_harvest               TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_analysis_result       TIMESTAMP(6) WITH LOCAL TIME ZONE,
    status_str_req           VARCHAR2(100 CHAR),
    status_msg_req           VARCHAR2(100 CHAR),
    status_icon_req          VARCHAR2(100 CHAR),
    status_flg_req           VARCHAR2(100 CHAR),
    status_str               VARCHAR2(100 CHAR),
    status_msg               VARCHAR2(100 CHAR),
    status_icon              VARCHAR2(100 CHAR),
    status_flg               VARCHAR2(100 CHAR),
    id_sample_type           NUMBER(24),
    id_exam_cat              NUMBER(24),
    flg_notes                VARCHAR2(1 CHAR),
    flg_doc                  VARCHAR2(1 CHAR),
    flg_time_harvest         VARCHAR2(1 CHAR),
    flg_status_req           VARCHAR2(2 CHAR),
    flg_status_det           VARCHAR2(2 CHAR),
    flg_status_harvest       VARCHAR2(1 CHAR),
    flg_status_result        VARCHAR2(1 CHAR),
    flg_referral             VARCHAR2(1 CHAR),
    flg_priority             VARCHAR2(1 CHAR),
    flg_col_inst             VARCHAR2(1 CHAR),
    id_prof_writes           NUMBER(24),
    id_institution           NUMBER(24),
    id_analysis_codification NUMBER(24),
    id_task_dependency       NUMBER(24),
    id_room_req              NUMBER(24),
    id_exec_institution      NUMBER(24),
    id_movement              NUMBER(24),
    id_prof_order            NUMBER(24),
    dt_order                 TIMESTAMP(6) WITH LOCAL TIME ZONE,
    id_order_type            NUMBER(12),
    flg_abnormality          VARCHAR2(1 CHAR),
    flg_orig_analysis        VARCHAR2(1 CHAR),
    notes                    VARCHAR2(1000 CHAR),
    notes_technician         VARCHAR2(1000 CHAR),
    notes_patient            CLOB,
    notes_cancel             VARCHAR2(1000 CHAR),
    flg_req_origin_module    VARCHAR2(1 CHAR),
    id_patient               NUMBER(24),
    id_visit                 NUMBER(24),
    id_episode               NUMBER(24),
    id_episode_origin        NUMBER(24),
    id_episode_destination   NUMBER(24),
    id_prev_episode          NUMBER(24),
    dt_dg_last_update        TIMESTAMP(6) WITH LOCAL TIME ZONE,
    notes_scheduler          VARCHAR2(1000 CHAR),
    id_epis_type             NUMBER(12),
    id_epis                  NUMBER(24)
);
/
