CREATE OR REPLACE TYPE t_obj_doc_area_register force IS OBJECT
(
    order_by_default            INTERVAL DAY(9) TO SECOND,
    order_default               DATE,
    id_epis_documentation       NUMBER(24),
    PARENT                      NUMBER(24),
    id_doc_template             NUMBER(24),
    template_desc               VARCHAR2(4000 CHAR),
    dt_creation                 VARCHAR2(4000 CHAR),
    dt_creation_tstz            TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_register                 VARCHAR2(4000),
    id_professional             NUMBER(24),
    nick_name                   VARCHAR2(800 CHAR),
    desc_speciality             VARCHAR2(200 CHAR),
    id_doc_area                 NUMBER(24),
    flg_status                  VARCHAR2(1),
    desc_status                 VARCHAR2(800 CHAR),
    id_episode                  NUMBER(24),
    flg_current_episode         VARCHAR2(1 CHAR),
    notes                       CLOB,
    dt_last_update              VARCHAR2(4000 CHAR),
    dt_last_update_tstz         TIMESTAMP(6) WITH LOCAL TIME ZONE,
    flg_detail                  VARCHAR2(1 CHAR),
    flg_external                VARCHAR2(1 CHAR),
    flg_type_register           VARCHAR2(1 CHAR),
    flg_table_origin            VARCHAR2(1 CHAR),
    flg_reviewed                VARCHAR2(1 CHAR),
    id_prof_cancel              NUMBER(24),
    dt_cancel_tstz              TIMESTAMP(6) WITH LOCAL TIME ZONE,
    id_cancel_reason            NUMBER(24),
    cancel_reason               VARCHAR2(4000 CHAR),
    cancel_notes                VARCHAR2(2000 CHAR),
    flg_edition_type            VARCHAR2(1),
    nick_name_prof_create       VARCHAR2(800 CHAR),
    desc_speciality_prof_create VARCHAR2(4000 CHAR),
    dt_clinical                 VARCHAR2(200 CHAR),
    dt_clinical_rep             VARCHAR2(200 CHAR)
);
/
