CREATE OR REPLACE TYPE t_rec_data_inpatient_base force AS OBJECT
(
    id_institution           NUMBER,
    id_software              NUMBER,
    id_episode               NUMBER,
    id_prev_episode          NUMBER,
    id_prev_epis_type        NUMBER,
    id_prof_discharge        NUMBER,
    dt_epis_dt_begin_tstz    TIMESTAMP WITH LOCAL TIME ZONE,
    dt_vis_dt_begin_tstz     TIMESTAMP WITH LOCAL TIME ZONE,
    dt_discharge             TIMESTAMP WITH LOCAL TIME ZONE,
    dt_discharge_pend        TIMESTAMP WITH LOCAL TIME ZONE,
    dt_discharge_adm        TIMESTAMP WITH LOCAL TIME ZONE,
  dis_flg_status           varchar2(0010 char),
    id_discharge_destination NUMBER,
    id_habit                 NUMBER,
    id_patient               NUMBER,
    id_first_dep_clin_serv   NUMBER,
    id_department_f          NUMBER,
    code_department_f        VARCHAR2(4000),
    id_clinical_service_f    NUMBER,
    code_clinical_service_f  VARCHAR2(4000),
    id_dep_clin_serv         NUMBER,
    id_department_c          NUMBER,
    code_department_c        VARCHAR2(4000),
    id_clinical_service_c    NUMBER,
    code_clinical_service_c  VARCHAR2(4000),
    id_department_now        NUMBER,
    code_department_now      VARCHAR2(4000),
    id_room_now              NUMBER,
    code_room_now            VARCHAR2(4000),
    id_bed_alloc             NUMBER,
    code_bed_alloc           VARCHAR2(4000),
    id_room_alloc            NUMBER,
    code_room_alloc          VARCHAR2(4000),
    id_department_alloc      NUMBER,
    code_department_alloc    VARCHAR2(4000),
    dt_last_update_tstz      TIMESTAMP WITH LOCAL TIME ZONE,
    flg_ehr                  VARCHAR2(1 CHAR)
);
/

