-- CHANGED BY: Nuno Neves
-- CHANGE DATE: 21/06/2012 16:45
-- CHANGE REASON: 
CREATE TYPE T_REC_TMP IS OBJECT(institution NUMBER(24), old_seq NUMBER(24), new_seq NUMBER(24));
-- CHANGE END: Nuno Neves