CREATE OR REPLACE TYPE t_rec_p1_grid AS OBJECT
(
    id_p1               NUMBER(24),
    num_req             VARCHAR2(50 CHAR),
    dt_p1               VARCHAR2(200 CHAR),
    flg_type            VARCHAR2(10 CHAR),
    prof_requested_name VARCHAR2(1000 CHAR),
    id_patient          NUMBER(24),
    pat_name            VARCHAR2(1000 CHAR),
    pat_gender          VARCHAR2(30 CHAR),
    pat_age             VARCHAR2(20 CHAR),
    photo               VARCHAR2(300 CHAR),
    inst_dest_name      VARCHAR2(200 CHAR),
    dest_department     VARCHAR2(100 CHAR),
    clin_srv_name       VARCHAR2(150 CHAR),
    p1_spec_name        VARCHAR2(200 CHAR),
    type_icon           VARCHAR2(150 CHAR),
    flg_status          VARCHAR2(50 CHAR),
    flg_status_desc     VARCHAR2(200 CHAR),
    status_icon         VARCHAR2(200 CHAR),
    status_rank         VARCHAR2(200 CHAR),
    status_colors       VARCHAR2(100 CHAR),
    priority_info       VARCHAR2(200 CHAR),
    priority_desc       VARCHAR2(300 CHAR),
    priority_icon       VARCHAR2(150 CHAR),
    dt_schedule         VARCHAR2(200 CHAR),
    hour_schedule       VARCHAR2(100 CHAR),
    dt_sch_millis       VARCHAR2(200 CHAR),
    dt_elapsed          VARCHAR2(200 CHAR),
    id_schedule         NUMBER(24),
    inst_orig_name      VARCHAR2(300 CHAR),
    flg_editable        VARCHAR2(10 CHAR),
    flg_task_editable   VARCHAR2(1 CHAR),
    desc_day            VARCHAR2(200 CHAR),
    desc_days           VARCHAR2(200 CHAR),
    date_field          VARCHAR2(200 CHAR),
    dt_server           VARCHAR2(100 CHAR),
    can_cancel          VARCHAR2(10 CHAR),
    can_sent            VARCHAR2(10 CHAR),
    observations        VARCHAR2(500 CHAR),
    id_rep_duplicata    NUMBER(24),
    id_rep_reprint      NUMBER(24),
    id_task_type        NUMBER(24),
    id_codification     NUMBER(24),
    dt_order            VARCHAR2(30 CHAR),
    flg_migrated        VARCHAR2(5 CHAR)
)
;
/
