CREATE OR REPLACE TYPE t_rec_gen_area_rank_tmp force AS OBJECT
(
    varch1    VARCHAR2(4000),
    varch2    VARCHAR2(4000),
    varch3    VARCHAR2(4000),
    varch4    VARCHAR2(4000),
    varch5    VARCHAR2(4000),
    varch6    VARCHAR2(4000),
    varch7    VARCHAR2(4000),
    varch8    VARCHAR2(4000),
    varch9    VARCHAR2(4000),
    varch10   VARCHAR2(4000),
    varch11   VARCHAR2(4000),
    varch12   VARCHAR2(4000),
    varch13   VARCHAR2(4000),
    varch14   VARCHAR2(4000),
    varch15   VARCHAR2(4000),
    numb1     NUMBER,
    numb2     NUMBER,
    numb3     NUMBER,
    numb4     NUMBER,
    numb5     NUMBER,
    numb6     NUMBER,
    numb7     NUMBER,
    numb8     NUMBER,
    numb9     NUMBER,
    numb10    NUMBER,
    numb11    NUMBER,
    numb12    NUMBER,
    numb13    NUMBER,
    numb14    NUMBER,
    numb15    NUMBER,
    dt_tstz1  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz2  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz3  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz4  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz5  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz6  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz7  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz8  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz9  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz10 TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz11 TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz12 TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz13 TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz14 TIMESTAMP(6) WITH LOCAL TIME ZONE,
    dt_tstz15 TIMESTAMP(6) WITH LOCAL TIME ZONE,
    rank      NUMBER
);
/
