DROP TYPE t_rec_iv_fluid_presc_values FORCE;

CREATE OR REPLACE TYPE t_rec_iv_fluid_presc_values AS OBJECT
(
    l_iv_id_drug_brand           VARCHAR2(255),
    l_iv_flg_type                VARCHAR2(1),
    l_iv_dci_id                  VARCHAR2(255),
    l_iv_form_farm_id            VARCHAR2(255),
    l_iv_flg_time                VARCHAR2(1),
    l_iv_dt_begin                VARCHAR2(255),
    l_iv_dt_end                  VARCHAR2(255),
    l_iv_flg_take_type           VARCHAR2(1),
    l_iv_id_drug                 VARCHAR2(255),
    l_iv_vers                    VARCHAR2(10),
    l_iv_route_id                VARCHAR2(11),
    l_iv_qty                     NUMBER(24, 4),
    l_iv_id_unit_measure         NUMBER(24),
    l_iv_unit_measure_desc       VARCHAR2(255),
    l_iv_value_bolus             NUMBER(24, 4),
    l_iv_id_unit_measure_bolus   NUMBER(24),
    l_iv_unit_measure_bolus_desc VARCHAR2(255),
    l_iv_value_drip              NUMBER(24, 4),
    l_iv_id_unit_measure_drip    NUMBER(24),
    l_iv_unit_measure_drip_desc  VARCHAR2(255),
    l_iv_flg_type2               VARCHAR2(1),
    l_iv_frequency               NUMBER(24, 4),
    l_iv_id_unit_measure_freq    NUMBER(24),
    l_iv_unit_measure_freq_desc  VARCHAR2(255),
    l_iv_id_prof_co_sign         NUMBER(24),
    l_iv_flg_co_sign             VARCHAR2(1),
    l_iv_dt_co_sign              VARCHAR2(255),
    l_iv_notes_co_sign           VARCHAR2(4000),
    l_iv_id_order_type           NUMBER(24),
    l_iv_id_irregular_directions NUMBER(24),
    l_iv_flg_justify             VARCHAR2(1),
    l_iv_desc_drug               VARCHAR2(255),
    l_iv_id_drug_fpd             VARCHAR2(255),
    l_iv_fpd_desc_drug           VARCHAR2(255),
    l_iv_mi_route_id             VARCHAR2(255),
    l_iv_route_descr             VARCHAR2(255),
    l_iv_dci_descr               VARCHAR2(255),
    l_iv_form_farm_descr         VARCHAR2(255),
    l_iv_qt_dos_comp             VARCHAR2(255),
    l_iv_short_desc_drug         VARCHAR2(255),
    l_iv_num_bottles             NUMBER(6),
    l_iv_num_schemes             NUMBER(6),
    l_iv_qty1                    NUMBER(24, 4),
    l_iv_id_measure_unit1        VARCHAR2(30),
    l_iv_unit_measure_unit1_desc VARCHAR2(255),
    l_iv_qty2                    NUMBER(24, 4),
    l_iv_id_measure_unit2        VARCHAR2(30),
    l_iv_unit_measure_unit2_desc VARCHAR2(255),
    l_iv_notes                   VARCHAR2(4000),
    l_iv_id_justify_reason       NUMBER(24),
    l_iv_justify_reason          VARCHAR2(1000),
    l_iv_take_in_case            VARCHAR2(1000),
    l_iv_id_drug_presc_det       NUMBER(24),
    l_iv_dt_begin_form           VARCHAR2(255),
    l_iv_dt_end_form             VARCHAR2(255)
);
/
-- CHANGED BY:  Pedro Morais
-- CHANGE DATE: 27/05/2011 14:26
-- CHANGE REASON: [ALERT-182014] Exchange Clinical Information - Dev DB - Medication - 3
--                
DROP TYPE t_tbl_iv_fluid_presc_values;

CREATE OR REPLACE TYPE t_rec_iv_fluid_presc_values AS OBJECT
(
    l_iv_id_drug_brand           VARCHAR2(255),
    l_iv_flg_type                VARCHAR2(1),
    l_iv_dci_id                  VARCHAR2(255),
    l_iv_form_farm_id            VARCHAR2(255),
    l_iv_flg_time                VARCHAR2(1),
    l_iv_dt_begin                VARCHAR2(255),
    l_iv_dt_end                  VARCHAR2(255),
    l_iv_flg_take_type           VARCHAR2(1),
    l_iv_id_drug                 VARCHAR2(255),
    l_iv_vers                    VARCHAR2(10),
    l_iv_route_id                VARCHAR2(11),
    l_iv_qty                     NUMBER(24, 4),
    l_iv_id_unit_measure         NUMBER(24),
    l_iv_unit_measure_desc       VARCHAR2(255),
    l_iv_value_bolus             NUMBER(24, 4),
    l_iv_id_unit_measure_bolus   NUMBER(24),
    l_iv_unit_measure_bolus_desc VARCHAR2(255),
    l_iv_value_drip              NUMBER(24, 4),
    l_iv_id_unit_measure_drip    NUMBER(24),
    l_iv_unit_measure_drip_desc  VARCHAR2(255),
    l_iv_flg_type2               VARCHAR2(1),
    l_iv_frequency               NUMBER(24, 4),
    l_iv_id_unit_measure_freq    NUMBER(24),
    l_iv_unit_measure_freq_desc  VARCHAR2(255),
    l_iv_id_prof_co_sign         NUMBER(24),
    l_iv_flg_co_sign             VARCHAR2(1),
    l_iv_dt_co_sign              VARCHAR2(255),
    l_iv_notes_co_sign           VARCHAR2(4000),
    l_iv_id_order_type           NUMBER(24),
    l_iv_id_irregular_directions NUMBER(24),
    l_iv_flg_justify             VARCHAR2(1),
    l_iv_desc_drug               VARCHAR2(255),
    l_iv_id_drug_fpd             VARCHAR2(255),
    l_iv_fpd_desc_drug           VARCHAR2(255),
    l_iv_mi_route_id             VARCHAR2(255),
    l_iv_route_descr             VARCHAR2(255),
    l_iv_dci_descr               VARCHAR2(255),
    l_iv_form_farm_descr         VARCHAR2(255),
    l_iv_qt_dos_comp             VARCHAR2(255),
    l_iv_short_desc_drug         VARCHAR2(255),
    l_iv_num_bottles             NUMBER(6),
    l_iv_num_schemes             NUMBER(6),
    l_iv_qty1                    NUMBER(24, 4),
    l_iv_id_measure_unit1        VARCHAR2(30),
    l_iv_unit_measure_unit1_desc VARCHAR2(255),
    l_iv_qty2                    NUMBER(24, 4),
    l_iv_id_measure_unit2        VARCHAR2(30),
    l_iv_unit_measure_unit2_desc VARCHAR2(255),
    l_iv_notes                   VARCHAR2(4000),
    l_iv_id_justify_reason       NUMBER(24),
    l_iv_justify_reason          VARCHAR2(1000),
    l_iv_take_in_case            VARCHAR2(1000),
    l_iv_id_drug_presc_det       NUMBER(24),
    l_iv_dt_begin_form           VARCHAR2(255),
    l_iv_dt_end_form             VARCHAR2(255),
    l_iv_route_code              VARCHAR2(255),
    l_iv_form_code               VARCHAR2(255),
    l_iv_rxnorm_code             VARCHAR2(255)
);
/
CREATE OR REPLACE TYPE t_tbl_iv_fluid_presc_values as TABLE OF t_rec_iv_fluid_presc_values;
/
-- CHANGE END:  Pedro Morais