drop type t_coll_pn_work_data;
/
CREATE OR REPLACE TYPE t_rec_pn_work_data IS OBJECT
(
    area_name            VARCHAR2(1000 CHAR),
    id_pn_soap_block     NUMBER(24),
    id_pn_data_block     NUMBER(24),
    id_parent            NUMBER(24),
    task_description     CLOB,
    task                 CLOB,
    dt_reg               VARCHAR2(200 CHAR),
    dt_register          TIMESTAMP(6) WITH LOCAL TIME ZONE,
    id_professional      NUMBER(24),
    id_task              NUMBER(24),
    id_task_type         NUMBER(24),
    table_origin         VARCHAR2(2 CHAR),
    rank                 NUMBER(24),
    flg_import_date      VARCHAR2(1 CHAR),
    id_episode           NUMBER(24),
    id_parent_struct_imp NUMBER(24),
    id_task_aggregator   NUMBER(24),
    flg_reviewed_epis    VARCHAR2(1 CHAR), -- Y- the task was reviewed in the current episode
    review_context       VARCHAR2(3 CHAR), --context of the review. If the task requires review
    flg_auto_populated      VARCHAR2(200 CHAR),
    flg_import           VARCHAR2(24 CHAR),
    flg_data_removable   VARCHAR2(24 CHAR),
    flg_synchronized        VARCHAR2(200 CHAR),
    id_parent_comments   NUMBER(24), --id task parent
    flg_has_comments     VARCHAR2(1 CHAR),
    parent_task_type     NUMBER(24),
    flg_parent_imported  VARCHAR2(1 CHAR),
    dt_task              TIMESTAMP(6) WITH LOCAL TIME ZONE,
    flg_type             VARCHAR2(24 CHAR),
    flg_ongoing          VARCHAR2(1 CHAR),
    flg_selected         VARCHAR2(24 CHAR),
    flg_group_on_import  VARCHAR2(1 CHAR),
    dt_group_import         TIMESTAMP(6) WITH LOCAL TIME ZONE,
    id_group_import         NUMBER(24),
    code_desc_group         VARCHAR2(200 CHAR),
    desc_group              VARCHAR2(200 CHAR),
    id_sub_group_import     NUMBER(24),
    code_desc_sub_group     VARCHAR2(200 CHAR),
    separator               VARCHAR2(3 CHAR),
    flg_scope               VARCHAR2(1 CHAR),
    id_group_table          NUMBER(24),
    table_position          NUMBER(24),
    flg_editable            VARCHAR2(1 CHAR),
    code_description        VARCHAR2(200 CHAR),
    universal_description   CLOB,
    flg_sos                 VARCHAR2(1 CHAR),
    dt_begin                TIMESTAMP(6) WITH LOCAL TIME ZONE,
    id_doc_area             NUMBER(24),
    flg_group_select_filter VARCHAR2(24 CHAR),
    flg_show_sub_title      VARCHAR2(1 CHAR),
    id_prof_review          NUMBER(24),
    dt_review               TIMESTAMP(6) WITH LOCAL TIME ZONE,
    code_status             VARCHAR2(200 CHAR),
    dt_end                  TIMESTAMP(6) WITH LOCAL TIME ZONE,
    id_task_notes           NUMBER(24),
    flg_status              VARCHAR2(24 CHAR),
    id_sample_type          NUMBER(24),
    code_desc_sample_type   VARCHAR2(200 CHAR),
    flg_review_avail        VARCHAR2(1 CHAR),
    flg_description         VARCHAR2(24 CHAR),
    description_condition   VARCHAR2(1000 CHAR),
    code_desc_group_parent  VARCHAR2(200 CHAR),
    instructions_hash       VARCHAR2(200 CHAR),
    flg_group_type          VARCHAR2(1 CHAR)
)';
/
CREATE OR REPLACE TYPE t_coll_pn_work_data AS table of t_rec_pn_work_data;
/
