CREATE OR REPLACE TYPE t_rec_patcriteriaactiveadmin AS OBJECT
(
    origem                   VARCHAR2(4000),
    acuity                   VARCHAR2(240),
    color_text               VARCHAR2(200),
    rank_acuity              NUMBER,
    id_episode               NUMBER(24),
    id_patient               NUMBER(24),
    care_stage               VARCHAR2(4000),
    dt_server                VARCHAR2(32),
    pat_age                  VARCHAR2(50),
    gender                   VARCHAR2(200),
    photo                    VARCHAR2(4000),
    name_pat                 VARCHAR2(200),
		name_pat_sort         VARCHAR2(200),
    pat_ndo                  VARCHAR2(1000),
    pat_nd_icon              VARCHAR2(10),
    num_clin_record          VARCHAR2(100),
    attaches                 NUMBER,
    transfer_req_time        VARCHAR2(4000),
    dt_begin                 VARCHAR2(4000),
    inp_admission_time       VARCHAR2(4000),
    disch_pend_time          VARCHAR2(4000),
    disch_time               VARCHAR2(4000),
    dt_follow_up_date        VARCHAR2(4000),
    label_follow_up_date     VARCHAR2(4000),
    hour_mask_follow_up_date VARCHAR2(4000),
    date_mask_follow_up_date VARCHAR2(4000),
    rank                     VARCHAR2(4000),
    flg_cancel               VARCHAR2(1),
    color_dt_begin           VARCHAR2(1),
    pat_age_for_order_by     NUMBER,
    fast_track_icon          VARCHAR2(200),
    fast_track_color         VARCHAR2(200),
    fast_track_status        VARCHAR2(1),
    esi_level                VARCHAR2(200)
)
/
