drop type t_Rec_access force ;
CREATE OR REPLACE TYPE t_rec_access force AS OBJECT
(
    data_origin             VARCHAR2(0050 CHAR),
    id_profile_template     NUMBER(24),
    flg_add_remove          VARCHAR2(0050 CHAR),
    id_sys_button           NUMBER(24),
    id_sys_button_prop      NUMBER(24),
    code_icon               VARCHAR2(1000 CHAR),
    code_button             VARCHAR2(1000 CHAR),
    skin                    VARCHAR2(1000 CHAR),
    intern_name_button      VARCHAR2(1000 CHAR),
    id_sys_screen_area      NUMBER(24),
    back_color              VARCHAR2(6 CHAR),
    border_color            VARCHAR2(6 CHAR),
    alpha                   NUMBER(12),
    screen_name             VARCHAR2(1000 CHAR),
    action                  VARCHAR2(1000 CHAR),
    rank                    NUMBER(12),
    sub_rank                NUMBER(12),
    flg_screen_mode         VARCHAR2(2 CHAR),
    code_tooltip_title      VARCHAR2(1000 CHAR),
    code_tooltip_desc       VARCHAR2(1000 CHAR),
    code_msg_copyright      VARCHAR2(1000 CHAR),
    flg_reset_context       VARCHAR2(1 CHAR),
    id_software_context     NUMBER(24),
    id_sys_shortcut         NUMBER(24),
    id_software             NUMBER(24),
    id_shortcut_pk          NUMBER(24),
    flg_cancel              VARCHAR2(1 CHAR),
    flg_content             VARCHAR2(1 CHAR),
    flg_create              VARCHAR2(1 CHAR),
    flg_detail              VARCHAR2(1 CHAR),
    flg_digital             VARCHAR2(1 CHAR),
    flg_freq                VARCHAR2(1 CHAR),
    flg_graph               VARCHAR2(1 CHAR),
    flg_help                VARCHAR2(1 CHAR),
    flg_no                  VARCHAR2(1 CHAR),
    flg_ok                  VARCHAR2(1 CHAR),
    flg_print               VARCHAR2(1 CHAR),
    flg_search              VARCHAR2(1 CHAR),
    flg_vision              VARCHAR2(1 CHAR),
    flg_action              VARCHAR2(1 CHAR),
    rank2                   NUMBER(6),
    flg_view                VARCHAR2(1 CHAR),
    flg_global_shortcut     VARCHAR2(1 CHAR),
    flg_info_button         VARCHAR2(1 CHAR),
    pta_position            NUMBER(24),
    sbp_position            NUMBER(24),
    pta_toolbar_level       NUMBER(24),
    sbp_toolbar_level       NUMBER(24),
    sbp_flg_visible         VARCHAR2(1 CHAR),
    sbp_flg_type            VARCHAR2(1 CHAR),
    sbp_flg_enabled         VARCHAR2(1 CHAR),
    code_button_text        VARCHAR2(100 CHAR),
    sb_tooltip_title        VARCHAR2(1000 CHAR),
    sb_tooltip_desc         VARCHAR2(1000 CHAR),
    my_rank                 NUMBER(6),
    id_profile_templ_access VARCHAR2(0050 CHAR),
    age_min                 NUMBER,
    age_max                 NUMBER,
    flg_gender              VARCHAR2(0010 CHAR),
    id_epis_type            NUMBER
)
;
/