CREATE OR REPLACE TYPE t_rec_triage_discrim force AS OBJECT
(
    id_triage                  NUMBER(24),
    id_triage_other            NUMBER(24),
    id_triage_color            NUMBER(24),
    id_triage_color_other      NUMBER(24),
    color_text                 VARCHAR2(1000 CHAR),
    color_text_other           VARCHAR2(1000 CHAR),
    acuity                     VARCHAR2(1000 CHAR),
    acuity_other               VARCHAR2(1000 CHAR),
    id_triage_discriminator    NUMBER(24),
    id_triage_discrim_other    NUMBER(24),
    id_triage_board            NUMBER(24),
    desc_triage_board          VARCHAR2(1000 CHAR),
    desc_discriminator         VARCHAR2(1000 CHAR),
    desc_discrim_other         VARCHAR2(1000 CHAR),
    desc_discrim_question      VARCHAR2(1000 CHAR),
    id_triage_disc_help        NUMBER(24),
    age_min                    NUMBER(5, 2),
    age_max                    NUMBER(5, 2),
    patient_age                VARCHAR2(1000 CHAR),
    flg_accepted_option        VARCHAR2(1 CHAR),
    flg_assessment_type        VARCHAR2(2 CHAR),
    vsign_ids                  VARCHAR2(1000 CHAR),
    vsign_flg_mandatory        VARCHAR2(1000 CHAR),
    vsign_flg_type             VARCHAR2(1000 CHAR),
    title_decision_point       VARCHAR2(1000 CHAR),
    title_decision_point_short VARCHAR2(1000 CHAR),
    esi_decision_point         VARCHAR2(1 CHAR),
    esi_level_header           VARCHAR2(1000 CHAR),
    flg_need_consent           VARCHAR2(1 CHAR),
    consent_field_group        VARCHAR2(1000 CHAR),
    box                        NUMBER(3),
    urgency_level              VARCHAR2(1000 CHAR),
    urgency_level_other        VARCHAR2(1000 CHAR),
    flg_context_help           VARCHAR2(1 CHAR),
    rank                       NUMBER(6),
    flg_critical_look          VARCHAR2(1 CHAR)
);
/
