-- CHANGED BY: Nuno Neves
-- CHANGE DATE: 23/12/2011
-- CHANGE REASON: [ALERT-211466]
CREATE OR REPLACE TYPE t_rec_icnp_epis_interv AS OBJECT
(  
  id_icnp_epis_interv        NUMBER(24),
  id_patient                 NUMBER(24),
  id_episode                 NUMBER(24),
  id_composition             NUMBER(12),
  flg_status                 VARCHAR2(1),
  freq                       NUMBER(6),
  notes                      VARCHAR2(4000),
  id_prof                    NUMBER(24),
  notes_close                VARCHAR2(4000),
  id_prof_close              NUMBER(24),
  forward_interv             NUMBER(24),
  notes_iteraction           VARCHAR2(4000),
  notes_close_iteraction     VARCHAR2(4000),
  flg_time                   VARCHAR2(1),
  flg_type                   VARCHAR2(1),
  interval                   NUMBER(12,4),
  num_take                   NUMBER(3),
  dt_icnp_epis_interv_tstz   TIMESTAMP(6) WITH LOCAL TIME ZONE,
  dt_begin_tstz              TIMESTAMP(6) WITH LOCAL TIME ZONE,
  dt_end_tstz                TIMESTAMP(6) WITH LOCAL TIME ZONE,
  dt_next_tstz               TIMESTAMP(6) WITH LOCAL TIME ZONE,
  dt_close_tstz              TIMESTAMP(6) WITH LOCAL TIME ZONE,
  flg_interval_unit          VARCHAR2(2),
  id_episode_origin          NUMBER(24),
  id_episode_destination     NUMBER(24),
  duration                   NUMBER(12),
  flg_duration_unit          VARCHAR2(1),
  id_prof_last_update        NUMBER(24),
  dt_last_update             TIMESTAMP(6) WITH LOCAL TIME ZONE,
  id_suspend_reason          NUMBER(24),
  id_suspend_prof            NUMBER(24),
  suspend_notes              VARCHAR2(1000 CHAR),
  dt_suspend                 TIMESTAMP(6) WITH LOCAL TIME ZONE,
  id_cancel_reason           NUMBER(24),
  id_cancel_prof             NUMBER(24),
  cancel_notes               VARCHAR2(1000 CHAR),
  dt_cancel                  TIMESTAMP(6) WITH LOCAL TIME ZONE,
  id_order_recurr_plan       NUMBER(24),
  flg_prn                    VARCHAR2(1),
  prn_notes                  CLOB,
  id_icnp_epis_interv_parent NUMBER(24),
  prev_flg_status            VARCHAR2(1)
);
-- CHANGE END: Nuno Neves