-- CHANGED BY: Joel Lopes
-- CHANGE DATE: 29/05/2014
-- CHANGE REASON: [ALERT-286361] 
CREATE OR REPLACE TYPE t_set_problem_cda FORCE AS OBJECT
(
        id                      NUMBER(24),
        id_problem              table_number,--NUMBER(24),
        TYPE                    VARCHAR2(2),
        dt_problem2             VARCHAR2(200),
        dt_problem              table_varchar,
        dt_problem_to_print     VARCHAR2(50),
        desc_probl              table_varchar/*VARCHAR2(4000)*/,
        title                   VARCHAR2(4000),
        flg_source              VARCHAR2(2),
        dt_order                VARCHAR2(14),
        flg_status              table_varchar,
        rank_type               NUMBER(6),
        rank_cancelled          NUMBER(1),
        rank_area               NUMBER(6),
        flg_cancel              VARCHAR2(2),
        desc_status             VARCHAR2(200),
        desc_nature             VARCHAR2(200),
        rank_status             NUMBER(6),
        rank_nature             NUMBER(6),
        flg_nature              table_varchar,
        title_notes             VARCHAR2(4000),
        prob_notes              table_varchar,
        title_canceled          VARCHAR2(4000),
        id_prob                 NUMBER(24),
        viewer_category         VARCHAR2(4000),
        viewer_category_desc    VARCHAR2(4000),
        viewer_id_prof          NUMBER(24),
        viewer_id_epis          NUMBER(24),
        viewer_date             VARCHAR2(14),
        registered_by_me        VARCHAR2(1),
        origin_specialty        VARCHAR2(200),
        id_origin_specialty     NUMBER(24),
        precaution_measures_str table_varchar,
        id_precaution_measures  table_table_number,
        header_warning          table_varchar,
        header_warning_str      VARCHAR2(200),
        resolution_date_str     VARCHAR2(200),
        resolution_date         table_varchar,
        warning_icon            VARCHAR2(4000),
        review_info             table_varchar,
        id_pat_habit            NUMBER(24),
        flg_area                VARCHAR2(1),
        id_terminology_version  NUMBER(24),
        id_content              VARCHAR2(200 CHAR),
        code_icd                VARCHAR2(200 CHAR),
        term_international_code VARCHAR2(200 CHAR),
        flg_info_button         VARCHAR2(1 CHAR),
        id_cancel_reason        NUMBER(24),
        cancel_notes            VARCHAR2(4000),
        id_problem_cancel       NUMBER
);
/
