DROP TYPE T_SEARCH FORCE;

CREATE OR REPLACE TYPE T_SEARCH AS OBJECT
(
CODE_TRANSLATION VARCHAR2(4000),
DESC_TRANSLATION VARCHAR2(4000),
POSITION         NUMBER,
RELEVANCE        FLOAT
);
/


-- cmf 18-12-2012
drop type t_search;