-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 08/04/2011 19:45
-- CHANGE REASON: [ALERT-122481] - Terminal illness
CREATE OR REPLACE TYPE "T_TABLE_ADV_DIR_DAR" AS TABLE OF T_REC_ADV_DIR_DAR
-- CHANGE END: Alexandre Santos
