-- CREATED BY: Pedro Pinheiro
-- CREATED DATE: 13/02/2012 12:05
-- CREATED REASON: [ALERT-217580]
DECLARE
    e_already_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_already_exists, -02303);
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE TYPE TABLE_T_SEARCH_LOB AS TABLE OF T_SEARCH_LOB';
EXCEPTION
    WHEN e_already_exists THEN
        NULL;
END;		
/		
-- CHANGE END: Pedro Pinheiro