-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 19/08/2011
-- CHANGE REASON: ALERT-168848 
CREATE OR REPLACE TYPE TABLE_TABLE_CLOB AS TABLE OF  TABLE_CLOB;
/


-- CHANGED BY: Ariel Machado
-- CHANGE DATE: 24/10/2011 17:18
-- CHANGE REASON: [ALERT-201238] Medical/Nursing notes. Remove 4k limitation for free text entries using CLOB.
CREATE OR REPLACE TYPE TABLE_TABLE_CLOB AS TABLE OF TABLE_CLOB;
-- CHANGE END: Ariel Machado


-- cmf 09-04-2012
DROP TYPE ALERT.TABLE_TABLE_CLOB FORCE;
