-- CHANGED BY: Luís Maia
-- CHANGED DATE: 2009-Abr-18
-- CHANGING REASON: Criação do TYPE "TL_INTERSECT_TASK_INTERVAL".
CREATE OR REPLACE TYPE "TL_INTERSECT_TASK_INTERVAL" AS OBJECT
( ID_TASK_REFID NUMBER(24),
  ID_TL_TASK NUMBER(24),
  ID_EPISODE NUMBER(24),
	ID_VISIT NUMBER(24),
	ID_PATIENT NUMBER(24),
	LAYER NUMBER(24),
  DATE_BEGIN TIMESTAMP(6) WITH LOCAL TIME ZONE,
  DATE_END TIMESTAMP(6) WITH LOCAL TIME ZONE,
  DATE_REQ TIMESTAMP(6) WITH LOCAL TIME ZONE,
  TRUNC_DATE_BEGIN DATE,
  TRUNC_DATE_END DATE,
  TRUNC_DATE_REQ DATE
)
/
-- CHANGE END Luís Maia