CREATE OR REPLACE TYPE "TL_INTERSECT_INTERVAL" AS OBJECT
(  ID_PARENT_EPISODE NUMBER(24),
  id_software number(24), 
  ID_EPISODE NUMBER(24), 
  DATE_BEGIN DATE,
  DATE_END DATE,
  DATE_FIRST_OBS DATE,
  DATE_LAST_INTERACTION DATE,
  TRUNC_DATE_BEGIN DATE,
  TRUNC_DATE_END DATE,
  TRUNC_DATE_FIRST_OBS DATE,
  TRUNC_DATE_LAST_INTERACTION DATE,
  NUMBER_INTERSECTED_INT NUMBER
)

/