CREATE OR REPLACE TYPE "ALERT"."TL_TAB_REG_DATE" AS TABLE OF TL_REG_DATE 

/

-- CHANGED BY: Luís Maia
-- CHANGED DATE: 2009-Abr-18
-- CHANGING REASON: DROP para que seja possível alterar a estrutura do type "TL_REG_DATE"
DROP TYPE TL_TAB_REG_DATE;
/
-- CHANGE END Luís Maia


-- CHANGED BY: Luís Maia
-- CHANGED DATE: 2009-Abr-18
-- CHANGING REASON: Reconstrução do TYPE
CREATE OR REPLACE TYPE "TL_TAB_REG_DATE" AS TABLE OF TL_REG_DATE
/
-- CHANGE END Luís Maia

