-- CHANGED BY: Luís Maia
-- CHANGED DATE: 2009-Abr-18
-- CHANGING REASON: Criação do TYPE "TL_TAB_INTERSECT_TASK_INTERVAL".
CREATE OR REPLACE TYPE "TL_TAB_INTERSECT_TASK_INTERVAL" AS TABLE OF TL_INTERSECT_TASK_INTERVAL
/
-- CHANGE END Luís Maia