-- CHANGED BY: Ana Matos
-- CHANGE DATE: 04/04/2016 10:57
-- CHANGE REASON: [ALERT-319949] 
DECLARE

    CURSOR c_analysis_req_det IS
        SELECT gtl.id_analysis_req_det,
               gtl.id_institution,
               gtl.id_software,
               gtl.id_professional,
               gtl.id_episode,
               ard.flg_time_harvest,
               ard.flg_status flg_status_ard,
               ard.flg_referral,
               gtl.dt_req_tstz,
               ard.dt_target_tstz,
               ard.dt_pend_req_tstz,
               h.flg_status flg_status_h,
               h.dt_harvest_tstz,
               h.dt_lab_reception_tstz dt_lab_reception_h,
               h.dt_mov_begin_tstz dt_mov_begin_h,
               m.dt_begin_tstz dt_begin_m,
               m.dt_end_tstz dt_end_m,
               CASE
                    WHEN ard.flg_status = 'F' THEN
                     CASE
                         WHEN ard.flg_urgency != 'N'
                              OR ares.flg_urgent = 'Y' THEN
                          rs.value || 'U'
                         ELSE
                          rs.value
                     END
                    ELSE
                     rs.value
                END flg_status_r
          FROM grid_task_lab gtl
         INNER JOIN analysis_req_det ard
            ON ard.id_analysis_req_det = gtl.id_analysis_req_det
          LEFT OUTER JOIN analysis_harvest ah
            ON ah.id_analysis_req_det = ard.id_analysis_req_det
          LEFT OUTER JOIN harvest h
            ON h.id_harvest = ah.id_harvest
          LEFT OUTER JOIN movement m
            ON m.id_movement = ard.id_movement
          LEFT OUTER JOIN (SELECT ar.id_analysis_req_det,
                                  ar.id_result_status,
                                  CASE
                                       WHEN pk_utils.is_number(dbms_lob.substr(ar.desc_analysis_result, 3800)) = 'Y'
                                            AND ar.analysis_result_value_2 IS NULL THEN
                                        CASE
                                            WHEN ar.analysis_result_value_1 < ar.ref_val_min THEN
                                             'Y'
                                            WHEN ar.analysis_result_value_1 > ar.ref_val_max THEN
                                             'Y'
                                            ELSE
                                             'N'
                                        END
                                       ELSE
                                        CASE
                                            WHEN ar.id_abnormality IS NOT NULL
                                                 AND ar.id_abnormality != 7 THEN
                                             'Y'
                                            ELSE
                                             'N'
                                        END
                                   END flg_urgent
                             FROM (SELECT ar.id_analysis_req_det,
                                          ar.id_result_status,
                                          arp.desc_analysis_result,
                                          arp.analysis_result_value_1,
                                          arp.analysis_result_value_2,
                                          arp.ref_val_min,
                                          arp.ref_val_max,
                                          arp.id_abnormality,
                                          row_number() over(PARTITION BY id_harvest, id_analysis_req_par ORDER BY dt_ins_result_tstz DESC) rn
                                     FROM analysis_result ar, analysis_result_par arp
                                    WHERE ar.id_analysis_result = arp.id_analysis_result) ar
                            WHERE ar.rn = 1) ares
            ON ares.id_analysis_req_det = ard.id_analysis_req_det
          LEFT OUTER JOIN result_status rs
            ON rs.id_result_status = ares.id_result_status;

    l_grid_task_lab grid_task_lab%ROWTYPE;

BEGIN

    FOR rec IN c_analysis_req_det
    LOOP
    
        IF rec.flg_status_ard IN ('R', 'D')
        THEN
            l_grid_task_lab.request := '0' ||
                                       pk_utils.get_status_string(NULL,
                                                                  profissional(rec.id_professional,
                                                                               rec.id_institution,
                                                                               rec.id_software),
                                                                  pk_ea_logic_analysis.get_analysis_status_str_det(NULL,
                                                                                                                   profissional(rec.id_professional,
                                                                                                                                rec.id_institution,
                                                                                                                                rec.id_software),
                                                                                                                   rec.id_episode,
                                                                                                                   rec.flg_time_harvest,
                                                                                                                   rec.flg_status_ard,
                                                                                                                   rec.flg_referral,
                                                                                                                   rec.flg_status_h,
                                                                                                                   rec.flg_status_r,
                                                                                                                   NULL,
                                                                                                                   rec.dt_req_tstz,
                                                                                                                   rec.dt_pend_req_tstz,
                                                                                                                   rec.dt_target_tstz),
                                                                  pk_ea_logic_analysis.get_analysis_status_msg_det(NULL,
                                                                                                                   profissional(rec.id_professional,
                                                                                                                                rec.id_institution,
                                                                                                                                rec.id_software),
                                                                                                                   rec.id_episode,
                                                                                                                   rec.flg_time_harvest,
                                                                                                                   rec.flg_status_ard,
                                                                                                                   rec.flg_referral,
                                                                                                                   rec.flg_status_h,
                                                                                                                   rec.flg_status_r,
                                                                                                                   NULL,
                                                                                                                   rec.dt_req_tstz,
                                                                                                                   rec.dt_pend_req_tstz,
                                                                                                                   rec.dt_target_tstz),
                                                                  pk_ea_logic_analysis.get_analysis_status_icon_det(NULL,
                                                                                                                    profissional(rec.id_professional,
                                                                                                                                 rec.id_institution,
                                                                                                                                 rec.id_software),
                                                                                                                    rec.id_episode,
                                                                                                                    rec.flg_time_harvest,
                                                                                                                    rec.flg_status_ard,
                                                                                                                    rec.flg_referral,
                                                                                                                    rec.flg_status_h,
                                                                                                                    rec.flg_status_r,
                                                                                                                    NULL,
                                                                                                                    rec.dt_req_tstz,
                                                                                                                    rec.dt_pend_req_tstz,
                                                                                                                    rec.dt_target_tstz),
                                                                  pk_ea_logic_analysis.get_analysis_status_flg_det(NULL,
                                                                                                                   profissional(rec.id_professional,
                                                                                                                                rec.id_institution,
                                                                                                                                rec.id_software),
                                                                                                                   rec.id_episode,
                                                                                                                   rec.flg_time_harvest,
                                                                                                                   rec.flg_status_ard,
                                                                                                                   rec.flg_referral,
                                                                                                                   rec.flg_status_h,
                                                                                                                   rec.flg_status_r,
                                                                                                                   NULL,
                                                                                                                   rec.dt_req_tstz,
                                                                                                                   rec.dt_pend_req_tstz,
                                                                                                                   rec.dt_target_tstz));
        END IF;
    
        IF rec.flg_status_ard = 'E'
        THEN
            IF rec.flg_status_h = 'P'
            THEN
                l_grid_task_lab.harvest := '0' ||
                                           pk_utils.get_status_string(NULL,
                                                                      profissional(rec.id_professional,
                                                                                   rec.id_institution,
                                                                                   rec.id_software),
                                                                      pk_ea_logic_analysis.get_analysis_status_str_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz),
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz),
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz)),
                                                                      pk_ea_logic_analysis.get_analysis_status_msg_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz),
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz),
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz)),
                                                                      pk_ea_logic_analysis.get_analysis_status_icon_det(NULL,
                                                                                                                        profissional(rec.id_professional,
                                                                                                                                     rec.id_institution,
                                                                                                                                     rec.id_software),
                                                                                                                        rec.id_episode,
                                                                                                                        rec.flg_time_harvest,
                                                                                                                        'R',
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        coalesce(rec.dt_harvest_tstz,
                                                                                                                                 rec.dt_pend_req_tstz,
                                                                                                                                 rec.dt_target_tstz,
                                                                                                                                 rec.dt_req_tstz),
                                                                                                                        coalesce(rec.dt_harvest_tstz,
                                                                                                                                 rec.dt_pend_req_tstz,
                                                                                                                                 rec.dt_target_tstz,
                                                                                                                                 rec.dt_req_tstz),
                                                                                                                        coalesce(rec.dt_harvest_tstz,
                                                                                                                                 rec.dt_pend_req_tstz,
                                                                                                                                 rec.dt_target_tstz,
                                                                                                                                 rec.dt_req_tstz)),
                                                                      pk_ea_logic_analysis.get_analysis_status_flg_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz),
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz),
                                                                                                                       coalesce(rec.dt_harvest_tstz,
                                                                                                                                rec.dt_pend_req_tstz,
                                                                                                                                rec.dt_target_tstz,
                                                                                                                                rec.dt_req_tstz)));
            
            ELSIF rec.flg_status_h = 'H'
            THEN
                l_grid_task_lab.harvest := '0' ||
                                           pk_utils.get_status_string(NULL,
                                                                      profissional(rec.id_professional,
                                                                                   rec.id_institution,
                                                                                   rec.id_software),
                                                                      pk_ea_logic_analysis.get_analysis_status_str_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       rec.dt_harvest_tstz,
                                                                                                                       rec.dt_harvest_tstz,
                                                                                                                       rec.dt_harvest_tstz),
                                                                      pk_ea_logic_analysis.get_analysis_status_msg_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       rec.dt_harvest_tstz,
                                                                                                                       rec.dt_harvest_tstz,
                                                                                                                       rec.dt_harvest_tstz),
                                                                      pk_ea_logic_analysis.get_analysis_status_icon_det(NULL,
                                                                                                                        profissional(rec.id_professional,
                                                                                                                                     rec.id_institution,
                                                                                                                                     rec.id_software),
                                                                                                                        rec.id_episode,
                                                                                                                        rec.flg_time_harvest,
                                                                                                                        'R',
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        rec.dt_harvest_tstz,
                                                                                                                        rec.dt_harvest_tstz,
                                                                                                                        rec.dt_harvest_tstz),
                                                                      pk_ea_logic_analysis.get_analysis_status_flg_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       rec.dt_harvest_tstz,
                                                                                                                       rec.dt_harvest_tstz,
                                                                                                                       rec.dt_harvest_tstz));
            ELSIF rec.flg_status_h = 'T'
            THEN
                l_grid_task_lab.transport := '0' ||
                                             pk_utils.get_status_string(NULL,
                                                                        profissional(rec.id_professional,
                                                                                     rec.id_institution,
                                                                                     rec.id_software),
                                                                        pk_ea_logic_analysis.get_analysis_status_str_det(NULL,
                                                                                                                         profissional(rec.id_professional,
                                                                                                                                      rec.id_institution,
                                                                                                                                      rec.id_software),
                                                                                                                         rec.id_episode,
                                                                                                                         rec.flg_time_harvest,
                                                                                                                         'R',
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz),
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz),
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz)),
                                                                        pk_ea_logic_analysis.get_analysis_status_msg_det(NULL,
                                                                                                                         profissional(rec.id_professional,
                                                                                                                                      rec.id_institution,
                                                                                                                                      rec.id_software),
                                                                                                                         rec.id_episode,
                                                                                                                         rec.flg_time_harvest,
                                                                                                                         'R',
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz),
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz),
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz)),
                                                                        pk_ea_logic_analysis.get_analysis_status_icon_det(NULL,
                                                                                                                          profissional(rec.id_professional,
                                                                                                                                       rec.id_institution,
                                                                                                                                       rec.id_software),
                                                                                                                          rec.id_episode,
                                                                                                                          rec.flg_time_harvest,
                                                                                                                          'R',
                                                                                                                          NULL,
                                                                                                                          NULL,
                                                                                                                          NULL,
                                                                                                                          NULL,
                                                                                                                          coalesce(rec.dt_begin_m,
                                                                                                                                   rec.dt_mov_begin_h,
                                                                                                                                   rec.dt_harvest_tstz),
                                                                                                                          coalesce(rec.dt_begin_m,
                                                                                                                                   rec.dt_mov_begin_h,
                                                                                                                                   rec.dt_harvest_tstz),
                                                                                                                          coalesce(rec.dt_begin_m,
                                                                                                                                   rec.dt_mov_begin_h,
                                                                                                                                   rec.dt_harvest_tstz)),
                                                                        pk_ea_logic_analysis.get_analysis_status_flg_det(NULL,
                                                                                                                         profissional(rec.id_professional,
                                                                                                                                      rec.id_institution,
                                                                                                                                      rec.id_software),
                                                                                                                         rec.id_episode,
                                                                                                                         rec.flg_time_harvest,
                                                                                                                         'R',
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         NULL,
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz),
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz),
                                                                                                                         coalesce(rec.dt_begin_m,
                                                                                                                                  rec.dt_mov_begin_h,
                                                                                                                                  rec.dt_harvest_tstz)));
            
            ELSIF rec.flg_status_h = 'F'
            THEN
                l_grid_task_lab.execute := '0' ||
                                           pk_utils.get_status_string(NULL,
                                                                      profissional(rec.id_professional,
                                                                                   rec.id_institution,
                                                                                   rec.id_software),
                                                                      pk_ea_logic_analysis.get_analysis_status_str_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz),
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz),
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz)),
                                                                      pk_ea_logic_analysis.get_analysis_status_msg_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz),
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz),
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz)),
                                                                      pk_ea_logic_analysis.get_analysis_status_icon_det(NULL,
                                                                                                                        profissional(rec.id_professional,
                                                                                                                                     rec.id_institution,
                                                                                                                                     rec.id_software),
                                                                                                                        rec.id_episode,
                                                                                                                        rec.flg_time_harvest,
                                                                                                                        'R',
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        NULL,
                                                                                                                        coalesce(rec.dt_end_m,
                                                                                                                                 rec.dt_lab_reception_h,
                                                                                                                                 rec.dt_harvest_tstz),
                                                                                                                        coalesce(rec.dt_end_m,
                                                                                                                                 rec.dt_lab_reception_h,
                                                                                                                                 rec.dt_harvest_tstz),
                                                                                                                        coalesce(rec.dt_end_m,
                                                                                                                                 rec.dt_lab_reception_h,
                                                                                                                                 rec.dt_harvest_tstz)),
                                                                      pk_ea_logic_analysis.get_analysis_status_flg_det(NULL,
                                                                                                                       profissional(rec.id_professional,
                                                                                                                                    rec.id_institution,
                                                                                                                                    rec.id_software),
                                                                                                                       rec.id_episode,
                                                                                                                       rec.flg_time_harvest,
                                                                                                                       'R',
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       NULL,
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz),
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz),
                                                                                                                       coalesce(rec.dt_end_m,
                                                                                                                                rec.dt_lab_reception_h,
                                                                                                                                rec.dt_harvest_tstz)));
            END IF;
        END IF;
    
        IF rec.flg_status_ard = 'F'
        THEN
            l_grid_task_lab.complete := '0' ||
                                        pk_utils.get_status_string(NULL,
                                                                   profissional(rec.id_professional,
                                                                                rec.id_institution,
                                                                                rec.id_software),
                                                                   pk_ea_logic_analysis.get_analysis_status_str_det(NULL,
                                                                                                                    profissional(rec.id_professional,
                                                                                                                                 rec.id_institution,
                                                                                                                                 rec.id_software),
                                                                                                                    rec.id_episode,
                                                                                                                    rec.flg_time_harvest,
                                                                                                                    rec.flg_status_ard,
                                                                                                                    rec.flg_referral,
                                                                                                                    rec.flg_status_h,
                                                                                                                    rec.flg_status_r,
                                                                                                                    NULL,
                                                                                                                    rec.dt_req_tstz,
                                                                                                                    rec.dt_pend_req_tstz,
                                                                                                                    rec.dt_target_tstz),
                                                                   pk_ea_logic_analysis.get_analysis_status_msg_det(NULL,
                                                                                                                    profissional(rec.id_professional,
                                                                                                                                 rec.id_institution,
                                                                                                                                 rec.id_software),
                                                                                                                    rec.id_episode,
                                                                                                                    rec.flg_time_harvest,
                                                                                                                    rec.flg_status_ard,
                                                                                                                    rec.flg_referral,
                                                                                                                    rec.flg_status_h,
                                                                                                                    rec.flg_status_r,
                                                                                                                    NULL,
                                                                                                                    rec.dt_req_tstz,
                                                                                                                    rec.dt_pend_req_tstz,
                                                                                                                    rec.dt_target_tstz),
                                                                   pk_ea_logic_analysis.get_analysis_status_icon_det(NULL,
                                                                                                                     profissional(rec.id_professional,
                                                                                                                                  rec.id_institution,
                                                                                                                                  rec.id_software),
                                                                                                                     rec.id_episode,
                                                                                                                     rec.flg_time_harvest,
                                                                                                                     rec.flg_status_ard,
                                                                                                                     rec.flg_referral,
                                                                                                                     rec.flg_status_h,
                                                                                                                     rec.flg_status_r,
                                                                                                                     NULL,
                                                                                                                     rec.dt_req_tstz,
                                                                                                                     rec.dt_pend_req_tstz,
                                                                                                                     rec.dt_target_tstz),
                                                                   pk_ea_logic_analysis.get_analysis_status_flg_det(NULL,
                                                                                                                    profissional(rec.id_professional,
                                                                                                                                 rec.id_institution,
                                                                                                                                 rec.id_software),
                                                                                                                    rec.id_episode,
                                                                                                                    rec.flg_time_harvest,
                                                                                                                    rec.flg_status_ard,
                                                                                                                    rec.flg_referral,
                                                                                                                    rec.flg_status_h,
                                                                                                                    rec.flg_status_r,
                                                                                                                    NULL,
                                                                                                                    rec.dt_req_tstz,
                                                                                                                    rec.dt_pend_req_tstz,
                                                                                                                    rec.dt_target_tstz));
        END IF;
    
        UPDATE grid_task_lab gtl
           SET gtl.request   = l_grid_task_lab.request,
               gtl.harvest   = l_grid_task_lab.harvest,
               gtl.transport = l_grid_task_lab.transport,
               gtl.execute   = l_grid_task_lab.execute,
               gtl.complete  = l_grid_task_lab.complete
         WHERE gtl.id_analysis_req_det = rec.id_analysis_req_det;
    
        l_grid_task_lab.request   := NULL;
        l_grid_task_lab.harvest   := NULL;
        l_grid_task_lab.transport := NULL;
        l_grid_task_lab.execute   := NULL;
        l_grid_task_lab.complete  := NULL;
    
    END LOOP;
END;
/
-- CHANGE END: Ana Matos