-- CHANGED BY: Ana Monteiro
-- CHANGE DATE: 05/11/2010 14:53
-- CHANGE REASON: [ALERT-137811] ALERT_75390 Possibilidade do médico hospital encaminhar o pedido para o administrativo hospital

--1- criacao de tabela de backup
CREATE TABLE wf_transition_config_bck AS 
 SELECT *
   FROM wf_transition_config;

--2- alteracoes a tabela
alter table WF_TRANSITION_CONFIG add ID_WORKFLOW_ACTION NUMBER(24);
alter table WF_TRANSITION_CONFIG add ICON VARCHAR2(200);

COMMENT ON COLUMN WF_TRANSITION_CONFIG.ID_WORKFLOW_ACTION IS 'Action identifier';
COMMENT ON COLUMN WF_TRANSITION_CONFIG.ICON IS 'Transition icon';

--3- script de migracao de dados

-- actualizar ID_WORKFLOW_ACTION da WF_TRANSITION_CONFIG
UPDATE wf_transition_config wc
SET ID_WORKFLOW_ACTION = (SELECT ID_WORKFLOW_ACTION
 FROM wf_transition w
WHERE w.id_workflow = wc.id_workflow
AND w.id_status_begin = wc.id_status_begin
AND w.id_status_end = wc.id_status_end);

--4- ddl final
alter table WF_TRANSITION_CONFIG modify ID_WORKFLOW_ACTION not null;

alter table WF_TRANSITION_CONFIG drop constraint WTC_PK cascade;
drop index WTC_PK;

alter table WF_TRANSITION_CONFIG add constraint WTC_PK primary key (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION, ID_SOFTWARE, ID_INSTITUTION, ID_CATEGORY, ID_PROFILE_TEMPLATE, ID_FUNCTIONALITY);
CREATE UNIQUE INDEX WTC_PK ON WF_TRANSITION_CONFIG (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION, ID_SOFTWARE, ID_INSTITUTION, ID_CATEGORY, ID_PROFILE_TEMPLATE, ID_FUNCTIONALITY);

alter table WF_TRANSITION_CONFIG DROP CONSTRAINT WTC_WTS_FK;

alter table WF_TRANSITION_CONFIG ADD CONSTRAINT WTC_WTS_FK foreign key (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION)
  references WF_TRANSITION (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION);

drop index WTC_WTS_FK_IDX;
create index WTC_WTS_FK_IDX on WF_TRANSITION_CONFIG (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION);

ALTER INDEX WTC_WTS_FK_IDX rebuild tablespace INDEX_M;
-- CHANGE END: Ana Monteiro

-- CHANGED BY: Ana Monteiro
-- CHANGE DATE: 24/11/2010 12:06
-- CHANGE REASON: [ALERT-137811] 

--1- criacao de tabela de backup
CREATE TABLE wf_transition_config_bck AS 
 SELECT *
   FROM wf_transition_config;

--2- alteracoes a tabela
alter table WF_TRANSITION_CONFIG add ID_WORKFLOW_ACTION NUMBER(24);
alter table WF_TRANSITION_CONFIG add ICON VARCHAR2(200);

COMMENT ON COLUMN WF_TRANSITION_CONFIG.ID_WORKFLOW_ACTION IS 'Action identifier';
COMMENT ON COLUMN WF_TRANSITION_CONFIG.ICON IS 'Transition icon';

--3- script de migracao de dados

-- actualizar ID_WORKFLOW_ACTION da WF_TRANSITION_CONFIG
UPDATE wf_transition_config wc
SET ID_WORKFLOW_ACTION = (SELECT ID_WORKFLOW_ACTION
 FROM wf_transition w
WHERE w.id_workflow = wc.id_workflow
AND w.id_status_begin = wc.id_status_begin
AND w.id_status_end = wc.id_status_end);

--4- ddl final
alter table WF_TRANSITION_CONFIG modify ID_WORKFLOW_ACTION not null;

alter table WF_TRANSITION_CONFIG drop constraint WTC_PK cascade;
drop index WTC_PK;

alter table WF_TRANSITION_CONFIG add constraint WTC_PK primary key (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION, ID_SOFTWARE, ID_INSTITUTION, ID_CATEGORY, ID_PROFILE_TEMPLATE, ID_FUNCTIONALITY);
--CREATE UNIQUE INDEX WTC_PK ON WF_TRANSITION_CONFIG (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION, ID_SOFTWARE, ID_INSTITUTION, ID_CATEGORY, ID_PROFILE_TEMPLATE, ID_FUNCTIONALITY);

alter table WF_TRANSITION_CONFIG DROP CONSTRAINT WTC_WTS_FK;

alter table WF_TRANSITION_CONFIG ADD CONSTRAINT WTC_WTS_FK foreign key (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION)
  references WF_TRANSITION (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION);

drop index WTC_WTS_FK_IDX;
create index WTC_WTS_FK_IDX on WF_TRANSITION_CONFIG (ID_WORKFLOW, ID_STATUS_BEGIN, ID_STATUS_END, ID_WORKFLOW_ACTION);

ALTER INDEX WTC_WTS_FK_IDX rebuild tablespace INDEX_M;
-- CHANGE END: Ana Monteiro