CREATE SEQUENCE  SEQ_complaint_alert_diagnosis MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;


alter sequence SEQ_COMPLAINT_ALERT_DIAGNOSIS noorder cache 500;

