
@@abnormality.aby_pk.idx
@@abnormality_nature.abn_pk.idx
@@action_criteria.actc_eql_fk_i.idx
@@action_criteria.actc_syec_fk_i.idx
@@action_criteria.actc_pk.idx
@@action_criteria.actc_doca_fk_i.idx
@@adverse_exam_allergy.eay_alg_fk_i.idx
@@adverse_exam_allergy.eay_exam_fk_i.idx
@@adverse_exam_allergy.eay_pk.idx
@@adverse_interv_allergy.aia_int_fk_i.idx
@@adverse_interv_allergy.aia_alg_fk_i.idx
@@adverse_interv_allergy.aia_pk.idx
@@allergy.alg_alg_fk_i.idx

@@allergy.alg_code_i.idx
@@allergy.alg_pk.idx
@@allergy_ext_sys.aes_epis_fk_i.idx
@@allergy_ext_sys.aes_ess_fk_i.idx
@@allocation_bed.all_bed_bed_fk_i.idx
@@allocation_bed.all_bed_epis_fk_i.idx
@@allocation_bed.all_bed_pk.idx
@@allocation_bed.all_bed_prof_fk_i.idx
@@analy_parm_limit.apl_pany_fk_i.idx
@@analy_parm_limit.apl_pk.idx
@@analysis.analy_code_i.idx
@@analysis.analy_pk.idx
@@analysis.analy_srt_fk_i.idx

@@analysis.analy_ste_fk_i.idx
@@analysis.analy_ect_fk_idx.idx
@@analysis_agp.anlg_agp_fk_i.idx
@@analysis_agp.anlg_pk.idx
@@analysis_agp.anlg_analy_fk_idx.idx
@@analysis_alias.aas_inst_fk_i.idx
@@analysis_alias.aas_analy_fk_i.idx
@@analysis_alias.aas_s_fk_i.idx
@@analysis_alias.aas_prof_fk_i.idx
@@analysis_alias.aas_pk.idx
@@analysis_dep_clin_serv.acst_dcs_fk_i.idx
@@analysis_dep_clin_serv.acst_analy_fk_i.idx
@@analysis_dep_clin_serv.acst_pk.idx

@@analysis_dep_clin_serv.acst_agp_fk_idx.idx
@@analysis_dep_clin_serv.acst_inst_fk_idx.idx
@@analysis_dep_clin_serv.acst_prof_fk_idx.idx
@@analysis_dep_clin_serv.acst_s_fk_idx.idx
@@analysis_desc.adc_pk.idx
@@analysis_ext_sys_delete.aes_pk.idx
@@analysis_ext_sys_delete.aes_analy_fk_idx.idx
@@analysis_ext_sys_delete.aes_ess_fk_idx.idx
@@analysis_ext_sys_delete.aes_inst_fk_idx.idx
@@analysis_group.agp_pk.idx
@@analysis_harvest.aht_harv_fk_i.idx
@@analysis_harvest.aht_ard_fk_i.idx
@@analysis_harvest.aht_pk.idx

@@analysis_instit_soft.ais_s_fk_i.idx
@@analysis_instit_soft.ais_inst_fk_i.idx
@@analysis_instit_soft.ais_ect_fk_i.idx
@@analysis_instit_soft.ais_analy_fk_i.idx
@@analysis_instit_soft.ais_pk.idx
@@analysis_loinc.alc_s_fk_i.idx
@@analysis_loinc.alc_inst_fk_i.idx
@@analysis_loinc.alc_analy_fk_i.idx
@@analysis_loinc.alc_pk.idx
@@analysis_loinc_template.alt_analy_fk_i.idx
@@analysis_loinc_template.alt_pk.idx
@@analysis_param.apm_analy_fk_i.idx
@@analysis_param.apm_pany_fk_i.idx

@@analysis_param.apm_pk.idx
@@analysis_param.apm_inst_fk_idx.idx
@@analysis_param.apm_s_fk_idx.idx
@@analysis_parameter.apr_pk.idx
@@analysis_param_instit.api_apr_fk_i.idx
@@analysis_param_instit.api_ais_fk_i.idx
@@analysis_param_instit.api_pk.idx
@@analysis_param_instit_sample.apis_api_fk_i.idx
@@analysis_param_instit_sample.apis_srt_fk_i.idx
@@analysis_param_instit_sample.apis_ste_fk_i.idx
@@analysis_param_instit_sample.apis_pk.idx
@@analysis_prep_mesg.apg_pme_fk_i.idx
@@analysis_prep_mesg.apg_analy_fk_i.idx

@@analysis_prep_mesg.apg_pk.idx
@@analysis_prep_mesg.apg_inst_fk_idx.idx
@@analysis_protocols.aps_pk.idx
@@analysis_protocols.aps_analy_fk_i.idx
@@analysis_protocols.aps_prt_fk_i.idx
@@analysis_req.art_schd_fk_i.idx
@@analysis_req.art_inst_fk_i.idx
@@analysis_req.art_schd_consult_fk_i.idx
@@analysis_req.art_epis_fk_i.idx
@@analysis_req.art_prof_cancel_fk_i.idx
@@analysis_req.art_prof_writes_fk_i.idx
@@analysis_req.art_pk.idx
@@analysis_req.art_prof_authz_fk_i.idx

@@analysis_req.art_prof_app_fk_i.idx
@@analysis_req.art_flg_time_i.idx
@@analysis_req.art_epis_status_i.idx
@@analysis_req.art_epis_dest_fk_idx.idx
@@analysis_req.art_epis_origin_fk_idx.idx
@@analysis_req.art_prt_fk_idx.idx
@@analysis_req.art_epis_fk2_i.idx
@@analysis_req_det.ard_ard_fk_i.idx
@@analysis_req_det.ard_mov_fk_i.idx
@@analysis_req_det.ard_art_fk_i.idx
@@analysis_req_det.ard_prof_fk_i.idx
@@analysis_req_det.ard_analy_fk_i.idx
@@analysis_req_det.ard_pk.idx

@@analysis_req_det.ard_flg_status_i.idx
@@analysis_req_det.ard_room_fk_idx.idx
@@analysis_req_par.arp_ard_fk_i.idx
@@analysis_req_par.arp_pany_fk_i.idx
@@analysis_req_par.arp_pk.idx
@@analysis_result.ares_ard_fk_i.idx
@@analysis_result.ares_inst_fk_i.idx
@@analysis_result.ares_pat_fk_i.idx
@@analysis_result.ares_prof_fk_i.idx
@@analysis_result.ares_analy_fk_i.idx
@@analysis_result.ares_pk.idx
@@analysis_result.ares_epis_fk_idx.idx
@@analysis_result.ares_prof_cancel_fk_i.idx

@@analysis_result_par.arlp_arp_fk_i.idx
@@analysis_result_par.arlp_ares_fk_i.idx
@@analysis_result_par.arlp_pany_fk_i.idx
@@analysis_result_par.arlp_prof_fk_i.idx
@@analysis_result_par.arlp_pk.idx
@@analysis_result_par.arlp_epis_fk_idx.idx
@@analysis_room.arm_analy_fk_i.idx
@@analysis_room.arm_room_fk_i.idx
@@analysis_room.arm_pk.idx
@@anesthesia_type.anest_type_pk.idx
@@bed.bed_code_i.idx
@@bed.bed_room_fk_i.idx
@@bed.bed_pk.idx

@@bed_schedule.bed_schd_pk.idx
@@bed_schedule.bed_schd_bed_fk_idx.idx
@@bed_schedule.bed_schd_schd_fk_idx.idx
@@beye_view_screen.bev_screen_pk.idx
@@birds_eye_view.beyeview_pk.idx
@@birds_eye_view.beyeview_bed_fk_idx.idx
@@birds_eye_view.beyeview_bev_screen_fk_idx.idx
@@birds_eye_view.beyeview_cats_fk_idx.idx
@@birds_eye_view.beyeview_room_fk_idx.idx
@@birds_eye_view.beyeview_si_fk_idx.idx
@@board.brd_pk.idx
@@board_group.bgp_pk.idx
@@board_grouping.bgg_brd_fk_i.idx

@@board_grouping.bgg_bgp_fk_i.idx
@@board_grouping.bgg_pk.idx
@@body_part.bpt_code_i.idx
@@body_part.bpt_pk.idx
@@body_part_image.bpi_int_name_i.idx
@@body_part_image.bpi_pk.idx
@@bp_clin_serv.bcs_bpi_fk_i.idx
@@bp_clin_serv.bcs_cse_fk_i.idx
@@building.building_pk.idx
@@category.cat_code_i.idx
@@category.cat_pk.idx
@@category_sub.cats_cat_fk_idx.idx
@@category_sub.cats_pk.idx

@@ch_contents.cct_pk.idx
@@ch_contents_text.ch_cct_pk.idx
@@child_feed_dev.cfd_pk.idx
@@clinical_service.cse_code_i.idx
@@clinical_service.cse_cse_fk_i.idx
@@clinical_service.cse_pk.idx
@@clin_record.crn_pat_fk_i.idx
@@clin_record.crn_inst_fk_i.idx
@@clin_record.crn_pk.idx
@@clin_record.crn_ptfam_fk_i.idx
@@clin_serv_ext_sys.cses_cse_fk_i.idx
@@clin_serv_ext_sys.cses_ess_fk_i.idx
@@clin_serv_ext_sys.cses_pk.idx

@@clin_serv_ext_sys.cses_inst_fk_idx.idx
@@clin_srv_type.cst_pk.idx
@@clin_srv_type.cst_cse_fk_idx.idx
@@cli_rec_req.crr_schd_fk_i.idx
@@cli_rec_req.crr_pk.idx
@@cli_rec_req.crr_epis_dest_fk_idx.idx
@@cli_rec_req.crr_epis_fk_idx.idx
@@cli_rec_req.crr_epis_origin_fk_idx.idx
@@cli_rec_req.crr_prof_cancel_fk_idx.idx
@@cli_rec_req.crr_prof_req_fk_idx.idx
@@cli_rec_req.crr_room_fk_idx.idx
@@cli_rec_req_det.crrd_crn_fk_i.idx
@@cli_rec_req_det.crrd_crr_fk_i.idx

@@cli_rec_req_det.crrd_pk.idx
@@cli_rec_req_det.crrd_prof_fk_idx.idx
@@cli_rec_req_mov.crm_crrd_fk_i.idx
@@cli_rec_req_mov.crm_pk.idx
@@cli_rec_req_mov.crm_prof_begin_mov_fk_idx.idx
@@cli_rec_req_mov.crm_prof_cancel_fk_idx.idx
@@cli_rec_req_mov.crm_prof_end_mov_fk_idx.idx
@@cli_rec_req_mov.crm_prof_get_file_fk_idx.idx
@@cli_rec_req_mov.crm_prof_req_transp_fk_idx.idx
@@color.col_pk.idx
@@complaint.cmplt_doctemp_fk_i.idx
@@complaint_triage_board.ctb_pk.idx
@@complete_history.cmpl_hist_pk.idx

@@complete_history.cmpl_hist_epis_fk_i.idx
@@complete_history.cmpl_hist_prof_fk_i.idx
@@complete_history.cmpl_hist_pat_fk_i.idx
@@consult_req.crq_pat_fk_i.idx
@@consult_req.crq_prof_auth_fk_i.idx
@@consult_req.crq_cse_fk_i.idx
@@consult_req.crq_inst_requests_fk_i.idx
@@consult_req.crq_epis_fk_i.idx
@@consult_req.crq_prof_req_fk_i.idx
@@consult_req.crq_inst_requested_fk_i.idx
@@consult_req.crq_prof_cancel_fk_i.idx
@@consult_req.crq_prof_appr_fk_i.idx
@@consult_req.crq_prof_proc_fk_i.idx

@@consult_req.crq_pk.idx
@@consult_req.crq_dcs_fk_i.idx
@@consult_req.crq_prof_requested_fk_i.idx
@@consult_req_prof.crp_prof_fk_i.idx
@@consult_req_prof.crp_crq_fk_i.idx
@@consult_req_prof.crp_pk.idx
@@contraceptive.cpe_pk.idx
@@contra_indic.cic_pk.idx
@@contra_indic.cic_iac_fk_i.idx
@@country.ctr_code_fk.idx
@@country.ctr_pk.idx
@@create$java$lob$table.sys_c005585.idx
@@criteria.crt_pk.idx

@@critical_care_read.ccrr_epis_fk_i.idx
@@critical_care_read.ccrr_prof_fk_i.idx
@@critical_care_read.ccrr_pk.idx
@@department.dep_inst_fk_i.idx
@@department.dep_code_i.idx
@@department.dep_pk.idx
@@department.dep_dpt_fk_idx.idx
@@department.dep_s_fk_idx.idx
@@dep_clin_serv.dcs_cse_fk_i.idx
@@dep_clin_serv.dcs_dep_fk_i.idx
@@dep_clin_serv.dcs_pk.idx
@@dep_clin_serv_type.depcst_dcst_fk_i.idx
@@dep_clin_serv_type.depcst_pk.idx

@@dep_clin_serv_type.dcst_sft_fk_i.idx
@@dependency.dpd_exam_fk_i.idx
@@dependency.dpd_analy_fk_i.idx
@@dependency.dpd_int_fk_i.idx
@@dependency.dpd_matr_fk_i.idx
@@dependency.dpd_pk.idx
@@dependency.dpd_cat_fk_i.idx
@@dependency.dpd_inst_fk_idx.idx
@@dept.dpt_pk.idx
@@dept.dpt_inst_fk_idx.idx
@@diagnosis.diag_code_i.idx
@@diagnosis.diag_diag_fk_i.idx
@@diagnosis.diag_pk.idx

@@diagnosis.dia_flgs_search_i.idx
@@diagnosis_dep_clin_serv.dsc_diag_fk_i.idx
@@diagnosis_dep_clin_serv.dsc_dcs_fk_i.idx
@@diagnosis_dep_clin_serv.dsc_pk.idx
@@diagnosis_dep_clin_serv.dcs_prof_fk_i.idx
@@diagnosis_dep_clin_serv.dsc_inst_fk_idx.idx
@@diagnosis_dep_clin_serv.dsc_s_fk_idx.idx
@@diagram.diagr_pk.idx
@@diagram.diagr_epis_fk_i.idx
@@diagram_detail.diagd_pk.idx
@@diagram_detail.diagd_diagr_fk_i.idx
@@diagram_detail.diagd_diagt_fk_i.idx
@@diagram_detail.diagd_diagli_fk_i.idx

@@diagram_detail.diagd_prof_fk.idx
@@diagram_detail.diagd_prof_fk2_i.idx
@@diagram_detail_notes.diagdn_pk.idx
@@diagram_detail_notes.diagdn_diagd_fk_i.idx
@@diagram_detail_notes.diagdn_prof_fk.idx
@@diagram_image.diagim_pk.idx
@@diagram_lay_imag.diagli_pk.idx
@@diagram_lay_imag.diagli_uk.idx
@@diagram_lay_imag.diagli_diagim_fk_i.idx
@@diagram_lay_imag.diagli_diagl_fk_i.idx
@@diagram_layout.diagl_pk.idx
@@diagram_tools.diagt_pk.idx
@@diagram_tools.diagt_diagtg_fk_i.idx

@@diagram_tools_group.diagtg_pk.idx
@@diet.dit_pk.idx
@@dietary_drug.ddg_pk.idx
@@diet_schedule.dse_pk.idx
@@dimension.dim_pk.idx
@@discharge.dis_epis_fk_i.idx
@@discharge.dis_drd_fk_i.idx
@@discharge.dis_prof_cancel_fk_i.idx
@@discharge.dis_pk.idx
@@discharge.dis_prof_admin_fk_idx.idx
@@discharge.dis_prof_med_fk_idx.idx
@@discharge.dis_trp_adm_fk_idx.idx
@@discharge_dest.ddst_pk.idx

@@discharge_detail.dsch_dtl_pk.idx
@@discharge_detail.dsch_dtl_trp_typ_fk_i.idx
@@discharge_detail.dsch_dtl_dsch_fk_i.idx
@@discharge_detail.dsch_dtl_prf_admit_fk_i.idx
@@discharge_detail.dsch_dtl_dcs_admit_fk_i.idx
@@discharge_detail.dsch_dtl_dttei_fk_i.idx
@@discharge_notes.dnt_pk.idx
@@discharge_notes.dnt_prof_fk_i.idx
@@discharge_notes.dnt_epis_fk_i.idx
@@discharge_notes.dnt_prof_fk2_i.idx
@@discharge_reason.drn_pk.idx
@@disc_help.dhp_pk.idx
@@disch_prep_mesg.dpm_pme_fk_i.idx

@@disch_prep_mesg.dpm_pk.idx
@@disch_prep_mesg.dpm_dis_fk.idx
@@disch_reas_dest.drd_dcs_fk_i.idx
@@disch_reas_dest.drd_drn_fk_i.idx
@@disch_reas_dest.drd_ddst_fk_i.idx
@@disch_reas_dest.drd_pk.idx
@@disch_reas_dest.drd_inst_fk_idx.idx
@@disch_reas_dest.drd_inst_param_fk_idx.idx
@@disch_reas_dest.drd_s_fk_idx.idx
@@disch_reas_dest.drd_ete_fk_i.idx
@@disch_reas_dest.drd_dep_fk_i.idx
@@disch_rea_transp_ent_inst.dttei_pk.idx
@@disch_rea_transp_ent_inst.dttei_dsch_rea_fk_i.idx

@@disch_rea_transp_ent_inst.dttei_tei_fk_i.idx
@@discriminator.disc_pk.idx
@@discriminator_help.dihp_dhp_fk_i.idx
@@discriminator_help.dihp_disc_fk_i.idx
@@discriminator_help.dihp_pk.idx
@@disc_vs_valid.dvv_disc_fk_i.idx
@@disc_vs_valid.dvv_vsn_fk_i.idx
@@disc_vs_valid.dvv_pk.idx
@@district.dst_pk.idx
@@doc_action_criteria.docactc_doceql_fk_i.idx
@@doc_action_criteria.docactc_docec_fk_i.idx
@@doc_action_criteria.docactc_docarea_fk_i.idx
@@doc_action_criteria.docactc_pk.idx

@@doc_action_criteria.docactc_docec_fk2_i.idx
@@doc_area.docarea_pk.idx
@@doc_component.doccomp_pk.idx
@@doc_criteria.doccrit_pk.idx
@@doc_destination.ddn_pk.idx
@@doc_destination.doc_destination_code_i.idx
@@doc_dimension.docdim_pk.idx
@@doc_element.doce_docdim_fk_i.idx
@@doc_element.doce_doc_fk_i.idx
@@doc_element.doce_pk.idx
@@doc_element_crit.docec_doccrit_fk_i.idx
@@doc_element_crit.docec_doce_fk_i.idx
@@doc_element_crit.docec_pk.idx

@@doc_element_qualif.doceql_docec_fk_i.idx
@@doc_element_qualif.doceql_docqual_fk_i.idx
@@doc_element_qualif.doceql_pk.idx
@@doc_element_quantif.doceqn_doceql_fk_i.idx
@@doc_element_quantif.doceqn_docquant_fk_i.idx
@@doc_element_quantif.doceqn_docec_fk_i.idx
@@doc_element_quantif.doceqn_pk.idx
@@doc_element_rel.docer_doce_fk_i.idx
@@doc_element_rel.docer_pk.idx
@@doc_element_rel.docer_docer_fk_i.idx
@@doc_external.del_pat_fk_i.idx
@@doc_external.del_inst_fk_i.idx
@@doc_external.de_extr_fk_i.idx

@@doc_external.del_epis_fk_i.idx
@@doc_external.del_ddn_fk_idx.idx
@@doc_external.del_doe_fk_idx.idx
@@doc_external.del_dte_fk_idx.idx
@@doc_external.del_pk.idx
@@doc_image.dig_pk.idx
@@doc_image.di_doce_fk_i.idx
@@doc_original.dog_pk.idx
@@doc_ori_type.doe_pk.idx
@@doc_ori_type.doc_ori_type_code_i.idx
@@doc_qualification.docqual_pk.idx
@@doc_quantification.docquant_pk.idx
@@doc_template.doctemp_doct_fk_i.idx

@@doc_template.doctemp_pk.idx
@@doc_template_diagnosis.doctd_doctemp_fk_i.idx
@@doc_template_diagnosis.doctd_diag_fk_i.idx
@@doc_template_diagnosis.doctd_pk.idx
@@doc_type.dte_code_i.idx
@@doc_type.dte_doe_fk_idx.idx
@@doc_type.dte_pk.idx
@@doc_type_soft.ddt_dte_fk_i.idx
@@doc_type_soft.dtt_s_fk.idx
@@doc_type_soft.dtt_pk.idx
@@document_area.doca_pk.idx
@@documentation.doc_docarea_fk_i.idx
@@documentation.doc_docdim_fk_i.idx

@@documentation.doc_doc_fk_i.idx
@@documentation.doc_doctemp_fk_i.idx
@@documentation.doc_s_fk_i.idx
@@documentation.doc_inst_fk_i.idx
@@documentation.doc_pk.idx
@@documentation.doc_doccomp_fk_i.idx
@@documentation_rel.docrel_doc_fk_i.idx
@@documentation_rel.docrel_doc_fk2_i.idx
@@documentation_rel.docrel_pk.idx
@@documentation_type.docty_pk.idx
@@document_type.doct_pk.idx
@@drug.drug_drbra_fk_i.idx
@@drug.drug_code_i.idx

@@drug.drug_drpha_fk_i.idx
@@drug.drug_drfrm_fk_i.idx
@@drug.drug_pk.idx
@@drug.drug_drrte_fk_idx.idx
@@drug_bolus.dbu_pk.idx
@@drug_brand.drbra_code_i.idx
@@drug_brand.drbra_pk.idx
@@drug_dep_clin_serv.dcst_dcs_fk_i.idx
@@drug_dep_clin_serv.dcst_drug_fk_i.idx
@@drug_dep_clin_serv.dcst_pk.idx
@@drug_dep_clin_serv.dcst_inst_fk_idx.idx
@@drug_dep_clin_serv.dcst_prof_fk_idx.idx
@@drug_dep_clin_serv.dcst_s_fk_idx.idx

@@drug_despachos.drdp_pk.idx
@@drug_despachos.drdp_code_i.idx
@@drug_despachos_soft_inst.ddsi_pk.idx
@@drug_despachos_soft_inst.ddsi_inst_fk_i.idx
@@drug_despachos_soft_inst.ddsi_s_fk_i.idx
@@drug_despachos_soft_inst.ddsi_drdp_fk_i.idx
@@drug_despachos_soft_inst.ddsi_drug_fk_i.idx
@@drug_drip.ddp_pk.idx
@@drug_form.drfrm_code_i.idx
@@drug_form.drfrm_pk.idx
@@drug_instit_justification.din_drug_justif_i.idx
@@drug_instit_justification.din_type_i.idx
@@drug_instit_justification.din_instit_i.idx

@@drug_instit_justification.din_softw_i.idx
@@drug_instit_justification.din_pk.idx
@@drug_justification.djn_pk.idx
@@drug_pharma.drpha_drphc_fk_i.idx
@@drug_pharma.drpha_code_i.idx
@@drug_pharma.drpha_pk.idx
@@drug_pharma_class.drphc_code_i.idx
@@drug_pharma_class.drphc_pk.idx
@@drug_pharma_class_link.dpcl_drphc_fk_i.idx
@@drug_pharma_class_link.dpcl_drug_fk_i.idx
@@drug_pharma_class_link.dpcl_pk.idx
@@drug_pharma_interaction.dpin_drpha_interact_fk_i.idx
@@drug_pharma_interaction.dpin_drpha_fk_i.idx

@@drug_pharma_interaction.drpha_drph_pk.idx
@@drug_plan.drpla_drug_fk_i.idx
@@drug_plan.drpla_pk.idx
@@drug_presc_det.dpdt_drug_fk_i.idx
@@drug_presc_det.dpdt_dpn_fk_i.idx
@@drug_presc_det.dpdt_prof_fk_i.idx
@@drug_presc_det.dpdt_pk.idx
@@drug_presc_det.dpdt_djn_fk_i.idx
@@drug_presc_det.dpdt_drdp_fk_i.idx
@@drug_presc_plan.drprp_prof_writes_fk_i.idx
@@drug_presc_plan.drprp_drtkt_fk_i.idx
@@drug_presc_plan.drprp_prof_cancel_fk_i.idx
@@drug_presc_plan.drprp_pk.idx

@@drug_presc_plan.dpp_flg_status_i.idx
@@drug_presc_plan.drprp_drgpr_fk_i.idx
@@drug_presc_plan.drprp_epis_fk_i.idx
@@drug_prescription.dpn_prof_fk_i.idx
@@drug_prescription.dpn_epis_fk_i.idx
@@drug_prescription.dpn_pk.idx
@@drug_prescription.dpn_epis_dest_fk_idx.idx
@@drug_prescription.dpn_epis_origin_fk_idx.idx
@@drug_prescription.dpn_prof_cancel_fk_idx.idx
@@drug_prescription.dpn_prt_fk_idx.idx
@@drug_prescription.dpn_epis_fk2_i.idx
@@drug_protocols.dps_prt_fk_i.idx
@@drug_protocols.dps_drug_fk_i.idx

@@drug_protocols.dps_pk.idx
@@drug_req.drq_dpn_fk_i.idx
@@drug_req.drq_prof_cancel_fk_i.idx
@@drug_req.drq_prof_req_fk_i.idx
@@drug_req.drq_pk.idx
@@drug_req.drq_epis_status_i.idx
@@drug_req.drq_prof_print_fk_i.idx
@@drug_req.drq_room_fk_idx.idx
@@drug_req.drq_prof_pending_fk_i.idx
@@drug_req_det.drdt_drq_fk_i.idx
@@drug_req_det.drdt_prof_cancel_fk_i.idx
@@drug_req_det.drdt_drug_fk_i.idx
@@drug_req_det.drdt_pk.idx

@@drug_req_det.drdt_drdp_fk_i.idx
@@drug_req_det.drdt_dcs_fk_idx.idx
@@drug_req_det.drdt_prof_pending_fk_i.idx
@@drug_req_supply.drs_drdt_fk_i.idx
@@drug_req_supply.drs_pk.idx
@@drug_req_supply.drs_prof_bgsupl_fk_idx.idx
@@drug_req_supply.drs_prof_cancel_fk_idx.idx
@@drug_req_supply.drs_prof_endsupl_fk_idx.idx
@@drug_req_supply.drs_prof_mov_fk_idx.idx
@@drug_req_supply.drs_prof_receive_fk_idx.idx
@@drug_req_supply.drs_prof_give_aux_fk_i.idx
@@drug_req_supply.drs_prof_utente_fk_i.idx
@@drug_req_supply.drs_prof_end_aux_fk_i.idx

@@drug_route.drrte_code_i.idx
@@drug_route.drrte_pk.idx
@@drug_take_plan.drtkp_drtkt_fk_i.idx
@@drug_take_plan.drtkp_drpla_fk_i.idx
@@drug_take_plan.drtkp_pk.idx
@@drug_take_time.drtkt_pk.idx
@@emb_dep_clin_serv.edv_pk.idx
@@emb_dep_clin_serv.edv_ddg_fk_i.idx
@@emb_dep_clin_serv.edv_mad_fk_i.idx
@@emb_dep_clin_serv.edv_prof_fk_i.idx
@@emb_dep_clin_serv.edv_ieb_fk_i.idx
@@emb_dep_clin_serv.edv_dcs_fk_i.idx
@@emb_dep_clin_serv.edv_s_fk_i.idx

@@epis_anamnesis.comp_prof_fk_i.idx
@@epis_anamnesis.comp_epis_fk_i.idx
@@epis_anamnesis.comp_pk.idx
@@epis_anamnesis.epis_anam_temp_prof_i.idx
@@epis_anamnesis.comp_pat_fk_i.idx
@@epis_anamnesis.comp_diag_fk_idx.idx
@@epis_anamnesis.comp_inst_fk_idx.idx
@@epis_anamnesis.comp_s_fk_idx.idx
@@epis_attending_notes.ean_pk.idx
@@epis_attending_notes.ean_epis_fk_i.idx
@@epis_attending_notes.ean_prof_fk2_i.idx
@@epis_attending_notes.ean_prof_fk_i.idx
@@epis_bartchart.ebar_epis_fk_i.idx

@@epis_bartchart.ebar_prof_fk2_i.idx
@@epis_bartchart.ebar_prof_fk_i.idx
@@epis_bartchart.ebar_pk.idx
@@epis_bartchart.ebar_ecomp_fk_i.idx
@@epis_bartchart_det.ebard_syec_fk_i.idx
@@epis_bartchart_det.ebard_syse_fk_i.idx
@@epis_bartchart_det.ebard_ebar_fk_i.idx
@@epis_bartchart_det.ebard_sysd_fk_i.idx
@@epis_bartchart_det.ebard_prof_fk_i.idx
@@epis_bartchart_det.ebard_pk.idx
@@epis_body_painting.bpg_prof_fk_i.idx
@@epis_body_painting.bpg_bpi_fk_i.idx
@@epis_body_painting.bpg_epis_fk_i.idx

@@epis_body_painting.bpg_pk.idx
@@epis_body_painting_det.bpd_bpg_fk_i.idx
@@epis_body_painting_det.bpd_pk.idx
@@epis_complaint.ecomp_prof_fk_i.idx
@@epis_complaint.ecomp_cmplt_fk_i.idx
@@epis_complaint.ecomp_epis_fk_i.idx
@@epis_complaint.ecomp_pk.idx
@@epis_diagnosis.eds_prof_cancel_fk_i.idx
@@epis_diagnosis.eds_diag_fk_i.idx
@@epis_diagnosis.eds_epis_fk_i.idx
@@epis_diagnosis.eds_prof_diag_fk_i.idx
@@epis_diagnosis.eds_pk.idx
@@epis_diagnosis.eds_edn_fk_i.idx

@@epis_diagnosis_hist.edh_eds_fk_i.idx
@@epis_diagnosis_hist.edh_prof_fk_i.idx
@@epis_diagnosis_hist.edh_pk.idx
@@epis_diagnosis_hist.edh_edn_fk_i.idx
@@epis_diagnosis_notes.edn_pk.idx
@@epis_diet.edt_epis_fk_i.idx
@@epis_diet.edt_prof_fk_i.idx
@@epis_diet.edt_dit_fk_i.idx
@@epis_diet.edt_prof_fk2_i.idx
@@epis_diet.edt_prof_fk3_i.idx
@@epis_diet.edt_pk.idx
@@epis_diet.edt_dse_fk_i.idx
@@epis_documentation.episd_prof_fk3_idx.idx

@@epis_documentation.episd_prof_fk2_i.idx
@@epis_documentation.episd_prof_fk_i.idx
@@epis_documentation.episd_epis_fk_i.idx
@@epis_documentation.episd_ecomp_fk_i.idx
@@epis_documentation.episd_pk.idx
@@epis_documentation.episd_doc_area_fk_idx.idx
@@epis_documentation_det.episdd_doc_fk_i.idx
@@epis_documentation_det.episdd_doce_fk_i.idx
@@epis_documentation_det.episdd_docec_fk_i.idx
@@epis_documentation_det.episdd_episd_fk_i.idx
@@epis_documentation_det.episdd_prof_fk_i.idx
@@epis_documentation_det.episdd_pk.idx
@@epis_drug_usage.due_prof_fk_i.idx

@@epis_drug_usage.due_epis_fk_i.idx
@@epis_drug_usage.due_drug_fk_i.idx
@@epis_drug_usage.due_pk.idx
@@epis_ext_sys.ees_epis_fk_i.idx
@@epis_ext_sys.ees_ess_fk_i.idx
@@epis_ext_sys.ees_pk.idx
@@epis_ext_sys.ees_inst_fk_idx.idx
@@epis_health_plan.ehp_php_fk_i.idx
@@epis_health_plan.ehp_epis_fk_i.idx
@@epis_health_plan.ehp_pk.idx
@@epis_hidrics.ehid_hidin_fk_i.idx
@@epis_hidrics.ehid_epis_fk_i.idx
@@epis_hidrics.ehid_prof_fk_i.idx

@@epis_hidrics.ehid_hidt_fk_i.idx
@@epis_hidrics.ehid_pk.idx
@@epis_hidrics.ehid_prof_fk3_i.idx
@@epis_hidrics.ehid_prof_fk2_i.idx
@@epis_hidrics_balance.ehbe_ehid_fk_i.idx
@@epis_hidrics_balance.ehbe_pk.idx
@@epis_hidrics_balance.ehbe_prof_fk_i.idx
@@epis_hidrics_det.ehidd_hid_fk_i.idx
@@epis_hidrics_det.ehidd_prof_fk_i.idx
@@epis_hidrics_det.ehidd_ehid_fk_i.idx
@@epis_hidrics_det.ehidd_pk.idx
@@epis_hidrics_det.ehidd_ehbe_fk_i.idx
@@epis_hidrics_det.ehidd_prof_fk2_i.idx

@@epis_info.eio_room_fk_i.idx
@@epis_info.eio_bed_fk_i.idx
@@epis_info.eio_prof_fk_i.idx
@@epis_info.eio_pk.idx
@@epis_info.eio_schd_episode_i.idx
@@epis_info.eio_epis_fk_i.idx
@@epis_info.eio_schd_fk_i.idx
@@epis_info.eio_dcs_fk_i.idx
@@epis_info.eio_nurse_fk_idx.idx
@@epis_info.eio_dcs_fk2_i.idx
@@epis_institution.ein_pk.idx
@@epis_institution.ein_epis_fk_idx.idx
@@epis_institution.ein_inst_fk_idx.idx

@@epis_interv.eiv_pk.idx
@@epis_interv.eiv_int_fk_idx.idx
@@epis_interv.eiv_ipn_fk_idx.idx
@@epis_interv.eiv_room_fk_idx.idx
@@epis_interval_notes.einotes_pk.idx
@@epis_interval_notes.einotes_prof_fk_i.idx
@@epis_interval_notes.einotes_epis_fk_i.idx
@@epis_man.emn_org_fk_i.idx
@@epis_man.emn_epis_fk_i.idx
@@epis_man.emn_wrn_fk_i.idx
@@epis_man.emn_room_fk_i.idx
@@epis_man.emn_col_fk_i.idx
@@epis_man.emn_prof_fk_i.idx

@@epis_man.emn_man_fk_i.idx
@@epis_man.emn_nss_fk_i.idx
@@epis_man.emn_pk.idx
@@epis_observation.obv_epis_fk_i.idx
@@epis_observation.obv_prof_fk_i.idx
@@epis_observation.obv_pk.idx
@@epis_observation.obv_epis_temp_prof_i.idx
@@epis_observation.obv_inst_fk_idx.idx
@@epis_observation.obv_s_fk_idx.idx
@@epis_obs_exam.eoe_pem_fk_i.idx
@@epis_obs_exam.eoe_prof_fk_i.idx
@@epis_obs_exam.eoe_epis_fk_i.idx
@@epis_obs_exam.eoe_pk.idx

@@epis_obs_photo.eop_prof_fk_i.idx
@@epis_obs_photo.eop_epis_fk_i.idx
@@epis_obs_photo.eop_pk.idx
@@episode.epis_vis_fk_i.idx
@@episode.epis_cse_fk_i.idx
@@episode.epis_pk.idx
@@episode.epis_ete_fk_i.idx
@@episode.epis_dt_begin_i.idx
@@episode.epis_dt_end_i.idx
@@episode.epis_status_i.idx
@@episode.epis_episode_info_ui.idx
@@episode.epis_epis_fk_i.idx
@@epis_photo.epo_eop_fk_i.idx

@@epis_photo.epo_pk.idx
@@epis_positioning.epg_prof_fk2_i.idx
@@epis_positioning.epg_epis_fk_i.idx
@@epis_positioning.epg_prof_fk_i.idx
@@epis_positioning.epg_pk.idx
@@epis_positioning.epg_prof_fk3_i.idx
@@epis_positioning_det.epgd_pog_fk_i.idx
@@epis_positioning_det.epgd_epg_fk_i.idx
@@epis_positioning_det.epgd_pk.idx
@@epis_positioning_plan.epgp_epgd_fk2_i.idx
@@epis_positioning_plan.epgp_prof_fk_i.idx
@@epis_positioning_plan.epgp_epgd_fk_i.idx
@@epis_positioning_plan.epgp_pk.idx

@@epis_problem.epp_ppm_fk_i.idx
@@epis_problem.epp_prof_fk_i.idx
@@epis_problem.epp_epis_fk_i.idx
@@epis_problem.epp_pk.idx
@@epis_prof_rec.eprc_pk.idx
@@epis_prof_resp.epr_prof_fk4_i.idx
@@epis_prof_resp.epr_prof_fk2_i.idx
@@epis_prof_resp.epr_room_fk_i.idx
@@epis_prof_resp.epr_prof_fk3_i.idx
@@epis_prof_resp.epr_dep_fk_i.idx
@@epis_prof_resp.epr_spc_fk_i.idx
@@epis_prof_resp.epr_prof_fk6_i.idx
@@epis_prof_resp.epr_bed_fk_i.idx

@@epis_prof_resp.epr_prof_fk7_i.idx
@@epis_prof_resp.epr_prof_fk5_i.idx
@@epis_prof_resp.epr_prof_fk_i.idx
@@epis_prof_resp.epr_dep_fk2_i.idx
@@epis_prof_resp.epr_epis_fk_i.idx
@@epis_prof_resp.epr_pk.idx
@@epis_protocols.epis_prot_prof_fk_idx.idx
@@epis_protocols.epis_prot_prof_fk2_idx.idx
@@epis_protocols.epis_prot_prt_fk_idx.idx
@@epis_protocols.epis_prot_pk.idx
@@epis_readmission.ern_epis_fk_i.idx
@@epis_readmission.ern_pk.idx
@@epis_recomend.ernd_pk.idx

@@epis_recomend.ernd_epis_fk_idx.idx
@@epis_recomend.ernd_prof_fk_idx.idx
@@epis_report.erept_pk.idx
@@epis_report_section.erns_pk.idx
@@epis_review_systems.ersy_prof_fk_i.idx
@@epis_review_systems.ersy_epis_fk_i.idx
@@epis_review_systems.ersy_prof_fk2_i.idx
@@epis_review_systems.ersy_pk.idx
@@epis_task.etk_epis_fk_i.idx
@@epis_task.etk_pk.idx
@@epis_triage.etrg_org_fk_i.idx
@@epis_triage.etrg_epis_fk_i.idx
@@epis_triage.etrg_twrn_fk_i.idx

@@epis_triage.etrg_tcol_fk_i.idx
@@epis_triage.etrg_room_fk_i.idx
@@epis_triage.etrg_tri_fk_i.idx
@@epis_triage.etrg_prof_fk_i.idx
@@epis_triage.etrg_nss_fk_i.idx
@@epis_triage.etrg_pk.idx
@@epis_triage.etrg_tnsr_fk_i.idx
@@epis_triage.etrg_comp_fk_i.idx
@@epis_type.ete_pk.idx
@@epis_type.ete_s_fk_idx.idx
@@epis_type_room.etr_pk.idx
@@epis_type_room.etr_ete_fk_idx.idx
@@epis_type_room.etr_inst_fk_idx.idx

@@epis_type_room.etr_room_fk_idx.idx
@@equip_protocols.epl_ssd_fk_idx.idx
@@equip_protocols.epl_prt_fk_idx.idx
@@equip_protocols.epl_sep_fk_idx.idx
@@estate.est_prof_fk_i.idx
@@estate.est_epis_fk_i.idx
@@estate.est_pk.idx
@@event_group.eg_pk.idx
@@event_group_soft_inst.egsi_pk.idx
@@exam.exam_code_i.idx
@@exam.exam_pk.idx
@@exam.exam_type_i.idx
@@exam.ex_flg_type_i.idx

@@exam.exam_ect_fk_idx.idx
@@exam_cat.ect_pk.idx
@@exam_cat_dcs.ecc_pk.idx
@@exam_cat_dcs.ecc_dcs_fk_i.idx
@@exam_cat_dcs.ecc_ect_fk_i.idx
@@exam_cat_dcs_ext_sys.eces_ess_fk_i.idx
@@exam_cat_dcs_ext_sys.eces_ecc_fk_i.idx
@@exam_cat_dcs_ext_sys.eces_pk.idx
@@exam_dep_clin_serv.ecst_dcs_fk_i.idx
@@exam_dep_clin_serv.ecst_exam_fk_i.idx
@@exam_dep_clin_serv.ecst_pk.idx
@@exam_dep_clin_serv.ecst_egp_fk_idx.idx
@@exam_dep_clin_serv.ecst_inst_fk_idx.idx

@@exam_dep_clin_serv.ecst_prof_fk_idx.idx
@@exam_dep_clin_serv.ecst_s_fk_idx.idx
@@exam_drug.edg_drug_fk_i.idx
@@exam_drug.edg_exam_fk_i.idx
@@exam_drug.edg_pk.idx
@@exam_drug.edg_inst_fk_idx.idx
@@exam_egp.exmg_egp_fk_i.idx
@@exam_egp.exmg_exam_fk_i.idx
@@exam_egp.exmg_pk.idx
@@exam_ext_sys_delete.emes_ess_fk_i.idx
@@exam_ext_sys_delete.emes_exam_fk_i.idx
@@exam_ext_sys_delete.emes_pk.idx
@@exam_group.egp_pk.idx

@@exam_prep_mesg.epmg_pme_fk_i.idx
@@exam_prep_mesg.epmg_exam_fk_i.idx
@@exam_prep_mesg.epmg_pk.idx
@@exam_prep_mesg.epmg_inst_fk_idx.idx
@@exam_protocols.eps_exam_fk_i.idx
@@exam_protocols.eps_prt_fk_i.idx
@@exam_protocols.eps_pk.idx
@@exam_req.ereq_schd_fk_i.idx
@@exam_req.ereq_inst_fk_i.idx
@@exam_req.ereq_prof_cancel_fk_i.idx
@@exam_req.ereq_prof_req_fk_i.idx
@@exam_req.ereq_schd_consult_fk_i.idx
@@exam_req.ereq_epis_fk_i.idx

@@exam_req.ereq_pk.idx
@@exam_req.ereq_prof_app_fk_i.idx
@@exam_req.ereq_prof_authz_fk_i.idx
@@exam_req.ereq_flg_time_i.idx
@@exam_req.ereq_epis_status_i.idx
@@exam_req.ereq_epis_dest_fk_idx.idx
@@exam_req.ereq_epis_origin_fk_idx.idx
@@exam_req.ereq_prof_resched_fk_idx.idx
@@exam_req.ereq_prt_fk_idx.idx
@@exam_req.ereq_epis_fk2_i.idx
@@exam_req_det.erd_mov_fk_i.idx
@@exam_req_det.erd_prof_fk_i.idx
@@exam_req_det.erd_ereq_fk_i.idx

@@exam_req_det.erd_exam_fk_i.idx
@@exam_req_det.erd_erd_fk_i.idx
@@exam_req_det.erd_pk.idx
@@exam_req_det.exam_req_det_status_i.idx
@@exam_req_det.erd_room_fk_idx.idx
@@exam_result.eres_exam_fk_i.idx
@@exam_result.eres_pat_fk_i.idx
@@exam_result.eres_erd_fk_i.idx
@@exam_result.eres_inst_fk_i.idx
@@exam_result.eres_prof_fk_i.idx
@@exam_result.eres_pk.idx
@@exam_result.exam_result_i_id_episode.idx
@@exam_result.exam_result_alert_i.idx

@@exam_result.er_exam_req_det_i.idx
@@exam_result.eres_prof_mov_fk_idx.idx
@@exam_result.eres_prof_receive_fk_idx.idx
@@exam_result.eres_epis_write_fk_i.idx
@@exam_room.erm_exam_fk_i.idx
@@exam_room.erm_room_fk_i.idx
@@exam_room.erm_pk.idx
@@external_cause.extc_code_i.idx
@@external_cause.extc_pk.idx
@@external_sys.ess_pk.idx
@@family_monetary.fmy_pk.idx
@@family_monetary.fmy_ptfam_fk_idx.idx
@@family_relationship.frp_pk.idx

@@family_relationship_relat.frn_pk.idx
@@family_relationship_relat.frn_frp_fk_idx.idx
@@family_relationship_relat.frn_frp_fk2_idx.idx
@@floors.flo_pk.idx
@@floors_department.flsdep_dep_fk_i.idx
@@floors_department.flsdep_pk.idx
@@floors_department.flsdep_finst_fk_i.idx
@@floors_dep_position.flsdepp_flsdep_fk_i.idx
@@floors_dep_position.flsdepp_pk.idx
@@floors_institution.finst_inst_fk_i.idx
@@floors_institution.finst_flo_fk_i.idx
@@floors_institution.finst_pk.idx
@@floors_institution.finst_building_fk_i.idx

@@geo_location.gln_pk.idx
@@geo_location.gln_ctr_fk_i.idx
@@ginec_obstet.oce_pk.idx
@@graffar_criteria.gca_pk.idx
@@graffar_crit_value.gcv_pk.idx
@@graffar_crit_value.gcv_gca_fk_i.idx
@@grid_task.gtk_pk.idx
@@grid_task.gtk_epis_fk_i.idx
@@grid_task_between.gtn_epis_fk_i.idx
@@grid_task_between.gtn_pk.idx
@@habit.hat_pk.idx
@@harvest.harv_epis_fk_i.idx
@@harvest.harv_prof_receive_tube_fk_i.idx

@@harvest.harv_bpt_fk_i.idx
@@harvest.harv_prof_cancel_fk_i.idx
@@harvest.harv_room_harvest_fk_i.idx
@@harvest.harv_room_receive_tube_fk_i.idx
@@harvest.harv_prof_mov_tube_fk_i.idx
@@harvest.harv_prof_harvest_fk_i.idx
@@harvest.harv_pk.idx
@@harvest.harv_flg_status_dt_i.idx
@@harvest.harv_inst_fk_idx.idx
@@harvest.harv_epis_fk2_i.idx
@@hcn_def_crit.hcn_def_crit_pk.idx
@@health_plan.hpn_code_i.idx
@@health_plan.hpn_pk.idx

@@health_plan_instit.hpi_pk.idx
@@health_plan_instit.hpi_hpn_fk_idx.idx
@@health_plan_instit.hpi_inst_fk_idx.idx
@@hemo_protocols.hemo_prot_pk.idx
@@hemo_protocols.hemo_prot_hemo_type_fk_idx.idx
@@hemo_protocols.hemo_prot_prt_fk_idx.idx
@@hemo_req.hemo_req_prof_req_fk_i.idx
@@hemo_req.hemo_req_pk.idx
@@hemo_req.hemo_req_id_schedule_i.idx
@@hemo_req.hemo_req_epis_fk_idx.idx
@@hemo_req.hemo_req_prof_fk2_idx.idx
@@hemo_req_det.hemo_rd_hemo_req_fk_i.idx
@@hemo_req_det.hemo_rd_hemo_type_fk_i.idx

@@hemo_req_det.hemo_rd_pk.idx
@@hemo_req_det.hemo_rd_prof_fk_idx.idx
@@hemo_req_supply.hemo_rs_hemo_rd_fk_i.idx
@@hemo_req_supply.hemo_rs_pk.idx
@@hemo_req_supply.hemo_rs_drbra_fk_idx.idx
@@hemo_req_supply.hemo_rs_prof_cancel_fk_idx.idx
@@hemo_req_supply.hemo_rs_prof_fk_idx.idx
@@hemo_req_supply.hemo_rs_prof_mov_fk_idx.idx
@@hemo_req_supply.hemo_rs_prof_receive_fk_idx.idx
@@hemo_req_supply.hemo_rs_prof_supply_fk_idx.idx
@@hemo_type.hemo_type_pk.idx
@@hidrics.hid_pk.idx
@@hidrics.hid_unitm_fk_i.idx

@@hidrics_interval.hidin_pk.idx
@@hidrics_relation.hrn_hidt_fk_i.idx
@@hidrics_relation.hrn_hid_fk_i.idx
@@hidrics_relation.hrn_s_fk_i.idx
@@hidrics_relation.hrn_inst_fk_i.idx
@@hidrics_type.hidt_pk.idx
@@home.home_prof_fk_i.idx
@@home.home_ptfam_fk_i.idx
@@home.home_pk.idx
@@icnp_axis.ias_icln_fk_i.idx
@@icnp_axis.ias_pk.idx
@@icnp_classification.icln_pk.idx
@@icnp_compo_clin_serv.icv_pk.idx

@@icnp_compo_clin_serv.icv_uk.idx
@@icnp_compo_dcs.icc_pk_i.idx
@@icnp_compo_dcs.icc_uk.idx
@@icnp_compo_dcs.icc_dcs_i.idx
@@icnp_compo_folder.icf_nu_i.idx
@@icnp_compo_folder.icr_pk.idx
@@icnp_compo_folder.icr_icn_fk_idx.idx
@@icnp_compo_folder.icr_inst_fk_idx.idx
@@icnp_compo_inst.ici_u_i.idx
@@icnp_compo_inst.ici_pk.idx
@@icnp_compo_inst.ici_inst_fk_idx.idx
@@icnp_composition.icn_nu_i.idx
@@icnp_composition.icn_pk.idx

@@icnp_composition_term.ict_itm_fk_i.idx
@@icnp_composition_term.ict_icn_fk_i.idx
@@icnp_composition_term.ict_pk.idx
@@icnp_dictionary.idy_pk.idx
@@icnp_epis_diag_interv.iedi_eipd_fk_i.idx
@@icnp_epis_diag_interv.iedi_eipi_fk_i.idx
@@icnp_epis_diag_interv.iedi_pk.idx
@@icnp_epis_diagnosis.eipd_nu_i.idx
@@icnp_epis_diagnosis.eipd_pk.idx
@@icnp_epis_diagnosis.eipd_eipd_fk_idx.idx
@@icnp_epis_diagnosis.eipd_icn_fk_idx.idx
@@icnp_epis_diagnosis.eipd_pat_fk_idx.idx
@@icnp_epis_diagnosis.eipd_prof_canc_fk_idx.idx

@@icnp_epis_diagnosis.eipd_prof_fk_idx.idx
@@icnp_epis_intervention.eipi_prof_fk_i.idx
@@icnp_epis_intervention.eipi_icn_fk_i.idx
@@icnp_epis_intervention.eipi_epis_fk_i.idx
@@icnp_epis_intervention.eipi_prof_canc_fk_i.idx
@@icnp_epis_intervention.eipi_pk.idx
@@icnp_epis_intervention.eipi_eipi_fk_idx.idx
@@icnp_epis_intervention.eipi_pat_fk_idx.idx
@@icnp_folder.if_nu_i.idx
@@icnp_folder.ifr_pk.idx
@@icnp_folder.ifr_s_fk_idx.idx
@@icnp_morph.ilc_pk.idx
@@icnp_morph.ilc_idy_fk_idx.idx

@@icnp_morph.ilc_idy_fk2_idx.idx
@@icnp_morph.ilc_idy_fk3_idx.idx
@@icnp_morph.ilc_idy_fk4_idx.idx
@@icnp_morph.ilc_idy_fk5_idx.idx
@@icnp_predefined_action.ipa_nu_i.idx
@@icnp_predefined_action.ida_pk.idx
@@icnp_predefined_action.ida_icn_fk_idx.idx
@@icnp_predefined_action.ida_icn_fk2_idx.idx
@@icnp_relationship.irp_itm_rel_fk_i.idx
@@icnp_relationship.irp_itm_fk_i.idx
@@icnp_relationship.irp_pk.idx
@@icnp_term.itm_ias_fk_i.idx
@@icnp_term.itm_itm_fk_i.idx

@@icnp_term.itm_pk.idx
@@icnp_transition_state.ite_pk.idx
@@identification_notes.inotes_docarea_fk_i.idx
@@identification_notes.inotes_pat_fk_i.idx
@@identification_notes.inotes_doca_fk_i.idx
@@identification_notes.inotes_epis_fk_i.idx
@@identification_notes.inotes_prof_fk_i.idx
@@identification_notes.inotes_pk.idx
@@implementation.impl_pk.idx
@@ine_location.iln_pk.idx
@@inf_atc.iac_pk.idx
@@inf_atc_lnk.ial_pk.idx
@@inf_atc_lnk.ial_imd_fk_i.idx

@@inf_atc_lnk.ial_iac_fk_i.idx
@@inf_cft.icf_idcode_ui.idx
@@inf_cft.icf_pk.idx
@@inf_cft.icf_parent_fk_i.idx
@@inf_cft.icf_cftid_ui.idx
@@inf_cft.icf_level2_fk_i.idx
@@inf_cft.icf_level4_fk_i.idx
@@inf_cft.icf_level5_fk_i.idx
@@inf_cft.icf_level1_fk_i.idx
@@inf_cft.icf_level3_fk_i.idx
@@inf_cft_lnk.icl_pk.idx
@@inf_cft_lnk.icl_icf_i.idx
@@inf_cft_lnk.icl_imd_fk_i.idx

@@inf_class_disp.icd_pk.idx
@@inf_class_estup.ice_pk.idx
@@inf_comerc.icc_pk.idx
@@inf_comerc.icc_ieb_fk_i.idx
@@inf_comerc.icc_ido_fk_i.idx
@@inf_dcipt.idt_pk.idx
@@inf_diabetes_lnk.idk_pk.idx
@@inf_diabetes_lnk.idk_imd_fk_i.idx
@@inf_diabetes_lnk.idk_itl_fk_i.idx
@@inf_diploma.idm_pk.idx
@@inf_dispo.ido_pk.idx
@@inf_emb.ieb_pk.idx
@@inf_emb.ieb_imd_fk_i.idx

@@inf_emb.ieb_igm_fk_i.idx
@@inf_emb.ieb_iet_fk_i.idx
@@inf_emb.ieb_ito_fk_i.idx
@@inf_emb_comerc.iec_pk.idx
@@inf_emb_unit.iet_pk.idx
@@inf_estado_aim.iem_pk.idx
@@inf_form_farm.iff_pk.idx
@@inf_grupo_hom.igm_pk.idx
@@inf_med.imd_itd_fk_i.idx
@@inf_med.imd_iff_fk_i.idx
@@inf_med.imd_idt_fk_i.idx
@@inf_med.imd_icd_fk_i.idx
@@inf_med.imd_pk.idx

@@inf_med.imd_iem_fk_i.idx
@@inf_med.imd_ita_fk_i.idx
@@inf_med.imd_ice_fk_i.idx
@@inf_patol_dip_lnk.ipdl_pk.idx
@@inf_patol_dip_lnk.ipdl_ida_fk_i.idx
@@inf_patol_dip_lnk.ipdl_ipp_fk_i.idx
@@inf_patol_esp.ipe_pk.idx
@@inf_patol_esp_lnk.ipel_pk.idx
@@inf_patol_esp_lnk.ipel_ipdl_fk_i.idx
@@inf_patol_esp_lnk.ipel_ieb_fk_i.idx
@@inf_preco.ipo_pk.idx
@@inf_preco.ipo_iebdata_i.idx
@@inf_preco.ipo_ieb_fk_i.idx

@@inf_preco.ipo_ito_fk_i.idx
@@inf_subst.ist_pk.idx
@@inf_subst_lnk.isk_imd_fk_i.idx
@@inf_subst_lnk.isk_ist_fk_i.idx
@@inf_tipo_diab_mel.itl_pk.idx
@@inf_tipo_preco.itp_pk.idx
@@inf_tipo_prod.itd_pk.idx
@@inf_titular_aim.ita_pk.idx
@@inf_tratamento.ito_pk.idx
@@inf_vias_admin.iva_pk.idx
@@inf_vias_admin_lnk.ivk_pk.idx
@@inf_vias_admin_lnk.ivk_imd_fk_i.idx
@@inf_vias_admin_lnk.ivk_iva_fk_i.idx

@@ingredient.ing_type_i.idx
@@ingredient.ing_pk.idx
@@inp_error.err_pk.idx
@@inp_log.log_pk.idx
@@instit_ext_sys.iess_ess_fk_i.idx
@@instit_ext_sys.iess_pk.idx
@@instit_ext_sys.iess_dcs_fk_idx.idx
@@instit_ext_sys.iess_inst_fk_idx.idx
@@institution.inst_code_i.idx
@@institution.inst_pk.idx
@@interv_dep_clin_serv.ics_dcs_fk_i.idx
@@interv_dep_clin_serv.ics_int_fk_i.idx
@@interv_dep_clin_serv.ics_pk.idx

@@interv_dep_clin_serv.ics_inst_fk_idx.idx
@@interv_dep_clin_serv.ics_prof_fk_idx.idx
@@interv_dep_clin_serv.ics_s_fk_idx.idx
@@interv_drug.idg_drug_fk_i.idx
@@interv_drug.idg_int_fk_i.idx
@@interv_drug.idg_pk.idx
@@interv_drug.idg_inst_fk_idx.idx
@@intervention.int_int_fk_i.idx
@@intervention.int_code_i.idx
@@intervention.int_pk.idx
@@intervention.int_bpt_fk_i.idx
@@intervention.int_ipa_fk_idx.idx
@@intervention.int_ssar_fk_idx.idx

@@interv_ext_sys_delete.ies_pk.idx
@@interv_ext_sys_delete.ies_ess_fk_idx.idx
@@interv_ext_sys_delete.ies_inst_fk_idx.idx
@@interv_ext_sys_delete.ies_int_fk_idx.idx
@@interv_physiatry_area.ipa_pk.idx
@@interv_prep_msg.ipm_pme_fk_i.idx
@@interv_prep_msg.ipm_int_fk_i.idx
@@interv_prep_msg.ipm_pk.idx
@@interv_prep_msg.ipm_inst_fk_idx.idx
@@interv_presc_det.ipd_pk.idx
@@interv_presc_det.ipd_interv_id_fk_i.idx
@@interv_presc_det.ipp_status_interv_i.idx
@@interv_presc_det.ipd_int_fk_idx.idx

@@interv_presc_det.ipd_prof_fk_idx.idx
@@interv_presc_det.ipn_dpdt_fk_idx.idx
@@interv_presc_det.ipn_mov_fk_idx.idx
@@interv_presc_det.nard_fk_idx.idx
@@interv_presc_plan.ipp_ipn_fk_i.idx
@@interv_presc_plan.ipp_prof_fk_i.idx
@@interv_presc_plan.ipp_pk.idx
@@interv_presc_plan.ipp_status_dt_plan_i.idx
@@interv_presc_plan.ipp_prof_take_fk_idx.idx
@@interv_presc_plan.ipp_wtt_fk_idx.idx
@@interv_presc_plan.ipp_epis_fk_i.idx
@@interv_prescription.presc_epis_fk_i.idx
@@interv_prescription.presc_prof_fk_i.idx

@@interv_prescription.presc_pk.idx
@@interv_prescription.ip_flg_time_i.idx
@@interv_prescription.presc_epis_dest_fk_idx.idx
@@interv_prescription.presc_epis_origin_fk_idx.idx
@@interv_prescription.presc_inst_fk_idx.idx
@@interv_prescription.presc_prof_cancel_fk_idx.idx
@@interv_prescription.presc_prt_fk_idx.idx
@@interv_prescription.presc_epis_fk2_i.idx
@@interv_protocols.ips_int_fk_idx.idx
@@interv_protocols.ips_prt_fk_i.idx
@@interv_protocols.ips_pk.idx
@@interv_room.irm_room_fk_i.idx
@@interv_room.irm_int_fk_i.idx

@@interv_room.irm_pk.idx
@@isencao.i_pk.idx
@@java$class$md5$table.sys_c007208.idx
@@language.lang_pk.idx
@@manchester.man_disc_fk_i.idx
@@manchester.man_col_fk_i.idx
@@manchester.man_brd_fk_i.idx
@@manchester.man_pk.idx
@@manipulated.mad_type_i.idx
@@manipulated.mdg_mgp_fk_i.idx
@@manipulated.mdg_pk.idx
@@manipulated_group.mgp_pk.idx
@@manipulated_ingredient.mit_mad_fk_i.idx

@@manipulated_ingredient.mit_ing_fk_i.idx
@@manipulated_ingredient.mit_pk.idx
@@match_epis.mtch_pk.idx
@@material.matr_mte_fk_i.idx
@@material.matr_matr_fk_i.idx
@@material.matr_pk.idx
@@material_protocols.mat_prot_pk.idx
@@material_req.mreq_schd_fk_i.idx
@@material_req.mreq_epis_fk_i.idx
@@material_req.mreq_prof_request_fk_i.idx
@@material_req.mreq_pk.idx
@@material_req_det.mrd_room_fk_i.idx
@@material_req_det.mrd_mreq_fk_i.idx

@@material_req_det.mrd_matr_fk_i.idx
@@material_req_det.mrd_pk.idx
@@material_type.mte_pk.idx
@@matr_dep_clin_serv.mcst_dcs_fk_i.idx
@@matr_dep_clin_serv.mcst_matr_fk_i.idx
@@matr_dep_clin_serv.mcst_pk.idx
@@matr_dep_clin_serv.mcst_inst_fk_idx.idx
@@matr_dep_clin_serv.mcst_s_fk_idx.idx
@@matr_room.mrm_matr_fk_i.idx
@@matr_room.mrm_room_fk_i.idx
@@matr_room.mrm_pk.idx
@@matr_scheduled.msd_schd_fk_i.idx
@@matr_scheduled.msd_matr_fk_i.idx

@@matr_scheduled.msd_pk.idx
@@mcdt_req_diagnosis.mrd_diag_fk_i.idx
@@mcdt_req_diagnosis.mrd_art_fk_i.idx
@@mcdt_req_diagnosis.mrd_ereq_fk_i.idx
@@mcdt_req_diagnosis.mrd_presc_fk_i.idx
@@mcdt_req_diagnosis.mrd_eds_fk_i.idx
@@mcdt_req_diagnosis.mrd_prof_fk_i.idx
@@mdm_prof_coding.mpc_epis_fk_i.idx
@@mdm_prof_coding.mpc_prof_fk_i.idx
@@mdm_prof_coding.mpc_pk.idx
@@monitorization.mont_pk.idx
@@monitorization.mont_epis_dest_fk_idx.idx
@@monitorization.mont_epis_fk_idx.idx

@@monitorization.mont_epis_origin_fk_idx.idx
@@monitorization.mont_prof_cancel_fk_idx.idx
@@monitorization.mont_prof_fk_idx.idx
@@monitorization_vs.mvs_mont_fk_i.idx
@@monitorization_vs.mvs_vsn_fk_i.idx
@@monitorization_vs.mvs_pk.idx
@@monitorization_vs.mvs_status_dt_i.idx
@@monitorization_vs.mvs_prof_cancel_fk_idx.idx
@@monitorization_vs_plan.mvsp_pk.idx
@@monitorization_vs_plan.mvsp_mvs_fk_i.idx
@@movement.mov_prof_receive_fk_i.idx
@@movement.mov_prof_request_fk_i.idx
@@movement.mov_epis_fk_i.idx

@@movement.mov_prof_cancel_fk_i.idx
@@movement.mov_prof_move_fk_i.idx
@@movement.mov_pk.idx
@@movement.mov_status_i.idx
@@movement.mov_room_from_fk_idx.idx
@@movement.mov_room_to_fk_idx.idx
@@movement.mov_epis_write_fk_i.idx
@@necessity.nss_code_i.idx
@@necessity.nss_pk.idx
@@nurse_activity_req.nar_pk.idx
@@nurse_activity_req.nar_epis_dest_fk_idx.idx
@@nurse_activity_req.nar_epis_fk_idx.idx
@@nurse_activity_req.nar_epis_origin_fk_idx.idx

@@nurse_activity_req.nar_prof_cancel_fk_idx.idx
@@nurse_activity_req.nar_prof_fk_idx.idx
@@nurse_activity_req.nar_schd_fk_idx.idx
@@nurse_actv_req_det.nard_pk.idx
@@nurse_actv_req_det.nard_nar_fk_idx.idx
@@nurse_actv_req_det.nard_prof_cancel_fk_idx.idx
@@nurse_actv_req_det.nard_wte_fk_idx.idx
@@nurse_discharge.nde_pk.idx
@@nurse_discharge.nde_epis_fk_idx.idx
@@nurse_discharge.nde_prof_cancel_fk_idx.idx
@@nurse_discharge.nde_prof_fk_idx.idx
@@nurse_tea_req.ntr_pk.idx
@@nurse_tea_req.ntr_epis_fk_idx.idx

@@nurse_tea_req.ntr_prof_cancel_fk_idx.idx
@@nurse_tea_req.ntr_prof_exec_fk_idx.idx
@@nurse_tea_req.ntr_prof_req_fk_idx.idx
@@occupation.occ_code_i.idx
@@occupation.occ_pk.idx
@@opinion.opn_epis_fk_i.idx
@@opinion.opn_prof_questions_fk_i.idx
@@opinion.opn_prof_questioned_fk_i.idx
@@opinion.opn_pk.idx
@@opinion.opn_spc_fk_i.idx
@@opinion.opn_flg_state_p_i.idx
@@opinion.opn_flg_state_i.idx
@@opinion_prof.opf_opn_fk_i.idx

@@opinion_prof.opf_prof_fk_i.idx
@@opinion_prof.opf_pk.idx
@@opinion_prof.opf_prof_opn_i.idx
@@origin.org_code_i.idx
@@origin.org_pk.idx
@@origin_soft.ost_pk.idx
@@origin_soft.ost_org_fk_idx.idx
@@origin_soft.ost_s_fk_idx.idx
@@outlook.pk_outlook.idx
@@param_analysis_ext_sys_delete.paes_pk.idx
@@param_analysis_ext_sys_delete.paes_ess_fk_idx.idx
@@param_analysis_ext_sys_delete.paes_inst_fk_idx.idx
@@param_analysis_ext_sys_delete.paes_pany_fk_idx.idx

@@parameter_analysis.pany_code_i.idx
@@parameter_analysis.pany_pk.idx
@@pat_allergy.pal_prof_write_fk_i.idx
@@pat_allergy.pal_pat_fk_i.idx
@@pat_allergy.pal_alg_fk_i.idx
@@pat_allergy.pal_drpha_fk_i.idx
@@pat_allergy.pal_pk.idx
@@pat_allergy.pal_epis_fk_idx.idx
@@pat_allergy.pal_inst_fk_idx.idx
@@pat_allergy_hist.pah_pk.idx
@@pat_allergy_hist.pah_epis_fk_idx.idx
@@pat_allergy_hist.pah_inst_fk_idx.idx
@@pat_allergy_hist.pah_pal_fk_idx.idx

@@pat_blood_group.pbg_pat_fk_i.idx
@@pat_blood_group.pbg_prof_fk_i.idx
@@pat_blood_group.pbg_pk.idx
@@pat_blood_group.pbg_epis_fk_idx.idx
@@pat_blood_group.pbg_inst_fk_idx.idx
@@pat_child_clin_rec.pccr_inst_fk_i.idx
@@pat_child_clin_rec.pccr_prof_fk_i.idx
@@pat_child_clin_rec.pccr_pat_fk_i.idx
@@pat_child_clin_rec.pccr_pk.idx
@@pat_child_feed_dev.pcf_prof_fk_i.idx
@@pat_child_feed_dev.pcf_fdp_fk_i.idx
@@pat_child_feed_dev.pcf_pat_fk_i.idx
@@pat_child_feed_dev.pcf_pk.idx

@@pat_cli_attributes.ptcat_pat_fk_i.idx
@@pat_cli_attributes.ptcat_pk.idx
@@pat_cli_attributes.ptcat_inst_fk_idx.idx
@@pat_cli_attributes.ptcat_recm_fk_idx.idx
@@pat_cntrceptiv.pce_prof_fk_i.idx
@@pat_cntrceptiv.pce_cpe_fk_i.idx
@@pat_cntrceptiv.pce_pat_fk_i.idx
@@pat_cntrceptiv.pce_pk.idx
@@pat_delivery.pdy_pat_fk_i.idx
@@pat_delivery.pdy_prof_fk_i.idx
@@pat_delivery.pdy_inst_fk_i.idx
@@pat_delivery.pdy_pk.idx
@@pat_delivery.pdy_ppy_fk_idx.idx

@@pat_dmgr_hist.pdt_pk.idx
@@pat_dmgr_hist.pdt_professional_fk_i.idx
@@pat_dmgr_hist.pdt_institution_fk_i.idx
@@pat_dmgr_hist.pdt_country_fk_i.idx
@@pat_dmgr_hist.pdt_scholarship_fk_i.idx
@@pat_dmgr_hist.pdt_recm_fk_i.idx
@@pat_dmgr_hist.pdt_occupations_fk_i.idx
@@pat_dmgr_hist.pdt_isencao_fk_i.idx
@@pat_doc.pdoc_pat_fk_i.idx
@@pat_doc.pdoc_dte_fk_i.idx
@@pat_doc.pdoc_pk.idx
@@pat_doc.pdoc_inst_fk_idx.idx
@@pat_ext_sys.pes_pat_fk_i.idx

@@pat_ext_sys.pes_ess_fk_i.idx
@@pat_ext_sys.pes_pk.idx
@@pat_ext_sys.pes_inst_fk_idx.idx
@@pat_family.ptfam_name_i.idx
@@pat_family.ptfam_pk.idx
@@pat_family.ptfam_inst_enroled_fk_idx.idx
@@pat_family.ptfam_inst_fk_idx.idx
@@pat_family.ptfam_scs_fk_idx.idx
@@pat_family_disease.ptfdi_prof_fk_i.idx
@@pat_family_disease.ptfdi_ptfmm_fk_i.idx
@@pat_family_disease.ptfdi_diag_fk_i.idx
@@pat_family_disease.ptfdi_pk.idx
@@pat_family_disease.ptfdi_inst_fk_idx.idx

@@pat_family_member.ptfmm_ptfam_fk_i.idx
@@pat_family_member.ptfmm_pk.idx
@@pat_family_member.ptfmm_frp_fk_idx.idx
@@pat_family_member.ptfmm_inst_fk_idx.idx
@@pat_family_member.ptfmm_pat_fk_idx.idx
@@pat_family_prof.pfp_prof_fk_i.idx
@@pat_family_prof.pfp_ptfam_fk_i.idx
@@pat_family_prof.pfp_inst_fk_i.idx
@@pat_family_prof.pfp_pk.idx
@@pat_family_prof.pfp_pat_fk_idx.idx
@@pat_fam_soc_hist.pfsh_ptfam_fk_i.idx
@@pat_fam_soc_hist.pfsh_pk.idx
@@pat_fam_soc_hist.pfsh_epis_fk_idx.idx

@@pat_fam_soc_hist.pfsh_inst_fk_idx.idx
@@pat_fam_soc_hist.pfsh_pat_fk_idx.idx
@@pat_fam_soc_hist.pfsh_prof_cancel_fk_idx.idx
@@pat_fam_soc_hist.pfsh_prof_write_fk_idx.idx
@@pat_ginec.ptgc_pat_fk_i.idx
@@pat_ginec.ptgc_pk.idx
@@pat_ginec_obstet.pgc_prof_fk_i.idx
@@pat_ginec_obstet.pgc_oce_fk_i.idx
@@pat_ginec_obstet.pgc_pat_fk_i.idx
@@pat_ginec_obstet.pgc_pk.idx
@@pat_graffar_crit.pgct_pk.idx
@@pat_graffar_crit.pgct_gcv_fk_i.idx
@@pat_graffar_crit.pgct_pat_fk_idx.idx

@@pat_graffar_crit.pgct_prof_fk_idx.idx
@@pat_habit.ptnot_pk.idx
@@pat_habit.ptnot_prof_cancel_fk_i.idx
@@pat_habit.ptnot_prof_writes_fk_i.idx
@@pat_habit.ptnot_pat_fk_i.idx
@@pat_habit.ptnot_epis_fk_idx.idx
@@pat_habit.ptnot_hat_fk_idx.idx
@@pat_habit.ptnot_inst_fk_idx.idx
@@pat_health_plan.php_hpn_fk_i.idx
@@pat_health_plan.php_pat_fk_i.idx
@@pat_health_plan.php_pk.idx
@@pat_health_plan.php_inst_fk_idx.idx
@@patient.pat_pk.idx

@@patient.pat_ptfam_fk_idx.idx
@@pat_job.ptjob_pat_fk_i.idx
@@pat_job.ptjob_pk.idx
@@pat_job.ptjob_occ_fk_i.idx
@@pat_job.ptjob_inst_fk_idx.idx
@@pat_med_decl.pmd_prof_writes_fk_i.idx
@@pat_med_decl.pmd_prof_cancel_fk_i.idx
@@pat_med_decl.pmd_pat_fk_i.idx
@@pat_med_decl.pmd_diag_fk_i.idx
@@pat_med_decl.pmd_pk.idx
@@pat_med_decl.pmd_inst_fk_idx.idx
@@pat_medication.pmn_prof_upd_fk_i.idx
@@pat_medication.pmn_drug_fk_i.idx

@@pat_medication.pmn_prof_writes_fk_i.idx
@@pat_medication.pmn_pat_fk_i.idx
@@pat_medication.pmn_prof_cancel_fk_i.idx
@@pat_medication.pmn_pk.idx
@@pat_medication.pmn_epis_fk_idx.idx
@@pat_medication.pmn_inst_fk_idx.idx
@@pat_medication_hist_list.pmhl_ieb_fk_i.idx
@@pat_medication_hist_list.pmhl_prof_fk_i.idx
@@pat_medication_hist_list.pmhl_pat_fk_i.idx
@@pat_medication_hist_list.pmhl_pk.idx
@@pat_medication_hist_list.pmhl_drug_fk_i.idx
@@pat_medication_hist_list.pmhl_imd_fk_i.idx
@@pat_medication_hist_list.pmhl_pml_fk_i.idx

@@pat_medication_hist_list.pmhl_inst_fk_i.idx
@@pat_medication_hist_list.pmhl_epis_fk_i.idx
@@pat_medication_hist_list.pmhl_ppn_fk_i.idx
@@pat_medication_hist_list.pmhl_softw_fk_i.idx
@@pat_medication_list.pml_ieb_fk_i.idx
@@pat_medication_list.pml_drug_fk_i.idx
@@pat_medication_list.pml_pat_fk_i.idx
@@pat_medication_list.pml_imd_fk_i.idx
@@pat_medication_list.pml_prof_fk_i.idx
@@pat_medication_list.pml_pk.idx
@@pat_medication_list.pml_ppn_fk_i.idx
@@pat_medication_list.pml_inst_fk_i.idx
@@pat_medication_list.pml_epis_fk_i.idx

@@pat_medication_list.pml_softw_fk_i.idx
@@pat_necessity.pny_nss_fk_i.idx
@@pat_necessity.pny_pat_fk_i.idx
@@pat_necessity.pny_pk.idx
@@pat_necessity.pny_inst_fk_idx.idx
@@pat_notes.pns_prof_cancel_fk_i.idx
@@pat_notes.pns_pat_fk_i.idx
@@pat_notes.pns_prof_writes_fk_i.idx
@@pat_notes.pns_pk.idx
@@pat_notes.pns_epis_fk_idx.idx
@@pat_notes.pns_inst_fk_idx.idx
@@pat_permission.ppn_pat_fk_i.idx
@@pat_permission.ppn_prof_fk_i.idx

@@pat_permission.ppn_pk.idx
@@pat_permission.ppn_inst_fk_idx.idx
@@pat_photo.ppo_pat_fk_i.idx
@@pat_photo.ppo_pk.idx
@@pat_pregnancy.ppy_prof_fk_i.idx
@@pat_pregnancy.ppy_pat_fk_i.idx
@@pat_pregnancy.ppy_pk.idx
@@pat_pregnancy_risk.pgr_gre_fk_i.idx
@@pat_pregnancy_risk.pgr_pat_fk_i.idx
@@pat_pregnancy_risk.pgr_prof_fk_i.idx
@@pat_pregnancy_risk.pgr_pk.idx
@@pat_pregn_fetus.ppf_ppy_fk_i.idx
@@pat_pregn_fetus.ppf_pk.idx

@@pat_pregn_fetus_biom.ppfb_ppf_fk_i.idx
@@pat_pregn_fetus_biom.ppfb_pk.idx
@@pat_pregn_fetus_biom.ppfb_prof_fk_idx.idx
@@pat_pregn_fetus_biom.ppfb_vsd_fk_idx.idx
@@pat_pregn_fetus_biom.ppfb_vsn_fk_idx.idx
@@pat_pregn_fetus_det.ppfd_ppf_fk_i.idx
@@pat_pregn_fetus_det.ppfd_pk.idx
@@pat_pregn_fetus_det.ppfd_prof_fk_idx.idx
@@pat_pregn_measure.ppme_pk.idx
@@pat_pregn_measure.ppme_ppy_fk_i.idx
@@pat_problem.ppm_diag_fk_i.idx
@@pat_problem.ppm_pat_fk_i.idx
@@pat_problem.ppm_prof_ins_fk_i.idx

@@pat_problem.ppm_pk.idx
@@pat_problem.ppm_comp_fk_idx.idx
@@pat_problem.ppm_eds_fk_idx.idx
@@pat_problem.ppm_epis_fk_idx.idx
@@pat_problem.ppm_hat_fk_idx.idx
@@pat_problem.ppm_inst_fk_idx.idx
@@pat_problem.ppm_ptnot_fk_idx.idx
@@pat_problem_hist.pph_pk.idx
@@pat_problem_hist.pph_comp_fk_idx.idx
@@pat_problem_hist.pph_epis_fk_idx.idx
@@pat_problem_hist.pph_inst_fk_idx.idx
@@pat_problem_hist.pph_ppm_fk_idx.idx
@@pat_problem_hist.pph_ptnot_fk_idx.idx

@@pat_prob_visit.ppv_ppm_fk_i.idx
@@pat_prob_visit.ppv_vis_fk_i.idx
@@pat_prob_visit.ppv_pk.idx
@@pat_sick_leave.pba_prof_fk_i.idx
@@pat_sick_leave.pba_pat_fk_i.idx
@@pat_sick_leave.pba_pk.idx
@@pat_sick_leave.pba_inst_fk_idx.idx
@@pat_soc_attributes.ptsat_pat_fk_i.idx
@@pat_soc_attributes.ptsat_sch_fk_i.idx
@@pat_soc_attributes.ptsat_ctr_address_fk_i.idx
@@pat_soc_attributes.ptsat_ctr_nation_fk_i.idx
@@pat_soc_attributes.ptsat_pk.idx
@@pat_soc_attributes.ptsat_rel_fk.idx

@@pat_soc_attributes.ptsat_i_fk_idx.idx
@@pat_soc_attributes.ptsat_inst_fk_idx.idx
@@pat_soc_attributes.ptsat_lang_fk_idx.idx
@@pat_tmp_remota.sys_c007687.idx
@@pat_vaccine.pve_pat_fk_i.idx
@@pat_vaccine.pve_inst_fk_i.idx
@@pat_vaccine.pve_vcc_fk_i.idx
@@pat_vaccine.pve_prof_fk_i.idx
@@pat_vaccine.pve_pk.idx
@@periodic_exam_educ.pee_pk.idx
@@periodic_exam_educ.pee_pee_fk_i.idx
@@periodic_exam_educ.pee_code_i.idx
@@periodic_exam_educ.pee_inst_fk_idx.idx

@@periodic_exam_educ.pee_s_fk_idx.idx
@@positioning.posi_pk.idx
@@positioning_type.ptype_pk.idx
@@postal_code_pt.pct_pt_pk.idx
@@pregnancy_risk_eval.gre_gre_fk_i.idx
@@pregnancy_risk_eval.gre_pk.idx
@@prep_message.pme_code_i.idx
@@prep_message.pme_pk.idx
@@presc_attention_det.pad_ppn_i.idx
@@presc_attention_det.pad_flg_attention_i.idx
@@presc_attention_det.pad_pk.idx
@@presc_attention_det.pad_s_fk_i.idx
@@presc_attention_det.pad_inst_fk_i.idx

@@presc_attention_det.pad_prof_fk_i.idx
@@presc_pat_problem.ppp_pk.idx
@@presc_pat_problem.ppp_pal_fk_i.idx
@@presc_pat_problem.ppp_ppm_fk_i.idx
@@presc_pat_problem.ppp_ppn_fk_i.idx
@@presc_pat_problem.ppp_prof_fk_i.idx
@@presc_pat_problem.ppp_prof_fk2_i.idx
@@prescription.prn_pk.idx
@@prescription.prn_inst_fk2_i.idx
@@prescription.prn_s_fk2_i.idx
@@prescription.prn_prof_fk2_i.idx
@@prescription.prn_s_fk_i.idx
@@prescription.prn_pat_fk_i.idx

@@prescription.prn_epis_fk_i.idx
@@prescription.prn_prof_fk_i.idx
@@prescription.prn_inst_fk_i.idx
@@prescription.prn_prof_fk3.idx
@@prescription.prn_epis_fk2_i.idx
@@prescription_number_seq.pnq_pk.idx
@@prescription_number_seq.pnq_ete_fk_i.idx
@@prescription_number_seq.pnq_cse_fk_i.idx
@@prescription_pharm.ppn_ida_fk_i.idx
@@prescription_pharm.ppn_ieb_fk_i.idx
@@prescription_pharm.prm_pk.idx
@@prescription_pharm.ppn_mad_fk_i.idx
@@prescription_pharm.ppn_ddg_fk_i.idx

@@prescription_pharm.ppn_prn_fk_i.idx
@@prescription_pharm.ppn_drug_fk_i.idx
@@prescription_pharm.ppn_iva_fk_i.idx
@@prescription_pharm_det.ppt_pk.idx
@@prescription_pharm_det.ppt_ppn_fk_i.idx
@@prescription_pharm_det.ppt_ing_fk_i.idx
@@prescription_print.ppr_prn_fk_i.idx
@@prescription_print.ppr_pxl_fk_i.idx
@@prescription_print.ppr_pk.idx
@@prescription_type.pty_code_i.idx
@@prescription_type.pty_pk.idx
@@prescription_type_access.ptya_pk.idx
@@prescription_xml.pxl_pk.idx

@@prescription_xml.pxl_xml_i.idx
@@prescription_xml_det.pdl_pk.idx
@@prof_access.pass_prof_fk_i.idx
@@prof_access.pass_dcs_fk_i.idx
@@prof_access.pass_pk.idx
@@prof_access.pass_inst_fk_idx.idx
@@prof_access.pass_sbpp_fk_idx.idx
@@prof_access.pass_s_context_fk_idx.idx
@@prof_access.pass_s_fk_idx.idx
@@prof_access.pass_ssst_fk_idx.idx
@@prof_access_field_func.paff_sfy_fk_i.idx
@@prof_access_field_func.paff_sfd_fk_i.idx
@@prof_access_field_func.paff_prof_fk_i.idx

@@prof_access_field_func.paff_pk.idx
@@prof_cat.pct_prof_fk_i.idx
@@prof_cat.pct_cat_fk_i.idx
@@prof_cat.pct_pk.idx
@@prof_cat.pct_cats_fk_i.idx
@@prof_cat.pct_inst_fk_idx.idx
@@prof_cat.pct_uk.idx
@@prof_dep_clin_serv.pcst_dcs_fk_i.idx
@@prof_dep_clin_serv.pcst_prof_fk_i.idx
@@prof_dep_clin_serv.pcst_pk.idx
@@prof_doc.pdc_dte_fk_i.idx
@@prof_doc.pdc_prof_fk_i.idx
@@prof_doc.pdc_pk.idx

@@prof_doc.pdc_inst_fk_idx.idx
@@prof_epis_interv.pei_eiv_fk_i.idx
@@prof_epis_interv.pei_pk.idx
@@prof_epis_interv.pei_cat_fk_idx.idx
@@prof_epis_interv.pei_prof_fk_idx.idx
@@professional.prof_spc_fk_i.idx
@@professional.prof_sch_fk_i.idx
@@professional.prof_ctr_fk_i.idx
@@professional.prof_pk.idx
@@prof_ext_sys.pess_prof_fk_i.idx
@@prof_ext_sys.pess_ess_fk_i.idx
@@prof_ext_sys.pess_pk.idx
@@prof_ext_sys.pess_inst_fk_idx.idx

@@prof_func.pfc_sfy_fk_i.idx
@@prof_func.pfc_prof_fk_i.idx
@@prof_func.pfc_pk.idx
@@prof_func.pfc_dcs_fk_idx.idx
@@prof_func.pfc_inst_fk_idx.idx
@@profile_templ_access.pta_pk.idx
@@profile_templ_access.pta_sbpp_fk_idx.idx
@@profile_templ_access.pta_s_context_fk_idx.idx
@@profile_templ_access.pta_s_fk_idx.idx
@@profile_templ_access.pta_spt_fk_idx.idx
@@profile_templ_access.pta_ssst_fk_idx.idx
@@profile_templ_acc_func.ptaf_sfd_fk_i.idx
@@profile_templ_acc_func.ptaf_spt_fk_i.idx

@@profile_templ_acc_func.ptaf_sfy_fk_i.idx
@@profile_templ_acc_func.ptaf_pk.idx
@@profile_template.spt_pk.idx
@@profile_template.spt_inst_fk_idx.idx
@@profile_template.spt_s_fk_idx.idx
@@profile_template.spt_spt_fk_idx.idx
@@prof_in_out.pio_prof_fk_i.idx
@@prof_in_out.pio_pk.idx
@@prof_in_out.pio_inst_fk_idx.idx
@@prof_in_out.pio_s_fk_idx.idx
@@prof_institution.prins_inst_fk_i.idx
@@prof_institution.prins_prof_fk_i.idx
@@prof_institution.prins_pk.idx

@@prof_institution.prins_uk.idx
@@prof_photo.pfpo_pk.idx
@@prof_photo.pfpo_prof_fk_i.idx
@@prof_preferences.pps_prof_fk_i.idx
@@prof_preferences.pps_lang_fk_i.idx
@@prof_preferences.pps_pk.idx
@@prof_preferences.pps_inst_fk_idx.idx
@@prof_preferences.pps_s_fk_idx.idx
@@prof_preferences.pps_uk.idx
@@prof_profile_template.pte_spt_fk_i.idx
@@prof_profile_template.pte_prof_fk_i.idx
@@prof_profile_template.pte_pk.idx
@@prof_profile_template.pte_inst_fk_idx.idx

@@prof_profile_template.pte_s_fk_idx.idx
@@prof_profile_template.pte_uk.idx
@@prof_room.spr_pk.idx
@@prof_room.spr_id_prof_fk.idx
@@prof_room.spr_cats_fk_idx.idx
@@prof_room.spr_room_fk_idx.idx
@@prof_room.spr_spt_fk_idx.idx
@@prof_soft_inst.psit_pk.idx
@@prof_soft_inst.psit_inst_fk_idx.idx
@@prof_soft_inst.psit_prof_fk_idx.idx
@@prof_soft_inst.psit_s_fk_idx.idx
@@prof_soft_inst.psit_uk.idx
@@prof_team.prof_team_inst_fk_idx.idx

@@prof_team.prof_team_prof_fk_idx.idx
@@prof_team.prof_team_s_fk_idx.idx
@@prof_team.prof_team_pk.idx
@@prof_team_det.prf_team_d_pk.idx
@@prof_team_det.prf_team_d_prof_team_fk_i.idx
@@prof_team_det.prf_team_d_cats_fk_idx.idx
@@prof_team_det.prf_team_d_prof_fk_idx.idx
@@prof_team_det.prf_team_d_prof_fk2_idx.idx
@@protoc_diag.pdig_inst_fk_idx.idx
@@protoc_diag.pdig_s_fk_idx.idx
@@protoc_diag.pdig_prt_fk_i.idx
@@protoc_diag.pdig_diag_fk_i.idx
@@protoc_diag.pdig_pk.idx

@@protocols.prt_inst_fk_idx.idx
@@protocols.prt_s_fk_idx.idx
@@protocols.prt_sipg_fk_idx.idx
@@protocols.prt_code_i.idx
@@protocols.prt_pk.idx
@@p1_doc_external.doc_ext_pk.idx
@@p1_doc_external_request.doc_req_doc_ext_fk_i.idx
@@p1_doc_external_request.doc_req_pk.idx
@@p1_documents.docs_pk.idx
@@p1_documents_done.docs_done_prof_fk_i.idx
@@p1_documents_done.docs_done_pk.idx
@@p1_external_request.ertx_dcs_fk_i.idx
@@p1_external_request.ertx_pat_fk_i.idx

@@p1_external_request.ertx_prof_fk_i.idx
@@p1_external_request.ertx_prof__fk_i.idx
@@p1_external_request.ertx_inst___fk_i.idx
@@p1_external_request.ertx_schd_fk_i.idx
@@p1_external_request.ertx_inst_fk_i.idx
@@p1_external_request.ertx_pk.idx
@@p1_ext_req_tracking.ert_ertx_fk_i.idx
@@p1_ext_req_tracking.ert_prins_fk_i.idx
@@p1_ext_req_tracking.ert_pk.idx
@@p1_history.hst_pat_fk_i.idx
@@p1_history.hst_pk.idx
@@p1_prblm_rec_procedure.prp_rec_proc_fk_i.idx
@@p1_prblm_rec_procedure.prp_prblm_fk_i.idx

@@p1_prblm_rec_procedure.prp_pk.idx
@@p1_problem.prblm_pk.idx
@@p1_problem_dep_clin_serv.pdcs_dcs_fk_i.idx
@@p1_problem_dep_clin_serv.pdcs_pk.idx
@@p1_recomended_procedure.rec_proc_pk.idx
@@recm.recm_pk.idx
@@records_review.rrw_pk.idx
@@records_review_read.rrwr_prof_fk_i.idx
@@records_review_read.rrwr_epis_fk_i.idx
@@records_review_read.rrwr_rrw_fk_i.idx
@@records_review_read.rrwr_pk.idx
@@religion.rel_pk.idx
@@rep_destination.rdn_pk.idx

@@reports.rep_pk.idx
@@reports_group.repgp_pk.idx
@@rep_prof_exception.rpnx_pk.idx
@@rep_profile_template.rpte_pk.idx
@@rep_profile_template_det.rpe_pk.idx
@@rep_prof_templ_access.rpsac_pk.idx
@@rep_prof_template.rpepr_pk.idx
@@rep_screen.sfc_pk.idx
@@rep_section.rsn_pk.idx
@@rep_section_det.rgp_pk.idx
@@result_status.rss_pk.idx
@@room.room_code_i.idx
@@room.room_dep_fk_i.idx

@@room.room_pk.idx
@@room_dep_clin_serv.rcst_room_fk_i.idx
@@room_dep_clin_serv.rcst_dcs_fk_i.idx
@@room_dep_clin_serv.rcst_pk.idx
@@room_dep_position.rdepp_room_fk.idx
@@room_dep_position.rdepp_pk.idx
@@room_ext_sys.res_pk.idx
@@room_ext_sys.res_ess_fk_idx.idx
@@room_ext_sys.res_room_fk_idx.idx
@@room_scheduled.rsd_room_fk_i.idx
@@room_scheduled.rsd_schd_fk_i.idx
@@room_scheduled.rsd_pk.idx
@@rotation_interval.ril_pk.idx

@@sample_recipient.srt_code_i.idx
@@sample_recipient.srt_pk.idx
@@sample_recipient.srt_id_code_sample_ui.idx
@@sample_text.sstt_sst_fk_i.idx
@@sample_text.sstt_pk.idx
@@sample_text.sstt_diag_fk_idx.idx
@@sample_text_freq.fst_pk.idx
@@sample_text_freq.fst_sstt_fk_idx.idx
@@sample_text_prof.stt_sst_fk_i.idx
@@sample_text_prof.stt_prof_fk_i.idx
@@sample_text_prof.stt_pk.idx
@@sample_text_prof.stt_inst_fk_idx.idx
@@sample_text_type.sst_pk.idx

@@sample_text_type.sst_s_fk_idx.idx
@@sample_text_type_cat.sttc_pk.idx
@@sample_text_type_cat.sttc_cat_fk_idx.idx
@@sample_text_type_cat.sttc_inst_fk_idx.idx
@@sample_text_type_cat.sttc_sst_fk_idx.idx
@@sample_type.ste_code_i.idx
@@sample_type.ste_pk.idx
@@scales.sce_pk.idx
@@scales_class.scsc_sce_fk_i.idx
@@scales_class.scsc_pk.idx
@@scales_doc_value.sde_sce_fk_i.idx
@@scales_doc_value.sde_pk.idx
@@sch_action.san_pk.idx

@@sch_cancel_reason.slr_pk.idx
@@sch_cancel_reason_inst.sli_pk.idx
@@sch_consult_vacancy.scv_pk.idx
@@schedule.schd_prof_requests_fk_i.idx
@@schedule.schd_inst_requested_fk_i.idx
@@schedule.schd_dcs_requests_fk_i.idx
@@schedule.schd_dcs_requested_fk_i.idx
@@schedule.schd_inst_requests_fk_i.idx
@@schedule.schd_prof_schedules_fk_i.idx
@@schedule.schd_pk.idx
@@schedule.schd_dt_begin_i.idx
@@schedule.schd_dt_dcs_requested.idx
@@schedule_alter.sar_schd_fk_i.idx

@@schedule_alter.sar_inst_fk_i.idx
@@schedule_alter.sar_prof_requests_fk_i.idx
@@schedule_alter.sar_prof_requested_fk_i.idx
@@schedule_alter.sar_dcs_fk_i.idx
@@schedule_alter.sar_pk.idx
@@schedule_outp.sop_pk.idx
@@schedule_outp.sop_flg_sched.idx
@@schedule_outp.sop_flg_state_i.idx
@@schedule_outp.sop_schd_fk_i.idx
@@schedule_sr.sched_sr_id_schedule.idx
@@schedule_sr.sched_sr_can_rea_fk_i.idx
@@schedule_sr.sr_sched_pk.idx
@@schedule_sr.sr_sched_dtarget_i.idx

@@schedule_sr.sr_sched_prof_reg.idx
@@schedule_sr.sched_sr_dep_fk_idx.idx
@@schedule_sr.sched_sr_diag_fk_idx.idx
@@schedule_sr.sched_sr_prof_fk_idx.idx
@@schedule_sr.sr_sched_epis_fk_idx.idx
@@schedule_sr.sr_sched_inst_fk_idx.idx
@@schedule_sr.sr_sched_pat_fk_idx.idx
@@schedule_sr_det.ssrtd_prof_fk_idx.idx
@@schedule_sr_det.ssrtd_sr_sched_fk_idx.idx
@@schedule_sr_det.ssrtd_pk.idx
@@sch_event.sct_pk.idx
@@sch_event_dcs.sec_pk.idx
@@sch_event_inst.sch_event_inst_pk.idx

@@sch_group.sgp_pk.idx
@@sch_group.sgp_patient_i.idx
@@sch_log.slg_pk.idx
@@scholarship.sch_code_i.idx
@@scholarship.sch_pk.idx
@@school.scl_sch_fk_i.idx
@@school.scl_pat_fk_i.idx
@@school.scl_pk.idx
@@sch_permission.scn_prof_flg.idx
@@sch_permission.scn_pk.idx
@@sch_permission.scn_prof_prof_dcs_event.idx
@@sch_prof_outp.spo_pk.idx
@@sch_prof_outp.spo_schd_fk_i.idx

@@sch_prof_outp.spo_prof_fk_i.idx
@@sch_resource.sre_pk.idx
@@sch_resource.sre_id_prof.idx
@@sch_schedule_request.ssr_pk.idx
@@sch_service.sse_pk.idx
@@sch_service_dcs.ssc_pk.idx
@@screen_template.step_pk.idx
@@serv_sched_access.ssa_inst_accesses_fk_i.idx
@@serv_sched_access.ssa_dcs_accessed_fk_i.idx
@@serv_sched_access.ssa_inst_accessed_fk_i.idx
@@serv_sched_access.ssa_dcs_accesses_fk_i.idx
@@serv_sched_access.ssa_pk.idx
@@slot.slt_room_fk_i.idx

@@slot.slt_dcs_availto_fk_i.idx
@@slot.slt_matr_fk_i.idx
@@slot.slt_prof_writes_fk_i.idx
@@slot.slt_dcs_avail_fk_i.idx
@@slot.slt_prof_avail_fk_i.idx
@@slot.slt_pk.idx
@@snomed_concepts.sc_pk.idx
@@snomed_descriptions.sd_pk.idx
@@snomed_descriptions.i_concept.idx
@@snomed_relationships.sr_pk.idx
@@snomed_relationships.i_concept1.idx
@@snomed_relationships.i_concept2.idx
@@social_class.scs_pk.idx

@@social_diagnosis.sds_pk.idx
@@social_diagnosis.sds_sds_fk_i.idx
@@social_epis_diag.esd_pk.idx
@@social_epis_diag.esd_see_fk_i.idx
@@social_epis_diag.esd_sds_fk_i.idx
@@social_epis_diag.esd_prof_cancel_fk_idx.idx
@@social_epis_diag.esd_prof_fk_idx.idx
@@social_epis_discharge.sed_pk.idx
@@social_epis_discharge.sed_see_fk_i.idx
@@social_epis_discharge.sed_drd_fk_idx.idx
@@social_epis_discharge.sed_prof_cancel_fk_idx.idx
@@social_epis_discharge.sed_prof_fk_idx.idx
@@social_epis_discharge.sed_trp_fk_idx.idx

@@social_epis_interv.esi_pk.idx
@@social_epis_interv.esi_see_fk_i.idx
@@social_epis_interv.esi_sin_fk_i.idx
@@social_epis_interv.esi_prof_cancel_fk_idx.idx
@@social_epis_interv.esi_prof_fk_idx.idx
@@social_episode.see_pk.idx
@@social_episode.see_epis_fk_idx.idx
@@social_episode.see_prof_fk_idx.idx
@@social_epis_request.sert_pk.idx
@@social_epis_request.sert_see_fk_i.idx
@@social_epis_request.sert_prof_fk_idx.idx
@@social_epis_situation.sesi_pk.idx
@@social_epis_situation.sesi_see_fk_i.idx

@@social_epis_solution.seso_pk.idx
@@social_epis_solution.seso_see_fk_i.idx
@@social_epis_solution.seso_prof_fk_idx.idx
@@social_intervention.sin_pk.idx
@@soft_inst_impl.sii_impl_fk_i.idx
@@soft_inst_impl.sii_dcs_fk_i.idx
@@soft_inst_impl.sii_si_fk_i.idx
@@soft_inst_impl.sii_pk.idx
@@soft_inst_services.sis_sii_fk_i.idx
@@soft_inst_services.sis_pk.idx
@@soft_lang.slng_pk.idx
@@soft_lang.slng_lae_fk_idx.idx
@@soft_lang.slng_sft_fk_idx.idx

@@software.s_pk.idx
@@software_dept.sdt_pk.idx
@@software_dept.sdt_s_fk_i.idx
@@software_dept.sdt_dpt_fk_i.idx
@@software_institution.si_pk.idx
@@software_institution.si_inst_fk_i.idx
@@software_institution.si_s_fk_i.idx
@@speciality.spc_code_i.idx
@@speciality.spc_pk.idx
@@spec_sys_appar.ssar_spc_fk_i.idx
@@spec_sys_appar.ssar_sai_fk_i.idx
@@spec_sys_appar.ssar_pk.idx
@@sr_base_diag.sbgd_pk.idx

@@sr_base_diag.sbg_diag_fk_idx.idx
@@sr_base_diag.sbg_epis_fk_idx.idx
@@sr_base_diag.sbg_prof_fk_idx.idx
@@sr_cancel_reason.sr_can_rea_pk.idx
@@sr_chklist.sr_cklist_ssd_fk_idx.idx
@@sr_chklist.sr_cklist_sr_cklist_fk_i.idx
@@sr_chklist.sr_cklist_pk.idx
@@sr_chklist_det.sr_cklst_d_sr_cklist_fk_i.idx
@@sr_chklist_det.sr_cklst_d_pk.idx
@@sr_chklist_det.sr_cklst_d_epis_fk_idx.idx
@@sr_chklist_det.sr_cklst_d_prof_fk_idx.idx
@@sr_chklist_det.sr_cklst_d_prof_fk2_idx.idx
@@sr_chklist_manual.sclm_pk.idx

@@sr_chklist_manual.scl_epis_fk_idx.idx
@@sr_chklist_manual.scl_prof_fk_idx.idx
@@sr_epis_interv.sev_pk.idx
@@sr_epis_interv.sev_interv_epis_uk.idx
@@sr_epis_interv.sev_prof_fk_idx.idx
@@sr_epis_interv.sev_prof_fk2_idx.idx
@@sr_epis_interv.sev_sin_fk_idx.idx
@@sr_epis_interv.sev_sr_can_rea_fk_idx.idx
@@sr_epis_interv_desc.sr_int_des_pk.idx
@@sr_epis_interv_desc.sr_int_des_epis_fk_idx.idx
@@sr_epis_interv_desc.sr_int_des_prof_can_fk_idx.idx
@@sr_epis_interv_desc.sr_int_des_prof_fk_idx.idx
@@sr_epis_interv_desc.sr_int_des_sin_fk_idx.idx

@@sr_equip.sep_pk.idx
@@sr_equip.sep_sep_fk_idx.idx
@@sr_equip_kit.setk_prof_fk_idx.idx
@@sr_equip_kit.setk_sep_fk_idx.idx
@@sr_equip_kit.setk_pk.idx
@@sr_equip_kit.setk_sep_fk2_idx.idx
@@sr_equip_kit.setk_spc_fk_idx.idx
@@sr_equip_period.sqpd_pk.idx
@@sr_equip_period.sqpd_sep_fk_idx.idx
@@sr_equip_period.sqpd_ssd_fk_idx.idx
@@sr_eval_det.sed_spev_fk_idx.idx
@@sr_eval_det.sevd_pk.idx
@@sr_eval_det.sevd_prof_fk_idx.idx

@@sr_eval_det.sevd_sen_fk_idx.idx
@@sr_eval_notes.seen_pk.idx
@@sr_eval_notes.seen_prof_fk_idx.idx
@@sr_eval_notes.seen_spev_fk_idx.idx
@@sr_eval_rule.sr_ev_rl_pk.idx
@@sr_eval_rule.sr_ev_rl_docarea_fk_idx.idx
@@sr_eval_rule.sr_ev_rl_docec_fk_idx.idx
@@sr_eval_summ.sevm_pk.idx
@@sr_eval_type.seet_docarea_fk_idx.idx
@@sr_eval_type.seet_inst_fk_idx.idx
@@sr_eval_type.seet_s_fk_idx.idx
@@sr_eval_type.seet_ssd_fk_idx.idx
@@sr_eval_type.seet_pk.idx

@@sr_evaluation.sen_pk.idx
@@sr_evaluation.sen_inst_fk_idx.idx
@@sr_evaluation.sen_s_fk_idx.idx
@@sr_eval_visit.spvs_pk.idx
@@sr_eval_visit.spev_seet_fk_idx.idx
@@sr_eval_visit.spvs_epis_fk_idx.idx
@@sr_eval_visit.spvs_prof_fk_idx.idx
@@sr_eval_visit.spvs_prof_fk2_idx.idx
@@sr_interv_dep_clin_serv.siv_dcs_fk_idx.idx
@@sr_interv_dep_clin_serv.siv_inst_fk_idx.idx
@@sr_interv_dep_clin_serv.siv_prof_fk_idx.idx
@@sr_interv_dep_clin_serv.siv_s_fk_idx.idx
@@sr_interv_dep_clin_serv.siv_sin_fk_idx.idx

@@sr_interv_desc.sr_itv_des_pk.idx
@@sr_interv_desc.sr_itv_des_inst_fk_idx.idx
@@sr_interv_desc.sr_itv_des_lang_fk_idx.idx
@@sr_interv_desc.sr_itv_des_s_fk_idx.idx
@@sr_interv_desc.sr_itv_des_sin_fk_idx.idx
@@sr_intervention.sint_pk.idx
@@sr_intervention.sin_sin_fk_idx.idx
@@sr_intervention.sin_spc_fk_idx.idx
@@sr_intervention.sin_sys_org_fk_idx.idx
@@sr_interv_group.sipg_pk.idx
@@sr_interv_group_det.sitgd_sin_fk_idx.idx
@@sr_interv_group_det.sitgd_sipg_fk_idx.idx
@@sr_nurse_rec.snc_pk.idx

@@sr_nurse_rec.snc_epis_fk_idx.idx
@@sr_nurse_rec.snc_prof_fk_idx.idx
@@sr_pat_status.spu_pk.idx
@@sr_pat_status.spu_epis_fk_idx.idx
@@sr_pat_status.spu_prof_fk_idx.idx
@@sr_pat_status_notes.spsn_pk.idx
@@sr_pat_status_notes.spsn_epis_fk_idx.idx
@@sr_pat_status_notes.spsn_prof_fk_idx.idx
@@sr_pat_status_period.sr_sts_per_pk.idx
@@sr_pat_status_period.sr_sts_per_ssd_fk_idx.idx
@@sr_pos_eval_det.sposed_prof_fk_idx.idx
@@sr_pos_eval_det.sposed_pk.idx
@@sr_pos_eval_det.sposed_sposev_fk_idx.idx

@@sr_pos_eval_visit.sposev_pk.idx
@@sr_pos_eval_visit.sposev_epis_fk_idx.idx
@@sr_pos_eval_visit.sposev_prof_fk_idx.idx
@@sr_pos_eval_visit.sposev_prof_fk2_idx.idx
@@sr_posit.sr_pos_inst_fk_idx.idx
@@sr_posit.sr_pos_pk.idx
@@sr_posit_req.spq_prof_fk_idx.idx
@@sr_posit_req.spq_prof_fk2_idx.idx
@@sr_posit_req.spq_prof_fk3_idx.idx
@@sr_posit_req.spq_prof_fk4_idx.idx
@@sr_posit_req.spq_sr_pos_fk_idx.idx
@@sr_posit_req.spq_epis_fk_idx.idx
@@sr_posit_req.spq_pk.idx

@@sr_pre_anest.spta_pk.idx
@@sr_pre_anest.spta_inst_fk_idx.idx
@@sr_pre_anest.spta_s_fk_idx.idx
@@sr_pre_anest.spta_spt_fk_idx.idx
@@sr_pre_anest_det.spand_pk.idx
@@sr_pre_anest_det.spand_epis_fk_idx.idx
@@sr_pre_anest_det.spand_prof_fk_idx.idx
@@sr_pre_anest_det.spand_spt_fk_idx.idx
@@sr_pre_eval.spe_pk.idx
@@sr_pre_eval.spe_inst_soft_i.idx
@@sr_pre_eval_det.sped_pk.idx
@@sr_pre_eval_det.sped_epis_visit_ui.idx
@@sr_pre_eval_visit.spev_pk.idx

@@sr_prof_recov_schd.sr_prsch_prof_fk_idx.idx
@@sr_prof_recov_schd.sr_prsch_pk.idx
@@sr_prof_recov_schd.sr_prsch_room_fk_idx.idx
@@sr_prof_shift.spsht_pk.idx
@@sr_prof_shift.spsht_inst_fk_idx.idx
@@sr_prof_shift.spsht_s_fk_idx.idx
@@sr_prof_team_det.sr_pf_team_cats_fk_idx.idx
@@sr_prof_team_det.sr_pf_team_pk.idx
@@sr_prof_team_det.sr_pf_team_epis_fk_idx.idx
@@sr_prof_team_det.sr_pf_team_prof_fk_idx.idx
@@sr_prof_team_det.sr_pf_team_prof_fk2_idx.idx
@@sr_prof_team_det.sr_pf_team_prof_fk3_idx.idx
@@sr_prof_team_det.sr_pf_team_prof_fk4_idx.idx

@@sr_prof_team_det.sr_pf_team_prof_team_fk_idx.idx
@@sr_receive.sr_recv_pk.idx
@@sr_receive.sr_recv_epis_fk_idx.idx
@@sr_receive.sr_recv_prof_fk_idx.idx
@@sr_receive_manual.srl_pk.idx
@@sr_receive_manual.srl_epis_fk_idx.idx
@@sr_receive_manual.srl_prof_fk_idx.idx
@@sr_receive_proc.sr_rec_pro_pk.idx
@@sr_receive_proc_det.sr_rcv_det_sr_rec_pro_fk_i.idx
@@sr_receive_proc_det.sr_rcv_det_pk.idx
@@sr_receive_proc_det.sr_rcv_det_epis_fk_idx.idx
@@sr_receive_proc_det.sr_rcv_det_prof_fk_idx.idx
@@sr_receive_proc_notes.sr_rcv_not_pk.idx

@@sr_receive_proc_notes.sr_rcv_not_epis_fk_idx.idx
@@sr_receive_proc_notes.sr_rcv_not_prof_fk_idx.idx
@@sr_reserv_req.srq_sep_pk.idx
@@sr_reserv_req.srq_epis_fk_idx.idx
@@sr_reserv_req.srq_prof_fk_idx.idx
@@sr_reserv_req.srq_prof_fk2_idx.idx
@@sr_reserv_req.srq_prof_fk3_idx.idx
@@sr_reserv_req.srq_prt_fk_idx.idx
@@sr_reserv_req.srq_sep_fk_idx.idx
@@sr_reserv_req.srq_sin_fk_idx.idx
@@sr_reserv_req.srq_ssd_fk_idx.idx
@@sr_room_status.sru_pk.idx
@@sr_room_status.sru_epis_fk_idx.idx

@@sr_room_status.sru_prof_fk_idx.idx
@@sr_room_status.sru_room_fk_idx.idx
@@sr_surgery_rec_det.sstd_pk.idx
@@sr_surgery_rec_det.sst_prof_fk_idx.idx
@@sr_surgery_rec_det.sst_sr_rec_fk_idx.idx
@@sr_surgery_record.sr_rec_cse_fk_idx.idx
@@sr_surgery_record.sr_rec_inst_fk_idx.idx
@@sr_surgery_record.sr_rec_pat_fk_idx.idx
@@sr_surgery_record.sr_rec_prof_fk_idx.idx
@@sr_surgery_record.sr_rec_prof_team_fk_idx.idx
@@sr_surgery_record.sr_rec_sin_fk_idx.idx
@@sr_surgery_record.sr_rec_id_schedule.idx
@@sr_surgery_record.sr_rec_anest_type_fk_i.idx

@@sr_surgery_record.sr_rec_pk.idx
@@sr_surgery_time.sr_times_pk.idx
@@sr_surgery_time.sr_times_inst_fk_idx.idx
@@sr_surgery_time.sr_times_s_fk_idx.idx
@@sr_surgery_time_det.sr_tim_det_pk.idx
@@sr_surgery_time_det.sr_tim_det_epis_fk_idx.idx
@@sr_surgery_time_det.sr_tim_det_prof_fk_idx.idx
@@sr_surgery_time_det.sr_tim_det_prof_fk2_idx.idx
@@sr_surgery_time_det.sr_tim_det_sr_times_fk_idx.idx
@@sr_surg_period.ssd_pk.idx
@@sr_surg_prot_det.sr_sp_det_sr_sp_task_fk_i.idx
@@sr_surg_prot_det.sr_sp_det_pk.idx
@@sr_surg_protocol.sr_prot_pk.idx

@@sr_surg_prot_task.sr_sp_task_sr_su_task_fk_i.idx
@@sr_surg_prot_task.sr_sp_task_sr_prot_fk_i.idx
@@sr_surg_prot_task.sr_sp_task_pk.idx
@@sr_surg_prot_task_det.sr_spt_det_sr_sp_task_fk_i.idx
@@sr_surg_prot_task_det.sr_spt_det_pk.idx
@@sr_surg_task.sr_su_task_pk.idx
@@sys_alert.sa_pk.idx
@@sys_alert.sa_sys_alt_tp_fk_idx.idx
@@sys_alert_det.sad_id_alert_flg_new_i.idx
@@sys_alert_det.sad_prof_alert_i.idx
@@sys_alert_det.at_alert_det_pk.idx
@@sys_alert_det.at_ide_fk_idx.idx
@@sys_alert_det.at_ii_fk_idx.idx

@@sys_alert_det.at_is_fk_idx.idx
@@sys_alert_prof.sap_sa_fk_i.idx
@@sys_alert_prof.sap_prof_fk_i.idx
@@sys_alert_prof.sap_inst_fk_i.idx
@@sys_alert_prof.sap_pk.idx
@@sys_alert_prof.sap_prof_template.idx
@@sys_alert_prof.sap_s_fk_idx.idx
@@sys_alert_profile.sapr_spt_fk_i.idx
@@sys_alert_profile.sapr_sa_fk_i.idx
@@sys_alert_profile.sapr_pk.idx
@@sys_alert_profile.sapr_inst_fk_idx.idx
@@sys_alert_software.sys_alt_sw_pk.idx
@@sys_alert_software.sys_alt_ssst_fk_idx.idx

@@sys_alert_software.sys_alt_sw_inst_fk_idx.idx
@@sys_alert_software.sys_alt_sw_sa_fk_idx.idx
@@sys_alert_software.sys_alt_sw_sw_fk_idx.idx
@@sys_alert_type.sys_alt_tp_pk.idx
@@sys_appar_organ.sys_aporg_sai_fk_i.idx
@@sys_appar_organ.sys_aporg_sys_org_fk_i.idx
@@sys_appar_organ.sys_aporg_pk.idx
@@sys_application_area.aaa_pk.idx
@@sys_application_type.sat_pk.idx
@@sys_btn_crit.sbt_pk.idx
@@sys_btn_crit.sbt_btn_fk_idx.idx
@@sys_btn_crit.sbt_crt_fk_idx.idx
@@sys_btn_sbg.sbs_sbg_fk_i.idx

@@sys_btn_sbg.sbs_btn_fk_i.idx
@@sys_btn_sbg.sbs_pk.idx
@@sys_btn_sbg.sbs_aaa_fk_i.idx
@@sys_btn_sbg.sbs_saa_fk_i.idx
@@sys_btn_sbg.sbs_btn_parent_fk_i.idx
@@sys_button.btn_pk.idx
@@sys_button_group.sbg_stb_fk_i.idx
@@sys_button_group.sbg_pk.idx
@@sys_button_prop.sbpp_pk.idx
@@sys_button_prop.sbpp_aaa_fk_idx.idx
@@sys_button_prop.sbpp_btn_fk_idx.idx
@@sys_button_prop.sbpp_saa_fk_idx.idx
@@sys_button_prop.sbpp_sat_fk_idx.idx

@@sys_button_prop.sbpp_sbpp_fk_idx.idx
@@sys_config.pk_sys_config.idx
@@sys_config.sc_id_config_i.idx
@@sys_config.sc_instsw_ui.idx
@@sys_config.scg_inst_fk_idx.idx
@@sys_config.scg_s_fk_idx.idx
@@sys_domain.sdn_lang_fk_i.idx
@@sys_domain.sdn_pk.idx
@@sys_element.syse_dim_fk_i.idx
@@sys_element.syse_sysd_fk_i.idx
@@sys_element.syse_elem_fk_i.idx
@@sys_element.syse_pk.idx
@@sys_element_crit.syec_syse_fk_i.idx

@@sys_element_crit.syec_pk.idx
@@sys_element_crit.syec_elemc_fk_i.idx
@@sys_entrance.pk_sys_entrance.idx
@@sys_error.ser_srqt_fk_i.idx
@@sys_error.ser_pk.idx
@@sys_field.sfd_pk.idx
@@sys_functionality.sfy_pk.idx
@@sys_functionality.sfy_s_fk_idx.idx
@@sys_login.pk_sys_login.idx
@@sys_message.sme_lang_fk_i.idx
@@sys_message.sme_pk.idx
@@sys_message.sme_langsw_ui.idx
@@sys_message.sme_inst_fk_idx.idx

@@sys_message.sme_s_fk_idx.idx
@@sys_request.srqt_ssn_fk_i.idx
@@sys_request.srqt_pk.idx
@@sys_request.srqt_dt_day.idx
@@sys_screen_area.saa_pk.idx
@@sys_screen_template.sste_pk.idx
@@sys_session.ssn_prof_fk_i.idx
@@sys_session.ssn_pk.idx
@@sys_shortcut.ssst_pk.idx
@@sys_shortcut.ssst_uk.idx
@@sys_shortcut.ssst_sbpp_fk_idx.idx
@@sys_shortcut.ssst_s_fk_idx.idx
@@sys_shortcut.ssst_ssst_fk_idx.idx

@@system_apparati.sai_pk.idx
@@system_organ.sys_org_pk.idx
@@sys_time_event_group.tgm_code_i.idx
@@sys_time_event_group.tgm_pk.idx
@@sys_toolbar.stb_pk.idx
@@tests_review.trw_prof_fk_i.idx
@@tests_review.trw_pk.idx
@@time_unit.tut_code_i.idx
@@time_unit.tut_pk.idx
@@toad_plan_sql.tpsql_idx.idx
@@toad_plan_table.tptbl_idx.idx
@@translation.trl_lang_fk_i.idx
@@translation.trl_pk.idx

@@translation.trl_lang_codetrans_i.idx
@@transp_ent_inst.tei_pk.idx
@@transp_ent_inst.tei_inst_fk_idx.idx
@@transp_ent_inst.tei_trp_fk_idx.idx
@@transp_entity.trp_pk.idx
@@transp_entity.trp_inst_fk_idx.idx
@@transportation.etp_trp_fk_i.idx
@@transportation.etp_trq_fk_i.idx
@@transportation.etp_prof_fk_i.idx
@@transportation.etp_epis_fk_i.idx
@@transportation.etp_pk.idx
@@transport_type.tte_pk.idx
@@transp_req.trq_inst_dest_fk_i.idx

@@transp_req.trq_prof_fk_i.idx
@@transp_req.trq_pat_fk_i.idx
@@transp_req.trq_inst_req_fk_i.idx
@@transp_req.trq_trg_fk_i.idx
@@transp_req.trq_tte_fk_i.idx
@@transp_req.trq_pk.idx
@@transp_req.trq_crq_fk_i.idx
@@transp_req.trq_ereq_fk_i.idx
@@transp_req.trq_art_fk_i.idx
@@transp_req_group.trg_tte_fk_i.idx
@@transp_req_group.trg_trp_fk_i.idx
@@transp_req_group.trg_pk.idx
@@treatment_management.tman_prof_fk_i.idx

@@treatment_management.tman_pk.idx
@@triage.tri_pk.idx
@@triage.tri_tdisc_fk_i.idx
@@triage.tri_tcol_fk_i.idx
@@triage.tri_typ_fk_i.idx
@@triage.tri_tbrd_fk_i.idx
@@triage_board.tbrd_pk.idx
@@triage_board_group.tbgp_typ_fk_i.idx
@@triage_board_group.tbgp_pk.idx
@@triage_board_grouping.tbgg_pk.idx
@@triage_color.tcol_pk.idx
@@triage_color.tcol_typ_fk_i.idx
@@triage_considerations.tc_pk.idx

@@triage_disc_help.tdhp_pk.idx
@@triage_discriminator.trdisc_pk.idx
@@triage_discriminator_help.tdihp_pk.idx
@@triage_n_consid.tnc_pk.idx
@@triage_nurse.tnsr_typ_fk_i.idx
@@triage_nurse.tnsr_pk.idx
@@triage_nurse.tnsr_tcol_fk_i.idx
@@triage_type.typ_tunits_fk_i.idx
@@triage_type.typ_pk.idx
@@triage_units.tunits_pk.idx
@@triage_white_reason.twrn_pk.idx
@@unit_mea_soft_inst.umsi_pk.idx
@@unit_mea_soft_inst.umsi_unitm_fk_i.idx

@@unit_mea_soft_inst.umsi_inst_fk_i.idx
@@unit_mea_soft_inst.umsi_s_fk_i.idx
@@unit_measure.unitm_umtype_fk_i.idx
@@unit_measure.unitm_pk.idx
@@unit_measure_type.umtype_pk.idx
@@vaccine.vcc_code_i.idx
@@vaccine.vcc_pk.idx
@@vaccine_dep_clin_serv.vdcs_pk.idx
@@vaccine_dep_clin_serv.vdcs_dcs_fk_idx.idx
@@vaccine_dep_clin_serv.vdcs_inst_fk_idx.idx
@@vaccine_dep_clin_serv.vdcs_prof_fk_idx.idx
@@vaccine_dep_clin_serv.vdcs_s_fk_idx.idx
@@vaccine_dep_clin_serv.vdcs_vcc_fk_idx.idx

@@vaccine_presc_det.vpc_prof_fk_i.idx
@@vaccine_presc_det.vpc_vpn_fk_i.idx
@@vaccine_presc_det.vpc_vcc_fk_i.idx
@@vaccine_presc_det.vpc_pk.idx
@@vaccine_presc_plan.vpp_prof_fk_i.idx
@@vaccine_presc_plan.vpp_vpc_fk_i.idx
@@vaccine_presc_plan.vpp_schd_fk_i.idx
@@vaccine_presc_plan.vpp_pk.idx
@@vaccine_prescription.vpn_epis_fk_i.idx
@@vaccine_prescription.vpn_prof_fk_i.idx
@@vaccine_prescription.vpn_pk.idx
@@vaccine_prescription.vpn_epis_dest_fk_idx.idx
@@vaccine_prescription.vpn_epis_origin_fk_idx.idx

@@vaccine_prescription.vpn_inst_fk_idx.idx
@@vaccine_prescription.vpn_prof_cancel_fk_idx.idx
@@vbz$object_stats.vbz$object_stats.idx
@@viewer.vir_pk.idx
@@viewer_refresh.vrh_pk.idx
@@viewer_refresh.vrh_vir_fk_idx.idx
@@viewer_synch_param.vsm_pk.idx
@@viewer_synch_param.vsm_vse_fk_idx.idx
@@viewer_synchronize.vse_pk.idx
@@viewer_synchronize.vse_btn_fk_idx.idx
@@viewer_synchronize.vse_inst_fk_idx.idx
@@viewer_synchronize.vse_pt_fk_idx.idx
@@viewer_synchronize.vse_s_fk_idx.idx

@@viewer_synchronize.vse_vir_fk_idx.idx
@@visit.vis_inst_fk_i.idx
@@visit.vis_pat_fk_i.idx
@@visit.vis_org_fk_i.idx
@@visit.vis_extc_fk_i.idx
@@visit.vis_pk.idx
@@vital_sign.vsn_code_i.idx
@@vital_sign.vsn_inter_name_i.idx
@@vital_sign.vsn_pk.idx
@@vital_sign_desc.vsd_svs_fk_i.idx
@@vital_sign_desc.vsd_code_i.idx
@@vital_sign_desc.vsd_pk.idx
@@vital_sign_notes.vsnotes_pk.idx

@@vital_sign_notes.vsnotes_prof_fk_i.idx
@@vital_sign_read.vsr_svs_fk_i.idx
@@vital_sign_read.vsr_prof_cancel_fk_i.idx
@@vital_sign_read.vsr_vsd_fk_i.idx
@@vital_sign_read.vsr_prof_read_fk_i.idx
@@vital_sign_read.vsr_epis_fk_i.idx
@@vital_sign_read.vsr_pk.idx
@@vital_sign_read.vsr_pat_fk_i.idx
@@vital_sign_read.vsr_inst_fk_idx.idx
@@vital_sign_read.vsr_inst_fk2_idx.idx
@@vital_sign_read.vsr_mvsp_fk_idx.idx
@@vital_sign_read.vsr_s_fk_idx.idx
@@vital_sign_read.vsr_s_fk2_idx.idx

@@vital_sign_relation.vsrn_vsn_detail_fk_i.idx
@@vital_sign_relation.vsrn_disc_fk_i.idx
@@vital_sign_relation.vsrn_vsn_parent_fk_i.idx
@@vital_sign_relation.vsrn_pk.idx
@@vital_sign_unit_measure.vsum_unitm_fk_i.idx
@@vital_sign_unit_measure.vsum_inst_fk_i.idx
@@vital_sign_unit_measure.vsum_s_fk_i.idx
@@vital_sign_unit_measure.vsum_vsn_fk_i.idx
@@vital_sign_unit_measure.vsum_pk.idx
@@vs_clin_serv.vcs_pk.idx
@@vs_clin_serv.vcs_dcs_fk_idx.idx
@@vs_clin_serv.vcs_svs_fk_idx.idx
@@vs_soft_inst.vssi_vsn_fk_i.idx

@@vs_soft_inst.vssi_inst_fk_i.idx
@@vs_soft_inst.vssi_unitm_fk_i.idx
@@vs_soft_inst.vssi_s_fk_i.idx
@@vs_soft_inst.vssi_pk.idx
@@white_reason.wrn_pk.idx
@@wl_call_queue.wcq_prof_fk_i.idx
@@wl_call_queue.wcq_wwl_fk_i.idx
@@wl_call_queue.wcq_wme_dest_fk_i.idx
@@wl_call_queue.wcq_wme_fk_i.idx
@@wl_call_queue.wcq_pk.idx
@@wl_machine.wme_room_fk_i.idx
@@wl_machine.wme_pk.idx
@@wl_mach_prof_queue.wmpq_wme_fk_i.idx

@@wl_mach_prof_queue.wmpq_wqe_fk_i.idx
@@wl_mach_prof_queue.wmpq_prof_fk_i.idx
@@wl_mach_prof_queue.wmpq_pk.idx
@@wl_msg_queue.wmq_pk.idx
@@wl_msg_queue.wmq_wme_fk_i.idx
@@wl_msg_queue.wmq_wqe_fk_i.idx
@@wl_prof_room.wpr_prof_fk_i.idx
@@wl_prof_room.wpr_room_fk_i.idx
@@wl_prof_room.wpr_pk.idx
@@wl_queue.wqe_pk.idx
@@wl_queue.wqe_dpt_fk_idx.idx
@@wl_status.wss_pk.idx
@@wl_waiting_line.wwl_pat_fk_i.idx

@@wl_waiting_line.wwl_wss_fk_i.idx
@@wl_waiting_line.wwl_cse_fk_i.idx
@@wl_waiting_line.wwl_prof_fk_i.idx
@@wl_waiting_line.wwl_wqe_fk_i.idx
@@wl_waiting_line.wwl_room_fk_i.idx
@@wl_waiting_line.wwl_pk.idx
@@wl_waiting_line.wwl_wwl_fk_i.idx
@@wl_waiting_line.wwl_epis_fk_idx.idx
@@wl_waiting_room.wwr_room_wait_fk_i.idx
@@wl_waiting_room.wwr_room_cons_fk_i.idx
@@wl_waiting_room.wwr_pk.idx
@@wound_charac.wcc_wcc_fk_i.idx
@@wound_charac.wcc_pk.idx

@@wound_eval_charac.wec_wcc_fk_i.idx
@@wound_eval_charac.wec_wen_fk_i.idx
@@wound_eval_charac.wec_pk.idx
@@wound_evaluation.wen_pk.idx
@@wound_evaluation.wen_nard_fk_idx.idx
@@wound_evaluation.wen_prof_fk_idx.idx
@@wound_treat.wtt_wen_fk_i.idx
@@wound_treat.wtt_pk.idx
@@wound_treat.wtt_prof_cancel_fk_idx.idx
@@wound_treat.wtt_prof_exec_fk_idx.idx
@@wound_treat.wtt_epis_fk_i.idx
@@wound_type.wte_wte_fk_i.idx
@@wound_type.wte_pk.idx

@@dr$d_idx$i.dr$d_idx$x.idx
@@dr$snomed_idx$i.dr$snomed_idx$x.idx
@@bp_clin_serv.bcs_pk.idx
@@complaint.cmplt_pk.idx
@@p1_problem_dep_clin_serv.pdcs_prblm_fk_i.idx
@@schedule_sr.sched_sr_spc_fk_idx.idx
@@social_epis_situation.sesi_prof_fk_idx.idx
