-- CHANGED BY: Ana Rita Martins 
-- CHANGE DATE: 11/05/2011
-- CHANGE REASON: ALERT-178273
grant select on ALERT.V_ANALYSIS_REQUEST to ALERT_ADTCOD;
grant select on ALERT.V_ANALYSIS_REQUEST_DETAIL to ALERT_ADTCOD;
grant select on ALERT.V_ANALYSIS_RESULT to ALERT_ADTCOD;
grant select on ALERT.V_ANALYSIS_HARVEST to ALERT_ADTCOD;
grant select on ALERT.V_EPIS_DIAGNOSIS to ALERT_ADTCOD;
grant select on ALERT.V_EPIS_SUPPLIES_DET to ALERT_ADTCOD;
grant select on ALERT.V_DIAGNOSIS_TRANSLATE_US to ALERT_ADTCOD;
grant select on ALERT.V_DIAGNOSIS_TRANSLATE_UK  to ALERT_ADTCOD;
grant select on ALERT.V_SUPPLY_WORKFLOW to ALERT_ADTCOD;
grant select on ALERT.V_EXAM_REQUEST to ALERT_ADTCOD;
grant select on ALERT.V_EXAM_REQUEST_DETAIL to ALERT_ADTCOD;
grant select on ALERT.V_EXAM_RESULT to ALERT_ADTCOD;
grant select on ALERT.V_HARVEST to ALERT_ADTCOD;
grant select on ALERT.V_DRUG_PRESCRIPTION to ALERT_ADTCOD;
grant select on ALERT.V_DRUG_PRESCRIPTION_DETAIL to ALERT_ADTCOD;
grant select on ALERT.V_INTERV_PRESCRIPTION to ALERT_ADTCOD;
grant select on ALERT.V_INTERV_PRESCRIPTION_DETAIL to ALERT_ADTCOD;
grant select on ALERT.V_INTERV_PRESCRIPTION_PLAN to ALERT_ADTCOD;
grant select on ALERT.V_DISCHARGE to ALERT_ADTCOD;
grant select on ALERT.V_PAT_HISTORY_DIAGNOSIS to ALERT_ADTCOD;
grant select on ALERT.V_PHYSICIAN_INSTITUTION_NL to ALERT_ADTCOD;
-- CHANGED END: Ana Rita Martins 