-- CHANGED BY: Luís Maia
-- CHANGE DATE: 31/07/2009 10:05
-- CHANGE REASON: [ALERT-38622] Added database model related with table BMNG_REASON
GRANT SELECT ON BMNG_REASON TO ALERT_VIEWER;
-- CHANGE END: Luís Maia