-- CHANGED BY: Luís Maia
-- CHANGE DATE: 31/07/2009 09:13
-- CHANGE REASON: [ALERT-38601] Added database model related with new table BMNG_ALLOCATION_BED
GRANT SELECT ON BMNG_ALLOCATION_BED TO ALERT_VIEWER;
-- CHANGE END: Luís Maia