-- CHANGED BY: Luís Maia
-- CHANGE DATE: 31/07/2009 10:57
-- CHANGE REASON: [ALERT-38623] Added database model associated with table BMNG_ACTION
GRANT SELECT ON BMNG_ACTION TO ALERT_VIEWER;
-- CHANGE END: Luís Maia