-- CHANGED BY: Luís Maia
-- CHANGE DATE: 31/07/2009 09:07
-- CHANGE REASON: [ALERT-38601] Added database model related with new table BMNG_REASON_TYPE
GRANT SELECT ON BMNG_REASON_TYPE TO ALERT_VIEWER;
-- CHANGE END: Luís Maia