-- ADDED BY: Jose Castro
-- ADDED DATE: 25/05/2010
-- ADDED REASON: ALERT-14487
grant select on ALERT.BODY_STRUCTURE_DCS to ALERT_VIEWER;
-- ADDED END



-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.BODY_STRUCTURE_DCS to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
