-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant INSERT on ALERT.BUILDING to ALERT_APEX_TOOLS;
grant SELECT on ALERT.BUILDING to ALERT_APEX_TOOLS;
grant UPDATE on ALERT.BUILDING to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso