-- CHANGED BY:  Rui Gomes
-- CHANGE DATE: 10/04/2011 18:30
-- CHANGE REASON: [ALERT-172042] 
grant references on CANCEL_REA_AREA to ALERT_DEFAULT;
-- CHANGE END:  Rui Gomes

-- CHANGED BY:  Telmo
-- CHANGE DATE: 04-05-2011
-- CHANGE REASON: APS-1581
grant select on CANCEL_REA_AREA to ALERT_APSSCHDLR_TR;
-- CHANGE END:  Telmo


-- CHANGED BY:  Rui Gomes
-- CHANGE DATE: 27/01/2012 17:16
-- CHANGE REASON: [ALERT-216286] 
grant references on CANCEL_REA_AREA to ALERT_DEFAULT;
-- CHANGE END:  Rui Gomes


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant INSERT on ALERT.CANCEL_REA_AREA to ALERT_APEX_TOOLS;
grant SELECT on ALERT.CANCEL_REA_AREA to ALERT_APEX_TOOLS;
grant UPDATE on ALERT.CANCEL_REA_AREA to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
