-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.CDR_INST_PAR_ACTION to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.CDR_INST_PAR_ACTION to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 17/05/2021
-- CHANGED REASON: EMR-44887
GRANT SELECT, INSERT, UPDATE ON cdr_inst_par_action TO alert_core_cnt WITH GRANT OPTION;
-- CHANGE END: Humberto Cardoso
