-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.CDR_PARAMETER to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.CDR_PARAMETER to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso

-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 17/05/2021
-- CHANGED REASON: EMR-44887
GRANT SELECT ON cdr_parameter TO alert_core_cnt WITH GRANT OPTION;
-- CHANGE END: Humberto Cardoso
