-- CHANGED BY: Ariel Machado
-- CHANGE DATE: 24/06/2010 15:29
-- CHANGE REASON: [ALERT-70633] Checklists: Back Office & Front Office (DDL)
GRANT SELECT ON CHECKLIST_VERSION TO ALERT_VIEWER;
-- CHANGE END: Ariel Machado


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.CHECKLIST_VERSION to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
