-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.CLIN_SERV_ALERT_DIAGNOSIS to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2018-07-12
-- CHANGED REASON: EMR-4688
GRANT SELECT, INSERT, UPDATE, DELETE ON clin_serv_alert_diagnosis TO alert_core_func WITH GRANT OPTION;
-- CHANGE END: Humberto Cardoso
