-- CHANGED BY: Susana Silva
-- CHANGE DATE: 04/03/2010 17:13
-- CHANGE REASON: [ALERT-79365] 
grant select on CODIFICATION to ALERT_DEFAULT;
-- CHANGE END: Susana Silva

-- CHANGED BY: Kátia Marques
-- CHANGE DATE: 26/08/2014
-- CHANGE REASON: APS-437 (http://alertjira/browse/APS-1979)
GRANT select on CODIFICATION to ALERT_APSSCHDLR_TR;
-- CHANGE END


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.CODIFICATION to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
