-- CHANGED BY: Sérgio Santos
-- CHANGE DATE: 03/07/2010 20:12
-- CHANGE REASON: [ALERT-109286] 
GRANT SELECT ON combination_spec TO alert_viewer;
GRANT ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE ON combination_spec TO inter_alert_v2;
-- CHANGE END: Sérgio Santos