-- CHANGED BY: Sérgio Santos
-- CHANGE DATE: 15/09/2010 11:54
-- CHANGE REASON: [ALERT-124887] 
GRANT SELECT ON consult_req TO inter_alert_v2;
-- CHANGE END: Sérgio Santos

-- CHANGED BY: Ruben Araujo
-- CHANGE DATE: 24/05/2016 
-- CHANGE REASON: [ALERT-320400] 
GRANT SELECT  ON ALERT.CONSULT_REQ to ALERT_PRODUCT_TR ;
-- CHANGE END: Ruben Araujo
