
PROMPT CREATING GRANTS ON ALERT

PROMPT CREATING TABLE GRANTS

GRANT SELECT ON ANALYSIS_ABN_PRINT TO INTER_ALERT_V2;
--Ricardo Bento 2008/11/28
GRANT SELECT ON mi_pharm_group TO INTER_ALERT_V2;

--Antonio Vieira: 24/11/2008
GRANT SELECT ON OTHER_PRODUCT TO INTER_ALERT_V2;
GRANT SELECT ON FORM_FARM_UNIT TO INTER_ALERT_V2;
--End
GRANT SELECT ON SUPPLIES TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_SUPPLIES TO INTER_ALERT_V2;
GRANT SELECT ON MI_MED TO INTER_ALERT_V2;
GRANT SELECT ON PAT_HEALTH_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON TRANSLATION TO INTER_ALERT_V2;
GRANT SELECT ON HEALTH_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_REQ TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_REQ_DET TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_REQ_SUPPLY TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_PRESC_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_PRESC_PLAN_STOCK TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_TRIAGE TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_SUPPLIES_DET TO INTER_ALERT_V2;
-- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON ANALYSIS_REQ_DET TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS TO INTER_ALERT_V2;
GRANT SELECT ON PROFESSIONAL TO INTER_ALERT_V2;
GRANT SELECT ON PATIENT TO INTER_ALERT_V2;
-- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON EPISODE TO INTER_ALERT_V2; 
GRANT SELECT ON HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_TYPE TO INTER_ALERT_V2;
GRANT SELECT ON SAMPLE_TYPE TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_REQ TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_GROUP TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_REQ_PAR TO INTER_ALERT_V2;
 -- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON ROOM TO INTER_ALERT_V2;
GRANT SELECT ON PROTOCOLS TO INTER_ALERT_V2;
GRANT SELECT ON CATEGORY TO INTER_ALERT_V2;
GRANT SELECT ON LANGUAGE TO INTER_ALERT_V2;
 -- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON ANALYSIS_RESULT_PAR TO INTER_ALERT_V2;
 -- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON ANALYSIS_RESULT TO INTER_ALERT_V2;
 -- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON EXAM_REQ_DET TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_PRESC_DET TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_PRESCRIPTION TO INTER_ALERT_V2;
GRANT SELECT ON PRESCRIPTION TO INTER_ALERT_V2;
GRANT SELECT ON DIAGNOSIS TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_DIAGNOSIS TO INTER_ALERT_V2;
GRANT SELECT ON MCDT_REQ_DIAGNOSIS TO INTER_ALERT_V2;
GRANT SELECT ON DISCHARGE TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_READMISSION TO INTER_ALERT_V2;
--[PP] 23/3/2009
GRANT SELECT, UPDATE ON EPIS_INFO TO INTER_ALERT_V2;
GRANT SELECT ON INTERVENTION TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_PRESCRIPTION TO INTER_ALERT_V2;
GRANT SELECT ON VITAL_SIGN_READ TO INTER_ALERT_V2;
GRANT SELECT ON VITAL_SIGN TO INTER_ALERT_V2;
GRANT SELECT, UPDATE ON EXAM_REQ TO INTER_ALERT_V2;
GRANT SELECT ON EXAM TO INTER_ALERT_V2;
GRANT SELECT ON DISCHARGE_DETAIL TO INTER_ALERT_V2;
GRANT SELECT ON PROF_INSTITUTION TO INTER_ALERT_V2;
GRANT SELECT ON DISCH_REAS_DEST TO INTER_ALERT_V2;
--GRANT SELECT ON EPIS_TASK TO INTER_ALERT_V2; not present in 2.6
GRANT SELECT ON EXAM_DEP_CLIN_SERV TO INTER_ALERT_V2;
GRANT SELECT ON PROF_CAT TO INTER_ALERT_V2;
GRANT SELECT ON PROF_PREFERENCES TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_PROF_RESP TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_PRESC_DET TO INTER_ALERT_V2;
GRANT SELECT ON SCH_GROUP TO INTER_ALERT_V2;
GRANT SELECT ON SCHEDULE TO INTER_ALERT_V2;
GRANT SELECT ON CLIN_RECORD TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT SELECT,UPDATE,INSERT ON EPIS_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON ALLERGY TO INTER_ALERT_V2;
GRANT SELECT ON ALLERGY_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON PAT_ALLERGY TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_PRESC_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON DEP_CLIN_SERV TO INTER_ALERT_V2;
GRANT SELECT ON INSTITUTION_LANGUAGE TO INTER_ALERT_V2;
GRANT SELECT ON INSTITUTION TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT INSERT ON WL_PATIENT_SONHO TO INTER_ALERT_V2;
GRANT UPDATE ON VISIT TO INTER_ALERT_V2;

 -- A rever, consultar ficheiro de excel
GRANT SELECT ON WL_PATIENT_SONHO TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE_COLOR TO INTER_ALERT_V2;
GRANT SELECT ON BED TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_ANAMNESIS TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE_BOARD TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE_DISCRIMINATOR TO INTER_ALERT_V2;
GRANT SELECT ON UNIT_MEA_SOFT_INST TO INTER_ALERT_V2;
GRANT SELECT ON UNIT_MEASURE TO INTER_ALERT_V2;
GRANT SELECT ON VITAL_SIGN_RELATION TO INTER_ALERT_V2;
GRANT SELECT ON SPECIALITY TO INTER_ALERT_V2;
GRANT SELECT ON VS_SOFT_INST TO INTER_ALERT_V2;
GRANT SELECT ON VITAL_SIGN_DESC TO INTER_ALERT_V2;
GRANT SELECT ON DEPARTMENT TO INTER_ALERT_V2;
GRANT SELECT ON EXAM_ROOM TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_LOINC TO INTER_ALERT_V2;
GRANT SELECT ON MOVEMENT TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
-- AM Passou ALERT_ADT
--GRANT SELECT,INSERT,UPDATE ON PAT_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON COUNTRY TO INTER_ALERT_V2;
GRANT SELECT ON PAT_SOC_ATTRIBUTES TO INTER_ALERT_V2;
--PASSOU ALERT_ADT
--GRANT SELECT ON SEQ_PAT_EXT_SYS TO INTER_ALERT_V2;
--GRANT SELECT ON PAT_NECESSITY TO INTER_ALERT_V2;
GRANT SELECT ON DOC_EXTERNAL TO INTER_ALERT_V2;
GRANT SELECT ON SYS_CONFIG TO INTER_ALERT_V2;
GRANT SELECT ON MI_ROUTE TO INTER_ALERT_V2;
GRANT SELECT ON DRUG TO INTER_ALERT_V2;
GRANT SELECT ON FLUIDS_PRESC_DET TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_COMPOSITION TO INTER_ALERT_V2;
GRANT SELECT ON PROF_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON PROF_DEP_CLIN_SERV TO INTER_ALERT_V2;
GRANT SELECT ON SCH_RESOURCE TO INTER_ALERT_V2;
GRANT SELECT ON SEQ_EPIS_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_ROOM TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE_WHITE_REASON TO INTER_ALERT_V2;
GRANT SELECT ON SAMPLE_RECIPIENT TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_INSTIT_SOFT TO INTER_ALERT_V2;
GRANT SELECT ON EXAM_CAT TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_QUESTION_RESPONSE TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_QUESTIONNAIRE TO INTER_ALERT_V2;
GRANT SELECT ON THERAPEUTIC_PROTOCOLS TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_THERAPEUTIC_PROTOCOLS to INTER_ALERT_V2;
GRANT SELECT ON prof_preferences TO INTER_ALERT_V2;
-- A rever, consultar Hugo Vieira
GRANT SELECT,INSERT,UPDATE ON EXTERNAL_DOC TO INTER_ALERT_V2;
--#S[AV]
GRANT SELECT ON sys_alert_event TO INTER_ALERT_V2;
GRANT SELECT ON FAST_TRACK TO INTER_ALERT_V2;
GRANT SELECT ON FAST_TRACK_INSTITUTION TO INTER_ALERT_V2;
--#E[AV]
-- [RF 31-03-2009]
GRANT SELECT ON exam_result TO INTER_ALERT_V2;

--[AV 06-04-2009]
GRANT SELECT ON PRESCRIPTION_INSTR_HIST TO INTER_ALERT_V2;

--#S[HS 13-04-2009]
GRANT SELECT ON IRREGULAR_DIRECTIONS_DCS_REL TO INTER_ALERT_V2;
GRANT SELECT ON IRREGULAR_DIRECTIONS_TIME TO INTER_ALERT_V2;
GRANT SELECT ON IRREGULAR_INTERVAL TO INTER_ALERT_V2;
GRANT SELECT ON IRREGULAR_FREQUENCY TO INTER_ALERT_V2;
GRANT SELECT ON IRREGULAR_DIRECTIONS TO INTER_ALERT_V2;
--#E[HS 13-04-2009]

--#S [RF] 14-04-2009
GRANT SELECT ON DISCHARGE_DEST TO INTER_ALERT_V2;
GRANT SELECT ON DISCHARGE_REASON TO INTER_ALERT_V2;
GRANT SELECT ON SOFTWARE TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_DEP_CLIN_SERV TO INTER_ALERT_V2;
GRANT SELECT ON CLINICAL_SERVICE TO INTER_ALERT_V2;
--#E [RF] 14-04-2009

--[PP] 23-03-2009 INTERALERTD-192
GRANT UPDATE ON SCH_GROUP TO INTER_ALERT_V2;
--[RB] 2009-04-29
--GRANT select ON ALERT.SCH_CONSULT_VAC_MFR TO INTERFACE_SONHO_V2; Moved to the end of this file
-- #S [RF] 19-05-2009    
GRANT SELECT ON epis_report TO INTER_ALERT_V2;
GRANT SELECT ON rep_section TO INTER_ALERT_V2;
GRANT SELECT ON rep_section_det TO INTER_ALERT_V2;
GRANT SELECT ON epis_report_section TO INTER_ALERT_V2;
GRANT SELECT ON epis_type_soft_inst TO INTER_ALERT_V2;
-- #E [RF] 19-05-2009
--RB 20100907
GRANT SELECT ON REF_MAP TO INTER_ALERT_V2;

PROMPT CREATING SEQUENCES GRANTS
GRANT SELECT ON SEQ_ANALYSIS_REQ_DET TO INTER_ALERT_V2;
GRANT SELECT ON SEQ_EPISODE TO INTER_ALERT_V2;
GRANT SELECT ON SEQ_VISIT TO INTER_ALERT_V2;
--AM passou ALERT_ADT
--GRANT SELECT ON SEQ_EXTERNAL_SYS TO INTER_ALERT_V2;
GRANT SELECT ON SEQ_EXAM_REQ_DET TO INTER_ALERT_V2;
--passou ALERT_ADT
--GRANT SELECT ON SEQ_PATIENT TO INTER_ALERT_V2;
-- A rever, consultar Hugo Vieira
GRANT SELECT ON SEQ_EXTERNAL_DOC TO INTER_ALERT_V2;
--[SM07-07-2009]
GRANT SELECT ON SCHEDULE_SR TO INTER_ALERT_V2; 
GRANT SELECT ON order_set_process_task_det TO INTER_ALERT_V2; 
GRANT SELECT ON order_set_process_task TO INTER_ALERT_V2; 
GRANT SELECT ON order_set_process TO INTER_ALERT_V2; 
--[PP 28-11-2009]
GRANT SELECT ON epis_recomend TO INTER_ALERT_V2;
GRANT SELECT ON notes_config TO INTER_ALERT_V2; 
GRANT SELECT ON opinion TO INTER_ALERT_V2; 
GRANT SELECT ON opinion_prof TO INTER_ALERT_V2; 

--[AV] 23-12-2010 ALERT-116266
GRANT SELECT ON ALERT.RESPONSE TO INTER_ALERT_V2;



PROMPT CREATING TYPES GRANTS
GRANT EXECUTE ON TABLE_NUMBER TO INTER_ALERT_V2;
--GRANT EXECUTE ON TABLE_VARCHAR TO INTER_ALERT_V2;  
GRANT EXECUTE ON TABLE_TABLE_NUMBER TO INTER_ALERT_V2;
--GRANT EXECUTE ON TABLE_TABLE_VARCHAR TO INTER_ALERT_V2;
GRANT EXECUTE ON PROFISSIONAL TO INTER_ALERT_V2;
GRANT EXECUTE ON TABLE_DATE TO INTER_ALERT_V2;

PROMPT CREATING PACKAGES GRANTS
GRANT EXECUTE ON PK_API_ANALYSIS TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_EXAM TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_ANALYSIS TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel

GRANT EXECUTE ON PK_API_DIAGNOSIS TO INTER_ALERT_V2;
-- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_EPISODE TO INTER_ALERT_V2; 
 -- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_SCHEDULE TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_VISIT TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_WAITINGLINESONHO TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
-- Removed in 2.6 GRANT EXECUTE ON PK_PFH_INTERFACE TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_UNIT_MEASURE TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_VITAL_SIGN TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_INP_EPISODE TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_MOVEMENT TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_SR_VISIT TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_VISIT TO INTER_ALERT_V2;
 -- A rever, consultar ficeiro de excel
GRANT EXECUTE ON PK_SCHEDULE_INTERFACE TO INTER_ALERT_V2;
-- A rever, consultar ficeiro de excel
GRANT EXECUTE ON PK_PRESCRIPTION TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_INTERV TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_DRUG TO INTER_ALERT_V2;
-- Rafael Fontes 15-01-2009
GRANT EXECUTE ON pk_api_alerts TO INTER_ALERT_V2;
-- PP 09-02-2009
GRANT EXECUTE ON pk_api_backoffice to INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_SUMMARY_PAGE TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_INPATIENT TO INTER_ALERT_V2;
--[AV] 17-03-2009

GRANT EXECUTE ON pk_alert_constant TO INTER_ALERT_V2;
 -- [AM 01-06-2009]
GRANT EXECUTE ON t_error_out TO INTER_ALERT_V2; 
grant execute on table_index_varchar to inter_alert_v2;
grant execute on index_varchar to inter_alert_v2;
--[PP 28-11-2009]
grant execute on pk_sysdomain to inter_alert_v2;
--[TS 03-12-2009]
GRANT EXECUTE ON pk_ref_inter_circle TO INTER_ALERT_V2;
--[PP 18-12-2009]
grant execute on pk_list to inter_alert_v2;
--[AV  12-05-2010]
grant execute on pk_api_edis to inter_alert_v2;
grant execute on pk_api_vacc to inter_alert_v2;
grant execute on pk_patient to inter_alert_v2;
grant execute on pk_api_dictation to inter_alert_v2;
--AV 20101223
grant execute on alert.t_health_plan to inter_alert_v2;


-- [RF] 22-07-2009
-- VIEWS
GRANT SELECT ON V_EPISODE TO INTER_ALERT_V2;
GRANT SELECT ON V_HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON V_ANALYSIS_HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON V_ANALYSIS_REQUEST TO INTER_ALERT_V2;
GRANT SELECT ON V_ANALYSIS_REQUEST_DETAIL TO INTER_ALERT_V2;
GRANT SELECT ON V_PROFESSIONAL TO INTER_ALERT_V2;
GRANT SELECT ON V_PROF_INSTITUTION TO INTER_ALERT_V2;
GRANT SELECT ON V_EPIS_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON v_pat_inst_attribute TO INTER_ALERT_V2;
GRANT SELECT ON v_pat_ext_sys TO INTER_ALERT_V2;
GRANT SELECT ON v_vital_sign_read TO INTER_ALERT_V2;
GRANT SELECT ON v_interv_prescription TO INTER_ALERT_V2;
GRANT SELECT ON v_interv_prescription_plan to INTER_ALERT_V2;
GRANT SELECT ON V_INTERV_PRESCRIPTION_DETAIL  TO INTER_ALERT_V2;
GRANT SELECT ON v_drug_prescription_plan TO INTER_ALERT_V2;
GRANT SELECT ON V_DRUG_PRESCRIPTION_DETAIL TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_supplies_det TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_anamnesis TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_diagnosis TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_readmission TO INTER_ALERT_V2;
GRANT SELECT ON v_discharge TO INTER_ALERT_V2;
GRANT SELECT ON v_discharge_detail TO INTER_ALERT_V2;
GRANT SELECT ON V_EPIS_PROF_RESP TO INTER_ALERT_V2;
GRANT SELECT ON V_PROF_CATEGORY TO INTER_ALERT_V2;
GRANT SELECT ON V_DRUG_PRESCRIPTION TO INTER_ALERT_V2;
GRANT SELECT ON V_DRUG_PRESCRIPTION_DETAIL TO INTER_ALERT_V2;
GRANT SELECT ON V_DRUG_PRESCRIPTION_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_type_soft_inst TO INTER_ALERT_V2;
GRANT SELECT ON v_episode_triage TO INTER_ALERT_V2;
GRANT SELECT ON v_pat_health_plan TO INTER_ALERT_V2;
GRANT SELECT ON v_exam_request TO INTER_ALERT_V2;
GRANT SELECT ON v_analysis_loinc TO INTER_ALERT_V2;
GRANT SELECT ON v_schedule TO INTER_ALERT_V2;
GRANT SELECT ON v_movement TO INTER_ALERT_V2;
GRANT SELECT ON v_exam_request_detail TO INTER_ALERT_V2;
--[AV] 16-02-2011
GRANT SELECT ON alert.v_physician_institution_nl TO INTER_ALERT_V2;
GRANT SELECT ON alert.v_outp_appointments_nl TO INTER_ALERT_V2;

--AM 20090819
GRANT SELECT ON alert.pat_history_diagnosis TO INTER_ALERT_V2;
--SM 20090820
GRANT SELECT ON alert.INSTITUTION_GROUP TO INTER_ALERT_V2;
--[AV] 10-09-2009
GRANT SELECT ON alert.analysis_parameter to INTER_ALERT_V2;

--AM 20090915
GRANT execute ON alert.pk_medication_workflow TO INTER_ALERT_V2;
GRANT select ON alert.DRUG_REQ_SUPPLY_dev TO INTER_ALERT_V2;

--PP 20090928
GRANT SELECT ON EPIS_DIET_REQ TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_DIET TO INTER_ALERT_V2;
GRANT SELECT ON DIET_TYPE TO INTER_ALERT_V2;
GRANT SELECT ON DIET_SCHEDULE_TIME TO INTER_ALERT_V2;
GRANT SELECT ON DIET_SCHEDULE TO INTER_ALERT_V2;
GRANT SELECT ON DIET_INSTIT_SOFT TO INTER_ALERT_V2;
GRANT SELECT ON DIET_PROF_INSTIT TO INTER_ALERT_V2;
GRANT SELECT ON DIET_PROF_PREF TO INTER_ALERT_V2;
--[AV]14-10-2009
GRANT SELECT ON EPIS_DIET_DET TO INTER_ALERT_V2; 


--AV 20091008
GRANT EXECUTE ON T_TBL_COMPONENT_STRUCT TO INTER_ALERT_V2; 

--AM 20091010
GRANT SELECT ON alert.sr_pat_status TO INTER_ALERT_V2;
--TS 20091102
GRANT SELECT ON EPIS_RECOMEND TO INTER_ALERT_V2;


--AV 20091029
Grant select on alert.discharge_notes to inter_alert_v2;

--PD 20091221
GRANT SELECT ON DIET TO INTER_ALERT_V2;
GRANT SELECT ON schedule_outp to INTER_ALERT_V2;
GRANT SELECT ON SCH_PROF_OUTP to INTER_ALERT_V2;

--AP/BR 20100122
GRANT SELECT ON supply_workflow TO INTER_ALERT_V2;
GRANT SELECT ON supply TO INTER_ALERT_V2;
GRANT SELECT ON supply_location TO INTER_ALERT_V2;
GRANT SELECT ON supply_reason TO INTER_ALERT_V2;
GRANT SELECT ON supply_request TO INTER_ALERT_V2;

--AM 20100127
grant select on epis_diagnosis_notes to inter_alert_v2;

--AV 20100204
GRANT SELECT ON COMPLAINT TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_COMPLAINT TO INTER_ALERT_V2;

--AP/BR 20100210
GRANT EXECUTE ON PK_API_SUPPLIES TO INTER_ALERT_V2;

--AV 20100225
GRANT SELECT ON EPIS_MULTI_PROF_RESP TO INTER_ALERT_V2;

--PP 20101322 - INTERALERTD-740
GRANT SELECT ON EPIS_DOCUMENTATION TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_DOCUMENTATION_DET TO INTER_ALERT_V2;
GRANT SELECT ON DOC_ELEMENT_CRIT TO INTER_ALERT_V2;
GRANT SELECT ON DOCUMENTATION TO INTER_ALERT_V2;
GRANT SELECT ON DOC_TEMPLATE TO INTER_ALERT_V2;
GRANT SELECT ON DOC_AREA TO INTER_ALERT_V2;
GRANT SELECT ON DOC_COMPONENT TO INTER_ALERT_V2;
GRANT SELECT ON DOC_ELEMENT TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_DOC_TEMPLATE TO INTER_ALERT_V2;

--AP/BR 20100210
GRANT select ON sr_epis_interv TO INTER_ALERT_V2;
GRANT select ON sr_intervention TO INTER_ALERT_V2;
GRANT select ON sr_prof_team_det TO INTER_ALERT_V2;
GRANT select ON alert.v_consult_req to INTER_ALERT_V2;

--AM 20100824
GRANT select ON alert.questionnaire to INTER_ALERT_V2;
GRANT select ON alert.room_questionnaire to INTER_ALERT_V2;

--PP 20100810 INTERALERTD-881
GRANT SELECT ON PRESCRIPTION_PHARM TO INTER_ALERT_V2;
GRANT SELECT ON schedule_exam TO INTER_ALERT_V2;
GRANT select ON sch_consult_vacancy TO inter_alert_v2;

GRANT SELECT ON alert.transfer_institution TO INTER_ALERT_V2;

--AP/BR 20101117
GRANT SELECT ON CPOE_PROCESS TO INTER_ALERT_V2;

--AV 20110223
GRANT SELECT ON alert.progress_notes TO INTER_ALERT_V2;
GRANT SELECT ON alert.analysis_instit_recipient TO INTER_ALERT_V2;

--AV 20110311
GRANT SELECT ON alert.exam_question_response TO INTER_ALERT_V2;

--AP/BR 20110317
GRANT SELECT ON alert.wl_queue TO INTER_ALERT_V2;
GRANT SELECT ON alert.wl_machine TO INTER_ALERT_V2;
GRANT SELECT ON alert.prof_room TO INTER_ALERT_V2;
grant EXECUTE on alert.pk_api_wl to inter_alert_v2;

GRANT SELECT ON alert.sch_api_map_ids TO inter_alert_v2;

--AM 20110528
GRANT EXECUTE ON alert.pk_medication_api TO inter_alert_v2;
GRANT SELECT ON alert.seq_drug_presc_det TO inter_alert_v2;
GRANT SELECT ON alert.seq_drug_presc_plan TO inter_alert_v2;
grant select on alert.presc_dir_frequency to inter_alert_v2;
grant select on alert.presc_frequency to inter_alert_v2;
grant select on alert.presc_frequency_time to inter_alert_v2;
grant select on alert.presc_freq_det to inter_alert_v2;
grant select on alert.drug_dep_clin_serv to inter_alert_v2;

-- AM 20110915
grant EXECUTE on t_table_presc_interop to inter_alert_v2;


--AV 2011-07-06 Changed to avoid stops during upgrades / instalations
--All grants for users different from INTER_ALERT_V2 must be enclosed in PLSQL code like the one below 
DECLARE
    CURSOR check_user_sonho_v2 IS
        SELECT username
          FROM all_users
         WHERE username = 'INTERFACE_SONHO_V2';
BEGIN
    FOR t_user IN check_user_sonho_v2
    LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON ALERT.SCH_CONSULT_VAC_MFR TO INTERFACE_SONHO_V2';
    END LOOP;
END;
/

-- RL/BR 20110915
GRANT EXECUTE ON ALERT.TS_EPISODE TO INTER_ALERT_V2;
GRANT EXECUTE ON ALERT.TS_EPIS_INFO TO INTER_ALERT_V2;
GRANT EXECUTE ON ALERT.T_DATA_GOV_MNT TO INTER_ALERT_V2;

-- AM 20120130
GRANT EXECUTE ON ALERT.table_timestamp_tstz TO INTER_ALERT_V2;

GRANT EXECUTE ON ALERT.pk_api_pfh_in TO INTER_ALERT_V2;
--AV 2012-07-25
GRANT EXECUTE ON ALERT.PK_PHARMACY TO INTER_ALERT_V2;

GRANT SELECT ON alert.professional TO INTER_ALERT_V2;

GRANT SELECT ON alert.INSTITUTION TO INTER_ALERT_V2;
GRANT SELECT ON alert.v_analysis_sample_type TO INTER_ALERT_V2;
grant select on alert.ANALYSIS_SAMPLE_TYPE_MIG to inter_alert_v2;

-- AV 2013-03-07
grant execute on alert.pk_movement to INTER_ALERT_V2;
grant execute on alert.pk_tools to INTER_ALERT_V2;
grant execute on alert.pk_barcode to INTER_ALERT_V2;
grant select on alert.nurse_discharge to INTER_ALERT_V2;
grant update on alert.discharge to inter_alert_v2;
grant update on alert.analysis_harvest to inter_alert_v2;

--LF 2017/11/2017/11/2017
--Grants for ACT

GRANT SELECT, INSERT, UPDATE, DELETE ON DIET_SCHEDULE_TIME to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON DASH_DOC_AREA_INST to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON DASH_DOC_AREA_MKT to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON HCN_DOCAREA_DEPT to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAST_HISTORY_MODE to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXAM_COMPLAINT to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXAM_EGP to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXAM_GROUP to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ICNP_DEFAULT_INSTRUCTIONS_MSI to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ICNP_TASK_COMP_SOFT_INST to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTERV_CATEGORY to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTERV_DCS_MOST_FREQ_EXCEPT to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTERV_QUESTIONNAIRE to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON NCH_ESTIMATED_INST to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ANALYSIS_BODY_STRUCTURE to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ANALYSIS_RES_CALCULATOR to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ANALYSIS_RES_PAR_CALC to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON ANALYSIS_SPECIMEN_CONDITION to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON LAB_TESTS_COMPLAINT to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON NECESSITY_DEPT_INST_SOFT to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROTOCOL_ITEM_SOFT_INST to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROTOC_DIAG to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON REF_COMPLETION_CFG to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON REF_SPEC_INSTITUTION to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTERV_PLAN to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTERV_PLAN_DEP_CLIN_SERV to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON TASK_GOAL to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON TASK_GOAL_TASK to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEFAULT_TEMPLATE_CFG to ALERT_APEX_TOOLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEPT_TEMPLATE to ALERT_APEX_TOOLS;