-- CHANGED BY: Pedro Carneiro
-- CHANGE DATE: 31/10/2011 11:19
-- CHANGE REASON: [ALERT-202541] select granted
grant select on diagnosis to alert_default;
-- CHANGE END: Pedro Carneiro

-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 17/05/2012 15:56
-- CHANGE REASON: [ALERT-230526] Grants
GRANT SELECT ON ALERT.DIAGNOSIS TO ADW_STG_PFH WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ADW_STG_P1 WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_ADTCOD WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_ADTCOD_CFG WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_APSSCHDLR_MT WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_CODING_MT WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_CODING_TR WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_CONFIG WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_DEFAULT WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_RESET WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_SUPPORT WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO ALERT_VIEWER WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO DSV WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS TO INTER_ALERT_V2 WITH GRANT OPTION;
-- CHANGE END: Alexandre Santos

--
grant select on alert.DIAGNOSIS to alert_inter;
