-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 17/05/2012 15:56
-- CHANGE REASON: [ALERT-230526] Grants
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ADW_STG_PFH WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ADW_STG_P1 WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_ADTCOD WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_ADTCOD_CFG WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_APSSCHDLR_MT WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_CODING_MT WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_CODING_TR WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_CONFIG WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_DEFAULT WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_RESET WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_SUPPORT WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO ALERT_VIEWER WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO DSV WITH GRANT OPTION;
GRANT SELECT ON ALERT.DIAGNOSIS_DEP_CLIN_SERV TO INTER_ALERT_V2 WITH GRANT OPTION;
-- CHANGE END: Alexandre Santos


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.DIAGNOSIS_DEP_CLIN_SERV to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
