-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2018-07-12
-- CHANGED REASON: EMR-4688
GRANT SELECT, INSERT, UPDATE, DELETE ON diagnosis_ea TO alert_core_func WITH GRANT OPTION;
-- CHANGE END: Humberto Cardoso



-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2019-04-17
-- CHANGED REASON: EMR-14740
GRANT SELECT, INSERT, UPDATE, DELETE ON diagnosis_ea TO alert_core_cnt WITH GRANT OPTION;
-- CHANGE END: Humberto Cardoso
