-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.DISCHARGE_REASON to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso

-- CHANGED BY: André Silva
-- CHANGE DATE: 06/04/2017
-- CHANGE REASON: ALERT-330044
GRANT SELECT ON discharge_reason TO alert_inter;
-- CHANGE END: André Silva