-- CHANGED BY: Sérgio Cunha
-- CHANGE DATE: 11/09/2009 19:56
-- CHANGE REASON: [ALERT-42984] 
  GRANT SELECT ON ALERT.DRUG_PRESC_PLAN_STOCK TO ALERT_VIEWER;
-- CHANGE END: Sérgio Cunha


-- CHANGED BY: Pedro Teixeira
-- CHANGE DATE: 13/11/2014
-- CHANGE REASON: ALERT-301713
GRANT SELECT ON ALERT.DRUG_PRESC_PLAN_STOCK TO ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Teixeira
