-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 03/07/2010 22:34
-- CHANGE REASON: [ALERT-109290] Fluid Balance - Reformulation
GRANT SELECT ON ALERT.EPIS_HIDRICS_DET_CHARACT TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos