-- CHANGED BY: José Brito
-- CHANGE DATE: 24/01/2010 19:51
-- CHANGE REASON: [ALERT-70160] Triage refactoring
GRANT SELECT ON ALERT.EPIS_TRIAGE_PAT_NECESSITY TO ALERT_VIEWER;
-- CHANGE END: José Brito