-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 03/07/2010 22:36
-- CHANGE REASON: [ALERT-109290] Fluid Balance - Reformulation
GRANT SELECT ON ALERT.EPIS_HCOLL_HIST TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos