-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 04/05/2012 16:36
-- CHANGE REASON: [ALERT-229222] VERSIONING TRANSACTIONAL MODEL - SCHEMA ALERT - DDL
GRANT SELECT ON ALERT.EPIS_DSTAG_PFACT_HIST TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos