GRANT SELECT ON ALERT.epis_mtos_score TO ALERT_VIEWER;




-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 15/11/2017 10:19
-- CHANGE REASON: [CINTERA-117] 
GRANT SELECT ON EPIS_MTOS_SCORE TO ALERT_INTER;
-- CHANGE END: Pedro Henriques

