-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 04/05/2012 16:35
-- CHANGE REASON: [ALERT-229222] VERSIONING TRANSACTIONAL MODEL - SCHEMA ALERT - DDL
GRANT SELECT ON ALERT.EPIS_DIAG_NOTES_HIST TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos