-- ADDED BY: Jose Castro
-- ADDED DATE: 25/05/2010
-- ADDED REASON: ALERT-14487
grant select on ALERT.EXAM_BODY_STRUCTURE to ALERT_VIEWER;
-- ADDED END



-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.EXAM_BODY_STRUCTURE to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso



-- CHANGED BY: Ana Moita
-- CHANGED DATE: 2018-7-23
-- CHANGED REASON: CEMR-1835

-- CHANGED BY: Howard Cheng
-- CHANGE DATE: 2018-05-29
-- CHANGE REASON: [CEMR-1590] [Subtask] [CNT] DB alert_core_cnt_api.pk_cnt_api_exam and alert_core_cnt.pk_cnt_exam
GRANT SELECT, INSERT, UPDATE ON ALERT.EXAM_BODY_STRUCTURE TO ALERT_CORE_CNT WITH GRANT OPTION;
-- CHANGE END: Howard Cheng
-- CHANGE END: Ana Moita
