
@@synonym_plan_table.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@table_dept.sql

@@sequence_seq_professional.sql
@@sequence_seq_presc_xml_0102.sql
@@sequence_seq_presc_xml_0102.sql
@@sequence_seq_presc_number_0102.sql
@@sequence_seq_presc_number_0102.sql
@@sequence_seq_presc_xml_0124.sql
@@sequence_seq_presc_xml_0124.sql
@@sequence_seq_presc_xml_0083.sql
@@sequence_seq_presc_xml_0083.sql
@@sequence_seq_presc_number_0124.sql
@@sequence_seq_presc_number_0124.sql
@@sequence_seq_presc_number_0083.sql
@@sequence_seq_presc_number_0083.sql

@@type_table_number.sql
@@synonym_table_number.sql
@@type_table_varchar.sql
@@synonym_table_varchar.sql
@@type_profissional.sql
@@type_profissional.sql
@@table_abnormality.sql
@@table_abnormality_nature.sql
@@table_action_criteria.sql
@@table_action_criteria.sql
@@table_action_criteria.sql
@@table_action_criteria.sql
@@table_action_criteria.sql

@@table_action_criteria.sql
@@table_action_criteria.sql
@@table_action_criteria.sql
@@table_action_criteria.sql
@@table_action_criteria.sql
@@table_action_criteria.sql
@@table_adverse_exam_allergy.sql
@@table_adverse_interv_allergy.sql
@@table_allergy.sql
@@table_allergy_ext_sys.sql
@@table_allocation_bed.sql
@@table_allocation_bed_10042007.sql
@@table_analy_parm_limit.sql

@@table_analysis.sql
@@table_analysis_agp.sql
@@table_analysis_agp_old.sql
@@table_analysis_alias.sql
@@table_analysis_dep_clin_serv.sql
@@table_analysis_dep_clin_serv_old.sql
@@table_analysis_desc.sql
@@table_analysis_ext_sys_delete.sql
@@table_analysis_group.sql
@@table_analysis_harvest.sql
@@table_analysis_instit_soft.sql
@@table_analysis_loinc.sql
@@table_analysis_loinc_template.sql

@@table_analysis_old.sql
@@table_analysis_param.sql
@@table_analysis_parameter.sql
@@table_analysis_param_instit.sql
@@table_analysis_param_instit_sample.sql
@@table_analysis_prep_mesg.sql
@@table_analysis_protocols.sql
@@table_analysis_protocols_old.sql
@@table_analysis_req.sql
@@table_analysis_req_det.sql
@@table_analysis_req_par.sql
@@table_analysis_result.sql
@@table_analysis_result_par.sql

@@table_analysis_room.sql
@@table_analysis_unit_measure.sql
@@table_anesthesia_type.sql
@@table_bed.sql
@@table_bed_schedule.sql
@@table_beye_view_screen.sql
@@table_birds_eye_view.sql
@@table_board.sql
@@table_board_group.sql
@@table_board_grouping.sql
@@table_body_part.sql
@@table_body_part_image.sql
@@table_bp_clin_serv.sql

@@table_building.sql
@@table_category.sql
@@table_category_sub.sql
@@table_ch_contents.sql
@@table_ch_contents_text.sql
@@table_child_feed_dev.sql
@@table_clinical_service.sql
@@table_clin_record.sql
@@table_clin_serv_ext_sys.sql
@@table_clin_srv_type.sql
@@table_cli_rec_req.sql
@@table_cli_rec_req_det.sql
@@table_cli_rec_req_mov.sql

@@table_color.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint.sql
@@table_complaint_diagnosis.sql

@@table_complaint_template.sql
@@table_complete_history.sql
@@table_consult_req.sql
@@table_consult_req_prof.sql
@@table_contraceptive.sql
@@table_contra_indic.sql
@@table_country.sql
@@table_create$java$lob$table.sql
@@table_criteria.sql
@@table_critical_care.sql
@@table_critical_care_det.sql
@@table_critical_care_read.sql
@@table_department.sql

@@table_dep_clin_serv.sql
@@table_dep_clin_serv_type.sql
@@table_dependency.sql
@@table_dept.sql
@@table_dept_template.sql
@@table_diagnosis.sql
@@table_diagnosis_dep_clin_serv.sql
@@table_diagram.sql
@@table_diagram_detail.sql
@@table_diagram_detail_notes.sql
@@table_diagram_image.sql
@@table_diagram_lay_imag.sql
@@table_diagram_layout.sql

@@table_diagram_tools.sql
@@table_diagram_tools_group.sql
@@table_diet.sql
@@table_dietary_drug.sql
@@table_diet_schedule.sql
@@table_dimension.sql
@@table_dimension.sql
@@table_dimension.sql
@@table_dimension.sql
@@table_dimension.sql
@@table_dimension.sql
@@table_dimension.sql
@@table_dimension.sql

@@table_dimension.sql
@@table_dimension.sql
@@table_dimension.sql
@@table_discharge.sql
@@table_discharge_dest.sql
@@table_discharge_detail.sql
@@table_discharge_notes.sql
@@table_discharge_reason.sql
@@table_disc_help.sql
@@table_disch_prep_mesg.sql
@@table_disch_reas_dest.sql
@@table_disch_rea_transp_ent_inst.sql
@@table_discriminator.sql

@@table_discriminator_help.sql
@@table_disc_vs_valid.sql
@@table_district.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql
@@table_doc_action_criteria.sql

@@table_doc_action_criteria.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_area.sql
@@table_doc_component.sql

@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_component.sql
@@table_doc_criteria.sql
@@table_doc_criteria.sql
@@table_doc_criteria.sql

@@table_doc_criteria.sql
@@table_doc_criteria.sql
@@table_doc_criteria.sql
@@table_doc_criteria.sql
@@table_doc_criteria.sql
@@table_doc_criteria.sql
@@table_doc_criteria.sql
@@table_doc_criteria.sql
@@table_doc_destination.sql
@@table_doc_destination.sql
@@table_doc_destination.sql
@@table_doc_destination.sql
@@table_doc_destination.sql

@@table_doc_destination.sql
@@table_doc_destination.sql
@@table_doc_destination.sql
@@table_doc_destination.sql
@@table_doc_destination.sql
@@table_doc_destination.sql
@@table_doc_dimension.sql
@@table_doc_dimension.sql
@@table_doc_dimension.sql
@@table_doc_dimension.sql
@@table_doc_dimension.sql
@@table_doc_dimension.sql
@@table_doc_dimension.sql

@@table_doc_dimension.sql
@@table_doc_dimension.sql
@@table_doc_dimension.sql
@@table_doc_dimension.sql
@@table_doc_element.sql
@@table_doc_element.sql
@@table_doc_element.sql
@@table_doc_element.sql
@@table_doc_element.sql
@@table_doc_element.sql
@@table_doc_element.sql
@@table_doc_element.sql
@@table_doc_element.sql

@@table_doc_element.sql
@@table_doc_element.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql
@@table_doc_element_crit.sql

@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_qualif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql

@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_quantif.sql
@@table_doc_element_rel.sql
@@table_doc_element_rel.sql
@@table_doc_element_rel.sql
@@table_doc_element_rel.sql

@@table_doc_element_rel.sql
@@table_doc_element_rel.sql
@@table_doc_element_rel.sql
@@table_doc_element_rel.sql
@@table_doc_element_rel.sql
@@table_doc_element_rel.sql
@@table_doc_element_rel.sql
@@table_doc_external.sql
@@table_doc_external.sql
@@table_doc_external.sql
@@table_doc_external.sql
@@table_doc_external.sql
@@table_doc_external.sql

@@table_doc_external.sql
@@table_doc_external.sql
@@table_doc_external.sql
@@table_doc_external.sql
@@table_doc_external.sql
@@table_doc_image.sql
@@table_doc_image.sql
@@table_doc_image.sql
@@table_doc_image.sql
@@table_doc_image.sql
@@table_doc_image.sql
@@table_doc_image.sql
@@table_doc_image.sql

@@table_doc_image.sql
@@table_doc_image.sql
@@table_doc_image.sql
@@table_doc_original.sql
@@table_doc_ori_type.sql
@@table_doc_ori_type.sql
@@table_doc_ori_type.sql
@@table_doc_ori_type.sql
@@table_doc_ori_type.sql
@@table_doc_ori_type.sql
@@table_doc_ori_type.sql
@@table_doc_ori_type.sql
@@table_doc_ori_type.sql

@@table_doc_ori_type.sql
@@table_doc_ori_type.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql
@@table_doc_qualification.sql

@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_quantification.sql
@@table_doc_template.sql
@@table_doc_template.sql

@@table_doc_template.sql
@@table_doc_template.sql
@@table_doc_template.sql
@@table_doc_template.sql
@@table_doc_template.sql
@@table_doc_template.sql
@@table_doc_template.sql
@@table_doc_template.sql
@@table_doc_template.sql
@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql

@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql
@@table_doc_template_diagnosis.sql
@@table_doc_type.sql
@@table_doc_type.sql
@@table_doc_type.sql
@@table_doc_type.sql
@@table_doc_type.sql
@@table_doc_type.sql

@@table_doc_type.sql
@@table_doc_type.sql
@@table_doc_type.sql
@@table_doc_type.sql
@@table_doc_type.sql
@@table_doc_type_soft.sql
@@table_doc_type_soft.sql
@@table_doc_type_soft.sql
@@table_doc_type_soft.sql
@@table_doc_type_soft.sql
@@table_doc_type_soft.sql
@@table_doc_type_soft.sql
@@table_doc_type_soft.sql

@@table_doc_type_soft.sql
@@table_doc_type_soft.sql
@@table_doc_type_soft.sql
@@table_document_area.sql
@@table_document_area.sql
@@table_document_area.sql
@@table_document_area.sql
@@table_document_area.sql
@@table_document_area.sql
@@table_document_area.sql
@@table_document_area.sql
@@table_document_area.sql
@@table_document_area.sql

@@table_document_area.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation.sql
@@table_documentation_rel.sql

@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_rel.sql
@@table_documentation_type.sql
@@table_documentation_type.sql
@@table_documentation_type.sql

@@table_documentation_type.sql
@@table_documentation_type.sql
@@table_documentation_type.sql
@@table_documentation_type.sql
@@table_documentation_type.sql
@@table_documentation_type.sql
@@table_documentation_type.sql
@@table_documentation_type.sql
@@table_document_type.sql
@@table_document_type.sql
@@table_document_type.sql
@@table_document_type.sql
@@table_document_type.sql

@@table_document_type.sql
@@table_document_type.sql
@@table_document_type.sql
@@table_document_type.sql
@@table_document_type.sql
@@table_document_type.sql
@@table_drug.sql
@@table_drug_bck.sql
@@table_drug_brand.sql
@@table_drug_dep_clin_serv.sql
@@table_drug_despachos.sql
@@table_drug_despachos_soft_inst.sql
@@table_drug_form.sql

@@table_drug_instit_justification.sql
@@table_drug_justification.sql
@@table_drug_pharma.sql
@@table_drug_pharma_class.sql
@@table_drug_pharma_class_link.sql
@@table_drug_pharma_interaction.sql
@@table_drug_plan.sql
@@table_drug_presc_det.sql
@@table_drug_presc_plan.sql
@@table_drug_prescription.sql
@@table_drug_protocols.sql
@@table_drug_req.sql
@@table_drug_req_det.sql

@@table_drug_req_supply.sql
@@table_drug_route.sql
@@table_drug_take_plan.sql
@@table_drug_take_time.sql
@@table_element_rel.sql
@@table_emb_dep_clin_serv.sql
@@table_epis_anamnesis.sql
@@table_epis_attending_notes.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart.sql

@@table_epis_bartchart.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart.sql
@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql

@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql
@@table_epis_bartchart_det.sql
@@table_epis_body_painting.sql
@@table_epis_body_painting_det.sql
@@table_epis_complaint.sql
@@table_epis_complaint.sql
@@table_epis_complaint.sql
@@table_epis_complaint.sql
@@table_epis_complaint.sql
@@table_epis_complaint.sql
@@table_epis_complaint.sql

@@table_epis_complaint.sql
@@table_epis_complaint.sql
@@table_epis_complaint.sql
@@table_epis_complaint.sql
@@table_epis_diagnosis.sql
@@table_epis_diagnosis_hist.sql
@@table_epis_diagnosis_notes.sql
@@table_epis_diet.sql
@@table_epis_documentation.sql
@@table_epis_documentation_det.sql
@@table_epis_drug_usage.sql
@@table_epis_ext_sys.sql
@@table_epis_health_plan.sql

@@table_epis_hidrics.sql
@@table_epis_hidrics_balance.sql
@@table_epis_hidrics_det.sql
@@table_epis_info.sql
@@table_epis_institution.sql
@@table_epis_interv.sql
@@table_epis_interval_notes.sql
@@table_epis_man.sql
@@table_epis_observation.sql
@@table_epis_obs_exam.sql
@@table_epis_obs_photo.sql
@@table_episode.sql
@@table_epis_photo.sql

@@table_epis_positioning.sql
@@table_epis_positioning_det.sql
@@table_epis_positioning_plan.sql
@@table_epis_problem.sql
@@table_epis_prof_rec.sql
@@table_epis_prof_resp.sql
@@table_epis_protocols.sql
@@table_epis_readmission.sql
@@table_epis_recomend.sql
@@table_epis_report.sql
@@table_epis_report_section.sql
@@table_epis_review_systems.sql
@@table_epis_task.sql

@@table_epis_triage.sql
@@table_epis_type.sql
@@table_epis_type_room.sql
@@table_equip_protocols.sql
@@table_estate.sql
@@table_exam.sql
@@table_exam_cat.sql
@@table_exam_cat_dcs.sql
@@table_exam_cat_dcs_bck1.sql
@@table_exam_dep_clin_serv.sql
@@table_exam_drug.sql
@@table_exam_egp.sql
@@table_exam_ext_sys_delete.sql

@@table_exam_group.sql
@@table_exam_prep_mesg.sql
@@table_exam_protocols.sql
@@table_exam_req.sql
@@table_exam_req_det.sql
@@table_exam_result.sql
@@table_exam_room.sql
@@table_external_cause.sql
@@table_external_sys.sql
@@table_family_monetary.sql
@@table_family_relationship.sql
@@table_family_relationship_relat.sql
@@table_floors.sql

@@table_floors_department.sql
@@table_floors_dep_position.sql
@@table_floors_institution.sql
@@table_geo_location.sql
@@table_ginec_obstet.sql
@@table_graffar_criteria.sql
@@table_graffar_crit_value.sql
@@table_grid_task.sql
@@table_grid_task_between.sql
@@table_habit.sql
@@table_harvest.sql
@@table_health_plan.sql
@@table_health_plan_instit.sql

@@table_hemo_protocols.sql
@@table_hemo_req.sql
@@table_hemo_req_det.sql
@@table_hemo_req_supply.sql
@@table_hemo_type.sql
@@table_hidrics.sql
@@table_hidrics_interval.sql
@@table_hidrics_relation.sql
@@table_hidrics_type.sql
@@table_home.sql
@@table_icnp_axis.sql
@@table_icnp_classification.sql
@@table_icnp_compo_clin_serv.sql

@@table_icnp_compo_dcs.sql
@@table_icnp_compo_folder.sql
@@table_icnp_compo_folder_060425.sql
@@table_icnp_compo_inst.sql
@@table_icnp_compo_inst_060425.sql
@@table_icnp_composition.sql
@@table_icnp_composition_term.sql
@@table_icnp_composition_060425.sql
@@table_icnp_dictionary.sql
@@table_icnp_epis_diag_interv.sql
@@table_icnp_epis_diag_interv_060425.sql
@@table_icnp_epis_diagnosis.sql
@@table_icnp_epis_diagnosis_060425.sql

@@table_icnp_epis_intervention.sql
@@table_icnp_epis_intervention_060425.sql
@@table_icnp_folder.sql
@@table_icnp_folder_060425.sql
@@table_icnp_morph.sql
@@table_icnp_predefined_action.sql
@@table_icnp_predefined_action_060425.sql
@@table_icnp_relationship.sql
@@table_icnp_term.sql
@@table_icnp_transition_state.sql
@@table_icnp_transition_state_060426.sql
@@table_identification_notes.sql
@@table_implementation.sql

@@table_import_analysis.sql
@@table_import_mcdt.sql
@@table_import_mcdt_migra.sql
@@table_import_mcdt_20060303.sql
@@table_import_prof_admin.sql
@@table_import_prof_med.sql
@@table_ine_location.sql
@@table_inf_atc.sql
@@table_inf_atc_lnk.sql
@@table_inf_cft.sql
@@table_inf_cft_lnk.sql
@@table_inf_class_disp.sql
@@table_inf_class_estup.sql

@@table_inf_comerc.sql
@@table_inf_dcipt.sql
@@table_inf_diabetes_lnk.sql
@@table_inf_diploma.sql
@@table_inf_dispo.sql
@@table_inf_emb.sql
@@table_inf_emb_comerc.sql
@@table_inf_emb_unit.sql
@@table_inf_estado_aim.sql
@@table_inf_form_farm.sql
@@table_inf_grupo_hom.sql
@@table_inf_med.sql
@@table_inf_patol_dip_lnk.sql

@@table_inf_patol_esp.sql
@@table_inf_patol_esp_lnk.sql
@@table_inf_preco.sql
@@table_inf_subst.sql
@@table_inf_subst_lnk.sql
@@table_inf_tipo_diab_mel.sql
@@table_inf_tipo_preco.sql
@@table_inf_tipo_prod.sql
@@table_inf_titular_aim.sql
@@table_inf_tratamento.sql
@@table_inf_vias_admin.sql
@@table_inf_vias_admin_lnk.sql
@@table_ingredient.sql

@@table_inp_error.sql
@@table_inp_log.sql
@@table_instit_ext_sys.sql
@@table_institution.sql
@@table_interv_dep_clin_serv.sql
@@table_interv_dep_clin_serv_migra.sql
@@table_interv_dep_clin_serv_20060303.sql
@@table_interv_drug.sql
@@table_intervention.sql
@@table_interv_ext_sys_delete.sql
@@table_interv_physiatry_area.sql
@@table_interv_prep_msg.sql
@@table_interv_presc_det.sql

@@table_interv_presc_plan.sql
@@table_interv_prescription.sql
@@table_interv_protocols.sql
@@table_interv_room.sql
@@table_isencao.sql
@@table_java$class$md5$table.sql
@@table_java$options.sql
@@table_language.sql
@@table_lixo.sql
@@table_manchester.sql
@@table_manipulated.sql
@@table_manipulated_group.sql
@@table_manipulated_ingredient.sql

@@table_match_epis.sql
@@table_material.sql
@@table_material_protocols.sql
@@table_material_req.sql
@@table_material_req_det.sql
@@table_material_type.sql
@@table_matr_dep_clin_serv.sql
@@table_matr_room.sql
@@table_matr_scheduled.sql
@@table_mcdt_req_diagnosis.sql
@@table_mdm_coding.sql
@@table_mdm_evaluation.sql
@@table_mdm_prof_coding.sql

@@table_monitorization.sql
@@table_monitorization_vs.sql
@@table_monitorization_vs_plan.sql
@@table_movement.sql
@@table_necessity.sql
@@table_nurse_activity_req.sql
@@table_nurse_actv_req_det.sql
@@table_nurse_discharge.sql
@@table_nurse_tea_req.sql
@@table_occupation.sql
@@table_opinion.sql
@@table_opinion_prof.sql
@@table_origin.sql

@@table_origin_soft.sql
@@table_outlook.sql
@@table_param_analysis_ext_sys_delete.sql
@@table_parameter_analysis.sql
@@table_pat_allergy.sql
@@table_pat_allergy_hist.sql
@@table_pat_blood_group.sql
@@table_pat_child_clin_rec.sql
@@table_pat_child_feed_dev.sql
@@table_pat_cli_attributes.sql
@@table_pat_cntrceptiv.sql
@@table_pat_delivery.sql
@@table_pat_doc.sql

@@table_pat_ext_sys.sql
@@table_pat_family.sql
@@table_pat_family_disease.sql
@@table_pat_family_member.sql
@@table_pat_family_prof.sql
@@table_pat_fam_soc_hist.sql
@@table_pat_ginec.sql
@@table_pat_ginec_obstet.sql
@@table_pat_graffar_crit.sql
@@table_pat_habit.sql
@@table_pat_health_plan.sql
@@table_pat_history.sql
@@table_pat_history_hist.sql

@@table_pat_history_type.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_patient.sql
@@table_pat_job.sql

@@table_pat_med_decl.sql
@@table_pat_medication.sql
@@table_pat_medication_hist_list.sql
@@table_pat_medication_list.sql
@@table_pat_necessity.sql
@@table_pat_notes.sql
@@table_pat_permission.sql
@@table_pat_photo.sql
@@table_pat_photo.sql
@@table_pat_photo.sql
@@table_pat_photo.sql
@@table_pat_pregnancy.sql
@@table_pat_pregnancy_risk.sql

@@table_pat_pregn_fetus.sql
@@table_pat_pregn_fetus_biom.sql
@@table_pat_pregn_fetus_det.sql
@@table_pat_pregn_measure.sql
@@table_pat_problem.sql
@@table_pat_problem_hist.sql
@@table_pat_prob_visit.sql
@@table_pat_sick_leave.sql
@@table_pat_soc_attributes.sql
@@table_pat_tmp_remota.sql
@@table_pat_vaccine.sql
@@table_periodic_exam_educ.sql
@@table_plan_table.sql

@@table_positioning.sql
@@table_positioning_type.sql
@@table_postal_code_pt.sql
@@table_pregnancy_risk_eval.sql
@@table_prep_message.sql
@@table_presc_attention_det.sql
@@table_presc_pat_problem.sql
@@table_prescription.sql
@@table_prescription_number_seq.sql
@@table_prescription_pharm.sql
@@table_prescription_pharm_det.sql
@@table_prescription_print.sql
@@table_prescription_type.sql

@@table_prescription_type_access.sql
@@table_prescription_xml.sql
@@table_prescription_xml_det.sql
@@table_prev_episodes_temp.sql
@@table_prof_access.sql
@@table_prof_access_bck.sql
@@table_prof_access_bck1.sql
@@table_prof_access_bck2.sql
@@table_prof_access_field_func.sql
@@table_prof_cat.sql
@@table_prof_dep_clin_serv.sql
@@table_prof_doc.sql
@@table_prof_epis_interv.sql

@@table_professional.sql
@@table_prof_ext_sys.sql
@@table_prof_func.sql
@@table_profile_templ_access.sql
@@table_profile_templ_access_bck_agn.sql
@@table_profile_templ_acc_func.sql
@@table_profile_template.sql
@@table_profile_template_bck_agn.sql
@@table_prof_in_out.sql
@@table_prof_institution.sql
@@table_prof_photo.sql
@@table_prof_photo.sql
@@table_prof_photo.sql

@@table_prof_photo.sql
@@table_prof_photo_medicomni.sql
@@table_prof_preferences.sql
@@table_prof_profile_template.sql
@@table_prof_room.sql
@@table_prof_soft_inst.sql
@@table_prof_team.sql
@@table_prof_team_det.sql
@@table_protoc_diag.sql
@@table_protocols.sql
@@table_p1_doc_external.sql
@@table_p1_doc_external_request.sql
@@table_p1_documents.sql

@@table_p1_documents_done.sql
@@table_p1_external_request.sql
@@table_p1_ext_req_tracking.sql
@@table_p1_history.sql
@@table_p1_prblm_rec_procedure.sql
@@table_p1_problem.sql
@@table_p1_problem_dep_clin_serv.sql
@@table_p1_recomended_procedure.sql
@@table_quest_sl_temp_explain1.sql
@@table_quest_temp_explain.sql
@@table_rb_interv_icd.sql
@@table_rb_profile_templ_access.sql
@@table_rb_sys_button_prop.sql

@@table_rb_sys_button_prop2.sql
@@table_rb_sys_shortcut.sql
@@table_recm.sql
@@table_records_review.sql
@@table_records_review_read.sql
@@table_religion.sql
@@table_rep_destination.sql
@@table_reports.sql
@@table_reports_group.sql
@@table_rep_prof_exception.sql
@@table_rep_profile_template.sql
@@table_rep_profile_template_det.sql
@@table_rep_prof_templ_access.sql

@@table_rep_prof_template.sql
@@table_rep_screen.sql
@@table_rep_section.sql
@@table_rep_section_det.sql
@@table_room.sql
@@table_room_dep_clin_serv.sql
@@table_room_dep_position.sql
@@table_room_ext_sys.sql
@@table_room_scheduled.sql
@@table_rotation_interval.sql
@@table_sample_recipient.sql
@@table_sample_text.sql
@@table_sample_text_freq.sql

@@table_sample_text_prof.sql
@@table_sample_text_type.sql
@@table_sample_text_type_cat.sql
@@table_sample_type.sql
@@table_scales.sql
@@table_scales_class.sql
@@table_scales_doc_value.sql
@@table_sch_action.sql
@@table_sch_cancel_reason.sql
@@table_sch_cancel_reason_inst.sql
@@table_sch_consult_vacancy.sql
@@table_sch_consult_vacancy_temp.sql
@@table_sch_default_consult_vacancy.sql

@@table_schedule.sql
@@table_schedule_alter.sql
@@table_schedule_outp.sql
@@table_schedule_sr.sql
@@table_schedule_sr_det.sql
@@table_sch_event.sql
@@table_sch_event_dcs.sql
@@table_sch_group.sql
@@table_sch_log.sql
@@table_scholarship.sql
@@table_school.sql
@@table_sch_permission.sql
@@table_sch_permission_temp.sql

@@table_sch_prof_outp.sql
@@table_sch_resource.sql
@@table_sch_schedule_request.sql
@@table_sch_service.sql
@@table_sch_service_dcs.sql
@@table_screen_template.sql
@@table_serv_sched_access.sql
@@table_slot.sql
@@table_snomed_concepts.sql
@@table_snomed_descriptions.sql
@@table_snomed_relationships.sql
@@table_social_class.sql
@@table_social_diagnosis.sql

@@table_social_epis_diag.sql
@@table_social_epis_discharge.sql
@@table_social_epis_interv.sql
@@table_social_episode.sql
@@table_social_epis_request.sql
@@table_social_epis_situation.sql
@@table_social_epis_solution.sql
@@table_social_intervention.sql
@@table_soft_inst_impl.sql
@@table_soft_inst_services.sql
@@table_soft_lang.sql
@@table_software.sql
@@table_software_dept.sql

@@table_software_institution.sql
@@table_speciality.sql
@@table_spec_sys_appar.sql
@@table_sqln_explain_plan.sql
@@table_sqln_explain_plan.sql
@@table_sqln_explain_plan.sql
@@table_sqln_explain_plan.sql
@@table_sqln_explain_plan.sql
@@table_sr_base_diag.sql
@@table_sr_cancel_reason.sql
@@table_sr_chklist.sql
@@table_sr_chklist_det.sql
@@table_sr_chklist_manual.sql

@@table_sr_doc_element.sql
@@table_sr_doc_element_crit.sql
@@table_sr_epis_interv.sql
@@table_sr_epis_interv_desc.sql
@@table_sr_equip.sql
@@table_sr_equip_kit.sql
@@table_sr_equip_period.sql
@@table_sr_eval_det.sql
@@table_sr_eval_notes.sql
@@table_sr_eval_rule.sql
@@table_sr_eval_summ.sql
@@table_sr_eval_type.sql
@@table_sr_evaluation.sql

@@table_sr_eval_visit.sql
@@table_sr_interv_dep_clin_serv.sql
@@table_sr_interv_desc.sql
@@table_sr_intervention.sql
@@table_sr_interv_group.sql
@@table_sr_interv_group_det.sql
@@table_sr_nurse_rec.sql
@@table_sr_pat_status.sql
@@table_sr_pat_status_notes.sql
@@table_sr_pat_status_period.sql
@@table_sr_pos_eval_det.sql
@@table_sr_pos_eval_visit.sql
@@table_sr_posit.sql

@@table_sr_posit_req.sql
@@table_sr_pre_anest.sql
@@table_sr_pre_anest_det.sql
@@table_sr_pre_eval.sql
@@table_sr_pre_eval_det.sql
@@table_sr_pre_eval_visit.sql
@@table_sr_prof_recov_schd.sql
@@table_sr_prof_shift.sql
@@table_sr_prof_team_det.sql
@@table_sr_receive.sql
@@table_sr_receive_manual.sql
@@table_sr_receive_proc.sql
@@table_sr_receive_proc_det.sql

@@table_sr_receive_proc_notes.sql
@@table_sr_reserv_req.sql
@@table_sr_room_status.sql
@@table_sr_surgery_rec_det.sql
@@table_sr_surgery_record.sql
@@table_sr_surgery_time.sql
@@table_sr_surgery_time_det.sql
@@table_sr_surg_period.sql
@@table_sr_surg_prot_det.sql
@@table_sr_surg_protocol.sql
@@table_sr_surg_prot_task.sql
@@table_sr_surg_prot_task_det.sql
@@table_sr_surg_task.sql

@@table_sys_alert.sql
@@table_sys_alert_det.sql
@@table_sys_alert_prof.sql
@@table_sys_alert_profile.sql
@@table_sys_alert_software.sql
@@table_sys_alert_type.sql
@@table_sys_appar_organ.sql
@@table_sys_application_area.sql
@@table_sys_application_type.sql
@@table_sys_btn_crit.sql
@@table_sys_btn_sbg.sql
@@table_sys_button.sql
@@table_sys_button_group.sql

@@table_sys_button_prop.sql
@@table_sys_config.sql
@@table_sys_documentation.sql
@@table_sys_domain.sql
@@table_sys_element.sql
@@table_sys_element.sql
@@table_sys_element.sql
@@table_sys_element.sql
@@table_sys_element.sql
@@table_sys_element.sql
@@table_sys_element.sql
@@table_sys_element.sql
@@table_sys_element.sql

@@table_sys_element.sql
@@table_sys_element.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql
@@table_sys_element_crit.sql

@@table_sys_entrance.sql
@@table_sys_error.sql
@@table_sys_field.sql
@@table_sys_functionality.sql
@@table_sys_login.sql
@@table_sys_message.sql
@@table_sys_message_bck.sql
@@table_sys_request.sql
@@table_sys_screen_area.sql
@@table_sys_screen_template.sql
@@table_sys_session.sql
@@table_sys_shortcut.sql
@@table_system_apparati.sql

@@table_system_organ.sql
@@table_sys_time_event_group.sql
@@table_sys_toolbar.sql
@@table_sys_vital_sign.sql
@@table_temp_portaria.sql
@@table_tests_review.sql
@@table_time_unit.sql
@@table_tmp_nurse_summary.sql
@@table_toad_plan_sql.sql
@@table_toad_plan_table.sql
@@table_translation.sql
@@table_translation_bck_20061214.sql
@@table_transp_ent_inst.sql

@@table_transp_entity.sql
@@table_transportation.sql
@@table_transport_type.sql
@@table_transp_req.sql
@@table_transp_req_group.sql
@@table_treatment_management.sql
@@table_triage.sql
@@table_triage_board_group.sql
@@table_triage_board_group.sql
@@table_triage_board_group.sql
@@table_triage_board_group.sql
@@table_triage_board_group.sql
@@table_triage_board_group.sql

@@table_triage_board_group.sql
@@table_triage_board_group.sql
@@table_triage_board_group.sql
@@table_triage_board_group.sql
@@table_triage_board_group.sql
@@table_triage_color.sql
@@table_triage_color.sql
@@table_triage_color.sql
@@table_triage_color.sql
@@table_triage_color.sql
@@table_triage_color.sql
@@table_triage_color.sql
@@table_triage_color.sql

@@table_triage_color.sql
@@table_triage_color.sql
@@table_triage_color.sql
@@table_triage_discriminator.sql
@@table_triage_disc_vs_valid.sql
@@table_triage_nurse.sql
@@table_triage_type.sql
@@table_triage_type.sql
@@table_triage_type.sql
@@table_triage_type.sql
@@table_triage_type.sql
@@table_triage_type.sql
@@table_triage_type.sql

@@table_triage_type.sql
@@table_triage_type.sql
@@table_triage_type.sql
@@table_triage_type.sql
@@table_triage_units.sql
@@table_unit_mea_soft_inst.sql
@@table_unit_measure.sql
@@table_unit_measure_convert.sql
@@table_unit_measure_type.sql
@@table_vaccine.sql
@@table_vaccine_dep_clin_serv.sql
@@table_vaccine_presc_det.sql
@@table_vaccine_presc_plan.sql

@@table_vaccine_prescription.sql
@@table_vbz$object_stats.sql
@@index_vbz$object_stats.sql
@@table_viewer.sql
@@table_viewer_refresh.sql
@@table_viewer_synch_param.sql
@@table_viewer_synchronize.sql
@@table_visit.sql
@@table_visit.sql
@@table_vital_sign.sql
@@table_vital_sign_desc.sql
@@table_vital_sign_notes.sql
@@table_vital_sign_read.sql

@@table_vital_sign_read_error.sql
@@table_vital_sign_relation.sql
@@table_vital_sign_unit_measure.sql
@@table_vs_clin_serv.sql
@@table_vs_soft_inst.sql
@@table_white_reason.sql
@@table_wl_call_queue.sql
@@table_wl_demo.sql
@@table_wl_demo_bck.sql
@@table_wl_machine.sql
@@table_wl_mach_prof_queue.sql
@@table_wl_msg_queue.sql
@@table_wl_patient_sonho.sql

@@table_wl_patient_sonho_imp.sql
@@table_wl_patient_sonho_transfered.sql
@@table_wl_prof_room.sql
@@table_wl_queue.sql
@@table_wl_status.sql
@@table_wl_topics.sql
@@table_wl_waiting_line.sql
@@table_wl_waiting_line_0104.sql
@@table_wl_waiting_room.sql
@@table_wound_charac.sql
@@table_wound_eval_charac.sql
@@table_wound_evaluation.sql
@@table_wound_treat.sql

@@table_wound_type.sql
@@table_institution.sql
@@table_language.sql
@@table_soft_lang.sql
@@table_software.sql
@@table_software_institution.sql
@@table_sys_config.sql
@@table_sys_message.sql
@@synonym_adverse_exam_allergy.sql
@@synonym_matr_scheduled.sql
@@synonym_matr_room.sql
@@synonym_matr_dep_clin_serv.sql
@@synonym_material_type.sql

@@synonym_material_req_det.sql
@@synonym_material_req.sql
@@synonym_material_protocols.sql
@@synonym_material.sql
@@synonym_manchester.sql
@@synonym_language.sql
@@synonym_java$options.sql
@@synonym_java$class$md5$table.sql
@@synonym_isencao.sql
@@synonym_interv_room.sql
@@synonym_interv_protocols.sql
@@synonym_interv_presc_plan.sql
@@synonym_interv_presc_det.sql

@@synonym_interv_prescription.sql
@@synonym_interv_prep_msg.sql
@@synonym_interv_physiatry_area.sql
@@synonym_interv_drug.sql
@@synonym_interv_dep_clin_serv.sql
@@synonym_intervention.sql
@@synonym_instit_ext_sys.sql
@@synonym_institution.sql
@@synonym_implementation.sql
@@synonym_icnp_term.sql
@@synonym_icnp_relationship.sql
@@synonym_icnp_predefined_action.sql
@@synonym_icnp_morph.sql

@@synonym_icnp_folder.sql
@@synonym_icnp_epis_intervention.sql
@@synonym_icnp_epis_diag_interv.sql
@@synonym_icnp_epis_diagnosis.sql
@@synonym_icnp_dictionary.sql
@@synonym_icnp_compo_inst.sql
@@synonym_icnp_compo_folder.sql
@@synonym_icnp_composition_term.sql
@@synonym_icnp_composition.sql
@@synonym_icnp_classification.sql
@@synonym_icnp_axis.sql
@@synonym_home.sql
@@synonym_hemo_type.sql

@@synonym_hemo_req_supply.sql
@@synonym_hemo_req_det.sql
@@synonym_hemo_req.sql
@@synonym_hemo_protocols.sql
@@synonym_health_plan.sql
@@synonym_harvest.sql
@@synonym_habit.sql
@@synonym_grid_task.sql
@@synonym_ginec_obstet.sql
@@synonym_external_sys.sql
@@synonym_external_cause.sql
@@synonym_exam_room.sql
@@synonym_exam_result.sql

@@synonym_exam_req_det.sql
@@synonym_exam_req.sql
@@synonym_exam_protocols.sql
@@synonym_exam_prep_mesg.sql
@@synonym_exam_group.sql
@@synonym_exam_egp.sql
@@synonym_exam_drug.sql
@@synonym_exam_dep_clin_serv.sql
@@synonym_exam.sql
@@synonym_estate.sql
@@synonym_epis_type_room.sql
@@synonym_epis_type.sql
@@synonym_sr_interv_desc.sql

@@synonym_sr_epis_interv_desc.sql
@@synonym_sr_chklist_det.sql
@@synonym_sr_chklist.sql
@@synonym_sr_cancel_reason.sql
@@synonym_sqln_explain_plan.sql
@@synonym_sqln_explain_plan.sql
@@synonym_sqln_explain_plan.sql
@@synonym_sqln_explain_plan.sql
@@synonym_sqln_explain_plan.sql
@@synonym_spec_sys_appar.sql
@@synonym_speciality.sql
@@synonym_soft_inst_services.sql
@@synonym_soft_inst_impl.sql

@@synonym_software_institution.sql
@@synonym_software.sql
@@synonym_snomed_relationships.sql
@@synonym_snomed_descriptions.sql
@@synonym_snomed_concepts.sql
@@synonym_slot.sql
@@synonym_serv_sched_access.sql
@@synonym_sch_service.sql
@@synonym_sch_resource.sql
@@synonym_sch_prof_outp.sql
@@synonym_sch_group.sql
@@synonym_school.sql
@@synonym_scholarship.sql

@@synonym_schedule_sr.sql
@@synonym_schedule_outp.sql
@@synonym_schedule_alter.sql
@@synonym_schedule.sql
@@synonym_sample_type.sql
@@synonym_sample_text_type_cat.sql
@@synonym_sample_text_type.sql
@@synonym_sample_text_prof.sql
@@synonym_sample_text_freq.sql
@@synonym_sample_text.sql
@@synonym_sample_recipient.sql
@@synonym_room_scheduled.sql
@@synonym_room_ext_sys.sql

@@synonym_room_dep_clin_serv.sql
@@synonym_room.sql
@@synonym_religion.sql
@@synonym_quest_temp_explain.sql
@@synonym_quest_sl_temp_explain1.sql
@@synonym_protoc_diag.sql
@@synonym_protocols.sql
@@synonym_prof_team_det.sql
@@synonym_prof_team.sql
@@synonym_prof_soft_inst.sql
@@synonym_prof_room.sql
@@synonym_prof_profile_template.sql
@@synonym_prof_preferences.sql

@@synonym_prof_photo.sql
@@synonym_prof_photo.sql
@@synonym_prof_photo.sql
@@synonym_prof_photo.sql
@@synonym_prof_in_out.sql
@@synonym_prof_institution.sql
@@synonym_prof_func.sql
@@synonym_prof_ext_sys.sql
@@synonym_prof_epis_interv.sql
@@synonym_prof_doc.sql
@@synonym_prof_dep_clin_serv.sql
@@synonym_prof_cat.sql
@@synonym_prof_access_field_func.sql

@@synonym_prof_access.sql
@@synonym_profile_templ_acc_func.sql
@@synonym_profile_templ_access.sql
@@synonym_profile_template.sql
@@synonym_professional.sql
@@synonym_prep_message.sql
@@synonym_pregnancy_risk_eval.sql
@@synonym_plan_table.sql
@@synonym_periodic_exam_educ.sql
@@synonym_pat_vaccine.sql
@@synonym_pat_soc_attributes.sql
@@synonym_wl_patient_sonho_imp.sql
@@synonym_wl_patient_sonho.sql

@@synonym_wl_msg_queue.sql
@@synonym_wl_mach_prof_queue.sql
@@synonym_wl_machine.sql
@@synonym_wl_demo_bck.sql
@@synonym_wl_demo.sql
@@synonym_wl_call_queue.sql
@@synonym_white_reason.sql
@@synonym_vs_clin_serv.sql
@@synonym_vital_sign_relation.sql
@@synonym_vital_sign_read.sql
@@synonym_vital_sign_desc.sql
@@synonym_vital_sign.sql
@@synonym_visit.sql

@@synonym_visit.sql
@@synonym_vbz$object_stats.sql
@@synonym_vaccine_presc_plan.sql
@@synonym_vaccine_presc_det.sql
@@synonym_vaccine_prescription.sql
@@synonym_vaccine_dep_clin_serv.sql
@@synonym_vaccine.sql
@@synonym_transp_req_group.sql
@@synonym_transp_req.sql
@@synonym_transp_ent_inst.sql
@@synonym_transp_entity.sql
@@synonym_transport_type.sql
@@synonym_transportation.sql

@@synonym_translation.sql
@@synonym_toad_plan_table.sql
@@synonym_toad_plan_sql.sql
@@synonym_time_unit.sql
@@synonym_sys_toolbar.sql
@@synonym_sys_time_event_group.sql
@@synonym_sys_shortcut.sql
@@synonym_sys_session.sql
@@synonym_sys_screen_area.sql
@@synonym_sys_request.sql
@@synonym_sys_message_bck.sql
@@synonym_sys_message.sql
@@synonym_sys_functionality.sql

@@synonym_sys_field.sql
@@synonym_sys_error.sql
@@synonym_sys_domain.sql
@@synonym_sys_config.sql
@@synonym_sys_button_prop.sql
@@synonym_sys_button_group.sql
@@synonym_sys_button.sql
@@synonym_sys_btn_sbg.sql
@@synonym_sys_btn_crit.sql
@@synonym_sys_application_type.sql
@@synonym_sys_application_area.sql
@@synonym_sys_alert_type.sql
@@synonym_sys_alert_software.sql

@@synonym_sys_alert_profile.sql
@@synonym_sys_alert_prof.sql
@@synonym_sys_alert_det.sql
@@synonym_sys_alert.sql
@@synonym_system_apparati.sql
@@synonym_sr_surg_task.sql
@@synonym_sr_surg_prot_task_det.sql
@@synonym_sr_surg_prot_task.sql
@@synonym_sr_surg_prot_det.sql
@@synonym_sr_surg_protocol.sql
@@synonym_sr_surgery_record.sql
@@synonym_sr_receive_proc_notes.sql
@@synonym_sr_receive_proc_det.sql

@@synonym_sr_receive_proc.sql
@@synonym_sr_prof_team_det.sql
@@synonym_sr_prof_recov_schd.sql
@@synonym_wound_type.sql
@@synonym_wound_treat.sql
@@synonym_wound_eval_charac.sql
@@synonym_wound_evaluation.sql
@@synonym_wound_charac.sql
@@synonym_wl_waiting_room.sql
@@synonym_wl_waiting_line_0104.sql
@@synonym_wl_waiting_line.sql
@@synonym_wl_topics.sql
@@synonym_wl_status.sql

@@synonym_wl_queue.sql
@@synonym_wl_prof_room.sql
@@synonym_wl_patient_sonho_transfered.sql
@@synonym_pat_sick_leave.sql
@@synonym_pat_prob_visit.sql
@@synonym_pat_problem_hist.sql
@@synonym_pat_problem.sql
@@synonym_pat_pregn_measure.sql
@@synonym_pat_pregn_fetus_det.sql
@@synonym_pat_pregn_fetus_biom.sql
@@synonym_pat_pregn_fetus.sql
@@synonym_pat_pregnancy_risk.sql
@@synonym_pat_pregnancy.sql

@@synonym_pat_photo.sql
@@synonym_pat_photo.sql
@@synonym_pat_photo.sql
@@synonym_pat_photo.sql
@@synonym_pat_permission.sql
@@synonym_pat_notes.sql
@@synonym_pat_necessity.sql
@@synonym_pat_med_decl.sql
@@synonym_pat_medication.sql
@@synonym_pat_job.sql
@@synonym_pat_health_plan.sql
@@synonym_pat_habit.sql
@@synonym_pat_ginec_obstet.sql

@@synonym_pat_ginec.sql
@@synonym_pat_fam_soc_hist.sql
@@synonym_pat_family_prof.sql
@@synonym_pat_family_member.sql
@@synonym_pat_family_disease.sql
@@synonym_pat_family.sql
@@synonym_pat_ext_sys.sql
@@synonym_pat_doc.sql
@@synonym_pat_delivery.sql
@@synonym_pat_cntrceptiv.sql
@@synonym_pat_cli_attributes.sql
@@synonym_pat_child_feed_dev.sql
@@synonym_pat_child_clin_rec.sql

@@synonym_pat_blood_group.sql
@@synonym_pat_allergy_hist.sql
@@synonym_pat_allergy.sql
@@synonym_patient.sql
@@synonym_patient.sql
@@synonym_patient.sql
@@synonym_patient.sql
@@synonym_patient.sql
@@synonym_patient.sql
@@synonym_patient.sql
@@synonym_patient.sql
@@synonym_patient.sql
@@synonym_patient.sql

@@synonym_patient.sql
@@synonym_parameter_analysis.sql
@@synonym_p1_recomended_procedure.sql
@@synonym_p1_problem_dep_clin_serv.sql
@@synonym_p1_problem.sql
@@synonym_p1_prblm_rec_procedure.sql
@@synonym_p1_history.sql
@@synonym_p1_ext_req_tracking.sql
@@synonym_p1_external_request.sql
@@synonym_p1_doc_external_request.sql
@@synonym_p1_doc_external.sql
@@synonym_p1_documents_done.sql
@@synonym_p1_documents.sql

@@synonym_outlook.sql
@@synonym_origin.sql
@@synonym_opinion_prof.sql
@@synonym_opinion.sql
@@synonym_occupation.sql
@@synonym_nurse_tea_req.sql
@@synonym_nurse_discharge.sql
@@synonym_nurse_actv_req_det.sql
@@synonym_nurse_activity_req.sql
@@synonym_necessity.sql
@@synonym_movement.sql
@@synonym_monitorization_vs_plan.sql
@@synonym_monitorization_vs.sql

@@synonym_monitorization.sql
@@synonym_epis_task.sql
@@synonym_epis_recomend.sql
@@synonym_epis_readmission.sql
@@synonym_epis_protocols.sql
@@synonym_epis_problem.sql
@@synonym_epis_photo.sql
@@synonym_epis_obs_photo.sql
@@synonym_epis_obs_exam.sql
@@synonym_epis_observation.sql
@@synonym_epis_man.sql
@@synonym_epis_interv.sql
@@synonym_epis_institution.sql

@@synonym_epis_info.sql
@@synonym_epis_health_plan.sql
@@synonym_epis_ext_sys.sql
@@synonym_epis_drug_usage.sql
@@synonym_epis_diagnosis.sql
@@synonym_epis_body_painting_det.sql
@@synonym_epis_body_painting.sql
@@synonym_epis_anamnesis.sql
@@synonym_episode.sql
@@synonym_drug_take_time.sql
@@synonym_drug_take_plan.sql
@@synonym_drug_route.sql
@@synonym_drug_req_supply.sql

@@synonym_drug_req_det.sql
@@synonym_drug_req.sql
@@synonym_drug_protocols.sql
@@synonym_drug_presc_plan.sql
@@synonym_drug_presc_det.sql
@@synonym_drug_prescription.sql
@@synonym_drug_plan.sql
@@synonym_drug_pharma_interaction.sql
@@synonym_drug_pharma_class.sql
@@synonym_drug_pharma.sql
@@synonym_drug_form.sql
@@synonym_drug_dep_clin_serv.sql
@@synonym_drug_brand.sql

@@synonym_drug.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_doc_type.sql
@@synonym_disc_vs_valid.sql

@@synonym_disc_help.sql
@@synonym_discriminator_help.sql
@@synonym_discriminator.sql
@@synonym_disch_reas_dest.sql
@@synonym_disch_prep_mesg.sql
@@synonym_discharge_reason.sql
@@synonym_discharge_dest.sql
@@synonym_discharge.sql
@@synonym_diagnosis_dep_clin_serv.sql
@@synonym_diagnosis.sql
@@synonym_analysis_result_par.sql
@@synonym_analysis_result.sql
@@synonym_analysis_req_par.sql

@@synonym_analysis_req_det.sql
@@synonym_analysis_req.sql
@@synonym_analysis_protocols.sql
@@synonym_analysis_prep_mesg.sql
@@synonym_analysis_param.sql
@@synonym_analysis_harvest.sql
@@synonym_ch_contents_text.sql
@@synonym_ch_contents.sql
@@synonym_child_feed_dev.sql
@@synonym_category.sql
@@synonym_bp_clin_serv.sql
@@synonym_body_part_image.sql
@@synonym_body_part.sql

@@synonym_board_grouping.sql
@@synonym_board_group.sql
@@synonym_consult_req.sql
@@synonym_color.sql
@@synonym_cli_rec_req_mov.sql
@@synonym_cli_rec_req_det.sql
@@synonym_cli_rec_req.sql
@@synonym_clin_srv_type.sql
@@synonym_clin_serv_ext_sys.sql
@@synonym_clin_record.sql
@@synonym_clinical_service.sql
@@synonym_dep_clin_serv_type.sql
@@synonym_dep_clin_serv.sql

@@synonym_dependency.sql
@@synonym_department.sql
@@synonym_criteria.sql
@@synonym_create$java$lob$table.sql
@@synonym_country.sql
@@synonym_contraceptive.sql
@@synonym_consult_req_prof.sql
@@synonym_board.sql
@@synonym_birds_eye_view.sql
@@synonym_beye_view_screen.sql
@@synonym_bed_schedule.sql
@@synonym_bed.sql
@@synonym_anesthesia_type.sql

@@synonym_analy_parm_limit.sql
@@synonym_analysis_room.sql
@@synonym_analysis.sql
@@synonym_analysis_agp.sql
@@synonym_analysis_dep_clin_serv.sql
@@synonym_analysis_group.sql
@@synonym_allergy.sql
@@synonym_adverse_interv_allergy.sql
@@synonym_unit_measure.sql
@@synonym_sch_event_dcs.sql
@@synonym_sch_event.sql
@@synonym_origin_soft.sql
@@synonym_sr_chklist_manual.sql

@@synonym_sr_evaluation.sql
@@synonym_sr_equip_kit.sql
@@synonym_sr_intervention.sql
@@synonym_sr_pat_status.sql
@@synonym_sr_pat_status_notes.sql
@@synonym_sr_pos_eval_visit.sql
@@synonym_sr_posit_req.sql
@@synonym_sr_nurse_rec.sql
@@synonym_sr_equip.sql
@@synonym_sr_posit.sql
@@synonym_sr_pre_anest.sql
@@synonym_sr_receive_manual.sql
@@synonym_sr_room_status.sql

@@synonym_sr_surg_period.sql
@@synonym_sr_pre_anest_det.sql
@@synonym_sr_epis_interv.sql
@@synonym_sr_eval_visit.sql
@@synonym_sr_pos_eval_det.sql
@@synonym_sr_surgery_rec_det.sql
@@synonym_sr_reserv_req.sql
@@synonym_sr_eval_det.sql
@@synonym_sr_eval_notes.sql
@@synonym_documentation_type.sql
@@synonym_documentation_type.sql
@@synonym_documentation_type.sql
@@synonym_documentation_type.sql

@@synonym_documentation_type.sql
@@synonym_documentation_type.sql
@@synonym_documentation_type.sql
@@synonym_documentation_type.sql
@@synonym_documentation_type.sql
@@synonym_documentation_type.sql
@@synonym_documentation_type.sql
@@synonym_triage_type.sql
@@synonym_triage_type.sql
@@synonym_triage_type.sql
@@synonym_triage_type.sql
@@synonym_triage_type.sql
@@synonym_triage_type.sql

@@synonym_triage_type.sql
@@synonym_triage_type.sql
@@synonym_triage_type.sql
@@synonym_triage_type.sql
@@synonym_triage_type.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql

@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element_crit.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql
@@synonym_sys_element.sql

@@synonym_sys_element.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template_diagnosis.sql
@@synonym_doc_template.sql

@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_template.sql
@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql

@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql
@@synonym_doc_quantification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql

@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_qualification.sql
@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql

@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql
@@synonym_doc_dimension.sql
@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql

@@synonym_doc_criteria.sql
@@synonym_doc_criteria.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql
@@synonym_doc_component.sql

@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_document_type.sql
@@synonym_doc_area.sql
@@synonym_doc_area.sql

@@synonym_doc_area.sql
@@synonym_doc_area.sql
@@synonym_doc_area.sql
@@synonym_doc_area.sql
@@synonym_doc_area.sql
@@synonym_doc_area.sql
@@synonym_doc_area.sql
@@synonym_doc_area.sql
@@synonym_doc_area.sql
@@synonym_document_area.sql
@@synonym_document_area.sql
@@synonym_document_area.sql
@@synonym_document_area.sql

@@synonym_document_area.sql
@@synonym_document_area.sql
@@synonym_document_area.sql
@@synonym_document_area.sql
@@synonym_document_area.sql
@@synonym_document_area.sql
@@synonym_document_area.sql
@@synonym_complaint.sql
@@synonym_complaint.sql
@@synonym_complaint.sql
@@synonym_complaint.sql
@@synonym_complaint.sql
@@synonym_complaint.sql

@@synonym_complaint.sql
@@synonym_complaint.sql
@@synonym_complaint.sql
@@synonym_complaint.sql
@@synonym_complaint.sql
@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql

@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql
@@synonym_doc_element_rel.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql
@@synonym_triage_color.sql

@@synonym_triage_color.sql
@@synonym_epis_documentation_det.sql
@@synonym_epis_documentation.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql
@@synonym_epis_complaint.sql

@@synonym_epis_complaint.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_doc_element_quantif.sql
@@synonym_documentation_rel.sql

@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_documentation_rel.sql
@@synonym_doc_element.sql
@@synonym_doc_element.sql
@@synonym_doc_element.sql

@@synonym_doc_element.sql
@@synonym_doc_element.sql
@@synonym_doc_element.sql
@@synonym_doc_element.sql
@@synonym_doc_element.sql
@@synonym_doc_element.sql
@@synonym_doc_element.sql
@@synonym_doc_element.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql

@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_crit.sql
@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql

@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql
@@synonym_doc_element_qualif.sql
@@synonym_documentation.sql
@@synonym_documentation.sql
@@synonym_documentation.sql
@@synonym_documentation.sql
@@synonym_documentation.sql
@@synonym_documentation.sql
@@synonym_documentation.sql
@@synonym_documentation.sql
@@synonym_documentation.sql

@@synonym_documentation.sql
@@synonym_documentation.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql
@@synonym_doc_action_criteria.sql

@@synonym_epis_triage.sql
@@synonym_triage.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql
@@synonym_epis_bartchart_det.sql

@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_epis_bartchart.sql
@@synonym_action_criteria.sql
@@synonym_action_criteria.sql

@@synonym_action_criteria.sql
@@synonym_action_criteria.sql
@@synonym_action_criteria.sql
@@synonym_action_criteria.sql
@@synonym_action_criteria.sql
@@synonym_action_criteria.sql
@@synonym_action_criteria.sql
@@synonym_action_criteria.sql
@@synonym_action_criteria.sql
@@synonym_floors.sql
@@synonym_floors_dep_position.sql
@@synonym_floors_department.sql
@@synonym_dimension.sql

@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_dimension.sql
@@synonym_vs_soft_inst.sql
@@synonym_doc_external.sql
@@synonym_doc_external.sql

@@synonym_doc_external.sql
@@synonym_doc_external.sql
@@synonym_doc_external.sql
@@synonym_doc_external.sql
@@synonym_doc_external.sql
@@synonym_doc_external.sql
@@synonym_doc_external.sql
@@synonym_doc_external.sql
@@synonym_doc_external.sql
@@package_pk_sr_evaluation.sql
@@synonym_pk_sr_evaluation.sql
@@synonym_epis_prof_resp.sql
@@synonym_triage_board_group.sql

@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@synonym_triage_board_group.sql
@@package_pk_translation.sql
@@package_pk_translation.sql
@@view_v_disch_reas_dest.sql

@@package_pk_sysconfig.sql
@@package_pk_sysconfig.sql
@@package_pk_date_utils.sql
@@package_pk_date_utils.sql
@@package_pk_reset.sql
@@package_pk_message.sql
@@package_pk_message.sql
@@function_sr_act_schedule_date.sql
@@package_pk_patphoto.sql
@@package_pk_types.sql
@@package_pk_p1_med_cs.sql
@@package_pk_p1_adm_hs.sql
@@package_pk_p1_adm_cs.sql

@@package_pk_biztalk.sql
@@package_pk_p1_sync.sql
@@package_pk_p1_med_hs.sql
@@package_pk_types.sql
@@package_pk_vital_sign.sql
@@package_pk_sr_reset.sql
@@package_pk_sr_reset.sql
@@package_pk_sr_surg_record.sql
@@package_pk_sr_surg_record.sql
@@package_pk_sr_tools.sql
@@package_pk_edis_reset.sql
@@package_pk_protocols.sql
@@package_pk_episode.sql

@@package_pk_clinical_info.sql
@@package_pk_grid.sql
@@package_pk_grid.sql
@@package_pk_movement.sql
@@package_pk_visit.sql
@@package_pk_login.sql
@@package_pk_inpatient.sql
@@package_pk_history.sql
@@package_pk_documentation.sql
@@package_pk_inp_nurse.sql
@@package_pk_inp_reset.sql
@@package_pk_documentation_new.sql
@@package_pk_bird_eye_view.sql

@@package_pk_diagnosis.sql
@@package_pk_inp_hidrics.sql
@@package_pk_inp_positioning.sql
@@package_pk_inp_episode.sql
@@package_pk_edis_proc.sql
@@package_pk_inp_diet.sql
@@package_pk_inp_evaluation.sql
@@package_pk_bed.sql
@@package_pk_access.sql
@@package_pk_access.sql
@@package_pk_sysdomain.sql
@@package_pk_wlmed.sql
@@package_pk_login_message.sql

@@package_pk_exam.sql
@@package_pk_analysis.sql
@@package_pk_sr_planning.sql
@@package_pk_alerts.sql
@@package_pk_alerts.sql
@@package_pk_tools.sql
@@package_pk_utils.sql
@@package_pk_demo.sql
@@package_pk_backoffice.sql
@@package_pk_sr_procedures.sql
@@package_pk_sr_output.sql
@@package_pk_login_list.sql
@@package_pk_login_list.sql

@@package_pk_sr_visit.sql
@@package_pk_sr_visit.sql
@@package_pk_interface_report_er_outp.sql
@@package_pk_clinical_record.sql
@@package_pk_search.sql
@@package_pk_discharge.sql
@@package_pk_wlnur.sql
@@package_pk_save.sql
@@package_pk_opinion.sql
@@package_pk_consult_req.sql
@@package_pk_waitinglinesonho.sql
@@package_pk_patient.sql
@@package_pk_patient.sql

@@package_pk_viewer.sql
@@package_pk_screen_template.sql
@@package_pk_diagram.sql
@@package_pk_infarmed.sql
@@package_pk_edis_list.sql
@@package_pk_inp_search.sql
@@package_pk_edis_summary.sql
@@package_pk_medical_decision.sql
@@package_pk_lab_tech.sql
@@package_pk_image_tech.sql
@@package_pk_inp_util.sql
@@package_pk_inp_grid.sql
@@package_pk_family.sql

@@package_pk_doc.sql
@@package_pk_woman_health.sql
@@package_pk_print_tool.sql
@@package_pk_presc_fluids.sql
@@package_pk_edis_tv.sql
@@package_pk_edis_triage.sql
@@package_pk_dmgr_hist.sql
@@package_pk_diagram_new.sql
@@package_pk_audit.sql
@@package_pk_edis_discharge.sql
@@package_pk_hand_off.sql
@@package_pk_match.sql
@@package_pk_problems.sql

@@package_pk_edis_grid.sql
@@package_pk_doc_attach.sql
@@package_rpe_experiencias.sql
@@package_pk_patphoto.sql
@@package_pk_barcode.sql
@@package_pk_wheel.sql
@@package_pk_sample_text.sql
@@package_pk_list.sql
@@package_pk_wladm.sql
@@package_pk_systracking.sql
@@package_pk_wlfinger_print.sql
@@package_pk_wlsession.sql
@@package_pk_wlpatient.sql

@@package_pk_wlcore.sql
@@package_pk_beye_view.sql
@@package_pk_sr_grid.sql
@@package_pk_hemo.sql
@@package_pk_sr_clinical_info.sql
@@package_pk_interv.sql
@@package_pk_vaccine.sql
@@package_pk_monitorization.sql
@@package_pk_profphoto.sql
@@package_pk_drug.sql
@@package_pk_nurse_activity.sql
@@package_pk_icnp.sql
@@package_pk_schedule.sql

@@package_pk_prescription.sql
@@package_pk_alert_er.sql
@@package_pk_p1_core.sql
@@package_pk_login_message.sql
@@package_pk_wlbackoffice.sql
@@trigger_manipulated_group.sql
