-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 09/06/2015 10:01
-- CHANGE REASON: [ALERT-312222 ] CL RED UC Internal medication prescription
GRANT SELECT ON ALERT.FLUIDS_PRESC_DET TO ALERT_PRODUCT_TR;
-- CHANGE END: Sofia Mendes

-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 09/06/2015 10:24
-- CHANGE REASON: [ALERT-312414 ] CL RED UC Internal medication prescription
GRANT SELECT ON ALERT.FLUIDS_PRESC_DET TO ALERT_PRODUCT_TR;
-- CHANGE END: Sofia Mendes