

GRANT SELECT ON ALERT.FOLLOW_UP_ENTITY TO ALERT_VIEWER;



-- CHANGED BY: Susana Silva
-- CHANGE DATE: 09/03/2010 09:32
-- CHANGE REASON: [ALERT-80043 ] 
grant select, references on FOLLOW_UP_ENTITY to ALERT_DEFAULT;
-- CHANGE END: Susana Silva