
GRANT SELECT ON ALERT.FOLLOW_UP_ENTITY_SOFT_INST TO ALERT_VIEWER;




-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.FOLLOW_UP_ENTITY_SOFT_INST to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
