GRANT SELECT ON ALERT.DISCH_DEST_INST TO PUBLIC;
GRANT SELECT ON ALERT.DISCH_DEST_INST TO INTER_ALERT_V2;
GRANT SELECT ON ALERT.DISCH_DEST_INST TO PIX;
GRANT SELECT ON ALERT.DISCH_DEST_INST TO ALERT_VIEWER;



-- CHANGED BY: Pedro Teixeira
-- CHANGE DATE: 25/03/2010 09:32
-- CHANGE REASON: [ALERT-83163] 
GRANT SELECT ON ALERT.DISCH_DEST_INST TO PUBLIC;
GRANT SELECT ON ALERT.DISCH_DEST_INST TO INTER_ALERT_V2;
GRANT SELECT ON ALERT.DISCH_DEST_INST TO ALERT_VIEWER;
-- CHANGE END: Pedro Teixeira