-- CHANGED BY: Susana Silva
-- CHANGE DATE: 04/03/2010 15:15
-- CHANGE REASON: [ALERT-79309] 
grant select on HEALTH_PROGRAM_SOFT_INST to ALERT_DEFAULT;
-- CHANGE END: Susana Silva


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.HEALTH_PROGRAM_SOFT_INST to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
