-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 05/07/2010 15:03
-- CHANGE REASON: [ALERT-109290] DB Versioning - TABLES
GRANT SELECT ON ALERT.HIDRICS_CHARACT TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.HIDRICS_CHARACT to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
