-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 03/07/2010 20:51
-- CHANGE REASON: [ALERT-109290] Fluid Balance - Reformulation
GRANT SELECT ON ALERT.HIDRICS_LOCATION TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.HIDRICS_LOCATION to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
