
  GRANT SELECT ON ICNP_AXIS_DCS TO ALERT_VIEWER;




-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.ICNP_AXIS_DCS to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
