
  GRANT SELECT ON ICNP_COMPOSITION_HIST TO ALERT_VIEWER;




-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.ICNP_COMPOSITION_HIST to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
