PROMPT CREATING GRANTS ON ALERT

PROMPT CREATING TABLE GRANTS

GRANT SELECT ON ANALYSIS_ABN_PRINT TO INTER_ALERT_V2;
--Ricardo Bento 2008/11/28
GRANT SELECT ON mi_pharm_group TO INTER_ALERT_V2;

--Antonio Vieira: 24/11/2008
GRANT SELECT ON OTHER_PRODUCT TO INTER_ALERT_V2;
GRANT SELECT ON FORM_FARM_UNIT TO INTER_ALERT_V2;
--End
GRANT SELECT ON SUPPLIES TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_SUPPLIES TO INTER_ALERT_V2;
GRANT SELECT ON MI_MED TO INTER_ALERT_V2;
GRANT SELECT ON PAT_HEALTH_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON TRANSLATION TO INTER_ALERT_V2;
GRANT SELECT ON HEALTH_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_REQ TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_REQ_DET TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_REQ_SUPPLY TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_PRESC_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_PRESC_PLAN_STOCK TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_TRIAGE TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_SUPPLIES_DET TO INTER_ALERT_V2;
-- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON ANALYSIS_REQ_DET TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS TO INTER_ALERT_V2;
GRANT SELECT ON PROFESSIONAL TO INTER_ALERT_V2;
GRANT SELECT ON PATIENT TO INTER_ALERT_V2;
-- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON EPISODE TO INTER_ALERT_V2; 
GRANT SELECT ON HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_TYPE TO INTER_ALERT_V2;
GRANT SELECT ON SAMPLE_TYPE TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_REQ TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_GROUP TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_REQ_PAR TO INTER_ALERT_V2;
 -- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON ROOM TO INTER_ALERT_V2;
GRANT SELECT ON PROTOCOLS TO INTER_ALERT_V2;
GRANT SELECT ON CATEGORY TO INTER_ALERT_V2;
GRANT SELECT ON LANGUAGE TO INTER_ALERT_V2;
 -- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON ANALYSIS_RESULT_PAR TO INTER_ALERT_V2;
 -- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON ANALYSIS_RESULT TO INTER_ALERT_V2;
 -- Rever, consultar ficheiro de excel
GRANT SELECT,UPDATE ON EXAM_REQ_DET TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_PRESC_DET TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_PRESCRIPTION TO INTER_ALERT_V2;
GRANT SELECT ON PRESCRIPTION TO INTER_ALERT_V2;
GRANT SELECT ON DIAGNOSIS TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_DIAGNOSIS TO INTER_ALERT_V2;
GRANT SELECT ON MCDT_REQ_DIAGNOSIS TO INTER_ALERT_V2;
GRANT SELECT ON DISCHARGE TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_READMISSION TO INTER_ALERT_V2;
--[PP] 23/3/2009
GRANT SELECT, UPDATE ON EPIS_INFO TO INTER_ALERT_V2;
GRANT SELECT ON INTERVENTION TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_PRESCRIPTION TO INTER_ALERT_V2;
GRANT SELECT ON VITAL_SIGN_READ TO INTER_ALERT_V2;
GRANT SELECT ON VITAL_SIGN TO INTER_ALERT_V2;
GRANT SELECT ON EXAM_REQ TO INTER_ALERT_V2;
GRANT SELECT ON EXAM TO INTER_ALERT_V2;
GRANT SELECT ON DISCHARGE_DETAIL TO INTER_ALERT_V2;
GRANT SELECT ON PROF_INSTITUTION TO INTER_ALERT_V2;
GRANT SELECT ON DISCH_REAS_DEST TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_TASK TO INTER_ALERT_V2;
GRANT SELECT ON EXAM_DEP_CLIN_SERV TO INTER_ALERT_V2;
GRANT SELECT ON PROF_CAT TO INTER_ALERT_V2;
GRANT SELECT ON PROF_PREFERENCES TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_PROF_RESP TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_PRESC_DET TO INTER_ALERT_V2;
GRANT SELECT ON SCH_GROUP TO INTER_ALERT_V2;
GRANT SELECT ON SCHEDULE TO INTER_ALERT_V2;
GRANT SELECT ON CLIN_RECORD TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT SELECT,UPDATE,INSERT ON EPIS_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON ALLERGY TO INTER_ALERT_V2;
GRANT SELECT ON ALLERGY_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON PAT_ALLERGY TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_PRESC_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON DEP_CLIN_SERV TO INTER_ALERT_V2;
GRANT SELECT ON INSTITUTION_LANGUAGE TO INTER_ALERT_V2;
GRANT SELECT ON INSTITUTION TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT INSERT ON WL_PATIENT_SONHO TO INTER_ALERT_V2;
GRANT UPDATE ON VISIT TO INTER_ALERT_V2;

 -- A rever, consultar ficheiro de excel
GRANT SELECT ON WL_PATIENT_SONHO TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE_COLOR TO INTER_ALERT_V2;
GRANT SELECT ON BED TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_ANAMNESIS TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE_BOARD TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE_DISCRIMINATOR TO INTER_ALERT_V2;
GRANT SELECT ON UNIT_MEA_SOFT_INST TO INTER_ALERT_V2;
GRANT SELECT ON UNIT_MEASURE TO INTER_ALERT_V2;
GRANT SELECT ON VITAL_SIGN_RELATION TO INTER_ALERT_V2;
GRANT SELECT ON SPECIALITY TO INTER_ALERT_V2;
GRANT SELECT ON VS_SOFT_INST TO INTER_ALERT_V2;
GRANT SELECT ON VITAL_SIGN_DESC TO INTER_ALERT_V2;
GRANT SELECT ON DEPARTMENT TO INTER_ALERT_V2;
GRANT SELECT ON EXAM_ROOM TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_LOINC TO INTER_ALERT_V2;
GRANT SELECT ON MOVEMENT TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
-- AM Passou ALERT_ADT
--GRANT SELECT,INSERT,UPDATE ON PAT_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON COUNTRY TO INTER_ALERT_V2;
GRANT SELECT ON PAT_SOC_ATTRIBUTES TO INTER_ALERT_V2;
--PASSOU ALERT_ADT
--GRANT SELECT ON SEQ_PAT_EXT_SYS TO INTER_ALERT_V2;
--GRANT SELECT ON PAT_NECESSITY TO INTER_ALERT_V2;
GRANT SELECT ON DOC_EXTERNAL TO INTER_ALERT_V2;
GRANT SELECT ON SYS_CONFIG TO INTER_ALERT_V2;
GRANT SELECT ON MI_ROUTE TO INTER_ALERT_V2;
GRANT SELECT ON DRUG TO INTER_ALERT_V2;
GRANT SELECT ON FLUIDS_PRESC_DET TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_COMPOSITION TO INTER_ALERT_V2;
GRANT SELECT ON PROF_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON PROF_DEP_CLIN_SERV TO INTER_ALERT_V2;
GRANT SELECT ON SCH_RESOURCE TO INTER_ALERT_V2;
GRANT SELECT ON SEQ_EPIS_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_ROOM TO INTER_ALERT_V2;
GRANT SELECT ON TRIAGE_WHITE_REASON TO INTER_ALERT_V2;
GRANT SELECT ON SAMPLE_RECIPIENT TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_INSTIT_SOFT TO INTER_ALERT_V2;
GRANT SELECT ON EXAM_CAT TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_QUESTION_RESPONSE TO INTER_ALERT_V2;
GRANT SELECT ON ANALYSIS_QUESTIONNAIRE TO INTER_ALERT_V2;
GRANT SELECT ON THERAPEUTIC_PROTOCOLS TO INTER_ALERT_V2;
GRANT SELECT ON DRUG_THERAPEUTIC_PROTOCOLS to INTER_ALERT_V2;
GRANT SELECT ON prof_preferences TO INTER_ALERT_V2;
-- A rever, consultar Hugo Vieira
GRANT SELECT,INSERT,UPDATE ON EXTERNAL_DOC TO INTER_ALERT_V2;
--#S[AV]
GRANT SELECT ON sys_alert_event TO INTER_ALERT_V2;
GRANT SELECT ON FAST_TRACK TO INTER_ALERT_V2;
GRANT SELECT ON FAST_TRACK_INSTITUTION TO INTER_ALERT_V2;
--#E[AV]
-- [RF 31-03-2009]
GRANT SELECT ON exam_result TO INTER_ALERT_V2;

--[AV 06-04-2009]
GRANT SELECT ON PRESCRIPTION_INSTR_HIST TO INTER_ALERT_V2;

--#S[HS 13-04-2009]
GRANT SELECT ON IRREGULAR_DIRECTIONS_DCS_REL TO INTER_ALERT_V2;
GRANT SELECT ON IRREGULAR_DIRECTIONS_TIME TO INTER_ALERT_V2;
GRANT SELECT ON IRREGULAR_INTERVAL TO INTER_ALERT_V2;
GRANT SELECT ON IRREGULAR_FREQUENCY TO INTER_ALERT_V2;
GRANT SELECT ON IRREGULAR_DIRECTIONS TO INTER_ALERT_V2;
--#E[HS 13-04-2009]

--#S [RF] 14-04-2009
GRANT SELECT ON DISCHARGE_DEST TO INTER_ALERT_V2;
GRANT SELECT ON DISCHARGE_REASON TO INTER_ALERT_V2;
GRANT SELECT ON SOFTWARE TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_DEP_CLIN_SERV TO INTER_ALERT_V2;
GRANT SELECT ON CLINICAL_SERVICE TO INTER_ALERT_V2;
--#E [RF] 14-04-2009

--[PP] 23-03-2009 INTERALERTD-192
GRANT UPDATE ON SCH_GROUP TO INTER_ALERT_V2;
--[RB] 2009-04-29
GRANT select ON ALERT.SCH_CONSULT_VAC_MFR TO INTERFACE_SONHO_V2;
-- #S [RF] 19-05-2009    
GRANT SELECT ON epis_report TO INTER_ALERT_V2;
GRANT SELECT ON rep_section TO INTER_ALERT_V2;
GRANT SELECT ON rep_section_det TO INTER_ALERT_V2;
GRANT SELECT ON epis_report_section TO INTER_ALERT_V2;
GRANT SELECT ON epis_type_soft_inst TO INTER_ALERT_V2;
-- #E [RF] 19-05-2009

PROMPT CREATING SEQUENCES GRANTS
GRANT SELECT ON SEQ_ANALYSIS_REQ_DET TO INTER_ALERT_V2;
GRANT SELECT ON SEQ_EPISODE TO INTER_ALERT_V2;
GRANT SELECT ON SEQ_VISIT TO INTER_ALERT_V2;
--AM passou ALERT_ADT
--GRANT SELECT ON SEQ_EXTERNAL_SYS TO INTER_ALERT_V2;
GRANT SELECT ON SEQ_EXAM_REQ_DET TO INTER_ALERT_V2;
--passou ALERT_ADT
--GRANT SELECT ON SEQ_PATIENT TO INTER_ALERT_V2;
-- A rever, consultar Hugo Vieira
GRANT SELECT ON SEQ_EXTERNAL_DOC TO INTER_ALERT_V2;
--[SM07-07-2009]
GRANT SELECT ON SCHEDULE_SR TO INTER_ALERT_V2; 
GRANT SELECT ON order_set_process_task_det TO INTER_ALERT_V2; 
GRANT SELECT ON order_set_process_task TO INTER_ALERT_V2; 
GRANT SELECT ON order_set_process TO INTER_ALERT_V2; 


PROMPT CREATING TYPES GRANTS
GRANT EXECUTE ON TABLE_NUMBER TO INTER_ALERT_V2;
GRANT EXECUTE ON TABLE_VARCHAR TO INTER_ALERT_V2;
GRANT EXECUTE ON TABLE_TABLE_NUMBER TO INTER_ALERT_V2;
GRANT EXECUTE ON TABLE_TABLE_VARCHAR TO INTER_ALERT_V2;
GRANT EXECUTE ON PROFISSIONAL TO INTER_ALERT_V2;

PROMPT CREATING PACKAGES GRANTS
GRANT EXECUTE ON PK_API_ANALYSIS TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_EXAM TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_ANALYSIS TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_TYPES TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_DIAGNOSIS TO INTER_ALERT_V2;
-- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_EPISODE TO INTER_ALERT_V2; 
 -- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_SCHEDULE TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_VISIT TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_WAITINGLINESONHO TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_PFH_INTERFACE TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_UNIT_MEASURE TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_VITAL_SIGN TO INTER_ALERT_V2;
 -- A rever, consultar ficheiro de excel
GRANT EXECUTE ON PK_INP_EPISODE TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_MOVEMENT TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_SR_VISIT TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_VISIT TO INTER_ALERT_V2;
 -- A rever, consultar ficeiro de excel
GRANT EXECUTE ON PK_SCHEDULE_INTERFACE TO INTER_ALERT_V2;
-- A rever, consultar ficeiro de excel
GRANT EXECUTE ON PK_PRESCRIPTION TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_INTERV TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_DRUG TO INTER_ALERT_V2;
-- Rafael Fontes 15-01-2009
GRANT EXECUTE ON pk_api_alerts TO INTER_ALERT_V2;
-- PP 09-02-2009
GRANT EXECUTE ON pk_api_backoffice to INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_SUMMARY_PAGE TO INTER_ALERT_V2;
GRANT EXECUTE ON PK_API_INPATIENT TO INTER_ALERT_V2;
--[AV] 17-03-2009
GRANT EXECUTE ON TABLE_NUMBER TO MAP;
-- [RF 19-05-2009]
GRANT EXECUTE ON pk_alert_constant TO INTER_ALERT_V2;
 -- [AM 01-06-2009]
GRANT EXECUTE ON t_error_out TO INTER_ALERT_V2; 
grant execute on table_index_varchar to inter_alert_v2;
grant execute on index_varchar to inter_alert_v2;



-- [RF] 22-07-2009
-- VIEWS
GRANT SELECT ON V_EPISODE TO INTER_ALERT_V2;
GRANT SELECT ON V_HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON V_ANALYSIS_HARVEST TO INTER_ALERT_V2;
GRANT SELECT ON V_ANALYSIS_REQUEST TO INTER_ALERT_V2;
GRANT SELECT ON V_ANALYSIS_REQUEST_DETAIL TO INTER_ALERT_V2;
GRANT SELECT ON V_PROFESSIONAL TO INTER_ALERT_V2;
GRANT SELECT ON V_PROF_INSTITUTION TO INTER_ALERT_V2;
GRANT SELECT ON V_EPIS_EXT_SYS TO INTER_ALERT_V2;
GRANT SELECT ON v_pat_inst_attribute TO INTER_ALERT_V2;
GRANT SELECT ON v_pat_ext_sys TO INTER_ALERT_V2;
GRANT SELECT ON v_vital_sign_read TO INTER_ALERT_V2;
GRANT SELECT ON v_interv_prescription TO INTER_ALERT_V2;
GRANT SELECT ON v_interv_prescription_plan to INTER_ALERT_V2;
GRANT SELECT ON V_INTERV_PRESCRIPTION_DETAIL  TO INTER_ALERT_V2;
GRANT SELECT ON v_drug_prescription_plan TO INTER_ALERT_V2;
GRANT SELECT ON V_DRUG_PRESCRIPTION_DETAIL TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_supplies_det TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_anamnesis TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_diagnosis TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_readmission TO INTER_ALERT_V2;
GRANT SELECT ON v_discharge TO INTER_ALERT_V2;
GRANT SELECT ON v_discharge_detail TO INTER_ALERT_V2;
GRANT SELECT ON V_EPIS_PROF_RESP TO INTER_ALERT_V2;
GRANT SELECT ON V_PROF_CATEGORY TO INTER_ALERT_V2;
GRANT SELECT ON V_DRUG_PRESCRIPTION TO INTER_ALERT_V2;
GRANT SELECT ON V_DRUG_PRESCRIPTION_DETAIL TO INTER_ALERT_V2;
GRANT SELECT ON V_DRUG_PRESCRIPTION_PLAN TO INTER_ALERT_V2;
GRANT SELECT ON v_epis_type_soft_inst TO INTER_ALERT_V2;
GRANT SELECT ON v_episode_triage TO INTER_ALERT_V2;
GRANT SELECT ON v_pat_health_plan TO INTER_ALERT_V2;
GRANT SELECT ON v_exam_request TO INTER_ALERT_V2;
GRANT SELECT ON v_analysis_loinc TO INTER_ALERT_V2;
GRANT SELECT ON v_schedule TO INTER_ALERT_V2;
GRANT SELECT ON v_movement TO INTER_ALERT_V2;
GRANT SELECT ON v_exam_request_detail TO INTER_ALERT_V2;

--AM 20090819
GRANT SELECT ON alert.pat_history_diagnosis TO INTER_ALERT_V2;
--SM 20090820
GRANT SELECT ON alert.INSTITUTION_GROUP TO INTER_ALERT_V2;
--[AV] 10-09-2009
GRANT SELECT ON alert.analysis_parameter to INTER_ALERT_V2;

--AM 20090915
GRANT execute ON alert.pk_medication_workflow TO INTER_ALERT_V2;
GRANT select ON alert.DRUG_REQ_SUPPLY_dev TO INTER_ALERT_V2;

--PP 20090928
GRANT SELECT ON EPIS_DIET_REQ TO INTER_ALERT_V2;
GRANT SELECT ON EPIS_DIET TO INTER_ALERT_V2;
GRANT SELECT ON DIET_TYPE TO INTER_ALERT_V2;
GRANT SELECT ON DIET_SCHEDULE_TIME TO INTER_ALERT_V2;
GRANT SELECT ON DIET_SCHEDULE TO INTER_ALERT_V2;
GRANT SELECT ON DIET_INSTIT_SOFT TO INTER_ALERT_V2;
GRANT SELECT ON DIET_PROF_INSTIT TO INTER_ALERT_V2;
GRANT SELECT ON DIET_PROF_PREF TO INTER_ALERT_V2;
--[AV]14-10-2009
GRANT SELECT ON EPIS_DIET_DET TO INTER_ALERT_V2; 
GRANT SELECT ON CANCEL_REASON TO INTER_ALERT_V2; 

--AV 20091008
GRANT EXECUTE ON T_TBL_COMPONENT_STRUCT TO INTER_ALERT_V2; 

--AM 20091010
GRANT SELECT ON alert.sr_pat_status TO INTER_ALERT_V2;
--TS 20091102
GRANT SELECT ON EPIS_RECOMEND TO INTER_ALERT_V2;