-- CHANGED BY: Ana Matos
-- CHANGE DATE: 18/07/2016 09:39
-- CHANGE REASON: [ALERT-323391] 
GRANT SELECT ON INTERV_QUESTION_RESPONSE TO INTER_ALERT_V2;
GRANT SELECT ON INTERV_QUESTION_RESPONSE TO ALERT_INTER;
-- CHANGE END: Ana Matos