-- CHANGED BY: Paulo Teixeira
-- CHANGE DATE: 26/08/2011 09:00
-- CHANGE REASON: [ALERT-190334] 
GRANT SELECT ON links TO alert_viewer;
GRANT ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE ON links TO inter_alert_v2;
-- CHANGE END: Paulo Teixeira