-- CHANGED BY:  Rui Gomes
-- CHANGE DATE: 20/09/2011 18:02
-- CHANGE REASON: [ALERT-157923] grants
grant references on ME_DIETARY to ALERT_DEFAULT;
-- CHANGE END:  Rui Gomes

-- CHANGED BY:  Rui Gomes
-- CHANGE DATE: 27/01/2012 17:16
-- CHANGE REASON: [ALERT-216286] 
grant references on ME_DIETARY to ALERT_DEFAULT;
-- CHANGE END:  Rui Gomes


GRANT SELECT ON ALERT.ME_DIETARY TO ALERT_PRODUCT_TR;