-- CHANGED BY: Carlos Loureiro
-- CHANGE DATE: 04/07/2010 03:09
-- CHANGE REASON: [ALERT-109296] TDE Core versioning (DDL)
grant select on ORDER_SET_TASK_DEPENDENCY to ALERT_VIEWER;
-- CHANGE END: Carlos Loureiro