-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 23/12/2009 16:59
-- CHANGE REASON: [ALERT-63465] 
GRANT SELECT ON ALERT.P1_EXTERNAL_REQUEST TO INTER_ALERT_V2;
GRANT SELECT ON ALERT.P1_EXTERNAL_REQUEST TO INTF_ALERT;
-- CHANGE END: Joana Barroso

-- CHANGED BY: Ana Matos
-- CHANGE DATE: 21/12/2016 10:34
-- CHANGE REASON: [ALERT-327229] 
GRANT SELECT ON P1_EXTERNAL_REQUEST TO ALERT_INTER;
-- CHANGE END: Ana Matos

-- CHANGED BY: Ruben Araujo
-- CHANGE DATE: 24/05/2016 
-- CHANGE REASON: [ALERT-320400] 
GRANT SELECT  ON ALERT.P1_EXTERNAL_REQUEST to ALERT_ADTCOD;
-- CHANGE END: Ruben Araujo

-- CHANGED BY: Cristina Oliveira
-- CHANGE DATE: 15/12/2020 10:33
-- CHANGE REASON: [EMR-39746]
grant select, references on p1_external_request to adw_stg  WITH GRANT OPTION;
-- CHANGE END: Cristina Oliveira