-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 18/12/2009 14:34
-- CHANGE REASON: [ALERT-63465] 
GRANT SELECT ON ALERT.P1_TRACKING TO ALERT_VIEWER;
GRANT SELECT ON ALERT.P1_TRACKING TO INTER_ALERT_V2;
GRANT SELECT ON ALERT.P1_TRACKING TO INTF_ALERT;
-- CHANGE END: Joana Barroso

-- CHANGED BY: Cristina Oliveira
-- CHANGE DATE: 15/12/2020 10:33
-- CHANGE REASON: [EMR-39746]
grant select, references on p1_tracking to adw_stg  WITH GRANT OPTION;
-- CHANGE END: Cristina Oliveira