

  GRANT EXECUTE ON ALERT.PK_VISIT TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_VISIT TO ALERT_VIEWER;


GRANT EXECUTE ON ALERT.PK_VISIT TO ALERT_VIEWER;



-- CHANGED BY: Eduardo Lourenco
-- CHANGE DATE: 13/04/2009 12:31
-- CHANGE REASON: [ALERT-23613] 
GRANT EXECUTE ON ALERT.PK_VISIT TO ALERT_ADTCOD;
-- CHANGE END: Eduardo Lourenco


-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 17/02/2017 15:50
-- CHANGE REASON: [ALERT-328098]
GRANT EXECUTE ON PK_VISIT TO ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Henriques