-- CHANGED BY: Luís Maia
-- CHANGE DATE: 08/06/2009 17:00
-- CHANGE REASON: [ALERT-29597] Give grants to ALERT_VIEWER to package ts_discharge_schedule
GRANT EXECUTE ON ALERT.TS_TASK_TIMELINE_EA TO ALERT_VIEWER;
-- CHANGE END: Luís Maia