-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 07/12/2009 14:17
-- CHANGE REASON: [ALERT-61272] 
GRANT EXECUTE ON ALERT.PK_SCHEDULE_ORIS TO ALERT_VIEWER;
-- CHANGE END: Sofia Mendes

-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 08/03/2010 17:01
-- CHANGE REASON: [ALERT-79978] 
GRANT EXECUTE ON ALERT.PK_SCHEDULE_ORIS TO ALERT_VIEWER;
-- CHANGE END: Sofia Mendes