-- CHANGED BY: Luís Maia
-- CHANGE DATE: 23/04/2009 17:59
-- CHANGE REASON: Give grants to ALERT_VIEWER to package pk_logic_movements
GRANT EXECUTE ON ALERT.PK_LOGIC_MOVEMENTS TO ALERT_VIEWER;
-- CHANGE END