-- CHANGED BY: José Silva
-- CHANGE DATE: 24/12/2010 08:47
-- CHANGE REASON: [ALERT-151946] Grand and Synonym for Severity Scores
GRANT EXECUTE ON ALERT.PK_SEV_SCORES_API_UI TO ALERT_VIEWER;
-- CHANGE END: José Silva