-- CHANGED BY: Ana Monteiro
-- CHANGE DATE: 05/01/2010 12:06
-- CHANGE REASON: [ALERT-31116] 
GRANT EXECUTE ON ALERT.PK_REF_PIO TO ALERT_VIEWER;
-- CHANGE END: Ana Monteiro

-- CHANGED BY: Ana Monteiro
-- CHANGE DATE: 05/01/2010 18:00
-- CHANGE REASON: [ALERT-58261] 
GRANT EXECUTE ON ALERT.PK_REF_PIO TO ALERT_VIEWER;
-- CHANGE END: Ana Monteiro

-- CHANGED BY: Ana Monteiro
-- CHANGE DATE: 08/03/2010 14:06
-- CHANGE REASON: [ALERT-79864] 
GRANT EXECUTE ON ALERT.PK_REF_PIO TO ALERT_VIEWER;
-- CHANGE END: Ana Monteiro