-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 21/06/2010 10:23
-- CHANGE REASON: [ALERT-89424] 
GRANT EXECUTE ON ALERT.PK_REF_RESET TO ALERT_VIEWER;
GRANT EXECUTE ON ALERT.PK_REF_RESET TO ALERT_RESET;
-- CHANGE END: Joana Barroso