GRANT EXECUTE ON ALERT.PK_CALC TO ALERT_VIEWER;



-- CHANGED BY: Eduardo Lourenco
-- CHANGE DATE: 28/03/2009 11:32
-- CHANGE REASON: [ALERT-18690] 
GRANT EXECUTE ON ALERT.PK_CALC TO ALERT_VIEWER;
-- CHANGE END