

  GRANT EXECUTE ON ALERT.PK_SR_RESET TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SR_RESET TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_SR_RESET TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SR_RESET TO ALERT_VIEWER;


GRANT EXECUTE ON ALERT.PK_SR_RESET TO ALERT_VIEWER;

