-- CREATED BY: Pedro Pinheiro
-- CREATED DATE: 14/02/2012 15:52
-- CREATED REASON: [ALERT-217580] 
grant execute on ALERT.PK_LUCENE_INDEX_ADMIN to ALERT_CONFIG;
grant execute on ALERT.PK_LUCENE_INDEX_ADMIN to ALERT_PRODUCT_MT;
-- CREATED END: Pedro Pinheiro