-- CHANGED BY: José Silva
-- CHANGE DATE: 12/03/2010 09:42
-- CHANGE REASON: [ALERT-80941] Reason for pending discharge: DB developments
GRANT EXECUTE ON ALERT.PK_API_DISCHARGE TO ALERT_VIEWER;
GRANT EXECUTE ON ALERT.PK_API_DISCHARGE TO INTER_ALERT_V2;
GRANT EXECUTE ON ALERT.PK_API_DISCHARGE TO INTER_ALERT_V3;
-- CHANGE END: José Silva

-- CHANGED BY: José Silva
-- CHANGE DATE: 14/01/2011 11:22
-- CHANGE REASON: [ALERT-155377] Transactional model
GRANT EXECUTE ON ALERT.PK_API_DISCHARGE TO ALERT_ADTCOD;
-- CHANGE END: José Silva