

  GRANT EXECUTE ON ALERT.PK_ACCESS TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_ACCESS TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_ACCESS TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_ACCESS TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_CHILD TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_CHILD TO ALERT_VIEWER;GRANT EXECUTE ON ALERT.PK_CHILD TO ALERT_VIEWER;

