-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 14/12/2010 10:38
-- CHANGE REASON: [ALERT-143824] 
GRANT EXECUTE ON PK_API_REFERRAL TO INTF_ALERT;
GRANT EXECUTE ON PK_API_REFERRAL TO ALERT_VIEWER;
-- CHANGE END: Joana Barroso