-- CHANGED BY:   Telmo Castro
-- CHANGE DATE:  09-03-2009
-- CHANGE REASON: ALERT-19390
grant execute on pk_alert_exceptions to finger_db;
--END
GRANT EXECUTE ON ALERT.PK_ALERT_EXCEPTIONS TO ALERT_VIEWER;

-- CHANGED BY:   Ariel Machado
-- CHANGE DATE:  09-03-2009
-- CHANGE REASON: ALERT-19390
GRANT EXECUTE ON ALERT.PK_ALERT_EXCEPTIONS TO PIX;
--END