-- CHANGED BY: Luís Maia
-- CHANGE DATE: 03/07/2009 14:19
-- CHANGE REASON: [ALERT-34629] Give grants to ALERT_VIEWER to package pk_ea_logic_tasktimeline
GRANT EXECUTE ON ALERT.PK_EA_LOGIC_TASKTIMELINE TO ALERT_VIEWER;
-- CHANGE END: Luís Maia