

  GRANT EXECUTE ON ALERT.PK_WLPATIENT TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_WLPATIENT TO ALERT_VIEWER;


GRANT EXECUTE ON ALERT.PK_WLPATIENT TO ALERT_VIEWER;

--RicardoNunoAlmeida  
--22-05-2009
--ALERT-29522
GRANT EXECUTE ON ALERT.PK_WLPATIENT TO FINGER_DB;
--END RNA
