

  GRANT EXECUTE ON ALERT.PK_BACKOFFICE TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_BACKOFFICE TO ALERT_VIEWER;


grant execute on pk_backoffice to aol;


GRANT EXECUTE ON ALERT.PK_BACKOFFICE TO ALERT_VIEWER;

grant execute on PK_BACKOFFICE to alert_idp;
