-- CHANGED BY: José Silva
-- CHANGE DATE: 13/09/2010 09:39
-- CHANGE REASON: [ALERT-124177] 
BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON ALERT.PK_DISCHARGE_CORE TO ALERT_VIEWER';
EXCEPTION
WHEN OTHERS THEN
  NULL;
END;
/
-- CHANGE END: José Silva