  GRANT EXECUTE ON ALERT.PK_PERIODIC_OBSERVATION TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_PERIODIC_OBSERVATION TO ALERT_VIEWER;
GRANT EXECUTE ON ALERT.PK_PERIODIC_OBSERVATION TO ALERT_VIEWER;

