-- CHANGED BY: Luís Maia
-- CHANGE DATE: 27/05/2009 08:26
-- CHANGE REASON: [ALERT-29524] Give grants to ALERT_VIEWER to package pk_logic_episode
GRANT EXECUTE ON ALERT.PK_LOGIC_EPISODE TO ALERT_VIEWER;
-- CHANGE END: Luís Maia