-- CHANGED BY: Luís Maia
-- CHANGE DATE: 26/05/2009 15:47
-- CHANGE REASON: [ALERT-29524] Give grants to ALERT_VIEWER to package ts_discharge_schedule
GRANT EXECUTE ON ALERT.TS_DISCHARGE_SCHEDULE TO ALERT_VIEWER;
-- CHANGE END: Luís Maia