-- CHANGED BY: Luis Fernandes
-- CHANGE DATE: 02/05/2019
-- CHANGE REASON: [EMR-15571]
GRANT EXECUTE ON PK_CMT_CONTENT_CORE TO ALERT_PRODUCT_MT;
-- CHANGE END: Luis Fernandes

-- CHANGED BY: Luis Fernandes
-- CHANGE DATE: 10/07/2019
-- CHANGE REASON: [EMR-17762]
grant EXECUTE on PK_CMT_CONTENT_CORE to ALERT_PRODUCT_MT WITH GRANT OPTION;
-- CHANGE END: Luis Fernandes