

  GRANT EXECUTE ON ALERT.PK_SR_VISIT TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SR_VISIT TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_SR_VISIT TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SR_VISIT TO ALERT_VIEWER;


GRANT EXECUTE ON ALERT.PK_SR_VISIT TO ALERT_VIEWER;



-- CHANGED BY: Eduardo Lourenco
-- CHANGE DATE: 13/04/2009 12:31
-- CHANGE REASON: [ALERT-23613] 
GRANT EXECUTE ON ALERT.PK_SR_VISIT TO ALERT_ADTCOD;
-- CHANGE END: Eduardo Lourenco