

  GRANT EXECUTE ON ALERT.PK_API_MANCHESTER TO INTER_ALERT_V2;
  GRANT EXECUTE ON ALERT.PK_API_MANCHESTER TO INTER_ALERT;
  GRANT EXECUTE ON ALERT.PK_API_MANCHESTER TO ALERT_VIEWER;
  
  
  GRANT EXECUTE ON ALERT.PK_API_MANCHESTER TO INTER_ALERT_V2;
  GRANT EXECUTE ON ALERT.PK_API_MANCHESTER TO INTER_ALERT_V3;
  GRANT EXECUTE ON ALERT.PK_API_MANCHESTER TO ALERT_VIEWER;