-- CHANGED BY: Luís Maia
-- CHANGE DATE: 26/05/2009 15:38
-- CHANGE REASON: [ALERT-29524] Give grants to ALERT_VIEWER to package pk_logic_discharge_sched
GRANT EXECUTE ON ALERT.PK_LOGIC_DISCHARGE_SCHED TO ALERT_VIEWER;
-- CHANGE END: Luís Maia