  GRANT EXECUTE ON ALERT.pk_fluids_utils TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.pk_fluids_utils TO LOG;

  GRANT EXECUTE ON ALERT.pk_fluids_utils TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.pk_fluids_utils TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.pk_fluids_utils TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.pk_fluids_utils TO LOG;

  GRANT EXECUTE ON ALERT.pk_fluids_utils TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.pk_fluids_utils TO INTER_ALERT;
