

  GRANT EXECUTE ON ALERT.PK_DATE_UTILS TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_DATE_UTILS TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_DATE_UTILS TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_DATE_UTILS TO ALERT_VIEWER;


GRANT EXECUTE ON ALERT.PK_DATE_UTILS TO ALERT_VIEWER;

