  GRANT EXECUTE ON ALERT.pk_iv_fluids TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.pk_iv_fluids TO LOG;

  GRANT EXECUTE ON ALERT.pk_iv_fluids TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.pk_iv_fluids TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.pk_iv_fluids TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.pk_iv_fluids TO LOG;

  GRANT EXECUTE ON ALERT.pk_iv_fluids TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.pk_iv_fluids TO INTER_ALERT;
GRANT EXECUTE ON ALERT.PK_IV_FLUIDS TO ALERT_VIEWER;

