

  GRANT EXECUTE ON ALERT.PK_SR_SURG_RECORD TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SR_SURG_RECORD TO ALERT_VIEWER;



  GRANT EXECUTE ON ALERT.PK_SR_SURG_RECORD TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SR_SURG_RECORD TO ALERT_VIEWER;


GRANT EXECUTE ON ALERT.PK_SR_SURG_RECORD TO ALERT_VIEWER;

