
  GRANT EXECUTE ON ALERT.PK_PFH_INTERFACE TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_PFH_INTERFACE TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.PK_PFH_INTERFACE TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_PFH_INTERFACE TO INTER_ALERT;


