-- CHANGED BY: Ana Monteiro
-- CHANGE DATE: 30/10/2009 02:35
-- CHANGE REASON: [ALERT-52665] 
GRANT EXECUTE ON ALERT.PK_REF_INTER_CIRCLE TO ALERT_VIEWER;
GRANT EXECUTE ON ALERT.PK_REF_INTER_CIRCLE TO INTF_ALERT;
-- CHANGE END: Ana Monteiro

-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 18/12/2009 14:34
-- CHANGE REASON: [ALERT-63465] 
GRANT EXECUTE ON ALERT.PK_REF_INTER_CIRCLE TO INTF_ALERT;
GRANT EXECUTE ON ALERT.PK_REF_INTER_CIRCLE TO INTER_ALERT_V2;
-- CHANGE END: Joana Barroso