-- CHANGED BY: José Silva
-- CHANGE DATE: 06/06/2011 11:19
-- CHANGE REASON: [ALERT-183624] Pregnancy developments
GRANT SELECT ON ALERT.PAT_PREGNANCY_DIAGNOSIS_HIST TO ALERT_VIEWER;
-- CHANGE END: José Silva