-- CHANGED BY: José Silva
-- CHANGE DATE: 06/06/2011 11:19
-- CHANGE REASON: [ALERT-183624] Pregnancy developments
GRANT SELECT ON ALERT.PAT_PREGNANCY_CODE TO ALERT_VIEWER;
-- CHANGE END: José Silva

-- CHANGED BY: Ana Coelho
-- CHANGE DATE: 22-06-2011
-- CHANGE REASON: [ALERT-185618]
grant select, update, delete on PAT_PREGNANCY_CODE to alert_reset;
-- CHANGE END: Ana Coelho
