-- CHANGED BY: Paulo Teixeira
-- CHANGE DATE: 26/07/2011 15:01
-- CHANGE REASON: [ALERT-188174] 
GRANT SELECT ON ped_area TO alert_viewer;
GRANT ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE ON ped_area TO inter_alert_v2;
-- CHANGE END: Paulo Teixeira