-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 28/03/2017 15:04
-- CHANGE REASON: [ALERT-329656]
BEGIN
    pk_versioning.run('GRANT SELECT ON ALERT.PGS_UPD_PATIENT TO ALERT_INTER WITH GRANT OPTION');
end;
/
-- CHANGE END: Pedro Henriques