-- CHANGED BY:  Mauro Sousa
-- CHANGE DATE: 12/11/2010 10:08
-- CHANGE REASON: [ALERT-101505] 
GRANT EXECUTE ON pk_api_backoffice_default TO ALERT_IDP, ALERT_ADTCOD_CFG;
-- CHANGE END:  Mauro Sousa

-- CHANGED BY:  Rui Gomes
-- CHANGE DATE: 21/05/2013 16:58
-- CHANGE REASON: [ALERT-248672] new obj
grant execute on ALERT.PK_API_BACKOFFICE_DEFAULT to ALERT_INTER with grant option;
-- CHANGE END:  Rui Gomes


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant EXECUTE on ALERT.PK_API_BACKOFFICE_DEFAULT to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
