-- CHANGED BY: orlando.antunes
-- CHANGE DATE: 02/09/2010 18:09
-- CHANGE REASON: [ALERT-121966] 
GRANT EXECUTE ON ALERT.PK_API_OUTP TO ALERT_VIEWER;

GRANT EXECUTE ON ALERT.PK_API_OUTP TO INTF_ALERT;
-- CHANGE END: orlando.antunes