-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 28/09/2017 10:03
-- CHANGE REASON: [ALERT-333217] 
GRANT EXECUTE ON pk_aih_api_ux TO ALERT_VIEWER;
-- CHANGE END: Pedro Henriques

-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 23/10/2017 10:03
-- CHANGE REASON: [ALERT-333721] 
GRANT ALL ON ALERT.PK_AIH_API_UX TO DSV;
GRANT ALL ON ALERT.PK_AIH_API_UX TO ALERT_RO;
-- CHANGE END: Pedro Henriques