-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 01/07/2010 14:55
-- CHANGE REASON: [ALERT-108775] Activity therapist
GRANT EXECUTE ON ALERT.PK_ACTIVITY_THERAPIST TO ALERT_VIEWER;
-- CHANGE END: Sofia Mendes