-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 02/07/2010 13:22
-- CHANGE REASON: [ALERT-108775] Activity therapist
GRANT EXECUTE ON ALERT.PK_ACT_THERAP_CONSTANT TO ALERT_VIEWER;
-- CHANGE END: Sofia Mendes