GRANT EXECUTE ON ALERT.PK_ANNOUNCED_ARRIVAL TO ALERT_VIEWER; 

-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 30/09/2011 14:39
-- CHANGE REASON: [ALERT-197754] Pre-hospital data - Road Traffic Accident (RTA)
--                DB Versioning - New tables
GRANT EXECUTE ON ALERT.PK_ANNOUNCED_ARRIVAL TO ALERT_ADTCOD;
-- CHANGE END: Alexandre Santos