-- CHANGED BY: Ana Matos
-- CHANGE DATE: 12/11/2018 17:01
-- CHANGE REASON: [EMR-8785] 
GRANT EXECUTE ON pk_api_pfh_reset FROM ALERT_APEX_TOOLS;
GRANT EXECUTE ON pk_api_pfh_reset TO ALERT_RESET;
-- CHANGE END: Ana Matos

-- CHANGED BY: Ana Matos
-- CHANGE DATE: 13/11/2018 08:06
-- CHANGE REASON: [EMR-8785] 
GRANT EXECUTE ON pk_api_pfh_reset TO ALERT_APEX_TOOLS;
GRANT EXECUTE ON pk_api_pfh_reset TO ALERT_RESET;
-- CHANGE END: Ana Matos