-- CHANGED BY: Paulo Fonseca
-- CHANGE DATE: 22-Feb-2010
-- CHANGE REASON: ALERT-69792 
GRANT EXECUTE ON ALERT.PK_API_VITAL_SIGN TO INTER_ALERT_V2;
-- CHANGE END: Paulo Fonseca

-- CHANGED BY: Diogo Oliveira
-- CHANGE DATE: 22-Feb-2010
GRANT EXECUTE ON PK_API_VITAL_SIGN TO ALERT_INTER;
-- CHANGE END: Diogo Oliveira