-- CHANGED BY: João Marques
-- CHANGE DATE: 01/07/2010 10:22
-- CHANGE REASON: [ALERT-105793] Added grant to package pk_api_exam
GRANT EXECUTE ON ALERT.PK_API_EXAM TO INTF_ALERT;
-- CHANGE END: João Marques
