-- CHANGED BY: orlando.antunes
-- CHANGE DATE: 18/06/2010 18:29
-- CHANGE REASON: [ALERT-105844] 
grant execute on PK_BACKOFFICE_ADM_SURGERY to ALERT_VIEWER;
-- CHANGE END: orlando.antunes


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant EXECUTE on ALERT.PK_BACKOFFICE_ADM_SURGERY to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
