-- CHANGED BY:  Mauro Sousa
-- CHANGE DATE: 01/02/2011 10:19
-- CHANGE REASON: [ALERT-158696] 
GRANT EXECUTE ON PK_BACKOFFICE_API_UI TO ALERT_VIEWER;
-- CHANGE END:  Mauro Sousa


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant EXECUTE on ALERT.PK_BACKOFFICE_API_UI to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
