


-- CHANGED BY: Adriana Salgueiro
-- CHANGED DATE: 2020-5-6
-- CHANGED REASON: EMR-31318

GRANT EXECUTE ON ALERT.PK_COMPLAINT_PRM TO ALERT_INTER WITH GRANT OPTION;
GRANT EXECUTE ON ALERT.PK_COMPLAINT_PRM TO ALERT_CORE_FUNC;
GRANT EXECUTE ON ALERT.PK_COMPLAINT_PRM TO ALERT_CORE_DATA;
-- CHANGE END: Adriana Salgueiro
