-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 07/05/2012 14:14
-- CHANGE REASON: [ALERT-229223] VERSIONING TRANSACTIONAL MODEL - SCHEMA ALERT - PACKAGES
GRANT EXECUTE ON ALERT.PK_DIAGNOSIS_UX TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos