-- ALERT-53823 - Event History clean process. 
GRANT EXECUTE ON PK_DATE_UTILS TO INTF_ALERT;


-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 23/11/2011 09:58
-- CHANGE REASON: [ALERT-206286 ] 
grant execute on PK_DATE_UTILS to ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 24/11/2011 15:44
-- CHANGE REASON: [ALERT-206850] 
GRANT EXECUTE ON PK_DATE_UTILS TO ALERT_PRODUCT_MT;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Rui Spratley
-- CHANGE DATE: 03/09/2014 10:26
-- CHANGE REASON: [ALERT-294266] 
grant execute on pk_date_utils to alert_tv;
-- CHANGE END: Rui Spratley

-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 09/04/2018 10:26
-- CHANGE REASON: [EMR-2575] 
GRANT EXECUTE ON PK_DATE_UTILS TO ALERT_APEX_TOOLS_CONTENT;
-- CHANGE END: Pedro Henriques