---

-- CHANGED BY: Elisabete Bugalho
-- CHANGE DATE: 18/05/2020 11:56
-- CHANGE REASON: [EMR-31872] - Change functions location
GRANT EXECUTE ON ALERT.PK_DATA_ACCESS TO ALERT_DATA_ACCESS;
-- CHANGE END: Elisabete Bugalho


-- CHANGED BY: Pedro Teixeira
-- CHANGED DATE: 17/06/2020
-- CHANGE REASON: EMR-32985
GRANT EXECUTE ON PK_DATA_ACCESS TO ALERT_PRODUCT_TR;
GRANT EXECUTE ON PK_DATA_ACCESS TO ALERT_PHARMACY_FUNC;
-- CHANGE END: Pedro Teixeira
