-- CHANGED BY: José Brito
-- CHANGE DATE: 28/10/2009 19:28
-- CHANGE REASON: [ALERT-52603] Taking responsibility over episode by multiple professionals
GRANT EXECUTE ON ALERT.PK_HAND_OFF_CORE TO ALERT_VIEWER;
-- CHANGE END: José Brito

-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 17/02/2017 15:50
-- CHANGE REASON: [ALERT-328098]
GRANT EXECUTE ON PK_HAND_OFF_CORE TO ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Henriques