-- CHANGED BY: João Martins
-- CHANGE DATE: 11/12/2009 21:08
-- CHANGE REASON: [ALERT-62132] CPOE Procedures/Dressings/Patient education
GRANT EXECUTE ON ALERT.PK_INTERV_CPOE TO ALERT_VIEWER;
-- CHANGE END: João Martins

-- CHANGED BY: cristina.oliveira
-- CHANGE DATE: 28/05/2014 09:46
-- CHANGE REASON: [ALERT-283445 ] 
GRANT EXECUTE ON pk_interv_cpoe TO ALERT_VIEWER;
-- CHANGE END: cristina.oliveira