-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 24/11/2011 14:42
-- CHANGE REASON: [ALERT-206805] 
GRANT EXECUTE ON PK_LUCENE TO ALERT_PRODUCT_MT;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Pedro Pinheiro
-- CHANGE DATE: 2012-10-26
-- CHANGE REASON: ALERT-243462
grant execute on ALERT.PK_LUCENE to public;
-- CHANGE END: Pedro Pinheiro