


-- CHANGED BY: Adriana Salgueiro
-- CHANGED DATE: 2020-1-20
-- CHANGED REASON: EMR-25501

GRANT EXECUTE ON ALERT.PK_LNK_PROD_INTERV_PRM TO ALERT_INTER WITH GRANT OPTION;
GRANT EXECUTE ON ALERT.PK_LNK_PROD_INTERV_PRM TO ALERT_CORE_FUNC;
GRANT EXECUTE ON ALERT.PK_LNK_PROD_INTERV_PRM TO ALERT_CORE_DATA;
-- CHANGE END: Adriana Salgueiro
