GRANT EXECUTE ON ALERT.PK_MEDS_ASSOCIATION_PRM TO ALERT_INTER WITH GRANT OPTION;
GRANT EXECUTE ON ALERT.PK_MEDS_ASSOCIATION_PRM TO ALERT_CORE_FUNC;
GRANT EXECUTE ON ALERT.PK_MEDS_ASSOCIATION_PRM TO ALERT_CORE_DATA;