-- CHANGED BY: João Martins
-- CHANGE DATE: 11/12/2009 21:08
-- CHANGE REASON: [ALERT-62132] CPOE Procedures/Dressings/Patient education
GRANT EXECUTE ON ALERT.PK_NURSE_ACTIVITY_CPOE TO ALERT_VIEWER;
-- CHANGE END: João Martins