-- CHANGED BY: Ariel Machado
-- CHANGE DATE: 03/11/2014 10:07
-- CHANGE REASON: [ALERT-290969] Nursing Care Plan: NANDA, NIC, NOC - Grants
GRANT EXECUTE ON PK_NNN_UX TO ALERT_VIEWER;
/
-- CHANGE END: Ariel Machado