-- CHANGED BY: Ana Matos
-- CHANGE DATE: 15/06/2016 11:20
-- CHANGE REASON: [ALERT-322211] 
GRANT EXECUTE ON pk_procedures_external_api_db TO ALERT_RESET;
-- CHANGE END: Ana Matos

-- CHANGED BY: Ana Matos
-- CHANGE DATE: 08/03/2017 11:17
-- CHANGE REASON: [ALERT-328947] 
GRANT EXECUTE ON PK_PROCEDURES_EXTERNAL_API_DB TO ALERT_INTER;
-- CHANGE END: Ana Matos

-- CHANGED BY: Ana Matos
-- CHANGE DATE: 08/03/2017 17:00
-- CHANGE REASON: [ALERT-328947] 
GRANT EXECUTE ON PK_PROCEDURES_EXTERNAL_API_DB TO ALERT_INTER;
-- CHANGE END: Ana Matos