GRANT EXECUTE ON ALERT.PK_PRE_HOSP_ACCIDENT TO ALERT_VIEWER; 

-- CHANGED BY: Bruno Martins
-- CHANGED DATE: 2009-11-04
-- CHANGE REASON: ADT-1660
grant execute on PK_PRE_HOSP_ACCIDENT to alert_adtcod;
-- CHANGED END: Bruno Martins