grant execute on PK_PROG_NOTES_OUT to ALERT_RESET;

-- CHANGED BY: Vanessa Barsottelli
-- CHANGE DATE: 17/01/2017 15:36
-- CHANGE REASON: [ALERT-326926] 
GRANT EXECUTE ON ALERT.PK_PROG_NOTES_OUT TO ALERT_INTER;
-- CHANGE END: Vanessa Barsottelli