-- CHANGED BY: Nuno Coelho
-- CHANGE DATE: 21/01/2019 12:18
-- CHANGE REASON: [EMR-8480] [DB] Create Software and profile
GRANT EXECUTE ON PK_PARAMEDICAL_UX TO ALERT_VIEWER;
-- CHANGE END: Nuno Coelho