-- CHANGED BY: José Brito
-- CHANGE DATE: 23/11/2011 16:49
-- CHANGE REASON: [ALERT-206340] Medication integration
GRANT EXECUTE ON ALERT_INTER.PK_RT_MED_PFH TO ALERT_VIEWER;
GRANT EXECUTE ON ALERT_INTER.PK_RT_MED_PFH TO ALERT;
GRANT EXECUTE ON ALERT_INTER.PK_RT_MED_PFH TO DSV;
-- CHANGE END: José Brito