-- CHANGED BY: José Brito
-- CHANGE DATE: 23/11/2011 16:48
-- CHANGE REASON: [ALERT-206340] Medication integration
GRANT EXECUTE ON ALERT_INTER.PK_RT_CORE_ALL TO ALERT_VIEWER;
GRANT EXECUTE ON ALERT_INTER.PK_RT_CORE_ALL TO ALERT;
GRANT EXECUTE ON ALERT_INTER.PK_RT_CORE_ALL TO DSV;
-- CHANGE END: José Brito