GRANT EXECUTE ON pk_supplies_api_db TO ALERT_INTER;

-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 15/06/2018 14:28
-- CHANGE REASON: [EMR-4137] 
GRANT EXECUTE ON PK_SUPPLIES_API_DB TO ALERT_RESET;
-- CHANGE END: Pedro Henriques

GRANT EXECUTE ON pk_supplies_api_db TO ALERT_PHARMACY_FUNC;
/