-- CHANGED BY: Gustavo Serrano
-- CHANGE DATE: 29/09/2009 16:21
-- CHANGE REASON: [ALERT-47078] Consulta de Pré-Operatório
GRANT EXECUTE ON PK_SR_DOCUMENTATION TO ALERT_VIEWER;
-- CHANGE END: Gustavo Serrano

-- CHANGED BY: Gustavo Serrano
-- CHANGE DATE: 08/10/2009 15:50
-- CHANGE REASON: [ALERT-46953] 
GRANT EXECUTE ON PK_SR_DOCUMENTATION TO ALERT_VIEWER;
-- CHANGE END: Gustavo Serrano