-- CHANGED BY: teresa.coutinho
-- CHANGE DATE: 09/04/2012 17:02
-- CHANGE REASON: [ALERT-226633 ] 
GRANT EXECUTE ON ALERT.PK_API_SUPPLIES TO alert_inter;
-- CHANGE END: teresa.coutinho

--ALERT-310431 (begin) vitor.reis
GRANT EXECUTE ON ALERT.PK_UNIT_MEASURE TO alert_product_tr;
--ALERT-310431 (end) vitor.reis


-- CHANGED BY: Pedro Teixeira
-- CHANGE DATE: 10/03/2017
-- CHANGE REASON: ALERT-329111
GRANT EXECUTE ON ALERT.PK_UNIT_MEASURE TO ALERT_PRODUCT_MT;
-- CHANGE END: Pedro Teixeira
