
-- CHANGED BY: Adriana Ramos
-- CHANGE DATE: 12/04/2019
-- CHANGE REASON: [EMR-4779]
GRANT EXECUTE ON PK_UX_EPIS_OUT_ON_PASS TO ALERT_VIEWER;
-- CHANGE END: Adriana Ramos

-- CHANGED BY: Adriana Ramos
-- CHANGE DATE: 12/04/2019
-- CHANGE REASON: [EMR-4779]
GRANT EXECUTE ON PK_UX_EPIS_OUT_ON_PASS TO ALERT_VIEWER;
-- CHANGE END: Adriana Ramos