-- CHANGED BY:  Rui Gomes
-- CHANGE DATE: 21/05/2013 16:56
-- CHANGE REASON: [ALERT-248672] new obj
grant execute on ALERT.PK_VITALSIGN_PRM to ALERT_INTER with grant option;
-- CHANGE END:  Rui Gomes


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant EXECUTE on ALERT.PK_VITALSIGN_PRM to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
