-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 23/12/2010 17:26
-- CHANGE REASON: [ALERT-151848] DB versioning - Packages
GRANT EXECUTE ON PK_WIZARDS_UX TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos