-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant DELETE on ALERT.PN_NOTE_TYPE_GROUP to ALERT_APEX_TOOLS;
grant INSERT on ALERT.PN_NOTE_TYPE_GROUP to ALERT_APEX_TOOLS;
grant SELECT on ALERT.PN_NOTE_TYPE_GROUP to ALERT_APEX_TOOLS;
grant UPDATE on ALERT.PN_NOTE_TYPE_GROUP to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso