-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant DELETE on ALERT.PO_PARAM_MC to ALERT_APEX_TOOLS;
grant INSERT on ALERT.PO_PARAM_MC to ALERT_APEX_TOOLS;
grant SELECT on ALERT.PO_PARAM_MC to ALERT_APEX_TOOLS;
grant UPDATE on ALERT.PO_PARAM_MC to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso