-- CHANGED BY: Paulo Teixeira
-- CHANGE DATE: 06/04/2011 11:41
-- CHANGE REASON: [ALERT-159066] 
GRANT SELECT ON prob_unaware TO alert_viewer;
GRANT ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE ON prob_unaware TO inter_alert_v2;
-- CHANGE END: Paulo Teixeira

-- CHANGED BY: Paulo Teixeira
-- CHANGE DATE: 06/04/2011 11:43
-- CHANGE REASON: [ALERT-159066] 
GRANT SELECT ON pat_prob_unaware TO alert_viewer;
GRANT ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE ON pat_prob_unaware TO inter_alert_v2;
-- CHANGE END: Paulo Teixeira