-- CHANGED BY: Tércio Soares
-- CHANGE DATE: 05/07/2010 10:35
-- CHANGE REASON: [ALERT-109173] 
grant select on PROFESSIONAL_FIELD_DATA to ALERT_VIEWER;
grant select, update, delete on PROFESSIONAL_FIELD_DATA to ALERT_RESET;
-- CHANGE END: Tércio Soares


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.PROFESSIONAL_FIELD_DATA to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
