-- CHANGED BY: Sérgio Santos
-- CHANGE DATE: 08/03/2010 15:50
-- CHANGE REASON: [ALERT-73258] 
grant select on PROFESSIONAL_RECORD to ALERT_VIEWER;
-- CHANGE END: Sérgio Santos


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.PROFESSIONAL_RECORD to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
