-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.PROF_DOC to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso

-- CHANGED BY: Pedro Henriques
-- CHANGED DATE: 2019-10-18
-- CHANGED REASON: ALERT-327486
GRANT ALL ON v_prof_doc TO alert_inter;
-- CHANGE END: Pedro Henriques


-- CHANGED BY: Pedro Henriques
-- CHANGED DATE: 2021-09-17
-- CHANGED REASON: EMR-48477
GRANT ALL ON PROF_DOC TO ALERT_INTER;
-- CHANGE END: Pedro Henriques