GRANT SELECT ON QUESTIONNAIRE_RESPONSE TO INTER_ALERT_V2;


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.QUESTIONNAIRE_RESPONSE to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
