-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 23/12/2009 16:59
-- CHANGE REASON: [ALERT-63465] 
GRANT SELECT ON ALERT.REF_MAP TO INTER_ALERT_V2;
GRANT SELECT ON ALERT.REF_MAP TO INTF_ALERT;
-- CHANGE END: Joana Barroso

-- CHANGED BY: Ana Coelho
-- CHANGE DATE: 7-APR-2011
-- CHANGE REASON: ALERT-171286 
grant select, update, delete on ALERT.REF_EXT_XML_DATA to alert_reset;
-- CHANGE END: Ana Coelho