-- CHANGED BY:  sergio.dias
-- CHANGE DATE: 29/07/2010 15:08
-- CHANGE REASON: [ALERT-116048] 
GRANT SELECT ON ALERT.REHAB_SCH_NEED TO ALERT_VIEWER;
-- CHANGE END:  sergio.dias

-- CHANGED BY:  diogo.oliveira
-- CHANGE DATE: 03/11/2017
GRANT SELECT ON rehab_sch_need TO ALERT_INTER;
-- CHANGE END:  diogo.oliveira