-- CHANGED BY:  sergio.dias
-- CHANGE DATE: 29/07/2010 14:49
-- CHANGE REASON: [ALERT-116048] 
GRANT SELECT ON ALERT.REHAB_INST_SOFT TO ALERT_VIEWER;
-- CHANGE END:  sergio.dias


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.REHAB_INST_SOFT to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
