GRANT ALTER ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2"; 
GRANT DELETE ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT INDEX ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT INSERT ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT SELECT ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT UPDATE ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT REFERENCES ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT ON COMMIT REFRESH ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT QUERY REWRITE ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT DEBUG ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT FLASHBACK ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT SELECT ON "ALERT"."REL_PAT_CLIN_SERV" TO "XDS_CDA";
GRANT SELECT ON "ALERT"."REL_PAT_CLIN_SERV" TO "ALERT_DEFAULT";
GRANT SELECT ON "ALERT"."REL_PAT_CLIN_SERV" TO "ALERT_RESET";


---- ANA COELHO 5/JUN/2009
GRANT ALTER ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2"; 
GRANT DELETE ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT INDEX ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT INSERT ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT SELECT ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT UPDATE ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT REFERENCES ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT ON COMMIT REFRESH ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT QUERY REWRITE ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT DEBUG ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";
GRANT FLASHBACK ON "ALERT"."REL_PAT_CLIN_SERV" TO "INTER_ALERT_V2";