


-- CHANGED BY: Adriana Salgueiro
-- CHANGED DATE: 2020-7-10
-- CHANGED REASON: EMR-34104

GRANT SELECT ON ALERT.SEQ_COMPLAINT_CATEGORY TO ALERT_CORE_CNT WITH GRANT OPTION;
GRANT SELECT ON ALERT.SEQ_COMPLAINT_CATEGORY TO ALERT_CORE_DATA WITH GRANT OPTION;
GRANT SELECT ON ALERT.SEQ_COMPLAINT_CATEGORY TO ALERT_CORE_FUNC WITH GRANT OPTION;
-- CHANGE END: Adriana Salgueiro
