-- CHANGED BY:  NUNO ANTUNES
-- CHANGE DATE: 19/05/2011 16:37
-- CHANGE REASON: [ALERT-180519] API Improvements for TUBA interface
GRANT SELECT ON seq_drug_presc_det TO INTER_ALERT_V2;
-- CHANGE END:  NUNO ANTUNES