-- CHANGED BY: Gustavo Serrano
-- CHANGE DATE: 11/12/2009 17:02
-- CHANGE REASON: [ALERT-61892] CPOE 2nd phase
grant select on SEQ_EPIS_POSITIONING_DET_HIST to ALERT_VIEWER;
-- CHANGE END: Gustavo Serrano