-- CHANGED BY: WEBBER CHIOU
-- CHANGED DATE: 2018/06/06
-- CHANGE REASON: [CEMR-1628] [SUBTASK] [CNT] DB ALERT_CORE_CNT_API.PK_CNT_API_SPECIALITY AND ALERT_CORE_CNT.PK_CNT_SPECIALITY
GRANT SELECT ON ALERT.SEQ_SPECIALITY TO ALERT_CORE_CNT;
-- CHANGE END: WEBBER CHIOU