
  GRANT SELECT ON ALERT.SEQ_PAT_SOC_ATTRIBUTES TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_PAT_SOC_ATTRIBUTES TO LOG;

  GRANT SELECT ON ALERT.SEQ_PAT_SOC_ATTRIBUTES TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_PAT_SOC_ATTRIBUTES TO ICD9;

  GRANT SELECT ON ALERT.SEQ_PAT_SOC_ATTRIBUTES TO INTER_ALERT;


