
  GRANT SELECT ON ALERT.SEQ_SCHEDULE TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE TO INTERFACE_SONHO;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE TO LOG;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE TO ICD9;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE TO INTER_ALERT;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE TO INTERFACE_SINUS;


