
  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY TO LOG;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY TO ICD9;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY TO INTER_ALERT;


