
  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_MEMBER TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_MEMBER TO LOG;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_MEMBER TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_MEMBER TO ICD9;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_MEMBER TO INTER_ALERT;


