
  GRANT SELECT ON ALERT.SEQ_PAT_EXT_SYS TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_PAT_EXT_SYS TO INTERFACE_SONHO;

  GRANT SELECT ON ALERT.SEQ_PAT_EXT_SYS TO LOG;

  GRANT SELECT ON ALERT.SEQ_PAT_EXT_SYS TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_PAT_EXT_SYS TO INTER_ALERT;


