
  GRANT SELECT ON ALERT.SEQ_PAT_CLI_ATTRIBUTES TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_PAT_CLI_ATTRIBUTES TO LOG;

  GRANT SELECT ON ALERT.SEQ_PAT_CLI_ATTRIBUTES TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_PAT_CLI_ATTRIBUTES TO ICD9;

  GRANT SELECT ON ALERT.SEQ_PAT_CLI_ATTRIBUTES TO INTER_ALERT;


