
  GRANT SELECT ON ALERT.SEQ_PAT_HEALTH_PLAN TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_PAT_HEALTH_PLAN TO LOG;

  GRANT SELECT ON ALERT.SEQ_PAT_HEALTH_PLAN TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_PAT_HEALTH_PLAN TO ICD9;

  GRANT SELECT ON ALERT.SEQ_PAT_HEALTH_PLAN TO INTER_ALERT;


