
  GRANT SELECT ON ALERT.SEQ_SCHEDULE_OUTP TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE_OUTP TO LOG;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE_OUTP TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE_OUTP TO ICD9;

  GRANT SELECT ON ALERT.SEQ_SCHEDULE_OUTP TO INTER_ALERT;


