
  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_PROF TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_PROF TO LOG;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_PROF TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_PROF TO ICD9;

  GRANT SELECT ON ALERT.SEQ_PAT_FAMILY_PROF TO INTER_ALERT;


