
  GRANT SELECT ON ALERT.SEQ_EPISODE TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_EPISODE TO INTERFACE_SONHO;

  GRANT SELECT ON ALERT.SEQ_EPISODE TO LOG;

  GRANT SELECT ON ALERT.SEQ_EPISODE TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_EPISODE TO ICD9;

  GRANT SELECT ON ALERT.SEQ_EPISODE TO INTER_ALERT;

  GRANT SELECT ON ALERT.SEQ_EPISODE TO INTERFACE_SINUS;


