
  GRANT SELECT ON ALERT.SEQ_SCH_PROF_OUTP TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_SCH_PROF_OUTP TO LOG;

  GRANT SELECT ON ALERT.SEQ_SCH_PROF_OUTP TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_SCH_PROF_OUTP TO ICD9;

  GRANT SELECT ON ALERT.SEQ_SCH_PROF_OUTP TO INTER_ALERT;


