
  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN_INSTIT TO INTERFACE_SONHO;

  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN_INSTIT TO LOG;

  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN_INSTIT TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN_INSTIT TO INTERFACE_ADMIN;

  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN_INSTIT TO INTER_ALERT;


