
  GRANT SELECT ON ALERT.SEQ_CLIN_RECORD TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_CLIN_RECORD TO LOG;

  GRANT SELECT ON ALERT.SEQ_CLIN_RECORD TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_CLIN_RECORD TO ICD9;

  GRANT SELECT ON ALERT.SEQ_CLIN_RECORD TO INTER_ALERT;


