
  GRANT SELECT ON ALERT.SEQ_PATIENT TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_PATIENT TO INTERFACE_SONHO;

  GRANT SELECT ON ALERT.SEQ_PATIENT TO LOG;

  GRANT SELECT ON ALERT.SEQ_PATIENT TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_PATIENT TO ICD9;

  GRANT SELECT ON ALERT.SEQ_PATIENT TO INTER_ALERT;

  GRANT SELECT ON ALERT.SEQ_PATIENT TO INTERFACE_SINUS;


