
  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN TO INTERFACE_SONHO;

  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN TO LOG;

  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN TO INTER_ALERT;

  GRANT SELECT ON ALERT.SEQ_HEALTH_PLAN TO INTERFACE_SINUS;


