-- CHANGED BY: Rita Lopes
-- CHANGE DATE: 06/12/2011 10:49
-- CHANGE REASON: [ALERT-208518] 
grant select on SR_EPIS_INTERV_HIST to ALERT_VIEWER;
grant select on SR_EPIS_INTERV_HIST to DSV;
-- CHANGE END: Rita Lopes