-- CHANGED BY: Susana Silva
-- CHANGE DATE: 05/03/2010 11:17
-- CHANGE REASON: [ALERT-79485] 
grant select, references on SR_INTERV_GROUP to ALERT_DEFAULT;
-- CHANGE END: Susana Silva


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.SR_INTERV_GROUP to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
