grant select on SR_INTERV_DURATION  to ALERT_VIEWER;


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.SR_INTERV_DURATION to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
