-- CHANGED BY: Susana Silva
-- CHANGE DATE: 05/03/2010 14:30
-- CHANGE REASON: [ALERT-79608] 
grant select, references on SR_POSIT to ALERT_DEFAULT;
-- CHANGE END: Susana Silva


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.SR_POSIT to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
