-- CHANGED BY: Gustavo Serrano
-- CHANGE DATE: 04/12/2009 15:00
-- CHANGE REASON: [ALERT-55090] 
grant select on SR_POSIT_INSTIT_SOFT to ALERT_VIEWER;
-- CHANGE END: Gustavo Serrano


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.SR_POSIT_INSTIT_SOFT to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
