-- CHANGED BY: Rita Lopes
-- CHANGE DATE: 06/12/2011 11:13
-- CHANGE REASON: [ALERT-208518] 
grant select on SR_PROF_TEAM_DET_HIST to ALERT_VIEWER;

grant select on SR_PROF_TEAM_DET_HIST to DSV;
-- CHANGE END: Rita Lopes