-- CHANGED BY: Gustavo Serrano
-- CHANGE DATE: 29/09/2009 16:21
-- CHANGE REASON: [ALERT-47078] Consulta de Pré-Operatório
GRANT SELECT ON SR_SURGERY_VALIDATION TO ALERT_VIEWER;
-- CHANGE END: Gustavo Serrano