-- CHANGED BY: Filipe Silva
-- CHANGE DATE: 02/12/2010 16:47
-- CHANGE REASON: [ALERT-146441] Associate a surgical procedure to supplies
GRANT SELECT ON SR_SUPPLY_COUNT TO ALERT_VIEWER;
-- CHANGE END: Filipe Silva