-- CHANGED BY: mario.mineiro
-- CHANGE DATE: 04/11/2013 16:58
-- CHANGE REASON: [ALERT-268675] grant SUPPLIER_MKT_INST to ALERT_PRODUCT_TR
GRANT SELECT ON SUPPLIER_MKT_INST TO ALERT_PRODUCT_TR;
-- CHANGE END: mario.mineiro