-- CHANGED BY: hugo.madureira
-- CHANGE DATE: 08/08/2014 17:15
-- CHANGE REASON: CODING-2252
GRANT SELECT ON SUPPLY_REASON TO ALERT_CODING_TR;
-- CHANGE END: hugo.madureira

-- CHANGED BY: hugo.madureira
-- CHANGE DATE: 20/08/2014 09:00
-- CHANGE REASON: CODING-2257
GRANT REFERENCES ON SUPPLY_REASON TO ALERT_CODING_TR;
-- CHANGE END: hugo.madureira


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.SUPPLY_REASON to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
