-- CHANGED BY: Susana Silva
-- CHANGE DATE: 26/11/2009 09:01
-- CHANGE REASON: [ALERT-12334] 
grant select, insert, update, delete, references, alter, index on SUPPLY to ALERT_VIEWER;
-- CHANGE END: Susana Silva

-- CHANGED BY: Suelmar Zanetti Castro
-- CHANGE DATE: 11/02/2014 09:50
-- CHANGE REASON: CODING-1823
GRANT SELECT, REFERENCES ON SUPPLY TO ALERT_CODING_TR;
-- CHANGE END: Suelmar Zanetti Castro


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.SUPPLY to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso



-- CHANGED BY: Ana Moita
-- CHANGED DATE: 2018-5-25
-- CHANGED REASON: CEMR-1415

GRANT SELECT, INSERT, UPDATE ON ALERT.SUPPLY TO ALERT_CORE_CNT WITH GRANT OPTION;

-- CHANGE END: Ana Moita
