-- CHANGED BY: Filipe Silva
-- CHANGE DATE: 02/12/2010 16:48
-- CHANGE REASON: [ALERT-146441] Associate a surgical procedure to supplies
GRANT SELECT ON SUPPLY_AREA TO ALERT_VIEWER;
-- CHANGE END: Filipe Silva

-- CHANGED BY:  Rui Gomes
-- CHANGE DATE: 14/11/2011 10:44
-- CHANGE REASON: [ALERT-204517] grants to needed tables
grant references, select  on supply_area to ALERT_DEFAULT;
-- CHANGE END:  Rui Gomes

-- CHANGED BY: hugo.madureira
-- CHANGE DATE: 2014-11-11
-- CHANGE REASON: CODING-2587
GRANT REFERENCES ON ALERT.SUPPLY_AREA TO ALERT_CODING_TR;
-- CHANGE END: hugo.madureira



-- CHANGED BY: Ana Moita
-- CHANGED DATE: 2018-5-25
-- CHANGED REASON: CEMR-1415

GRANT SELECT ON ALERT.SUPPLY_AREA TO ALERT_CORE_CNT WITH GRANT OPTION;
-- CHANGE END: Ana Moita
