-- CHANGED BY: Susana Silva
-- CHANGE DATE: 26/11/2009 10:18
-- CHANGE REASON: [ALERT-12334 ] 
grant select, insert, update, delete, references, alter, index on SUPPLY_LOC_DEFAULT to ALERT_VIEWER;
-- CHANGE END: Susana Silva


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.SUPPLY_LOC_DEFAULT to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso



-- CHANGED BY: Ana Moita
-- CHANGED DATE: 2018-5-25
-- CHANGED REASON: CEMR-1415

GRANT SELECT, INSERT, UPDATE, DELETE ON ALERT.SUPPLY_LOC_DEFAULT TO ALERT_CORE_CNT WITH GRANT OPTION;
-- CHANGE END: Ana Moita
