
  GRANT EXECUTE ON ALERT.PK_DRUG TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_DRUG TO INTER_ALERT_V2;


  GRANT EXECUTE ON ALERT.PK_DRUG TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_DRUG TO INTER_ALERT_V2;


