
  GRANT ALTER ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.UNIT_MEA_SOFT_INST TO ALERT_VIEWER;


