
  GRANT ALTER ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.EPIS_INTERVAL_NOTES TO ALERT_VIEWER;


