
  GRANT SELECT ON ALERT.DISCH_REA_TRANSP_ENT_INST TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DISCH_REA_TRANSP_ENT_INST TO LOG;

  GRANT SELECT ON ALERT.DISCH_REA_TRANSP_ENT_INST TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.DISCH_REA_TRANSP_ENT_INST TO INTER_ALERT;


