
  GRANT ALTER ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.EXAM_CAT TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.EXAM_CAT TO ALERT_VIEWER;


