
  GRANT EXECUTE ON ALERT.PK_PATIENT TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_PATIENT TO ALERT_VIEWER;


  GRANT EXECUTE ON ALERT.PK_PATIENT TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_PATIENT TO ALERT_VIEWER;


