
  GRANT EXECUTE ON ALERT.PK_TYPES TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_TYPES TO SNOMED_CT;

  GRANT EXECUTE ON ALERT.PK_TYPES TO LOG;

  GRANT EXECUTE ON ALERT.PK_TYPES TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_TYPES TO INTER_ALERT;

  GRANT EXECUTE ON ALERT.PK_TYPES TO LOINC;


  GRANT EXECUTE ON ALERT.PK_TYPES TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_TYPES TO SNOMED_CT;

  GRANT EXECUTE ON ALERT.PK_TYPES TO LOG;

  GRANT EXECUTE ON ALERT.PK_TYPES TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_TYPES TO INTER_ALERT;

  GRANT EXECUTE ON ALERT.PK_TYPES TO LOINC;


