
  GRANT EXECUTE ON ALERT.PK_DISCHARGE TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_DISCHARGE TO LOG;

  GRANT EXECUTE ON ALERT.PK_DISCHARGE TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_DISCHARGE TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.PK_DISCHARGE TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_DISCHARGE TO LOG;

  GRANT EXECUTE ON ALERT.PK_DISCHARGE TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_DISCHARGE TO INTER_ALERT;


