
  GRANT SELECT ON ALERT.VIEWER TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.VIEWER TO VIEWER_CONFIG;

  GRANT INSERT ON ALERT.VIEWER TO VIEWER_CONFIG;

  GRANT SELECT ON ALERT.VIEWER TO VIEWER_CONFIG;

  GRANT UPDATE ON ALERT.VIEWER TO VIEWER_CONFIG;


