
  GRANT EXECUTE ON ALERT.PK_EPISODE TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_EPISODE TO INTER_ALERT_V2;


  GRANT EXECUTE ON ALERT.PK_EPISODE TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_EPISODE TO INTER_ALERT_V2;


