

  GRANT DELETE ON ALERT.PROF_PHOTO TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.PROF_PHOTO TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.PROF_PHOTO TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.PROF_PHOTO TO ALERT_VIEWER;


