
  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO LOG;

  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO ICD9;

  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO LOG;

  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO ICD9;

  GRANT EXECUTE ON ALERT.PK_SCHEDULE TO INTER_ALERT;


