
  GRANT EXECUTE ON ALERT.PK_MOVEMENT TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_MOVEMENT TO LOG;

  GRANT EXECUTE ON ALERT.PK_MOVEMENT TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_MOVEMENT TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.PK_MOVEMENT TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_MOVEMENT TO LOG;

  GRANT EXECUTE ON ALERT.PK_MOVEMENT TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_MOVEMENT TO INTER_ALERT;


