
  GRANT EXECUTE ON ALERT.PK_EXAM TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_EXAM TO LOG;

  GRANT EXECUTE ON ALERT.PK_EXAM TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_EXAM TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.PK_EXAM TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_EXAM TO LOG;

  GRANT EXECUTE ON ALERT.PK_EXAM TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_EXAM TO INTER_ALERT;


