
  GRANT SELECT ON ALERT.PRESCRIPTION TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.PRESCRIPTION TO INTERFACE;

  GRANT SELECT ON ALERT.PRESCRIPTION TO INTERFACE;

  GRANT UPDATE ON ALERT.PRESCRIPTION TO INTERFACE;


