
  GRANT EXECUTE ON ALERT.PK_WAITINGLINESONHO TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_WAITINGLINESONHO TO LOG;

  GRANT EXECUTE ON ALERT.PK_WAITINGLINESONHO TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_WAITINGLINESONHO TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.PK_WAITINGLINESONHO TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_WAITINGLINESONHO TO LOG;

  GRANT EXECUTE ON ALERT.PK_WAITINGLINESONHO TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_WAITINGLINESONHO TO INTER_ALERT;


