

  GRANT ALTER ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.DOCUMENTATION TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.DOCUMENTATION TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.DOCUMENTATION TO ALERT_VIEWER;


