
  GRANT EXECUTE ON ALERT.PK_ACCESS TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_ACCESS TO ALERT_VIEWER;


  GRANT EXECUTE ON ALERT.PK_ACCESS TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_ACCESS TO ALERT_VIEWER;


