
  GRANT EXECUTE ON ALERT.PK_ANALYSIS TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_ANALYSIS TO LOG;

  GRANT EXECUTE ON ALERT.PK_ANALYSIS TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_ANALYSIS TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.PK_ANALYSIS TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_ANALYSIS TO LOG;

  GRANT EXECUTE ON ALERT.PK_ANALYSIS TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_ANALYSIS TO INTER_ALERT;


