
  GRANT EXECUTE ON ALERT.PK_VISIT TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_VISIT TO INTERFACE;

  GRANT EXECUTE ON ALERT.PK_VISIT TO LOG;

  GRANT EXECUTE ON ALERT.PK_VISIT TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_VISIT TO ICD9;

  GRANT EXECUTE ON ALERT.PK_VISIT TO INTER_ALERT;


  GRANT EXECUTE ON ALERT.PK_VISIT TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_VISIT TO INTERFACE;

  GRANT EXECUTE ON ALERT.PK_VISIT TO LOG;

  GRANT EXECUTE ON ALERT.PK_VISIT TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_VISIT TO ICD9;

  GRANT EXECUTE ON ALERT.PK_VISIT TO INTER_ALERT;


