
  GRANT EXECUTE ON ALERT.PK_ALERTS TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_ALERTS TO ALERT_VIEWER;


  GRANT EXECUTE ON ALERT.PK_ALERTS TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_ALERTS TO ALERT_VIEWER;


