
  GRANT SELECT ON ALERT.VIEWER_SYNCH_PARAM TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.VIEWER_SYNCH_PARAM TO VIEWER_CONFIG;

  GRANT INSERT ON ALERT.VIEWER_SYNCH_PARAM TO VIEWER_CONFIG;

  GRANT SELECT ON ALERT.VIEWER_SYNCH_PARAM TO VIEWER_CONFIG;

  GRANT UPDATE ON ALERT.VIEWER_SYNCH_PARAM TO VIEWER_CONFIG;


