
  GRANT SELECT ON ALERT.DISCHARGE_DETAIL TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DISCHARGE_DETAIL TO LOG;

  GRANT SELECT ON ALERT.DISCHARGE_DETAIL TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.DISCHARGE_DETAIL TO INTER_ALERT;


