

  GRANT DELETE ON ALERT.SQLN_EXPLAIN_PLAN TO PUBLIC;

  GRANT INSERT ON ALERT.SQLN_EXPLAIN_PLAN TO PUBLIC;

  GRANT SELECT ON ALERT.SQLN_EXPLAIN_PLAN TO PUBLIC;

  GRANT UPDATE ON ALERT.SQLN_EXPLAIN_PLAN TO PUBLIC;

  GRANT SELECT ON ALERT.SQLN_EXPLAIN_PLAN TO ALERT_VIEWER;


