
  GRANT ALTER ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.RECORDS_REVIEW TO ALERT_VIEWER;


