
  GRANT EXECUTE ON ALERT.PK_PRESCRIPTION TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_PRESCRIPTION TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_PRESCRIPTION TO INFARMED;


  GRANT EXECUTE ON ALERT.PK_PRESCRIPTION TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_PRESCRIPTION TO INTER_ALERT_V2;

  GRANT EXECUTE ON ALERT.PK_PRESCRIPTION TO INFARMED;


