
  GRANT ALTER ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.FLOORS_INSTITUTION TO ALERT_VIEWER;


