
  GRANT SELECT ON ALERT.VIEWER_REFRESH TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.VIEWER_REFRESH TO VIEWER_CONFIG;

  GRANT INSERT ON ALERT.VIEWER_REFRESH TO VIEWER_CONFIG;

  GRANT SELECT ON ALERT.VIEWER_REFRESH TO VIEWER_CONFIG;

  GRANT UPDATE ON ALERT.VIEWER_REFRESH TO VIEWER_CONFIG;


