
  GRANT ALTER ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.DISCHARGE_NOTES TO ALERT_VIEWER;


