
  GRANT EXECUTE ON ALERT.PK_SYSCONFIG TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SYSCONFIG TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_SYSCONFIG TO INTERFACE;


  GRANT EXECUTE ON ALERT.PK_SYSCONFIG TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SYSCONFIG TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_SYSCONFIG TO INTERFACE;


