
  GRANT ALTER ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.DIAGRAM TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.DIAGRAM TO ALERT_VIEWER;


