

  GRANT ALTER ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.TRIAGE_BOARD_GROUP TO ALERT_VIEWER;


