
  GRANT ALTER ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.TREATMENT_MANAGEMENT TO ALERT_VIEWER;


