
  GRANT EXECUTE ON ALERT.PK_SR_VISIT TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SR_VISIT TO ALERT_VIEWER;


  GRANT EXECUTE ON ALERT.PK_SR_VISIT TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_SR_VISIT TO ALERT_VIEWER;


