
  GRANT DELETE ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.V_DISCH_REAS_DEST TO ALERT_VIEWER;


