
  GRANT EXECUTE ON ALERT.PK_BARCODE TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_BARCODE TO INTER_ALERT_V2;


  GRANT EXECUTE ON ALERT.PK_BARCODE TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PK_BARCODE TO INTER_ALERT_V2;


