
  GRANT ALTER ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.CRITICAL_CARE TO ALERT_VIEWER;


