
  GRANT ALTER ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.MDM_PROF_CODING TO ALERT_VIEWER;


