
  GRANT EXECUTE ON ALERT.PK_MESSAGE TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_MESSAGE TO ALERT_VIEWER;


  GRANT EXECUTE ON ALERT.PK_MESSAGE TO PUBLIC;

  GRANT EXECUTE ON ALERT.PK_MESSAGE TO ALERT_VIEWER;


