
  GRANT DELETE ON ALERT.SCH_CONSULT_VACANCY TO INTERFACE;

  GRANT INSERT ON ALERT.SCH_CONSULT_VACANCY TO INTERFACE;

  GRANT SELECT ON ALERT.SCH_CONSULT_VACANCY TO INTERFACE;

  GRANT UPDATE ON ALERT.SCH_CONSULT_VACANCY TO INTERFACE;


