
  GRANT ALTER ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT REFERENCES ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.TESTS_REVIEW TO ALERT_VIEWER;


