
  GRANT SELECT ON ALERT.SEQ_SCH_GROUP TO INTERFACE;

  GRANT SELECT ON ALERT.SEQ_SCH_GROUP TO LOG;

  GRANT SELECT ON ALERT.SEQ_SCH_GROUP TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.SEQ_SCH_GROUP TO ICD9;

  GRANT SELECT ON ALERT.SEQ_SCH_GROUP TO INTER_ALERT;


