GRANT SELECT ON ALERT.SYS_ALERT_EVENT TO FINGER_DB;
GRANT INSERT ON ALERT.SYS_ALERT_EVENT TO FINGER_DB;
GRANT UPDATE ON ALERT.SYS_ALERT_EVENT TO FINGER_DB;
grant select, insert, update, delete on ALERT.SYS_ALERT_EVENT to ALERT_IDP;

grant select on ALERT.sys_alert_event to ALERT_INTER with grant option;


-- CHANGED BY: Pedro Henriques
-- CHANGE DATE: 17/02/2017 15:50
-- CHANGE REASON: [ALERT-328098]
GRANT select, insert, update, delete ON SYS_ALERT_EVENT TO ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Henriques