-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 23/11/2011 09:58
-- CHANGE REASON: [ALERT-206286 ]
grant execute on T_ERROR_OUT to ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 24/11/2011 14:42
-- CHANGE REASON: [ALERT-206805]
GRANT EXECUTE ON T_ERROR_OUT TO ALERT_PRODUCT_MT;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Ricardo Pinho
-- CHANGE DATE: 13/12/2001
-- CHANGE REASON: [ALERT-209000]
GRANT EXECUTE ON T_ERROR_OUT TO ALERT_IDP;
-- CHANGE END: Ricardo Pinho

GRANT EXECUTE ON T_ERROR_OUT TO PUBLIC;