
  GRANT SELECT ON ALERT.P1_TASK_DONE TO ALERT_VIEWER;




-- CHANGED BY: Ana Monteiro
-- CHANGE DATE: 08/03/2010 14:06
-- CHANGE REASON: [ALERT-79864] 
GRANT SELECT on P1_TASK_DONE to INTERFACE_P1;
-- CHANGE END: Ana Monteiro