

  GRANT ALTER ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.COMPLAINT TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.COMPLAINT TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.COMPLAINT TO ALERT_VIEWER;


