GRANT SELECT ON TASK_TYPE TO ALERT_VIEWER;


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2014-6-5
-- CHANGED REASON:ALERT-288901
GRANT SELECT ON TASK_TYPE TO ALERT_CORE_DATA WITH GRANT OPTION;
-- CHANGE END: Humberto Cardoso
