

  GRANT ALTER ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.DOC_ELEMENT TO ALERT_VIEWER;


