

  GRANT ALTER ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.DOCUMENT_TYPE TO ALERT_VIEWER;


