-- CHANGED BY: José Silva
-- CHANGE DATE: 11/03/2010 19:09
-- CHANGE REASON: [ALERT-80873] Reason for pending discharge: DB developments
GRANT SELECT ON ALERT.DISCHARGE_REP_NOTES TO ALERT_VIEWER;
GRANT SELECT ON ALERT.DISCHARGE_REP_NOTES TO INTER_ALERT_V2;
GRANT SELECT ON ALERT.DISCHARGE_REP_NOTES TO INTER_ALERT_V3;
-- CHANGE END: José Silva