

  GRANT ALTER ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.ACTION_CRITERIA TO ALERT_VIEWER;


