
  GRANT SELECT ON ALERT.P1_TRACKING TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.P1_TRACKING TO LOG;

  GRANT SELECT ON ALERT.P1_TRACKING TO INTER_ALERT_V2;

  GRANT SELECT ON ALERT.P1_TRACKING TO INTER_ALERT;


