-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 05/01/2010 17:23
-- CHANGE REASON: [ALERT-59019] 
GRANT SELECT ON ALERT.SYS_FUNC_CATEGORY TO ALERT_VIEWER;
-- CHANGE END: Joana Barroso

-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 18/01/2010 15:50
-- CHANGE REASON: [ALERT-67408] 
GRANT SELECT ON ALERT.SYS_FUNC_CATEGORY TO ALERT_VIEWER;
-- CHANGE END: Joana Barroso