-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 23/11/2011 09:58
-- CHANGE REASON: [ALERT-206286 ] 
grant execute on TABLE_T_SEARCH to ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 24/11/2011 12:40
-- CHANGE REASON: [ALERT-206772] 
grant execute on TABLE_T_SEARCH to ALERT_PRODUCT_TR;
grant execute on TABLE_T_SEARCH to ALERT_PRODUCT_MT;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 24/11/2011 18:31
-- CHANGE REASON: [ALERT-206929] 
GRANT EXECUTE ON TABLE_T_SEARCH TO ALERT_INTER;
-- CHANGE END: Pedro Quinteiro