grant select on MI_MED to ALERT_VIEWER;


-- CHANGED BY: Tércio Soares
-- CHANGE DATE: 09/04/2010 11:42
-- CHANGE REASON: [ALERT-87226] 
GRANT REFERENCES ON MI_MED TO alert_default;
-- CHANGE END: Tércio Soares

GRANT SELECT ON MI_MED TO INTF_ALERT;
