-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 03/07/2010 21:39
-- CHANGE REASON: [ALERT-109290] Fluid Balance - Reformulation
GRANT SELECT ON ALERT.EPIS_HIDRICS_LINE TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos