

  GRANT ALTER ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.DIMENSION TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.DIMENSION TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.DIMENSION TO ALERT_VIEWER;


