-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 06/07/2010 21:24
-- CHANGE REASON: [ALERT-109293] DB Versioning - TS_PACKAGES
GRANT SELECT ON ALERT.EPIS_HIDRICS_LINE_HIST TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos