GRANT EXECUTE ON table_table_varchar TO INTF_ALERT; 
-- CHANGED BY: João Marques
-- CHANGE DATE: 09-07-2010
-- CHANGE REASON: ALERT-105793
GRANT EXECUTE ON table_table_varchar TO INTF_ALERT;


-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 23/11/2011 09:58
-- CHANGE REASON: [ALERT-206286 ] 
grant execute on TABLE_TABLE_VARCHAR to ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 24/11/2011 14:42
-- CHANGE REASON: [ALERT-206805] 
GRANT EXECUTE ON TABLE_TABLE_VARCHAR TO ALERT_PRODUCT_MT;
-- CHANGE END: Pedro Quinteiro