-- CHANGED BY: Nuno Ferreira
-- CHANGE DATE: 21/07/2009
-- CHANGE REASON: [ALERT-37072]
BEGIN
    EXECUTE IMMEDIATE 'GRANT SELECT ON CM_CURSOR TO ALERT_VIEWER';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/