

  GRANT ALTER ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.PATIENT TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.PATIENT TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.PATIENT TO ALERT_VIEWER;

grant select on alert.patient to aol;
GRANT SELECT ON ALERT_ADTCOD.PATIENT TO ALERT_AT_VIEWER;