

  GRANT ALTER ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.SYS_ELEMENT_CRIT TO ALERT_VIEWER;


