
  GRANT SELECT ON ALERT.P1_MATCH TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.P1_MATCH TO INTERFACE;

  GRANT INSERT ON ALERT.P1_MATCH TO INTERFACE;

  GRANT SELECT ON ALERT.P1_MATCH TO INTERFACE;

  GRANT UPDATE ON ALERT.P1_MATCH TO INTERFACE;

  GRANT INSERT ON ALERT.P1_MATCH TO ICD9;

  GRANT SELECT ON ALERT.P1_MATCH TO ICD9;

  GRANT UPDATE ON ALERT.P1_MATCH TO ICD9;


