

  GRANT DELETE ON ALERT.VITAL_SIGN_SCALES_ACCESS TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.VITAL_SIGN_SCALES_ACCESS TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.VITAL_SIGN_SCALES_ACCESS TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.VITAL_SIGN_SCALES_ACCESS TO ALERT_VIEWER;
  
  grant update on ALERT.VITAL_SIGN_SCALES_ACCESS to ALERT_VIEWER;