

  GRANT DELETE ON ALERT.PAT_PHOTO TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.PAT_PHOTO TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.PAT_PHOTO TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.PAT_PHOTO TO ALERT_VIEWER;


