-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 23/11/2011 09:58
-- CHANGE REASON: [ALERT-206286 ] 
grant execute on TABLE_INTERVAL to ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Pedro Quinteiro
-- CHANGE DATE: 24/11/2011 14:42
-- CHANGE REASON: [ALERT-206805] 
GRANT EXECUTE ON TABLE_INTERVAL TO ALERT_PRODUCT_MT;
GRANT EXECUTE ON TABLE_INTERVAL TO ALERT_PRODUCT_TR;
-- CHANGE END: Pedro Quinteiro

-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 14/09/2016 10:03
-- CHANGE REASON: [ALERT-324785 ] error in CDA API
GRANT all ON TABLE_INTERVAL TO ALERT_PRODUCT_TR with grant option;
GRANT all ON TABLE_INTERVAL TO ALERT_INTER;
-- CHANGE END: Sofia Mendes