

  GRANT ALTER ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT DELETE ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT INDEX ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT INSERT ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT SELECT ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT UPDATE ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;


  GRANT REFERENCES ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT ON COMMIT REFRESH ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT QUERY REWRITE ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT DEBUG ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;

  GRANT FLASHBACK ON ALERT.DOC_TEMPLATE_DIAGNOSIS TO ALERT_VIEWER;





-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2019-09-10
-- CHANGED REASON: EMR-20122
GRANT SELECT, UPDATE ON doc_template_diagnosis TO alert_core_func WITH GRANT OPTION;
-- CHANGE END: Humberto Cardoso

