

  GRANT SELECT ON ALERT.PROF_INSTITUTION TO ALERT_VIEWER;
  grant all on alert.prof_institution to aol;




-- CHANGED BY: SUSANA SILVA
-- CHANGE DATE: 2009/01/09
-- CHANGE REASON: ALERT-12718
grant select on PROF_INSTITUTION to FINGER_DB;
-- CHANGE END