-- CHANGED BY: Eduardo Lourenco
-- CHANGE DATE: 29/05/2009 19:13
-- CHANGE REASON: [ALERT-10700] New header in the application
GRANT SELECT ON ALERT.HEADER TO ALERT_VIEWER;
-- CHANGE END: Eduardo Lourenco