-- CHANGED BY: Elisabete Bugalho
-- CHANGE DATE: 21/04/2015 16:17
-- CHANGE REASON: [ALERT-31026901] CO-SIGN  - Database model Versioning
GRANT SELECT ON ALERT.TASK_TYPE_ACTIONS TO ALERT_VIEWER;
-- CHANGE END: Elisabete Bugalho