-- CHANGED BY: António Neto
-- CHANGE DATE: 25/02/2011 17:33
-- CHANGE REASON: [ALERT-164703] DDL Reports - H & P reformulation in INPATIENT
GRANT SELECT ON TIMEFR_REP_GRP_SOFT_INST TO ALERT_VIEWER;
-- CHANGE END: António Neto