-- CHANGED BY: António Neto
-- CHANGE DATE: 25/02/2011 17:33
-- CHANGE REASON: [ALERT-164703] DDL Reports - H & P reformulation in INPATIENT
GRANT SELECT ON TIMEFRAME_GROUP TO ALERT_VIEWER;
-- CHANGE END: António Neto