-- CHANGED BY: Susana Silva
-- CHANGE DATE: 05/03/2010 09:25
-- CHANGE REASON: [ALERT-79466] 
grant select on TRANSFER_OPTION to ALERT_DEFAULT;
-- CHANGE END: Susana Silva


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.TRANSFER_OPTION to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
