-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2020-02-04
-- CHANGED REASON: EMR-26320
GRANT SELECT, INSERT, UPDATE ON triage_n_consid TO alert_core_cnt WITH GRANT OPTION;
-- CHANGE END: Humberto Cardoso
