-- CHANGED BY: Alexandre Santos
-- CHANGE DATE: 28/06/2013 15:46
-- CHANGE REASON: [ALERT-260856] Ability to perform triage based on EST (Échelle Suisse de Tri) (ALERT_188926) - VERSIONING DB DDL
GRANT SELECT ON ALERT.TRIAGE_DISC_CONSENT TO ALERT_VIEWER;
-- CHANGE END: Alexandre Santos