-- CHANGED BY: José Silva
-- CHANGE DATE: 03/05/2012 18:24
-- CHANGE REASON: [ALERT-228955] EST simplified triage
GRANT SELECT ON ALERT.TRIAGE_DS_COMPONENT TO ALERT_VIEWER;
-- CHANGE END: José Silva

-- CHANGED BY: José Silva
-- CHANGE DATE: 03/05/2012 18:40
-- CHANGE REASON: [ALERT-228955] EST simplified triage
GRANT SELECT ON ALERT.TRIAGE_DS_COMPONENT TO ALERT_VIEWER;
-- CHANGE END: José Silva