-- CHANGED BY: José Brito
-- CHANGE DATE: 24/01/2010 19:51
-- CHANGE REASON: [ALERT-70160] Triage refactoring
GRANT SELECT ON ALERT.TRIAGE_UNIT_MEA_CONVERSION TO ALERT_VIEWER;
-- CHANGE END: José Brito