

  GRANT EXECUTE ON ALERT.PROFISSIONAL TO ALERT_VIEWER;

  GRANT EXECUTE ON ALERT.PROFISSIONAL TO FINGER_DB;


GRANT EXECUTE ON ALERT.PROFISSIONAL TO ALERT_SYS;

GRANT EXECUTE ON ALERT.PROFISSIONAL TO INTF_ALERT;