-- CHANGED BY: Ana Matos
-- CHANGE DATE: 20/12/2012 17:34
-- CHANGE REASON: [ALERT-247611] 
GRANT SELECT ON v_analysis_sample_type TO ALERT_INTER;
GRANT SELECT ON v_analysis_sample_type TO INTER_ALERT_V2;
-- CHANGE END: Ana Matos