GRANT SELECT ON v_diagnosis TO INTF_ALERT;

-- CHANGED BY: José Silva
-- CHANGE DATE: 23/07/2012 10:51
-- CHANGE REASON: [ALERT-236974] Associate ID_CODIFICATION with diagnoses standards
GRANT SELECT ON ALERT.V_DIAGNOSIS TO ALERT_ADTCOD;
GRANT SELECT ON ALERT.V_DIAGNOSIS TO ALERT_ADTCOD_CFG;
GRANT SELECT ON ALERT.V_DIAGNOSIS TO ALERT_CODING_MT;
GRANT SELECT ON ALERT.V_DIAGNOSIS TO ALERT_CODING_TR;
-- CHANGE END: José Silva