GRANT SELECT ON V_DRUG_PRESCRIPTION_DETAIL TO INTF_ALERT;
GRANT SELECT ON V_DRUG_PRESCRIPTION_DETAIL TO ALERT_ADTCOD;


-- CHANGED BY: Ana Rita Martins
-- CHANGED DATE: 2011-04-21
-- CHANGE REASON: ALERT-174340  
grant select on V_DRUG_PRESCRIPTION_DETAIL to ALERT_INTER;
GRANT SELECT ON V_DRUG_PRESCRIPTION_DETAIL TO ALERT_ADTCOD;
-- CHANGED END: Ana Rita Martins
