-- CHANGED BY: Luís Maia
-- CHANGE DATE: 28/09/2009 15:13
-- CHANGE REASON: [ALERT-46532] Add permissions to user intf_alert.
GRANT SELECT ON V_INSTITUTION_TRANSFER TO INTF_ALERT;
-- CHANGE END: Luís Maia