-- CHANGED BY: Ana Matos
-- CHANGE DATE: 15/02/2016 09:22
-- CHANGE REASON: [ALERT-318583] 
GRANT SELECT ON v_interv_pp_modifiers TO ALERT_INTER;

GRANT SELECT ON v_interv_pp_modifiers TO INTER_ALERT_V2;
-- CHANGE END: Ana Matos