-- CHANGED BY:  Joel Lopes
-- CHANGE DATE: 06/03/2014 09:45
-- CHANGE REASON: [ALERT-278171] 
GRANT SELECT ON V_PAT_PROBLEMS TO ALERT_INTER;
-- CHANGE END:  Joel Lopes

-- CHANGED BY: hugo.madureira
-- CHANGE DATE: 2014-10-29
-- CHANGE REASON: CODING-1878
GRANT SELECT ON V_PAT_PROBLEMS TO ALERT_CODING_TR;
-- CHANGE END: hugo.madureira
