-- CHANGED BY: orlando.antunes
-- CHANGE DATE: 12/01/2011 09:54
-- CHANGE REASON: [ALERT-154804] 
GRANT SELECT ON v_pat_cit TO ALERT_ADTCOD;
GRANT SELECT ON v_pat_cit TO INTF_ALERT;
-- CHANGE END: orlando.antunes

-- CHANGED BY: orlando.antunes
-- CHANGE DATE: 17/01/2011 14:46
-- CHANGE REASON: [ALERT-154804] 
GRANT SELECT ON v_pat_cit TO ALERT_ADTCOD;
GRANT SELECT ON v_pat_cit TO INTF_ALERT;
-- CHANGE END: orlando.antunes