-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 02/12/2010 16:32
-- CHANGE REASON: [ALERT-142288 ] [INPATIENT]: APS/SCH - Data Migration
GRANT SELECT ON V_ROOM_CLINICAL_SERVICES TO intf_alert;
GRANT SELECT ON V_ROOM_CLINICAL_SERVICES TO alert_apsschdlr_tr;
-- CHANGE END: Sofia Mendes