-- CHANGED BY: Paulo Fonseca
-- CHANGE DATE: 05-Feb-2010
-- CHANGE REASON: ALERT-78089
GRANT SELECT ON V_ROOM_TYPE TO intf_alert, inter_alert_v2;
-- CHANGE END: Paulo Fonseca


-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 22/11/2010 15:06
-- CHANGE REASON: [ALERT-142288] [INPATIENT]: APS/SCH - Data Migration
GRANT SELECT ON V_ROOM_TYPE TO alert_apsschdlr_tr;
-- CHANGE END: Sofia Mendes