-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 22/11/2010 15:06
-- CHANGE REASON: [ALERT-142288] [INPATIENT]: APS/SCH - Data Migration
GRANT SELECT ON V_SCHEDULABLE_ROOMS TO intf_alert;
GRANT SELECT ON V_SCHEDULABLE_ROOMS TO alert_apsschdlr_tr;
-- CHANGE END: Sofia Mendes