-- CHANGED BY: Jorge Canossa
-- CHANGE DATE: 07-Dez-2010
-- CHANGE REASON: ALERT-147559
GRANT SELECT ON V_SURGICAL_PROCEDURES TO intf_alert;
GRANT SELECT ON V_SURGICAL_PROCEDURES TO alert_apsschdlr_tr;
-- CHANGE END: Jorge Canossa
