-- CHANGED BY: Rui Spratley
-- CHANGE DATE: 21/03/2009 16:34
-- CHANGE REASON: [ALERT-19860] Interface views
grant select on V_VITAL_SIGN_READ to alert_adtcod, intf_alert;
-- CHANGE END

-- CHANGED BY: Diogo Oliveira
-- CHANGE DATE: 23/10/2017
GRANT SELECT ON V_VITAL_SIGN_READ TO ALERT_INTER; 
-- CHANGE END