-- CHANGED BY: Ariel Machado
-- CHANGE DATE: 03/12/2009 15:09
-- CHANGE REASON: [ALERT-58817] Grants and synonyms to ALERT Views
GRANT SELECT ON ALERT.V_XDS_EVENT_CODE TO INTF_ALERT;
-- CHANGE END: Ariel Machado