-- CHANGED BY: Paulo Teixeira
-- CHANGE DATE: 02/12/2013 09:32
-- CHANGE REASON: [ALERT-270040] 
GRANT DELETE,INSERT,SELECT,UPDATE ON VS_ATTRIBUTE TO alert_config;
GRANT SELECT ON VS_ATTRIBUTE TO alert_viewer;
GRANT ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE ON VS_ATTRIBUTE TO inter_alert_v2;
-- CHANGE END: Paulo Teixeira