-- CHANGED BY: Paulo Teixeira
-- CHANGE DATE: 02/12/2013 09:32
-- CHANGE REASON: [ALERT-270040] 
GRANT DELETE,INSERT,SELECT,UPDATE ON VS_READ_ATTRIBUTE TO alert_config;
GRANT SELECT ON VS_READ_ATTRIBUTE TO alert_viewer;
GRANT ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE ON VS_READ_ATTRIBUTE TO inter_alert_v2;
-- CHANGE END: Paulo Teixeira

-- CHANGED BY: Diogo Oliveira
-- CHANGE DATE: 03/11/2017
GRANT SELECT ON vs_read_attribute TO ALERT_INTER;
-- CHANGE END: Diogo Oliveira