-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 19/04/2010 15:47
-- CHANGE REASON: [ALERT-90193] 
GRANT SELECT ON ALERT.WF_WORKFLOW_MARKET TO ALERT_VIEWER;
-- CHANGE END: Joana Barroso
-- CHANGE END: Joana Barroso