-- CHANGED BY: Paulo Teixeira
-- CHANGE DATE: 25/08/2010 10:41
-- CHANGE REASON: [ALERT-95691] 
GRANT SELECT ON work_type TO alert_viewer;
GRANT ALTER,DEBUG,DELETE,FLASHBACK,INDEX,INSERT,ON COMMIT REFRESH,QUERY REWRITE,REFERENCES,SELECT,UPDATE ON work_type TO inter_alert_v2;
-- CHANGE END: Paulo Teixeira