grant select on WTL_URG_LEVEL  to ALERT_VIEWER;


-- CHANGED BY: Humberto Cardoso
-- CHANGED DATE: 2017-1-03
-- CHANGED REASON: ALERT-327486
grant SELECT on ALERT.WTL_URG_LEVEL to ALERT_APEX_TOOLS;
-- CHANGE END: Humberto Cardoso
