set sqlbl on;

@@child_feed_dev.tab
@@category_sub.tab
@@ch_contents.tab
@@bed_schedule.tab
@@beye_view_screen.tab
@@birds_eye_view.tab
@@board.tab
@@board_group.tab
@@ch_contents_text.tab
@@board_grouping.tab
@@body_part.tab
@@body_part_image.tab
@@bp_clin_serv.tab

@@building.tab
@@category.tab
@@abnormality.tab
@@abnormality_nature.tab
@@action_criteria.tab
@@adverse_exam_allergy.tab
@@adverse_interv_allergy.tab
@@allergy.tab
@@allergy_ext_sys.tab
@@allocation_bed.tab
@@allocation_bed_10042007.tab
@@analy_parm_limit.tab
@@analysis.tab

@@analysis_agp.tab
@@analysis_agp_old.tab
@@analysis_alias.tab
@@analysis_dep_clin_serv.tab
@@analysis_dep_clin_serv_old.tab
@@analysis_desc.tab
@@analysis_ext_sys_delete.tab
@@analysis_group.tab
@@analysis_harvest.tab
@@analysis_instit_soft.tab
@@analysis_loinc.tab
@@analysis_loinc_template.tab
@@analysis_old.tab

@@analysis_param.tab
@@analysis_parameter.tab
@@analysis_param_instit.tab
@@analysis_param_instit_sample.tab
@@analysis_prep_mesg.tab
@@analysis_protocols.tab
@@analysis_protocols_old.tab
@@analysis_req.tab
@@analysis_req_det.tab
@@analysis_req_par.tab
@@analysis_result.tab
@@analysis_result_par.tab
@@analysis_room.tab

@@analysis_unit_measure.tab
@@anesthesia_type.tab
@@bed.tab
@@clinical_service.tab
@@clin_record.tab
@@clin_serv_ext_sys.tab
@@clin_srv_type.tab
@@cli_rec_req.tab
@@cli_rec_req_det.tab
@@cli_rec_req_mov.tab
@@color.tab
@@complaint.tab
@@complaint_diagnosis.tab

@@complaint_template.tab
@@complaint_triage_board.tab
@@complete_history.tab
@@consult_req.tab
@@consult_req_prof.tab
@@contraceptive.tab
@@contra_indic.tab
@@country.tab
@@create$java$lob$table.tab
@@criteria.tab
@@critical_care.tab
@@critical_care_det.tab
@@critical_care_read.tab

@@department.tab
@@dep_clin_serv.tab
@@dep_clin_serv_type.tab
@@dependency.tab
@@dept.tab
@@dept_template.tab
@@diagnosis.tab
@@diagnosis_dep_clin_serv.tab
@@diagram.tab
@@diagram_detail.tab
@@diagram_detail_notes.tab
@@diagram_image.tab
@@diagram_lay_imag.tab

@@diagram_layout.tab
@@diagram_tools.tab
@@diagram_tools_group.tab
@@diet.tab
@@dietary_drug.tab
@@diet_schedule.tab
@@dimension.tab
@@discharge.tab
@@discharge_dest.tab
@@discharge_detail.tab
@@discharge_notes.tab
@@discharge_reason.tab
@@disc_help.tab

@@disch_prep_mesg.tab
@@disch_reas_dest.tab
@@disch_rea_transp_ent_inst.tab
@@discriminator.tab
@@discriminator_help.tab
@@disc_vs_valid.tab
@@district.tab
@@doc_action_criteria.tab
@@doc_area.tab
@@doc_component.tab
@@doc_criteria.tab
@@doc_destination.tab
@@doc_dimension.tab

@@doc_element.tab
@@doc_element_crit.tab
@@doc_element_qualif.tab
@@doc_element_quantif.tab
@@doc_element_rel.tab
@@doc_external.tab
@@doc_image.tab
@@doc_original.tab
@@doc_ori_type.tab
@@doc_qualification.tab
@@doc_quantification.tab
@@doc_template.tab
@@doc_template_diagnosis.tab

@@doc_type.tab
@@doc_type_soft.tab
@@document_area.tab
@@documentation.tab
@@documentation_rel.tab
@@documentation_type.tab
@@document_type.tab
@@drug.tab
@@drug_bck.tab
@@drug_bolus.tab
@@drug_brand.tab
@@drug_dep_clin_serv.tab
@@drug_despachos.tab

@@drug_despachos_soft_inst.tab
@@drug_drip.tab
@@drug_form.tab
@@drug_instit_justification.tab
@@drug_justification.tab
@@drug_pharma.tab
@@drug_pharma_class.tab
@@drug_pharma_class_link.tab
@@drug_pharma_interaction.tab
@@drug_plan.tab
@@drug_presc_det.tab
@@drug_presc_plan.tab
@@drug_prescription.tab

@@drug_protocols.tab
@@drug_req.tab
@@drug_req_det.tab
@@drug_req_supply.tab
@@drug_route.tab
@@drug_take_plan.tab
@@drug_take_time.tab
@@element_rel.tab
@@emb_dep_clin_serv.tab
@@epis_anamnesis.tab
@@epis_attending_notes.tab
@@epis_bartchart.tab
@@epis_bartchart_det.tab

@@epis_body_painting.tab
@@epis_body_painting_det.tab
@@epis_complaint.tab
@@epis_diagnosis.tab
@@epis_diagnosis_hist.tab
@@epis_diagnosis_notes.tab
@@epis_diet.tab
@@epis_documentation.tab
@@epis_documentation_det.tab
@@epis_drug_usage.tab
@@epis_ext_sys.tab
@@epis_health_plan.tab
@@epis_hidrics.tab

@@epis_hidrics_balance.tab
@@epis_hidrics_det.tab
@@epis_info.tab
@@epis_institution.tab
@@epis_interv.tab
@@epis_interval_notes.tab
@@epis_man.tab
@@epis_observation.tab
@@epis_obs_exam.tab
@@epis_obs_photo.tab
@@episode.tab
@@epis_photo.tab
@@epis_positioning.tab

@@epis_positioning_det.tab
@@epis_positioning_plan.tab
@@epis_pregnancy.tab
@@epis_problem.tab
@@epis_prof_rec.tab
@@epis_prof_resp.tab
@@epis_protocols.tab
@@epis_readmission.tab
@@epis_recomend.tab
@@epis_report.tab
@@epis_report_section.tab
@@epis_review_systems.tab
@@epis_task.tab

@@epis_triage.tab
@@epis_type.tab
@@epis_type_room.tab
@@equip_protocols.tab
@@error.tab
@@error_hist.tab
@@estate.tab
@@event.tab
@@event_group.tab
@@event_group_soft_inst.tab
@@event_hist.tab
@@event_most_freq.tab
@@exam.tab

@@exam_cat.tab
@@exam_cat_dcs.tab
@@exam_cat_dcs_bck1.tab
@@exam_cat_dcs_ext_sys.tab
@@exam_dep_clin_serv.tab
@@exam_drug.tab
@@exam_egp.tab
@@exam_ext_sys_delete.tab
@@exam_group.tab
@@exam_prep_mesg.tab
@@exam_protocols.tab
@@exam_req.tab
@@exam_req_det.tab

@@exam_result.tab
@@exam_room.tab
@@external_cause.tab
@@external_sys.tab
@@family_monetary.tab
@@family_relationship.tab
@@family_relationship_relat.tab
@@floors.tab
@@floors_department.tab
@@floors_dep_position.tab
@@floors_institution.tab
@@geo_location.tab
@@ginec_obstet.tab

@@graffar_criteria.tab
@@graffar_crit_value.tab
@@grid_task.tab
@@grid_task_between.tab
@@habit.tab
@@harvest.tab
@@hcn_def_crit.tab
@@health_plan.tab
@@health_plan_instit.tab
@@hemo_protocols.tab
@@hemo_req.tab
@@hemo_req_det.tab
@@hemo_req_supply.tab

@@hemo_type.tab
@@hidrics.tab
@@hidrics_interval.tab
@@hidrics_relation.tab
@@hidrics_type.tab
@@home.tab
@@icnp_axis.tab
@@icnp_classification.tab
@@icnp_compo_clin_serv.tab
@@icnp_compo_dcs.tab
@@icnp_compo_folder.tab
@@icnp_compo_folder_060425.tab
@@icnp_compo_inst.tab

@@icnp_compo_inst_060425.tab
@@icnp_composition.tab
@@icnp_composition_term.tab
@@icnp_composition_060425.tab
@@icnp_dictionary.tab
@@icnp_epis_diag_interv.tab
@@icnp_epis_diag_interv_060425.tab
@@icnp_epis_diagnosis.tab
@@icnp_epis_diagnosis_060425.tab
@@icnp_epis_intervention.tab
@@icnp_epis_intervention_060425.tab
@@icnp_folder.tab
@@icnp_folder_060425.tab

@@icnp_morph.tab
@@icnp_predefined_action.tab
@@icnp_predefined_action_060425.tab
@@icnp_relationship.tab
@@icnp_term.tab
@@icnp_transition_state.tab
@@icnp_transition_state_060426.tab
@@identification_notes.tab
@@implementation.tab
@@import_analysis.tab
@@import_mcdt.tab
@@import_mcdt_migra.tab
@@import_mcdt_20060303.tab

@@import_prof_admin.tab
@@import_prof_med.tab
@@ine_location.tab
@@inf_atc.tab
@@inf_atc_bck.tab
@@inf_atc_lnk.tab
@@inf_atc_lnk_bck.tab
@@inf_atc_lnk_new.tab
@@inf_atc_new.tab
@@inf_cft.tab
@@inf_cft_bck.tab
@@inf_cft_lnk.tab
@@inf_cft_lnk_bck.tab

@@inf_cft_lnk_new.tab
@@inf_cft_new.tab
@@inf_class_disp.tab
@@inf_class_disp_bck.tab
@@inf_class_disp_new.tab
@@inf_class_estup.tab
@@inf_class_estup_bck.tab
@@inf_class_estup_new.tab
@@inf_comerc.tab
@@inf_comerc_bck.tab
@@inf_comerc_new.tab
@@inf_dcipt.tab
@@inf_dcipt_bck.tab

@@inf_dcipt_new.tab
@@inf_diabetes_lnk.tab
@@inf_diabetes_lnk_bck.tab
@@inf_diabetes_lnk_new.tab
@@inf_diploma.tab
@@inf_diploma_bck.tab
@@inf_diploma_new.tab
@@inf_dispo.tab
@@inf_dispo_bck.tab
@@inf_dispo_new.tab
@@inf_emb.tab
@@inf_emb_bck.tab
@@inf_emb_comerc.tab

@@inf_emb_comerc_bck.tab
@@inf_emb_new.tab
@@inf_emb_unit.tab
@@inf_emb_unit_bck.tab
@@inf_emb_unit_new.tab
@@inf_estado_aim.tab
@@inf_estado_aim_bck.tab
@@inf_estado_aim_new.tab
@@inf_form_farm.tab
@@inf_form_farm_bck.tab
@@inf_form_farm_new.tab
@@inf_grupo_hom.tab
@@inf_grupo_hom_bck.tab

@@inf_grupo_hom_new.tab
@@inf_med.tab
@@inf_med_bck.tab
@@inf_med_new.tab
@@inf_patol_dip_lnk.tab
@@inf_patol_dip_lnk_bck.tab
@@inf_patol_dip_lnk_new.tab
@@inf_patol_esp.tab
@@inf_patol_esp_bck.tab
@@inf_patol_esp_lnk.tab
@@inf_patol_esp_lnk_bck.tab
@@inf_patol_esp_lnk_new.tab
@@inf_patol_esp_new.tab

@@inf_preco.tab
@@inf_preco_bck.tab
@@inf_preco_new.tab
@@inf_subst.tab
@@inf_subst_bck.tab
@@inf_subst_lnk.tab
@@inf_subst_lnk_bck.tab
@@inf_subst_lnk_new.tab
@@inf_subst_new.tab
@@inf_tipo_diab_mel.tab
@@inf_tipo_diab_mel_bck.tab
@@inf_tipo_diab_mel_new.tab
@@inf_tipo_preco.tab

@@inf_tipo_preco_bck.tab
@@inf_tipo_preco_new.tab
@@inf_tipo_prod.tab
@@inf_tipo_prod_bck.tab
@@inf_tipo_prod_new.tab
@@inf_titular_aim.tab
@@inf_titular_aim_bck.tab
@@inf_titular_aim_new.tab
@@inf_tratamento.tab
@@inf_tratamento_bck.tab
@@inf_tratamento_new.tab
@@inf_vias_admin.tab
@@inf_vias_admin_bck.tab

@@inf_vias_admin_lnk.tab
@@inf_vias_admin_lnk_bck.tab
@@inf_vias_admin_lnk_new.tab
@@inf_vias_admin_new.tab
@@ingredient.tab
@@inp_error.tab
@@inp_log.tab
@@instit_ext_sys.tab
@@institution.tab
@@interv_dep_clin_serv.tab
@@interv_dep_clin_serv_migra.tab
@@interv_dep_clin_serv_20060303.tab
@@interv_drug.tab

@@intervention.tab
@@interv_ext_sys_delete.tab
@@interv_physiatry_area.tab
@@interv_prep_msg.tab
@@interv_presc_det.tab
@@interv_presc_plan.tab
@@interv_prescription.tab
@@interv_protocols.tab
@@interv_room.tab
@@isencao.tab
@@java$class$md5$table.tab
@@java$options.tab
@@language.tab

@@lixo.tab
@@manchester.tab
@@manipulated.tab
@@manipulated_group.tab
@@manipulated_ingredient.tab
@@match_epis.tab
@@material.tab
@@material_protocols.tab
@@material_req.tab
@@material_req_det.tab
@@material_type.tab
@@matr_dep_clin_serv.tab
@@matr_room.tab

@@matr_scheduled.tab
@@mcdt_req_diagnosis.tab
@@mdm_coding.tab
@@mdm_evaluation.tab
@@mdm_prof_coding.tab
@@monitorization.tab
@@monitorization_vs.tab
@@monitorization_vs_plan.tab
@@movement.tab
@@necessity.tab
@@nurse_activity_req.tab
@@nurse_actv_req_det.tab
@@nurse_discharge.tab

@@nurse_tea_req.tab
@@occupation.tab
@@opinion.tab
@@opinion_prof.tab
@@origin.tab
@@origin_soft.tab
@@outlook.tab
@@param_analysis_ext_sys_delete.tab
@@parameter_analysis.tab
@@pat_allergy.tab
@@pat_allergy_hist.tab
@@pat_blood_group.tab
@@pat_child_clin_rec.tab

@@pat_child_feed_dev.tab
@@pat_cli_attributes.tab
@@pat_cntrceptiv.tab
@@pat_delivery.tab
@@pat_dmgr_hist.tab
@@pat_doc.tab
@@pat_ext_sys.tab
@@pat_family.tab
@@pat_family_disease.tab
@@pat_family_member.tab
@@pat_family_prof.tab
@@pat_fam_soc_hist.tab
@@pat_ginec.tab

@@pat_ginec_obstet.tab
@@pat_graffar_crit.tab
@@pat_habit.tab
@@pat_health_plan.tab
@@pat_history.tab
@@pat_history_hist.tab
@@pat_history_type.tab
@@patient.tab
@@pat_job.tab
@@pat_med_decl.tab
@@pat_medication.tab
@@pat_medication_hist_list.tab
@@pat_medication_list.tab

@@pat_necessity.tab
@@pat_notes.tab
@@pat_permission.tab
@@pat_photo.tab
@@pat_pregnancy.tab
@@pat_pregnancy_risk.tab
@@pat_pregn_fetus.tab
@@pat_pregn_fetus_biom.tab
@@pat_pregn_fetus_det.tab
@@pat_pregn_measure.tab
@@pat_problem.tab
@@pat_problem_hist.tab
@@pat_prob_visit.tab

@@pat_sick_leave.tab
@@pat_soc_attributes.tab
@@pat_tmp_remota.tab
@@pat_vaccine.tab
@@periodic_exam_educ.tab
@@plan_table.tab
@@positioning.tab
@@positioning_type.tab
@@postal_code_pt.tab
@@pregnancy_risk_eval.tab
@@prep_message.tab
@@presc_attention_det.tab
@@presc_pat_problem.tab

@@prescription.tab
@@prescription_number_seq.tab
@@prescription_pharm.tab
@@prescription_pharm_det.tab
@@prescription_print.tab
@@prescription_type.tab
@@prescription_type_access.tab
@@prescription_xml.tab
@@prescription_xml_det.tab
@@prev_episodes_temp.tab
@@prof_access.tab
@@prof_access_bck.tab
@@prof_access_bck1.tab

@@prof_access_bck2.tab
@@prof_access_bck_20070214.tab
@@prof_access_field_func.tab
@@prof_cat.tab
@@prof_dep_clin_serv.tab
@@prof_doc.tab
@@prof_epis_interv.tab
@@professional.tab
@@prof_ext_sys.tab
@@prof_func.tab
@@profile_templ_access.tab
@@profile_templ_access_bck_agn.tab
@@profile_templ_acc_func.tab

@@profile_template.tab
@@profile_template_bck_agn.tab
@@prof_in_out.tab
@@prof_institution.tab
@@prof_photo.tab
@@prof_photo_medicomni.tab
@@prof_preferences.tab
@@prof_profile_template.tab
@@prof_room.tab
@@prof_soft_inst.tab
@@prof_team.tab
@@prof_team_det.tab
@@protoc_diag.tab

@@protocols.tab
@@p1_doc_external.tab
@@p1_doc_external_request.tab
@@p1_documents.tab
@@p1_documents_done.tab
@@p1_external_request.tab
@@p1_ext_req_tracking.tab
@@p1_history.tab
@@p1_prblm_rec_procedure.tab
@@p1_problem.tab
@@p1_problem_dep_clin_serv.tab
@@p1_recomended_procedure.tab
@@rb_interv_icd.tab

@@rb_profile_templ_access.tab
@@rb_sys_button_prop.tab
@@rb_sys_button_prop2.tab
@@rb_sys_shortcut.tab
@@recm.tab
@@records_review.tab
@@records_review_read.tab
@@religion.tab
@@rep_destination.tab
@@reports.tab
@@reports_group.tab
@@rep_prof_exception.tab
@@rep_profile_template.tab

@@rep_profile_template_det.tab
@@rep_prof_templ_access.tab
@@rep_prof_template.tab
@@rep_screen.tab
@@rep_section.tab
@@rep_section_det.tab
@@result_status.tab
@@room.tab
@@room_dep_clin_serv.tab
@@room_dep_position.tab
@@room_ext_sys.tab
@@room_scheduled.tab
@@rotation_interval.tab

@@sample_recipient.tab
@@sample_text.tab
@@sample_text_bck.tab
@@sample_text_freq.tab
@@sample_text_freq_bck.tab
@@sample_text_prof.tab
@@sample_text_type.tab
@@sample_text_type_cat.tab
@@sample_type.tab
@@scales.tab
@@scales_class.tab
@@scales_doc_value.tab
@@sch_action.tab

@@sch_cancel_reason.tab
@@sch_cancel_reason_inst.tab
@@sch_consult_vacancy.tab
@@sch_consult_vacancy_temp.tab
@@sch_default_consult_vacancy.tab
@@schedule.tab
@@schedule_alter.tab
@@schedule_outp.tab
@@schedule_sr.tab
@@schedule_sr_det.tab
@@sch_event.tab
@@sch_event_dcs.tab
@@sch_event_inst.tab

@@sch_group.tab
@@sch_log.tab
@@scholarship.tab
@@school.tab
@@sch_permission.tab
@@sch_permission_temp.tab
@@sch_prof_outp.tab
@@sch_resource.tab
@@sch_schedule_request.tab
@@sch_service.tab
@@sch_service_dcs.tab
@@screen_template.tab
@@serv_sched_access.tab

@@slot.tab
@@snomed_concepts.tab
@@snomed_descriptions.tab
@@snomed_relationships.tab
@@social_class.tab
@@social_diagnosis.tab
@@social_epis_diag.tab
@@social_epis_discharge.tab
@@social_epis_interv.tab
@@social_episode.tab
@@social_epis_request.tab
@@social_epis_situation.tab
@@social_epis_solution.tab

@@social_intervention.tab
@@soft_inst_impl.tab
@@soft_inst_services.tab
@@soft_lang.tab
@@software.tab
@@software_dept.tab
@@software_institution.tab
@@speciality.tab
@@spec_sys_appar.tab
@@sqln_explain_plan.tab
@@sr_base_diag.tab
@@sr_cancel_reason.tab
@@sr_chklist.tab

@@sr_chklist_det.tab
@@sr_chklist_manual.tab
@@sr_doc_element.tab
@@sr_doc_element_crit.tab
@@sr_epis_interv.tab
@@sr_epis_interv_desc.tab
@@sr_equip.tab
@@sr_equip_kit.tab
@@sr_equip_period.tab
@@sr_eval_det.tab
@@sr_eval_notes.tab
@@sr_eval_rule.tab
@@sr_eval_summ.tab

@@sr_eval_type.tab
@@sr_evaluation.tab
@@sr_eval_visit.tab
@@sr_interv_dep_clin_serv.tab
@@sr_interv_desc.tab
@@sr_intervention.tab
@@sr_interv_group.tab
@@sr_interv_group_det.tab
@@sr_nurse_rec.tab
@@sr_pat_status.tab
@@sr_pat_status_notes.tab
@@sr_pat_status_period.tab
@@sr_pos_eval_det.tab

@@sr_pos_eval_visit.tab
@@sr_posit.tab
@@sr_posit_req.tab
@@sr_pre_anest.tab
@@sr_pre_anest_det.tab
@@sr_pre_eval.tab
@@sr_pre_eval_det.tab
@@sr_pre_eval_visit.tab
@@sr_prof_recov_schd.tab
@@sr_prof_shift.tab
@@sr_prof_team_det.tab
@@sr_receive.tab
@@sr_receive_manual.tab

@@sr_receive_proc.tab
@@sr_receive_proc_det.tab
@@sr_receive_proc_notes.tab
@@sr_reserv_req.tab
@@sr_room_status.tab
@@sr_surgery_rec_det.tab
@@sr_surgery_record.tab
@@sr_surgery_time.tab
@@sr_surgery_time_det.tab
@@sr_surg_period.tab
@@sr_surg_prot_det.tab
@@sr_surg_protocol.tab
@@sr_surg_prot_task.tab

@@sr_surg_prot_task_det.tab
@@sr_surg_task.tab
@@sys_alert.tab
@@sys_alert_det.tab
@@sys_alert_prof.tab
@@sys_alert_profile.tab
@@sys_alert_software.tab
@@sys_alert_type.tab
@@sys_appar_organ.tab
@@sys_application_area.tab
@@sys_application_type.tab
@@sys_btn_crit.tab
@@sys_btn_sbg.tab

@@sys_button.tab
@@sys_button_group.tab
@@sys_button_prop.tab
@@sys_config.tab
@@sys_documentation.tab
@@sys_domain.tab
@@sys_element.tab
@@sys_element_crit.tab
@@sys_entrance.tab
@@sys_error.tab
@@sys_field.tab
@@sys_functionality.tab
@@sys_login.tab

@@sys_message.tab
@@sys_message_bck.tab
@@sys_request.tab
@@sys_screen_area.tab
@@sys_screen_template.tab
@@sys_session.tab
@@sys_shortcut.tab
@@system_apparati.tab
@@system_organ.tab
@@sys_time_event_group.tab
@@sys_toolbar.tab
@@sys_vital_sign.tab
@@temp_portaria.tab

@@tests_review.tab
@@time.tab
@@time_event_group.tab
@@time_group.tab
@@time_group_soft_inst.tab
@@time_unit.tab
@@toad_plan_sql.tab
@@toad_plan_table.tab
@@translation.tab
@@translation_bck_20061214.tab
@@transp_ent_inst.tab
@@transp_entity.tab
@@transportation.tab

@@transport_type.tab
@@transp_req.tab
@@transp_req_group.tab
@@treatment_management.tab
@@triage.tab
@@triage_board.tab
@@triage_board_group.tab
@@triage_board_grouping.tab
@@triage_color.tab
@@triage_considerations.tab
@@triage_disc_help.tab
@@triage_discriminator.tab
@@triage_discriminator_help.tab

@@triage_disc_vs_valid.tab
@@triage_n_consid.tab
@@triage_nurse.tab
@@triage_type.tab
@@triage_units.tab
@@triage_white_reason.tab
@@unit_mea_soft_inst.tab
@@unit_measure.tab
@@unit_measure_convert.tab
@@unit_measure_type.tab
@@vaccine.tab
@@vaccine_dep_clin_serv.tab
@@vaccine_desc.tab

@@vaccine_det.tab
@@vaccine_dose.tab
@@vaccine_dose_admin.tab
@@vaccine_presc_det.tab
@@vaccine_presc_plan.tab
@@vaccine_prescription.tab
@@vaccine_status.tab
@@vbz$object_stats.tab
@@viewer.tab
@@viewer_refresh.tab
@@viewer_synch_param.tab
@@viewer_synchronize.tab
@@visit.tab

@@vital_sign.tab
@@vital_sign_desc.tab
@@vital_sign_notes.tab
@@vital_sign_read.tab
@@vital_sign_read_error.tab
@@vital_sign_relation.tab
@@vital_sign_unit_measure.tab
@@vs_clin_serv.tab
@@vs_soft_inst.tab
@@white_reason.tab
@@wl_call_queue.tab
@@wl_demo.tab
@@wl_demo_bck.tab

@@wl_machine.tab
@@wl_mach_prof_queue.tab
@@wl_msg_queue.tab
@@wl_patient_sonho.tab
@@wl_patient_sonho_imp.tab
@@wl_patient_sonho_transfered.tab
@@wl_prof_room.tab
@@wl_queue.tab
@@wl_status.tab
@@wl_topics.tab
@@wl_waiting_line.tab
@@wl_waiting_line_0104.tab
@@wl_waiting_room.tab

@@wound_charac.tab
@@wound_eval_charac.tab
@@wound_evaluation.tab
@@wound_treat.tab
@@wound_type.tab
@@dr$d_idx$i.tab
@@dr$d_idx$r.tab
@@dr$snomed_idx$i.tab
@@dr$snomed_idx$r.tab
@@dr$snomed_idx$n.tab
@@dr$snomed_idx$k.tab
@@dr$d_idx$k.tab
@@dr$d_idx$n.tab

@@tmp_nurse_summary.tab
@@sch_mult_reschedule_aux.tab
@@quest_temp_explain.tab
@@quest_sl_temp_explain1.tab

