-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 05/01/2010 17:23
-- CHANGE REASON: [ALERT-59019] 
ALTER INDEX SFCY_CAT_FK_IDX REBUILD TABLESPACE INDEX_M;
ALTER INDEX SFCY_SFY_FK_IDX REBUILD TABLESPACE INDEX_M;
ALTER INDEX SFCY_PK REBUILD TABLESPACE INDEX_M;
-- CHANGE END: Joana Barroso

-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 18/01/2010 15:49
-- CHANGE REASON: [ALERT-67408] 
ALTER INDEX SFCY_CAT_FK_IDX REBUILD TABLESPACE INDEX_M;
ALTER INDEX SFCY_SFY_FK_IDX REBUILD TABLESPACE INDEX_M;
ALTER INDEX SFCY_PK REBUILD TABLESPACE INDEX_M;
-- CHANGE END: Joana Barroso

-- CHANGED BY: Sérgio Cunha
-- CHANGE DATE: 05/03/2010 15:09
-- CHANGE REASON: [ALERT-78201] 
ALTER INDEX ORD_TP_SFT_INST_PK REBUILD TABLESPACE INDEX_M;
ALTER INDEX ORD_TP_SFT_INST_INST_FK_IDX REBUILD TABLESPACE INDEX_M;
ALTER INDEX ORD_TP_SFT_INST_ORD_TP_FK_IDX REBUILD TABLESPACE INDEX_M;
ALTER INDEX ORD_TP_SFT_INST_SFT_FK_IDX REBUILD TABLESPACE INDEX_M;
-- CHANGE END: Sérgio Cunha

-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 17/11/2011 11:31
-- CHANGE REASON: Partial scores: Lack of tablespaces in some indexes
ALTER INDEX SGR_DOC_FK_IDX rebuild tablespace INDEX_S;

ALTER INDEX SC_SF_FK_IDX rebuild tablespace INDEX_S;

ALTER INDEX ESS_PAT_FK_IDX rebuild tablespace INDEX_L;

ALTER INDEX ESSH_PAT_FK_IDX rebuild tablespace INDEX_L;
-- CHANGE END: Sofia Mendes

-- CHANGED BY: Sofia Mendes
-- CHANGE DATE: 17/11/2011 12:39
-- CHANGE REASON: [ALERT-205280 ] Partial scores: Lack of tablespaces in some indexes
ALTER INDEX SGR_DOC_FK_IDX rebuild tablespace INDEX_S;

ALTER INDEX SC_SF_FK_IDX rebuild tablespace INDEX_S;

ALTER INDEX ESS_PAT_FK_IDX rebuild tablespace INDEX_L;

ALTER INDEX ESSH_PAT_FK_IDX rebuild tablespace INDEX_L;
-- CHANGE END: Sofia Mendes