-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 05/01/2010 17:23
-- CHANGE REASON: [ALERT-59019] 
ALTER TABLE SYS_FUNC_CATEGORY MOVE TABLESPACE TABLE_M;
ALTER TABLE REF_MAP MOVE TABLESPACE TABLE_L;
-- CHANGE END: Joana Barroso

-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 18/01/2010 15:50
-- CHANGE REASON: [ALERT-67408] 
ALTER TABLE SYS_FUNC_CATEGORY MOVE TABLESPACE TABLE_M;
ALTER TABLE REF_MAP MOVE TABLESPACE TABLE_L;
-- CHANGE END: Joana Barroso

-- CHANGED BY: Sérgio Cunha
-- CHANGE DATE: 05/03/2010 15:09
-- CHANGE REASON: [ALERT-78201] 
ALTER TABLE ORDER_TYPE_SOFT_INST MOVE TABLESPACE TABLE_M;
-- CHANGE END: Sérgio Cunha

-- CHANGED BY: Joana Barroso
-- CHANGE DATE: 25/01/2011 16:52
-- CHANGE REASON: [ALERT-157333] 
ALTER TABLE REF_SPEC_INSTITUTION MOVE TABLESPACE TABLE_S;
ALTER TABLE REF_SPEC_MARKET MOVE TABLESPACE TABLE_S;
-- CHANGE END: Joana Barroso