/*-- Last Change Revision: $Rev: 2029136 $*/
/*-- Last Change by: $Author: mario.fernandes $*/
/*-- Date of last change: $Date: 2022-08-02 18:49:58 +0100 (ter, 02 ago 2022) $*/
CREATE OR REPLACE PACKAGE TS_EPIS_DIAG_TUMORS_HIST
/*
| Generated by or retrieved from QCGU - DO NOT MODIFY!
| QCGU - "Get it right, do it fast" - www.ToadWorld.com
| QCGU Universal ID: {1BD37A66-EA60-4927-9A64-F6DD89237236}
| Created On: Março 14, 2012 14:9:22
| Created By: ALERT
*/
IS

  -- Collection of %ROWTYPE records based on "EPIS_DIAG_TUMORS_HIST"
     TYPE EPIS_DIAG_TUMORS_HIST_tc IS TABLE OF EPIS_DIAG_TUMORS_HIST%ROWTYPE INDEX BY BINARY_INTEGER;
     TYPE epis_diag_tumors_hist_ntt IS TABLE OF EPIS_DIAG_TUMORS_HIST%ROWTYPE;
     TYPE epis_diag_tumors_hist_vat IS VARRAY(100) OF EPIS_DIAG_TUMORS_HIST%ROWTYPE;

  -- Same type structure, with a static name.
     TYPE aat IS TABLE OF EPIS_DIAG_TUMORS_HIST%ROWTYPE INDEX BY BINARY_INTEGER;
     TYPE ntt IS TABLE OF EPIS_DIAG_TUMORS_HIST%ROWTYPE;
     TYPE vat IS VARRAY(100) OF EPIS_DIAG_TUMORS_HIST%ROWTYPE;

   -- Column Collection based on column "ID_EPIS_DIAGNOSIS_HIST"
   TYPE ID_EPIS_DIAGNOSIS_HIST_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_EPIS_DIAGNOSIS"
   TYPE ID_EPIS_DIAGNOSIS_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "TUMOR_NUM"
   TYPE TUMOR_NUM_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_TOPOGRAPHY"
   TYPE ID_TOPOGRAPHY_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_TOPOG_INST_OWNER"
   TYPE ID_TOPOG_INST_OWNER_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_LATERALITY"
   TYPE ID_LATERALITY_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_LAT_INST_OWNER"
   TYPE ID_LAT_INST_OWNER_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_MORPHOLOGY"
   TYPE ID_MORPHOLOGY_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_MORPH_INST_OWNER"
   TYPE ID_MORPH_INST_OWNER_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_BEHAVIOR"
   TYPE ID_BEHAVIOR_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_BEHAV_INST_OWNER"
   TYPE ID_BEHAV_INST_OWNER_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_HISTOLOGICAL_GRADE"
   TYPE ID_HISTOLOGICAL_GRADE_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_HGRADE_INST_OWNER"
   TYPE ID_HGRADE_INST_OWNER_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_OTHER_GRADING_SYS"
   TYPE ID_OTHER_GRADING_SYS_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_OGRADSYS_INST_OWNER"
   TYPE ID_OGRADSYS_INST_OWNER_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "FLG_UNKNOWN_DIMENSION"
   TYPE FLG_UNKNOWN_DIMENSION_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "NUM_DIMENSION"
   TYPE NUM_DIMENSION_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "DESC_DIMENSION"
   TYPE DESC_DIMENSION_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ADDITIONAL_PATHOL_INFO"
   TYPE ADDITIONAL_PATHOL_INFO_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "DT_EPIS_DIAGNOSIS_TUMORS"
   TYPE DT_EPIS_DIAGNOSIS_TUMORS_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_USER"
   TYPE CREATE_USER_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_TIME"
   TYPE CREATE_TIME_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_INSTITUTION"
   TYPE CREATE_INSTITUTION_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_USER"
   TYPE UPDATE_USER_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_TIME"
   TYPE UPDATE_TIME_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_INSTITUTION"
   TYPE UPDATE_INSTITUTION_cc IS TABLE OF EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE INDEX BY BINARY_INTEGER;

   -- Insert one row, providing primary key if present
   PROCEDURE ins (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE,
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE,
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE
      ,
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE DEFAULT NULL,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE DEFAULT NULL,
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE DEFAULT NULL,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE DEFAULT NULL,
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE DEFAULT NULL,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE DEFAULT NULL,
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE DEFAULT NULL,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE DEFAULT NULL,
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE DEFAULT NULL,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE DEFAULT NULL,
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE DEFAULT NULL,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE DEFAULT NULL,
      flg_unknown_dimension_in IN EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE DEFAULT NULL,
      num_dimension_in IN EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE DEFAULT NULL,
      desc_dimension_in IN EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE DEFAULT NULL,
      additional_pathol_info_in IN EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE DEFAULT NULL,
      dt_epis_diagnosis_tumors_in IN EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE DEFAULT NULL,
      create_user_in IN EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE DEFAULT NULL
      -- Pass false if you want errors to propagate out unhandled
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   PROCEDURE ins (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE,
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE,
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE
      ,
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE DEFAULT NULL,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE DEFAULT NULL,
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE DEFAULT NULL,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE DEFAULT NULL,
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE DEFAULT NULL,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE DEFAULT NULL,
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE DEFAULT NULL,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE DEFAULT NULL,
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE DEFAULT NULL,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE DEFAULT NULL,
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE DEFAULT NULL,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE DEFAULT NULL,
      flg_unknown_dimension_in IN EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE DEFAULT NULL,
      num_dimension_in IN EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE DEFAULT NULL,
      desc_dimension_in IN EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE DEFAULT NULL,
      additional_pathol_info_in IN EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE DEFAULT NULL,
      dt_epis_diagnosis_tumors_in IN EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE DEFAULT NULL,
      create_user_in IN EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE DEFAULT NULL
      -- Pass false if you want errors to propagate out unhandled
     ,handle_error_in IN BOOLEAN := TRUE
      );


   -- Insert a row based on a record.
   PROCEDURE ins (
      rec_in IN EPIS_DIAG_TUMORS_HIST%ROWTYPE
     ,sequence_in IN VARCHAR2 := NULL
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE ins (
      rec_in IN EPIS_DIAG_TUMORS_HIST%ROWTYPE
     ,sequence_in IN VARCHAR2 := NULL
     ,handle_error_in IN BOOLEAN := TRUE
   );

   -- Insert a collection of rows using FORALL; all primary key values
   -- must have already been generated, or are handled in triggers.
   PROCEDURE ins (
      rows_in IN EPIS_DIAG_TUMORS_HIST_tc
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE ins (
      rows_in IN EPIS_DIAG_TUMORS_HIST_tc
     ,handle_error_in IN BOOLEAN := TRUE
   );

   -- Update any/all columns by primary key. If you pass NULL, then
   -- the current column value is set to itself. If you need a more
   -- selected UPDATE then use one of the onecol procedures below.

  PROCEDURE upd (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE,
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE,
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE,
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE DEFAULT NULL,
      ID_TOPOGRAPHY_nin IN BOOLEAN := TRUE,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE DEFAULT NULL,
      ID_TOPOG_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE DEFAULT NULL,
      ID_LATERALITY_nin IN BOOLEAN := TRUE,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE DEFAULT NULL,
      ID_LAT_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE DEFAULT NULL,
      ID_MORPHOLOGY_nin IN BOOLEAN := TRUE,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE DEFAULT NULL,
      ID_MORPH_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE DEFAULT NULL,
      ID_BEHAVIOR_nin IN BOOLEAN := TRUE,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE DEFAULT NULL,
      ID_BEHAV_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE DEFAULT NULL,
      ID_HISTOLOGICAL_GRADE_nin IN BOOLEAN := TRUE,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE DEFAULT NULL,
      ID_HGRADE_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE DEFAULT NULL,
      ID_OTHER_GRADING_SYS_nin IN BOOLEAN := TRUE,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE DEFAULT NULL,
      ID_OGRADSYS_INST_OWNER_nin IN BOOLEAN := TRUE,
      flg_unknown_dimension_in IN EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE DEFAULT NULL,
      FLG_UNKNOWN_DIMENSION_nin IN BOOLEAN := TRUE,
      num_dimension_in IN EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE DEFAULT NULL,
      NUM_DIMENSION_nin IN BOOLEAN := TRUE,
      desc_dimension_in IN EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE DEFAULT NULL,
      DESC_DIMENSION_nin IN BOOLEAN := TRUE,
      additional_pathol_info_in IN EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE DEFAULT NULL,
      ADDITIONAL_PATHOL_INFO_nin IN BOOLEAN := TRUE,
      dt_epis_diagnosis_tumors_in IN EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE DEFAULT NULL,
      DT_EPIS_DIAGNOSIS_TUMORS_nin IN BOOLEAN := TRUE,
      create_user_in IN EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );


       PROCEDURE upd (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE,
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE,
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE,
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE DEFAULT NULL,
      ID_TOPOGRAPHY_nin IN BOOLEAN := TRUE,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE DEFAULT NULL,
      ID_TOPOG_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE DEFAULT NULL,
      ID_LATERALITY_nin IN BOOLEAN := TRUE,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE DEFAULT NULL,
      ID_LAT_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE DEFAULT NULL,
      ID_MORPHOLOGY_nin IN BOOLEAN := TRUE,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE DEFAULT NULL,
      ID_MORPH_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE DEFAULT NULL,
      ID_BEHAVIOR_nin IN BOOLEAN := TRUE,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE DEFAULT NULL,
      ID_BEHAV_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE DEFAULT NULL,
      ID_HISTOLOGICAL_GRADE_nin IN BOOLEAN := TRUE,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE DEFAULT NULL,
      ID_HGRADE_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE DEFAULT NULL,
      ID_OTHER_GRADING_SYS_nin IN BOOLEAN := TRUE,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE DEFAULT NULL,
      ID_OGRADSYS_INST_OWNER_nin IN BOOLEAN := TRUE,
      flg_unknown_dimension_in IN EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE DEFAULT NULL,
      FLG_UNKNOWN_DIMENSION_nin IN BOOLEAN := TRUE,
      num_dimension_in IN EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE DEFAULT NULL,
      NUM_DIMENSION_nin IN BOOLEAN := TRUE,
      desc_dimension_in IN EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE DEFAULT NULL,
      DESC_DIMENSION_nin IN BOOLEAN := TRUE,
      additional_pathol_info_in IN EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE DEFAULT NULL,
      ADDITIONAL_PATHOL_INFO_nin IN BOOLEAN := TRUE,
      dt_epis_diagnosis_tumors_in IN EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE DEFAULT NULL,
      DT_EPIS_DIAGNOSIS_TUMORS_nin IN BOOLEAN := TRUE,
      create_user_in IN EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
     handle_error_in IN BOOLEAN := TRUE
      );



      PROCEDURE upd (
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE DEFAULT NULL,
      ID_TOPOGRAPHY_nin IN BOOLEAN := TRUE,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE DEFAULT NULL,
      ID_TOPOG_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE DEFAULT NULL,
      ID_LATERALITY_nin IN BOOLEAN := TRUE,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE DEFAULT NULL,
      ID_LAT_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE DEFAULT NULL,
      ID_MORPHOLOGY_nin IN BOOLEAN := TRUE,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE DEFAULT NULL,
      ID_MORPH_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE DEFAULT NULL,
      ID_BEHAVIOR_nin IN BOOLEAN := TRUE,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE DEFAULT NULL,
      ID_BEHAV_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE DEFAULT NULL,
      ID_HISTOLOGICAL_GRADE_nin IN BOOLEAN := TRUE,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE DEFAULT NULL,
      ID_HGRADE_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE DEFAULT NULL,
      ID_OTHER_GRADING_SYS_nin IN BOOLEAN := TRUE,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE DEFAULT NULL,
      ID_OGRADSYS_INST_OWNER_nin IN BOOLEAN := TRUE,
      flg_unknown_dimension_in IN EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE DEFAULT NULL,
      FLG_UNKNOWN_DIMENSION_nin IN BOOLEAN := TRUE,
      num_dimension_in IN EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE DEFAULT NULL,
      NUM_DIMENSION_nin IN BOOLEAN := TRUE,
      desc_dimension_in IN EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE DEFAULT NULL,
      DESC_DIMENSION_nin IN BOOLEAN := TRUE,
      additional_pathol_info_in IN EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE DEFAULT NULL,
      ADDITIONAL_PATHOL_INFO_nin IN BOOLEAN := TRUE,
      dt_epis_diagnosis_tumors_in IN EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE DEFAULT NULL,
      DT_EPIS_DIAGNOSIS_TUMORS_nin IN BOOLEAN := TRUE,
      create_user_in IN EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
    where_in varchar2,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );


      PROCEDURE upd (
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE DEFAULT NULL,
      ID_TOPOGRAPHY_nin IN BOOLEAN := TRUE,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE DEFAULT NULL,
      ID_TOPOG_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE DEFAULT NULL,
      ID_LATERALITY_nin IN BOOLEAN := TRUE,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE DEFAULT NULL,
      ID_LAT_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE DEFAULT NULL,
      ID_MORPHOLOGY_nin IN BOOLEAN := TRUE,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE DEFAULT NULL,
      ID_MORPH_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE DEFAULT NULL,
      ID_BEHAVIOR_nin IN BOOLEAN := TRUE,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE DEFAULT NULL,
      ID_BEHAV_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE DEFAULT NULL,
      ID_HISTOLOGICAL_GRADE_nin IN BOOLEAN := TRUE,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE DEFAULT NULL,
      ID_HGRADE_INST_OWNER_nin IN BOOLEAN := TRUE,
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE DEFAULT NULL,
      ID_OTHER_GRADING_SYS_nin IN BOOLEAN := TRUE,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE DEFAULT NULL,
      ID_OGRADSYS_INST_OWNER_nin IN BOOLEAN := TRUE,
      flg_unknown_dimension_in IN EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE DEFAULT NULL,
      FLG_UNKNOWN_DIMENSION_nin IN BOOLEAN := TRUE,
      num_dimension_in IN EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE DEFAULT NULL,
      NUM_DIMENSION_nin IN BOOLEAN := TRUE,
      desc_dimension_in IN EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE DEFAULT NULL,
      DESC_DIMENSION_nin IN BOOLEAN := TRUE,
      additional_pathol_info_in IN EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE DEFAULT NULL,
      ADDITIONAL_PATHOL_INFO_nin IN BOOLEAN := TRUE,
      dt_epis_diagnosis_tumors_in IN EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE DEFAULT NULL,
      DT_EPIS_DIAGNOSIS_TUMORS_nin IN BOOLEAN := TRUE,
      create_user_in IN EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
    where_in varchar2,
     handle_error_in IN BOOLEAN := TRUE
      );



   PROCEDURE upd_ins (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE,
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE,
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE,
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE DEFAULT NULL,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE DEFAULT NULL,
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE DEFAULT NULL,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE DEFAULT NULL,
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE DEFAULT NULL,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE DEFAULT NULL,
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE DEFAULT NULL,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE DEFAULT NULL,
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE DEFAULT NULL,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE DEFAULT NULL,
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE DEFAULT NULL,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE DEFAULT NULL,
      flg_unknown_dimension_in IN EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE DEFAULT NULL,
      num_dimension_in IN EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE DEFAULT NULL,
      desc_dimension_in IN EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE DEFAULT NULL,
      additional_pathol_info_in IN EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE DEFAULT NULL,
      dt_epis_diagnosis_tumors_in IN EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE DEFAULT NULL,
      create_user_in IN EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

      PROCEDURE upd_ins (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE,
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE,
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE,
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE DEFAULT NULL,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE DEFAULT NULL,
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE DEFAULT NULL,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE DEFAULT NULL,
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE DEFAULT NULL,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE DEFAULT NULL,
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE DEFAULT NULL,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE DEFAULT NULL,
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE DEFAULT NULL,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE DEFAULT NULL,
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE DEFAULT NULL,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE DEFAULT NULL,
      flg_unknown_dimension_in IN EPIS_DIAG_TUMORS_HIST.FLG_UNKNOWN_DIMENSION%TYPE DEFAULT NULL,
      num_dimension_in IN EPIS_DIAG_TUMORS_HIST.NUM_DIMENSION%TYPE DEFAULT NULL,
      desc_dimension_in IN EPIS_DIAG_TUMORS_HIST.DESC_DIMENSION%TYPE DEFAULT NULL,
      additional_pathol_info_in IN EPIS_DIAG_TUMORS_HIST.ADDITIONAL_PATHOL_INFO%TYPE DEFAULT NULL,
      dt_epis_diagnosis_tumors_in IN EPIS_DIAG_TUMORS_HIST.DT_EPIS_DIAGNOSIS_TUMORS%TYPE DEFAULT NULL,
      create_user_in IN EPIS_DIAG_TUMORS_HIST.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN EPIS_DIAG_TUMORS_HIST.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN EPIS_DIAG_TUMORS_HIST.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN EPIS_DIAG_TUMORS_HIST.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
     handle_error_in IN BOOLEAN := TRUE
      );

   PROCEDURE upd (
      rec_in IN EPIS_DIAG_TUMORS_HIST%ROWTYPE,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );

      PROCEDURE upd (
      rec_in IN EPIS_DIAG_TUMORS_HIST%ROWTYPE,
     handle_error_in IN BOOLEAN := TRUE
      );

      PROCEDURE upd (
      col_in IN EPIS_DIAG_TUMORS_HIST_tc,
      ignore_if_null_in IN BOOLEAN := TRUE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );

      PROCEDURE upd (
      col_in IN EPIS_DIAG_TUMORS_HIST_tc,
      ignore_if_null_in IN BOOLEAN := TRUE
     ,handle_error_in IN BOOLEAN := TRUE
      );





   -- Use Native Dynamic SQL increment a single NUMBER column
   -- for all rows specified by the dynamic WHERE clause
   PROCEDURE increment_onecol (
      colname_in IN ALL_TAB_COLUMNS.COLUMN_NAME%TYPE,
      where_in IN VARCHAR2 := NULL
      , increment_value_in IN NUMBER DEFAULT 1
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE increment_onecol (
      colname_in IN ALL_TAB_COLUMNS.COLUMN_NAME%TYPE,
      where_in IN VARCHAR2 := NULL
      , increment_value_in IN NUMBER DEFAULT 1
     ,handle_error_in IN BOOLEAN := TRUE
   );









    -- Delete one row by primary key
   PROCEDURE del (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE,
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE,
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

-- Delete one row by primary key
   PROCEDURE del (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE,
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE,
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );


   -- Delete all rows for primary key column ID_EPIS_DIAGNOSIS_HIST
   PROCEDURE del_ID_EPIS_DIAGNOSIS_HIST (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column ID_EPIS_DIAGNOSIS_HIST
   PROCEDURE del_ID_EPIS_DIAGNOSIS_HIST (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );


   -- Delete all rows for primary key column ID_EPIS_DIAGNOSIS
   PROCEDURE del_ID_EPIS_DIAGNOSIS (
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column ID_EPIS_DIAGNOSIS
   PROCEDURE del_ID_EPIS_DIAGNOSIS (
      id_epis_diagnosis_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );


   -- Delete all rows for primary key column TUMOR_NUM
   PROCEDURE del_TUMOR_NUM (
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column TUMOR_NUM
   PROCEDURE del_TUMOR_NUM (
      tumor_num_in IN EPIS_DIAG_TUMORS_HIST.TUMOR_NUM%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );

   -- Delete all rows for this EDTMRSH_CNCPTTR1_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR1_FK (
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this EDTMRSH_CNCPTTR1_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR1_FK (
      id_topography_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOGRAPHY%TYPE,
      id_topog_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_TOPOG_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this EDTMRSH_CNCPTTR2_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR2_FK (
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this EDTMRSH_CNCPTTR2_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR2_FK (
      id_laterality_in IN EPIS_DIAG_TUMORS_HIST.ID_LATERALITY%TYPE,
      id_lat_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_LAT_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this EDTMRSH_CNCPTTR3_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR3_FK (
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this EDTMRSH_CNCPTTR3_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR3_FK (
      id_morphology_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPHOLOGY%TYPE,
      id_morph_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_MORPH_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this EDTMRSH_CNCPTTR4_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR4_FK (
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this EDTMRSH_CNCPTTR4_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR4_FK (
      id_behavior_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAVIOR%TYPE,
      id_behav_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_BEHAV_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this EDTMRSH_CNCPTTR5_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR5_FK (
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this EDTMRSH_CNCPTTR5_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR5_FK (
      id_histological_grade_in IN EPIS_DIAG_TUMORS_HIST.ID_HISTOLOGICAL_GRADE%TYPE,
      id_hgrade_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_HGRADE_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this EDTMRSH_CNCPTTR6_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR6_FK (
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this EDTMRSH_CNCPTTR6_FK foreign key value
   PROCEDURE del_EDTMRSH_CNCPTTR6_FK (
      id_other_grading_sys_in IN EPIS_DIAG_TUMORS_HIST.ID_OTHER_GRADING_SYS%TYPE,
      id_ogradsys_inst_owner_in IN EPIS_DIAG_TUMORS_HIST.ID_OGRADSYS_INST_OWNER%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this EDTMRSH_EDH_FK foreign key value
   PROCEDURE del_EDTMRSH_EDH_FK (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this EDTMRSH_EDH_FK foreign key value
   PROCEDURE del_EDTMRSH_EDH_FK (
      id_epis_diagnosis_hist_in IN EPIS_DIAG_TUMORS_HIST.ID_EPIS_DIAGNOSIS_HIST%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows specified by dynamic WHERE clause
   PROCEDURE del_by (
      where_clause_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows specified by dynamic WHERE clause
   PROCEDURE del_by (
      where_clause_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified VARCHAR2 column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
      );


      -- Delete all rows where the specified VARCHAR2 column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified DATE column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN DATE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified DATE column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN DATE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );


      -- Delete all rows where the specified TIMESTAMP column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN TIMESTAMP WITH LOCAL TIME ZONE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified TIMESTAMP column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN TIMESTAMP WITH LOCAL TIME ZONE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified NUMBER column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN NUMBER
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified NUMBER column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN NUMBER
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Initialize a record with default values for columns in the table.
   PROCEDURE initrec (
      epis_diag_tumors_hist_inout IN OUT EPIS_DIAG_TUMORS_HIST%ROWTYPE
   );

   FUNCTION initrec RETURN EPIS_DIAG_TUMORS_HIST%ROWTYPE;



   FUNCTION get_data_rowid(
        rows_in IN TABLE_VARCHAR
        ) RETURN EPIS_DIAG_TUMORS_HIST_tc;


   FUNCTION get_data_rowid_pat(
        rows_in IN TABLE_VARCHAR
        ) RETURN EPIS_DIAG_TUMORS_HIST_tc;

END TS_EPIS_DIAG_TUMORS_HIST;
/
