/*-- Last Change Revision: $Rev: 2029324 $*/
/*-- Last Change by: $Author: mario.fernandes $*/
/*-- Date of last change: $Date: 2022-08-02 18:51:02 +0100 (ter, 02 ago 2022) $*/
CREATE OR REPLACE PACKAGE TS_PROF_FOLLOW_EPISODE
/*
| Generated by or retrieved from QCGU - DO NOT MODIFY!
| QCGU - "Get it right, do it fast" - www.ToadWorld.com
| QCGU Universal ID: {1BD37A66-EA60-4927-9A64-F6DD89237236}
| Created On: Setembro 17, 2012 16:29:28
| Created By: ALERT
*/
IS

  -- Collection of %ROWTYPE records based on "PROF_FOLLOW_EPISODE"
     TYPE PROF_FOLLOW_EPISODE_tc IS TABLE OF PROF_FOLLOW_EPISODE%ROWTYPE INDEX BY BINARY_INTEGER;
     TYPE prof_follow_episode_ntt IS TABLE OF PROF_FOLLOW_EPISODE%ROWTYPE;
     TYPE prof_follow_episode_vat IS VARRAY(100) OF PROF_FOLLOW_EPISODE%ROWTYPE;

  -- Same type structure, with a static name.
     TYPE aat IS TABLE OF PROF_FOLLOW_EPISODE%ROWTYPE INDEX BY BINARY_INTEGER;
     TYPE ntt IS TABLE OF PROF_FOLLOW_EPISODE%ROWTYPE;
     TYPE vat IS VARRAY(100) OF PROF_FOLLOW_EPISODE%ROWTYPE;

   -- Column Collection based on column "ID_PROFESSIONAL"
   TYPE ID_PROFESSIONAL_cc IS TABLE OF PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_EPISODE"
   TYPE ID_EPISODE_cc IS TABLE OF PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_SCHEDULE"
   TYPE ID_SCHEDULE_cc IS TABLE OF PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "FLG_ACTIVE"
   TYPE FLG_ACTIVE_cc IS TABLE OF PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_USER"
   TYPE CREATE_USER_cc IS TABLE OF PROF_FOLLOW_EPISODE.CREATE_USER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_TIME"
   TYPE CREATE_TIME_cc IS TABLE OF PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_INSTITUTION"
   TYPE CREATE_INSTITUTION_cc IS TABLE OF PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_USER"
   TYPE UPDATE_USER_cc IS TABLE OF PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_TIME"
   TYPE UPDATE_TIME_cc IS TABLE OF PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_INSTITUTION"
   TYPE UPDATE_INSTITUTION_cc IS TABLE OF PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE INDEX BY BINARY_INTEGER;

   -- Insert one row, providing primary key if present
   PROCEDURE ins (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE,
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE,
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE
      ,
      flg_active_in IN PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE DEFAULT NULL,
      create_user_in IN PROF_FOLLOW_EPISODE.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE DEFAULT NULL
      -- Pass false if you want errors to propagate out unhandled
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   PROCEDURE ins (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE,
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE,
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE
      ,
      flg_active_in IN PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE DEFAULT NULL,
      create_user_in IN PROF_FOLLOW_EPISODE.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE DEFAULT NULL
      -- Pass false if you want errors to propagate out unhandled
     ,handle_error_in IN BOOLEAN := TRUE
      );


   -- Insert a row based on a record.
   PROCEDURE ins (
      rec_in IN PROF_FOLLOW_EPISODE%ROWTYPE
     ,sequence_in IN VARCHAR2 := NULL
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE ins (
      rec_in IN PROF_FOLLOW_EPISODE%ROWTYPE
     ,sequence_in IN VARCHAR2 := NULL
     ,handle_error_in IN BOOLEAN := TRUE
   );

   -- Insert a collection of rows using FORALL; all primary key values
   -- must have already been generated, or are handled in triggers.
   PROCEDURE ins (
      rows_in IN PROF_FOLLOW_EPISODE_tc
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE ins (
      rows_in IN PROF_FOLLOW_EPISODE_tc
     ,handle_error_in IN BOOLEAN := TRUE
   );

   -- Update any/all columns by primary key. If you pass NULL, then
   -- the current column value is set to itself. If you need a more
   -- selected UPDATE then use one of the onecol procedures below.

  PROCEDURE upd (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE,
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE,
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE,
      flg_active_in IN PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE DEFAULT NULL,
      FLG_ACTIVE_nin IN BOOLEAN := TRUE,
      create_user_in IN PROF_FOLLOW_EPISODE.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );


       PROCEDURE upd (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE,
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE,
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE,
      flg_active_in IN PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE DEFAULT NULL,
      FLG_ACTIVE_nin IN BOOLEAN := TRUE,
      create_user_in IN PROF_FOLLOW_EPISODE.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
     handle_error_in IN BOOLEAN := TRUE
      );



      PROCEDURE upd (
      flg_active_in IN PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE DEFAULT NULL,
      FLG_ACTIVE_nin IN BOOLEAN := TRUE,
      create_user_in IN PROF_FOLLOW_EPISODE.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
    where_in varchar2,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );


      PROCEDURE upd (
      flg_active_in IN PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE DEFAULT NULL,
      FLG_ACTIVE_nin IN BOOLEAN := TRUE,
      create_user_in IN PROF_FOLLOW_EPISODE.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
    where_in varchar2,
     handle_error_in IN BOOLEAN := TRUE
      );



   PROCEDURE upd_ins (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE,
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE,
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE,
      flg_active_in IN PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE DEFAULT NULL,
      create_user_in IN PROF_FOLLOW_EPISODE.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

      PROCEDURE upd_ins (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE,
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE,
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE,
      flg_active_in IN PROF_FOLLOW_EPISODE.FLG_ACTIVE%TYPE DEFAULT NULL,
      create_user_in IN PROF_FOLLOW_EPISODE.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN PROF_FOLLOW_EPISODE.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN PROF_FOLLOW_EPISODE.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN PROF_FOLLOW_EPISODE.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN PROF_FOLLOW_EPISODE.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN PROF_FOLLOW_EPISODE.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
     handle_error_in IN BOOLEAN := TRUE
      );

   PROCEDURE upd (
      rec_in IN PROF_FOLLOW_EPISODE%ROWTYPE,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );

      PROCEDURE upd (
      rec_in IN PROF_FOLLOW_EPISODE%ROWTYPE,
     handle_error_in IN BOOLEAN := TRUE
      );

      PROCEDURE upd (
      col_in IN PROF_FOLLOW_EPISODE_tc,
      ignore_if_null_in IN BOOLEAN := TRUE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );

      PROCEDURE upd (
      col_in IN PROF_FOLLOW_EPISODE_tc,
      ignore_if_null_in IN BOOLEAN := TRUE
     ,handle_error_in IN BOOLEAN := TRUE
      );





   -- Use Native Dynamic SQL increment a single NUMBER column
   -- for all rows specified by the dynamic WHERE clause
   PROCEDURE increment_onecol (
      colname_in IN ALL_TAB_COLUMNS.COLUMN_NAME%TYPE,
      where_in IN VARCHAR2 := NULL
      , increment_value_in IN NUMBER DEFAULT 1
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE increment_onecol (
      colname_in IN ALL_TAB_COLUMNS.COLUMN_NAME%TYPE,
      where_in IN VARCHAR2 := NULL
      , increment_value_in IN NUMBER DEFAULT 1
     ,handle_error_in IN BOOLEAN := TRUE
   );









    -- Delete one row by primary key
   PROCEDURE del (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE,
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE,
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

-- Delete one row by primary key
   PROCEDURE del (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE,
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE,
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );


   -- Delete all rows for primary key column ID_PROFESSIONAL
   PROCEDURE del_ID_PROFESSIONAL (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column ID_PROFESSIONAL
   PROCEDURE del_ID_PROFESSIONAL (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );


   -- Delete all rows for primary key column ID_EPISODE
   PROCEDURE del_ID_EPISODE (
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column ID_EPISODE
   PROCEDURE del_ID_EPISODE (
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );


   -- Delete all rows for primary key column ID_SCHEDULE
   PROCEDURE del_ID_SCHEDULE (
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column ID_SCHEDULE
   PROCEDURE del_ID_SCHEDULE (
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );

   -- Delete all rows for this PFE_EPIS_FK foreign key value
   PROCEDURE del_PFE_EPIS_FK (
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this PFE_EPIS_FK foreign key value
   PROCEDURE del_PFE_EPIS_FK (
      id_episode_in IN PROF_FOLLOW_EPISODE.ID_EPISODE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this PFE_PROF_FK foreign key value
   PROCEDURE del_PFE_PROF_FK (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this PFE_PROF_FK foreign key value
   PROCEDURE del_PFE_PROF_FK (
      id_professional_in IN PROF_FOLLOW_EPISODE.ID_PROFESSIONAL%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this PFE_SCHED_FK foreign key value
   PROCEDURE del_PFE_SCHED_FK (
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this PFE_SCHED_FK foreign key value
   PROCEDURE del_PFE_SCHED_FK (
      id_schedule_in IN PROF_FOLLOW_EPISODE.ID_SCHEDULE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows specified by dynamic WHERE clause
   PROCEDURE del_by (
      where_clause_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows specified by dynamic WHERE clause
   PROCEDURE del_by (
      where_clause_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified VARCHAR2 column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
      );


      -- Delete all rows where the specified VARCHAR2 column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified DATE column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN DATE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified DATE column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN DATE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );


      -- Delete all rows where the specified TIMESTAMP column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN TIMESTAMP WITH LOCAL TIME ZONE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified TIMESTAMP column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN TIMESTAMP WITH LOCAL TIME ZONE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified NUMBER column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN NUMBER
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified NUMBER column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN NUMBER
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Initialize a record with default values for columns in the table.
   PROCEDURE initrec (
      prof_follow_episode_inout IN OUT PROF_FOLLOW_EPISODE%ROWTYPE
   );

   FUNCTION initrec RETURN PROF_FOLLOW_EPISODE%ROWTYPE;



   FUNCTION get_data_rowid(
        rows_in IN TABLE_VARCHAR
        ) RETURN PROF_FOLLOW_EPISODE_tc;


   FUNCTION get_data_rowid_pat(
        rows_in IN TABLE_VARCHAR
        ) RETURN PROF_FOLLOW_EPISODE_tc;

END TS_PROF_FOLLOW_EPISODE;
/
