/*-- Last Change Revision: $Rev: 2029410 $*/
/*-- Last Change by: $Author: mario.fernandes $*/
/*-- Date of last change: $Date: 2022-08-02 18:51:31 +0100 (ter, 02 ago 2022) $*/
CREATE OR REPLACE PACKAGE TS_VS_PATIENT_EA
/*
| Generated by or retrieved from QCGU - DO NOT MODIFY!
| QCGU - "Get it right, do it fast" - www.ToadWorld.com
| QCGU Universal ID: {1BD37A66-EA60-4927-9A64-F6DD89237236}
| Created On: Novembro 22, 2011 11:35:18
| Created By: ALERT
*/
IS

  -- Collection of %ROWTYPE records based on "VS_PATIENT_EA"
     TYPE VS_PATIENT_EA_tc IS TABLE OF VS_PATIENT_EA%ROWTYPE INDEX BY BINARY_INTEGER;
     TYPE vs_patient_ea_ntt IS TABLE OF VS_PATIENT_EA%ROWTYPE;
     TYPE vs_patient_ea_vat IS VARRAY(100) OF VS_PATIENT_EA%ROWTYPE;

  -- Same type structure, with a static name.
     TYPE aat IS TABLE OF VS_PATIENT_EA%ROWTYPE INDEX BY BINARY_INTEGER;
     TYPE ntt IS TABLE OF VS_PATIENT_EA%ROWTYPE;
     TYPE vat IS VARRAY(100) OF VS_PATIENT_EA%ROWTYPE;

   -- Column Collection based on column "ID_PATIENT"
   TYPE ID_PATIENT_cc IS TABLE OF VS_PATIENT_EA.ID_PATIENT%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_VITAL_SIGN"
   TYPE ID_VITAL_SIGN_cc IS TABLE OF VS_PATIENT_EA.ID_VITAL_SIGN%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_UNIT_MEASURE"
   TYPE ID_UNIT_MEASURE_cc IS TABLE OF VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "N_RECORDS"
   TYPE N_RECORDS_cc IS TABLE OF VS_PATIENT_EA.N_RECORDS%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_FIRST_VSR"
   TYPE ID_FIRST_VSR_cc IS TABLE OF VS_PATIENT_EA.ID_FIRST_VSR%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_MIN_VSR"
   TYPE ID_MIN_VSR_cc IS TABLE OF VS_PATIENT_EA.ID_MIN_VSR%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_MAX_VSR"
   TYPE ID_MAX_VSR_cc IS TABLE OF VS_PATIENT_EA.ID_MAX_VSR%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_LAST_1_VSR"
   TYPE ID_LAST_1_VSR_cc IS TABLE OF VS_PATIENT_EA.ID_LAST_1_VSR%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_LAST_2_VSR"
   TYPE ID_LAST_2_VSR_cc IS TABLE OF VS_PATIENT_EA.ID_LAST_2_VSR%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "ID_LAST_3_VSR"
   TYPE ID_LAST_3_VSR_cc IS TABLE OF VS_PATIENT_EA.ID_LAST_3_VSR%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_USER"
   TYPE CREATE_USER_cc IS TABLE OF VS_PATIENT_EA.CREATE_USER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_TIME"
   TYPE CREATE_TIME_cc IS TABLE OF VS_PATIENT_EA.CREATE_TIME%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "CREATE_INSTITUTION"
   TYPE CREATE_INSTITUTION_cc IS TABLE OF VS_PATIENT_EA.CREATE_INSTITUTION%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_USER"
   TYPE UPDATE_USER_cc IS TABLE OF VS_PATIENT_EA.UPDATE_USER%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_TIME"
   TYPE UPDATE_TIME_cc IS TABLE OF VS_PATIENT_EA.UPDATE_TIME%TYPE INDEX BY BINARY_INTEGER;
   -- Column Collection based on column "UPDATE_INSTITUTION"
   TYPE UPDATE_INSTITUTION_cc IS TABLE OF VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE INDEX BY BINARY_INTEGER;

   -- Insert one row, providing primary key if present
   PROCEDURE ins (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE,
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE,
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE
      ,
      n_records_in IN VS_PATIENT_EA.N_RECORDS%TYPE DEFAULT NULL,
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE DEFAULT NULL,
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE DEFAULT NULL,
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE DEFAULT NULL,
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE DEFAULT NULL,
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE DEFAULT NULL,
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE DEFAULT NULL,
      create_user_in IN VS_PATIENT_EA.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN VS_PATIENT_EA.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN VS_PATIENT_EA.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN VS_PATIENT_EA.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN VS_PATIENT_EA.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE DEFAULT NULL
      -- Pass false if you want errors to propagate out unhandled
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   PROCEDURE ins (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE,
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE,
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE
      ,
      n_records_in IN VS_PATIENT_EA.N_RECORDS%TYPE DEFAULT NULL,
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE DEFAULT NULL,
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE DEFAULT NULL,
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE DEFAULT NULL,
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE DEFAULT NULL,
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE DEFAULT NULL,
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE DEFAULT NULL,
      create_user_in IN VS_PATIENT_EA.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN VS_PATIENT_EA.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN VS_PATIENT_EA.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN VS_PATIENT_EA.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN VS_PATIENT_EA.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE DEFAULT NULL
      -- Pass false if you want errors to propagate out unhandled
     ,handle_error_in IN BOOLEAN := TRUE
      );


   -- Insert a row based on a record.
   PROCEDURE ins (
      rec_in IN VS_PATIENT_EA%ROWTYPE
     ,sequence_in IN VARCHAR2 := NULL
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE ins (
      rec_in IN VS_PATIENT_EA%ROWTYPE
     ,sequence_in IN VARCHAR2 := NULL
     ,handle_error_in IN BOOLEAN := TRUE
   );

   -- Insert a collection of rows using FORALL; all primary key values
   -- must have already been generated, or are handled in triggers.
   PROCEDURE ins (
      rows_in IN VS_PATIENT_EA_tc
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE ins (
      rows_in IN VS_PATIENT_EA_tc
     ,handle_error_in IN BOOLEAN := TRUE
   );

   -- Update any/all columns by primary key. If you pass NULL, then
   -- the current column value is set to itself. If you need a more
   -- selected UPDATE then use one of the onecol procedures below.

  PROCEDURE upd (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE,
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE,
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE,
      n_records_in IN VS_PATIENT_EA.N_RECORDS%TYPE DEFAULT NULL,
      N_RECORDS_nin IN BOOLEAN := TRUE,
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE DEFAULT NULL,
      ID_FIRST_VSR_nin IN BOOLEAN := TRUE,
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE DEFAULT NULL,
      ID_MIN_VSR_nin IN BOOLEAN := TRUE,
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE DEFAULT NULL,
      ID_MAX_VSR_nin IN BOOLEAN := TRUE,
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE DEFAULT NULL,
      ID_LAST_1_VSR_nin IN BOOLEAN := TRUE,
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE DEFAULT NULL,
      ID_LAST_2_VSR_nin IN BOOLEAN := TRUE,
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE DEFAULT NULL,
      ID_LAST_3_VSR_nin IN BOOLEAN := TRUE,
      create_user_in IN VS_PATIENT_EA.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN VS_PATIENT_EA.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN VS_PATIENT_EA.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN VS_PATIENT_EA.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN VS_PATIENT_EA.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );


       PROCEDURE upd (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE,
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE,
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE,
      n_records_in IN VS_PATIENT_EA.N_RECORDS%TYPE DEFAULT NULL,
      N_RECORDS_nin IN BOOLEAN := TRUE,
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE DEFAULT NULL,
      ID_FIRST_VSR_nin IN BOOLEAN := TRUE,
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE DEFAULT NULL,
      ID_MIN_VSR_nin IN BOOLEAN := TRUE,
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE DEFAULT NULL,
      ID_MAX_VSR_nin IN BOOLEAN := TRUE,
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE DEFAULT NULL,
      ID_LAST_1_VSR_nin IN BOOLEAN := TRUE,
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE DEFAULT NULL,
      ID_LAST_2_VSR_nin IN BOOLEAN := TRUE,
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE DEFAULT NULL,
      ID_LAST_3_VSR_nin IN BOOLEAN := TRUE,
      create_user_in IN VS_PATIENT_EA.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN VS_PATIENT_EA.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN VS_PATIENT_EA.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN VS_PATIENT_EA.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN VS_PATIENT_EA.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
     handle_error_in IN BOOLEAN := TRUE
      );



      PROCEDURE upd (
      n_records_in IN VS_PATIENT_EA.N_RECORDS%TYPE DEFAULT NULL,
      N_RECORDS_nin IN BOOLEAN := TRUE,
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE DEFAULT NULL,
      ID_FIRST_VSR_nin IN BOOLEAN := TRUE,
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE DEFAULT NULL,
      ID_MIN_VSR_nin IN BOOLEAN := TRUE,
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE DEFAULT NULL,
      ID_MAX_VSR_nin IN BOOLEAN := TRUE,
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE DEFAULT NULL,
      ID_LAST_1_VSR_nin IN BOOLEAN := TRUE,
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE DEFAULT NULL,
      ID_LAST_2_VSR_nin IN BOOLEAN := TRUE,
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE DEFAULT NULL,
      ID_LAST_3_VSR_nin IN BOOLEAN := TRUE,
      create_user_in IN VS_PATIENT_EA.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN VS_PATIENT_EA.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN VS_PATIENT_EA.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN VS_PATIENT_EA.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN VS_PATIENT_EA.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
    where_in varchar2,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );


      PROCEDURE upd (
      n_records_in IN VS_PATIENT_EA.N_RECORDS%TYPE DEFAULT NULL,
      N_RECORDS_nin IN BOOLEAN := TRUE,
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE DEFAULT NULL,
      ID_FIRST_VSR_nin IN BOOLEAN := TRUE,
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE DEFAULT NULL,
      ID_MIN_VSR_nin IN BOOLEAN := TRUE,
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE DEFAULT NULL,
      ID_MAX_VSR_nin IN BOOLEAN := TRUE,
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE DEFAULT NULL,
      ID_LAST_1_VSR_nin IN BOOLEAN := TRUE,
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE DEFAULT NULL,
      ID_LAST_2_VSR_nin IN BOOLEAN := TRUE,
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE DEFAULT NULL,
      ID_LAST_3_VSR_nin IN BOOLEAN := TRUE,
      create_user_in IN VS_PATIENT_EA.CREATE_USER%TYPE DEFAULT NULL,
      CREATE_USER_nin IN BOOLEAN := TRUE,
      create_time_in IN VS_PATIENT_EA.CREATE_TIME%TYPE DEFAULT NULL,
      CREATE_TIME_nin IN BOOLEAN := TRUE,
      create_institution_in IN VS_PATIENT_EA.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      CREATE_INSTITUTION_nin IN BOOLEAN := TRUE,
      update_user_in IN VS_PATIENT_EA.UPDATE_USER%TYPE DEFAULT NULL,
      UPDATE_USER_nin IN BOOLEAN := TRUE,
      update_time_in IN VS_PATIENT_EA.UPDATE_TIME%TYPE DEFAULT NULL,
      UPDATE_TIME_nin IN BOOLEAN := TRUE,
      update_institution_in IN VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
      UPDATE_INSTITUTION_nin IN BOOLEAN := TRUE,
    where_in varchar2,
     handle_error_in IN BOOLEAN := TRUE
      );



   PROCEDURE upd_ins (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE,
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE,
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE,
      n_records_in IN VS_PATIENT_EA.N_RECORDS%TYPE DEFAULT NULL,
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE DEFAULT NULL,
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE DEFAULT NULL,
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE DEFAULT NULL,
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE DEFAULT NULL,
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE DEFAULT NULL,
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE DEFAULT NULL,
      create_user_in IN VS_PATIENT_EA.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN VS_PATIENT_EA.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN VS_PATIENT_EA.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN VS_PATIENT_EA.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN VS_PATIENT_EA.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

      PROCEDURE upd_ins (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE,
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE,
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE,
      n_records_in IN VS_PATIENT_EA.N_RECORDS%TYPE DEFAULT NULL,
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE DEFAULT NULL,
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE DEFAULT NULL,
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE DEFAULT NULL,
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE DEFAULT NULL,
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE DEFAULT NULL,
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE DEFAULT NULL,
      create_user_in IN VS_PATIENT_EA.CREATE_USER%TYPE DEFAULT NULL,
      create_time_in IN VS_PATIENT_EA.CREATE_TIME%TYPE DEFAULT NULL,
      create_institution_in IN VS_PATIENT_EA.CREATE_INSTITUTION%TYPE DEFAULT NULL,
      update_user_in IN VS_PATIENT_EA.UPDATE_USER%TYPE DEFAULT NULL,
      update_time_in IN VS_PATIENT_EA.UPDATE_TIME%TYPE DEFAULT NULL,
      update_institution_in IN VS_PATIENT_EA.UPDATE_INSTITUTION%TYPE DEFAULT NULL,
     handle_error_in IN BOOLEAN := TRUE
      );

   PROCEDURE upd (
      rec_in IN VS_PATIENT_EA%ROWTYPE,
     handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );

      PROCEDURE upd (
      rec_in IN VS_PATIENT_EA%ROWTYPE,
     handle_error_in IN BOOLEAN := TRUE
      );

      PROCEDURE upd (
      col_in IN VS_PATIENT_EA_tc,
      ignore_if_null_in IN BOOLEAN := TRUE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out IN OUT TABLE_VARCHAR
      );

      PROCEDURE upd (
      col_in IN VS_PATIENT_EA_tc,
      ignore_if_null_in IN BOOLEAN := TRUE
     ,handle_error_in IN BOOLEAN := TRUE
      );





   -- Use Native Dynamic SQL increment a single NUMBER column
   -- for all rows specified by the dynamic WHERE clause
   PROCEDURE increment_onecol (
      colname_in IN ALL_TAB_COLUMNS.COLUMN_NAME%TYPE,
      where_in IN VARCHAR2 := NULL
      , increment_value_in IN NUMBER DEFAULT 1
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
   );

   PROCEDURE increment_onecol (
      colname_in IN ALL_TAB_COLUMNS.COLUMN_NAME%TYPE,
      where_in IN VARCHAR2 := NULL
      , increment_value_in IN NUMBER DEFAULT 1
     ,handle_error_in IN BOOLEAN := TRUE
   );









    -- Delete one row by primary key
   PROCEDURE del (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE,
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE,
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

-- Delete one row by primary key
   PROCEDURE del (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE,
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE,
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );


   -- Delete all rows for primary key column ID_PATIENT
   PROCEDURE del_ID_PATIENT (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column ID_PATIENT
   PROCEDURE del_ID_PATIENT (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );


   -- Delete all rows for primary key column ID_VITAL_SIGN
   PROCEDURE del_ID_VITAL_SIGN (
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column ID_VITAL_SIGN
   PROCEDURE del_ID_VITAL_SIGN (
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );


   -- Delete all rows for primary key column ID_UNIT_MEASURE
   PROCEDURE del_ID_UNIT_MEASURE (
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     );

     -- Delete all rows for primary key column ID_UNIT_MEASURE
   PROCEDURE del_ID_UNIT_MEASURE (
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
     );

   -- Delete all rows for this VPEA_FSTVSR_FK foreign key value
   PROCEDURE del_VPEA_FSTVSR_FK (
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_FSTVSR_FK foreign key value
   PROCEDURE del_VPEA_FSTVSR_FK (
      id_first_vsr_in IN VS_PATIENT_EA.ID_FIRST_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this VPEA_L1VSR_FK foreign key value
   PROCEDURE del_VPEA_L1VSR_FK (
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_L1VSR_FK foreign key value
   PROCEDURE del_VPEA_L1VSR_FK (
      id_last_1_vsr_in IN VS_PATIENT_EA.ID_LAST_1_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this VPEA_L2VSR_FK foreign key value
   PROCEDURE del_VPEA_L2VSR_FK (
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_L2VSR_FK foreign key value
   PROCEDURE del_VPEA_L2VSR_FK (
      id_last_2_vsr_in IN VS_PATIENT_EA.ID_LAST_2_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this VPEA_L3VSR_FK foreign key value
   PROCEDURE del_VPEA_L3VSR_FK (
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_L3VSR_FK foreign key value
   PROCEDURE del_VPEA_L3VSR_FK (
      id_last_3_vsr_in IN VS_PATIENT_EA.ID_LAST_3_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this VPEA_MAXVSR_FK foreign key value
   PROCEDURE del_VPEA_MAXVSR_FK (
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_MAXVSR_FK foreign key value
   PROCEDURE del_VPEA_MAXVSR_FK (
      id_max_vsr_in IN VS_PATIENT_EA.ID_MAX_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this VPEA_MINVSR_FK foreign key value
   PROCEDURE del_VPEA_MINVSR_FK (
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_MINVSR_FK foreign key value
   PROCEDURE del_VPEA_MINVSR_FK (
      id_min_vsr_in IN VS_PATIENT_EA.ID_MIN_VSR%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this VPEA_P_FK foreign key value
   PROCEDURE del_VPEA_P_FK (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_P_FK foreign key value
   PROCEDURE del_VPEA_P_FK (
      id_patient_in IN VS_PATIENT_EA.ID_PATIENT%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this VPEA_UM_FK foreign key value
   PROCEDURE del_VPEA_UM_FK (
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_UM_FK foreign key value
   PROCEDURE del_VPEA_UM_FK (
      id_unit_measure_in IN VS_PATIENT_EA.ID_UNIT_MEASURE%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Delete all rows for this VPEA_VS_FK foreign key value
   PROCEDURE del_VPEA_VS_FK (
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows for this VPEA_VS_FK foreign key value
   PROCEDURE del_VPEA_VS_FK (
      id_vital_sign_in IN VS_PATIENT_EA.ID_VITAL_SIGN%TYPE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows specified by dynamic WHERE clause
   PROCEDURE del_by (
      where_clause_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows specified by dynamic WHERE clause
   PROCEDURE del_by (
      where_clause_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified VARCHAR2 column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
      );


      -- Delete all rows where the specified VARCHAR2 column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN VARCHAR2
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified DATE column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN DATE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified DATE column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN DATE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );


      -- Delete all rows where the specified TIMESTAMP column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN TIMESTAMP WITH LOCAL TIME ZONE
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified TIMESTAMP column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN TIMESTAMP WITH LOCAL TIME ZONE
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

    -- Delete all rows where the specified NUMBER column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN NUMBER
     ,handle_error_in IN BOOLEAN := TRUE
      );

      -- Delete all rows where the specified NUMBER column has
   -- a value that matches the specfified value.
   PROCEDURE del_by_col (
      colname_in IN VARCHAR2,
      colvalue_in IN NUMBER
     ,handle_error_in IN BOOLEAN := TRUE
     , rows_out OUT TABLE_VARCHAR
      );

   -- Initialize a record with default values for columns in the table.
   PROCEDURE initrec (
      vs_patient_ea_inout IN OUT VS_PATIENT_EA%ROWTYPE
   );

   FUNCTION initrec RETURN VS_PATIENT_EA%ROWTYPE;



   FUNCTION get_data_rowid(
        rows_in IN TABLE_VARCHAR
        ) RETURN VS_PATIENT_EA_tc;


   FUNCTION get_data_rowid_pat(
        rows_in IN TABLE_VARCHAR
        ) RETURN VS_PATIENT_EA_tc;

END TS_VS_PATIENT_EA;
/
