--Run as user ALERT
BEGIN
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_unit_mea_soft_inst', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_sample_type', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_sample_recipient', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_exam_cat_cs', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_exam_cat', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_event', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_clinical_service', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_unit_measure', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_a_p_f', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_parameter', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_param', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_mrk_vrs', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_a_l_t', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_loinc', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_instit_soft', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_a_i_r', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_a_g_m_v', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_group', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_desc', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_clin_serv', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis_agp', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.insert_into_frmw_objects('ALERT_DEFAULT', 'A_146833_analysis', 'TABLE', 'CNT', 'N', 'N', 'N');
END;
/


BEGIN
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_CLINICAL_SERVICE', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_EXAM_CAT', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_EXAM_CAT_CS', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_SAMPLE_TYPE', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_SAMPLE_RECIPIENT', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_MRK_VRS', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_GROUP', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_GROUP_MRK_VRS', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_PARAMETER', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_PARAM', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_PARAM_FUNCIONALITY', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_APF', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_INSTIT_SOFT', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_INSTIT_RECIPIENT', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_LOINC', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_LOINC_TEMPLATE', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_CLIN_SERV', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_DESC', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_AGP', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_ANALYSIS_UNIT_MEASURE', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_EVENT', 'TABLE', 'CNT', 'N', 'N', 'N');
PK_FRMW_OBJECTS.INSERT_INTO_FRMW_OBJECTS('ALERT_DEFAULT', 'ERR$_UNIT_MEA_SOFT_INST', 'TABLE', 'CNT', 'N', 'N', 'N');
END;
/



